import { ModuleData } from '../../types/curriculum';

export const Day_20_MODULE: ModuleData = {
  id: 'day-20',
  slug: 'milestone-2-assessment',
  day: 20,
  title: 'Day 20 — Milestone 2 Challenge: Multi-Table Analyst',
  shortTitle: 'Milestone 2 Challenge',
  type: 'assignment',
  milestoneId: 'milestone-2',
  description: 'The CFO walks in with a stack of questions: "How much revenue did we make? Which categories are our stars? Who are our best customers? Which suppliers should we follow up with?" Write multi-table JOINs, financial aggregations, and anti-joins to answer real business questions — no hand-holding. You\'re now working like an analyst.',
  estimatedMinutes: 90,
  completionLearnings: [
    'Calculate total revenue across multi-table order data',
    'Break revenue down by category to identify which product lines drive profit',
    'Find high-value customers using GROUP BY and HAVING',
    'Use anti-JOINs to discover suppliers whose products have never been ordered',
  ],
  concepts: [
    {
      id: 'milestone-2-eval',
      order: 1,
      title: '1. Real Financial Scenario: Multi-Table Revenue Analysis',
      shortDescription: 'The CFO four questions; multi-table JOINs and aggregations required; no templates.',
      theory: {
        summary: 'The CFO asks four questions: (1) What\'s our total revenue? (2) Which categories are revenue leaders? (3) High-value customers? (4) Suppliers we haven\'t ordered from? You have all the tools from Days 9–19. No templates. No hints. This is what the analyst role looks like.',
        introTable: {
          tableName: 'order_items',
          description: 'Line item financial transactions',
          columns: ['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price'],
          rows: [
            [1, 1, 1, 2, 15.99],
            [2, 1, 4, 1, 65.00],
            [3, 2, 6, 1, 55.00],
          ],
        },
        explanation: [
          '### The Business Scenario',
          'Friday morning. The CFO asks:\n1. **"What\'s our total revenue?"** — SUM across all line items.\n2. **"Which categories are revenue leaders?"** — Group by category, SUM by category.\n3. **"High-value customers?"** — Aggregate by customer, filter with HAVING.\n4. **"Suppliers we haven\'t ordered from?"** — Anti-JOIN: suppliers NOT in the order data.',
          '',
          'You have all the tools from Days 9–19. No templates. No hints. This is what the analyst role looks like.',
        ],
        targetQuery: {
          sql: 'SELECT cat.name, SUM(oi.quantity * oi.unit_price) AS category_revenue\nFROM categories cat\nJOIN products p ON cat.category_id = p.category_id\nJOIN order_items oi ON p.product_id = oi.product_id\nGROUP BY cat.category_id, cat.name\nORDER BY category_revenue DESC;',
          explanation: 'Aggregate multi-table revenue breakdown across categories, products, and line items, sorted highest revenue first.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: FROM categories cat JOIN products p JOIN order_items oi',
            sqlSnippet: 'FROM categories cat JOIN products p ON cat.category_id = p.category_id JOIN order_items oi ON p.product_id = oi.product_id',
            explanation: 'Joins 3 tables to link category names to product purchases.',
            tableData: {
              tableName: 'Matched Multi-Table Line Items',
              columns: ['cat.name', 'p.name', 'oi.quantity', 'oi.unit_price'],
              rows: [
                ['Electronics', 'Wireless Mouse', 2, 15.99],
                ['Electronics', 'Mechanical Keyboard', 1, 65.00],
                ['Kitchen & Dining', 'Stainless Steel Pan Set', 1, 55.00],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: GROUP BY cat.category_id, cat.name ORDER BY category_revenue DESC',
            sqlSnippet: 'SELECT cat.name, SUM(oi.quantity * oi.unit_price) AS category_revenue GROUP BY cat.category_id, cat.name ORDER BY category_revenue DESC',
            explanation: 'Computes total sales revenue generated per category.',
            tableData: {
              tableName: 'Category Revenue Summary Result',
              columns: ['name', 'category_revenue'],
              highlightedColumns: ['name', 'category_revenue'],
              highlightedRows: [0, 1, 2],
              rows: [
                ['Electronics', 448.47],
                ['Office Furniture', 209.99],
                ['Accessories', 161.42],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Multi-table join and aggregate competency',
            sql: 'SELECT cat.name, SUM(oi.quantity * oi.unit_price) AS category_revenue\nFROM categories cat\nJOIN products p ON cat.category_id = p.category_id\nJOIN order_items oi ON p.product_id = oi.product_id\nGROUP BY cat.category_id, cat.name\nORDER BY category_revenue DESC;',
            description: 'Multi-table category revenue reporting.',
          },
        ],
        keyTakeaway: 'Demonstrate multi-table JOIN and aggregation mastery.',
        exampleQuery: 'SELECT SUM(quantity * unit_price) AS total_revenue FROM order_items;',
        exampleQueryExplanation: 'One number: the company\'s total revenue across every order.',
        liveDemoSql: 'SELECT SUM(quantity * unit_price) AS total_revenue FROM order_items;',
        liveDemoNotes: 'The headline revenue figure for the whole store.',
        mcqs: [
          {
            question: 'Which supplier in the seed dataset has products that have never been ordered?',
            options: ['A. LogiTech Direct', 'B. Unity Traders BD', 'C. KeyChron Components', 'D. SoundWave Acoustic'],
            correctIndex: 1,
            explanation: 'Unity Traders BD has products in the catalog, but none have ever been referenced in order_items.',
          },
        ],
        masteryPoints: ['Pass all 4 Milestone 2 independent verification deliverables'],
      },
      tasks: [
        {
          id: 'day16-c1-t1',
          title: 'Warmup 1: Total Revenue Calculation',
          description: 'Calculate the grand total revenue across all order line items.',
          instructions: [
            'Select `SUM(quantity * unit_price) AS total_revenue` from `order_items`.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'order_items',
          initialSql: '-- Warmup 1: Grand total revenue\n',
          solutionSql: 'SELECT SUM(quantity * unit_price) AS total_revenue FROM order_items;',
          solutionExplanation: 'Calculates the sum product of quantity and unit_price for all order items.',
          hints: [{ level: 1, text: 'Use `SELECT SUM(quantity * unit_price) AS total_revenue FROM order_items;`' }],
          validation: {
            requireExactResult: true,
            targetTable: 'order_items',
            expectedRowCount: 1,
          },
          successMessage: 'Warmup 1 completed! Total revenue calculated.',
        },
        {
          id: 'day16-c1-t2',
          title: 'Warmup 2: Category Revenue Breakdown',
          description: 'Join categories, products, and order_items to compute total revenue generated per category, sorted highest first.',
          instructions: [
            'Query `categories cat` JOIN `products p` ON `cat.category_id = p.category_id` JOIN `order_items oi` ON `p.product_id = oi.product_id`.',
            'Select `cat.name`, `SUM(oi.quantity * oi.unit_price) AS category_revenue`.',
            'Group by `cat.category_id`, `cat.name`.',
            'Order by `category_revenue DESC`.',
          ],
          type: 'independent',
          primaryTable: 'categories',
          secondaryTables: ['products', 'order_items'],
          initialSql: '-- Warmup 2: Revenue by category\n',
          solutionSql: 'SELECT cat.name, SUM(oi.quantity * oi.unit_price) AS category_revenue FROM categories cat JOIN products p ON cat.category_id = p.category_id JOIN order_items oi ON p.product_id = oi.product_id GROUP BY cat.category_id, cat.name ORDER BY category_revenue DESC;',
          solutionExplanation: 'Joins 3 tables and computes revenue per category.',
          hints: [{ level: 1, text: 'Use `GROUP BY cat.category_id, cat.name ORDER BY category_revenue DESC;`' }],
          validation: {
            requireExactResult: true,
            targetTable: 'categories',
            requireJoin: true,
            requireGroupBy: true,
            requireOrderBy: [{ column: 'category_revenue', direction: 'DESC' }],
            expectedRowCount: 5,
          },
          successMessage: 'Warmup 2 completed! Category revenue breakdown calculated.',
        },
      ],
    },
  ],

  // ===========================================================================
  // DAY 16 CHALLENGE: MILESTONE 2 MASTERY CHECKPOINT (ENDING ACTIVITY)
  // ===========================================================================
  challenge: {
    id: 'day-20-homework',
    title: 'Day 20 — Milestone 2 Mastery Checkpoint (Ending Activity)',
    scenario: 'Complete all 4 deliverables independently to verify Milestone 2 relational mastery:',
    tasks: [
      {
        id: 'day16-hw-1',
        title: 'Deliverable 1 (Core): Grand total revenue across all orders',
        description: 'Total revenue (SUM across order_items).',
        instructions: [
          'Select `SUM(quantity * unit_price) AS total_revenue` from `order_items`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'order_items',
        initialSql: '-- Deliverable 1: Total revenue\n',
        solutionSql: 'SELECT SUM(quantity * unit_price) AS total_revenue FROM order_items;',
        solutionExplanation: 'Calculates grand total revenue across all order line items.',
        hints: [{ level: 1, text: 'Use `SELECT SUM(quantity * unit_price) AS total_revenue FROM order_items;`' }],
        validation: {
          requireExactResult: true,
          targetTable: 'order_items',
          expectedRowCount: 1,
        },
        successMessage: 'Deliverable 1 verified! Grand total revenue calculated.',
      },
      {
        id: 'day16-hw-2',
        title: 'Deliverable 2 (Combination): Revenue by product category',
        description: 'Revenue by category (categories → products → order_items).',
        instructions: [
          'Select `cat.name`, `SUM(oi.quantity * oi.unit_price) AS category_revenue` from `categories cat` JOIN `products p` ON `cat.category_id = p.category_id` JOIN `order_items oi` ON `p.product_id = oi.product_id` GROUP BY `cat.category_id`, `cat.name` ORDER BY `category_revenue DESC`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'categories',
        secondaryTables: ['products', 'order_items'],
        initialSql: '-- Deliverable 2: Revenue by category\n',
        solutionSql: 'SELECT cat.name, SUM(oi.quantity * oi.unit_price) AS category_revenue FROM categories cat JOIN products p ON cat.category_id = p.category_id JOIN order_items oi ON p.product_id = oi.product_id GROUP BY cat.category_id, cat.name ORDER BY category_revenue DESC;',
        solutionExplanation: 'Joins categories -> products -> order_items and sums revenue per category.',
        hints: [{ level: 1, text: 'Use `GROUP BY cat.category_id, cat.name ORDER BY category_revenue DESC;`' }],
        validation: {
          requireExactResult: true,
          targetTable: 'categories',
          requireJoin: true,
          requireGroupBy: true,
          expectedRowCount: 5,
        },
        successMessage: 'Deliverable 2 verified! Revenue by category calculated.',
      },
      {
        id: 'day16-hw-3',
        title: 'Deliverable 3 (Transfer): High-value customers who spent more than $200',
        description: 'Customers who\'ve spent more than $200.',
        instructions: [
          'Select `c.customer_id`, `c.name`, `SUM(oi.quantity * oi.unit_price) AS total_spent` from `customers c` JOIN `orders o` ON `c.customer_id = o.customer_id` JOIN `order_items oi` ON `o.order_id = oi.order_id` GROUP BY `c.customer_id`, `c.name` HAVING `SUM(oi.quantity * oi.unit_price) > 200` ORDER BY `total_spent DESC`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'customers',
        secondaryTables: ['orders', 'order_items'],
        initialSql: '-- Deliverable 3: Customers who spent more than $200\n',
        solutionSql: 'SELECT c.customer_id, c.name, SUM(oi.quantity * oi.unit_price) AS total_spent FROM customers c JOIN orders o ON c.customer_id = o.customer_id JOIN order_items oi ON o.order_id = oi.order_id GROUP BY c.customer_id, c.name HAVING SUM(oi.quantity * oi.unit_price) > 200 ORDER BY total_spent DESC;',
        solutionExplanation: 'Filters aggregated customer spending with `HAVING SUM(...) > 200`.',
        hints: [{ level: 1, text: 'Use `HAVING SUM(oi.quantity * oi.unit_price) > 200 ORDER BY total_spent DESC;`' }],
        validation: {
          requireExactResult: true,
          targetTable: 'customers',
          requireJoin: true,
          requireGroupBy: true,
          requireHaving: true,
          expectedRowCount: 1,
        },
        successMessage: 'Deliverable 3 verified! High-value customers identified.',
      },
      {
        id: 'day16-hw-4',
        title: 'Deliverable 4 (Hard Problem): Suppliers whose products have never been ordered',
        description: 'Suppliers whose products have never been ordered (find Unity Traders BD via anti-join).',
        instructions: [
          'Select `s.supplier_id`, `s.name` from `suppliers s` LEFT JOIN `products p` ON `s.supplier_id = p.supplier_id` LEFT JOIN `order_items oi` ON `p.product_id = oi.product_id` GROUP BY `s.supplier_id`, `s.name` HAVING `COUNT(oi.order_item_id) = 0`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'suppliers',
        secondaryTables: ['products', 'order_items'],
        initialSql: '-- Deliverable 4: Suppliers whose products have never been ordered\n',
        solutionSql: 'SELECT s.supplier_id, s.name FROM suppliers s LEFT JOIN products p ON s.supplier_id = p.supplier_id LEFT JOIN order_items oi ON p.product_id = oi.product_id GROUP BY s.supplier_id, s.name HAVING COUNT(oi.order_item_id) = 0;',
        solutionExplanation: 'Anti-join identifying suppliers with zero order item records (Unity Traders BD).',
        hints: [{ level: 1, text: 'Use `GROUP BY s.supplier_id, s.name HAVING COUNT(oi.order_item_id) = 0;`' }],
        validation: {
          requireExactResult: true,
          targetTable: 'suppliers',
          requireJoin: true,
          requireGroupBy: true,
          expectedRowCount: 1,
        },
        successMessage: 'Deliverable 4 verified! Unordered supplier Unity Traders BD found.',
      },
    ],
  },
};
