import { ModuleData } from '../../types/curriculum';

// =============================================================================
// DAY 30 - Schema Design & Normalization (id: schema-design-normalization - order 30)
// The dependency chain (why, not memorization):
//   C1 Redundancy (the disease) -> C2 Update anomaly (the symptom) ->
//   C3 1NF (atomic values) -> C4 Functional dependency (the foundation) ->
//   C5 2NF & 3NF (the splits the dependencies justify)
// =============================================================================
export const Day_30_MODULE: ModuleData = {
  id: 'day-30',
  slug: 'schema-design-normalization',
  day: 30,
  title: 'Day 30 - Design Better Schemas: Normalization Fundamentals',
  shortTitle: 'Schema Design & Normal Forms',
  type: 'module',
  milestoneId: 'milestone-3',
  description: 'Design schemas instead of just consuming them. Understand why redundant facts rot data and lead to update anomalies, then fix problems step by step: 1NF atomic values, functional dependencies, and the 2NF/3NF splits they justify.',
  estimatedMinutes: 65,
  completionLearnings: [
    'Identify redundancy and the update anomalies it causes',
    'Check tables for 1NF: atomic values, no repeating groups',
    'Trace functional dependencies before decomposing any table',
    'Justify 2NF and 3NF splits from dependencies, not from checklists',
  ],
  concepts: [
    {
      id: 'norm-redundancy',
      order: 1,
      title: '1. Redundancy: The Same Fact, Stored Twice',
      shortDescription: 'Duplicated facts are duplicated chances to be wrong.',
      theory: {
        summary: 'Redundancy means the same fact lives in more than one place. See it with data you already know: join order_items to products and the product name repeats on every line item that mentions it. In a JOIN that repetition is harmless (computed, not stored). Stored in a real table, every copy is a chance to disagree with the others.',
        introTable: {
          tableName: 'A fat orders table (anti-pattern)',
          description: 'Product facts copied onto every order line.',
          columns: ['order_id', 'product_name', 'product_price', 'quantity'],
          rows: [
            [1, 'Wireless Mouse', 15.99, 2],
            [1, 'Wireless Mouse', 15.99, 1],
            [2, 'Wireless Mouse', 15.99, 5],
            [3, 'Bluetooth Speaker', 45.5, 1],
          ],
        },
        explanation: [
          'Run this against the real database and count the repetition yourself:',
          '```sql\nSELECT p.name, COUNT(*) AS copies\nFROM order_items oi JOIN products p ON oi.product_id = p.product_id\nGROUP BY p.name\nORDER BY copies DESC;\n```',
          'QUESTION_BLOCK::COUNT::If a product appears on 6 line items, how many copies of its name and price does the fat table hold?',
          'QUESTION_BLOCK::SOURCE::Where does the name ACTUALLY live in our seeded schema?',
          'Six copies - one per line item. In our seeded schema the fact lives once, in products, and order_items carries only the reference (product_id). The fat table is what you get when you denormalize for convenience: every fact, everywhere it is needed.',
          'Redundancy is not automatically evil - reporting copies (caches, exports) exist in every real system. The rule: a fact may have exactly ONE authoritative home. Everything else references it.',
        ],
        targetQuery: {
          sql: 'SELECT p.name, COUNT(*) AS copies\nFROM order_items oi JOIN products p ON oi.product_id = p.product_id\nGROUP BY p.name\nORDER BY copies DESC;',
          explanation: 'Counts how many times each product fact would be duplicated in a fat table.',
          badge: "The query we're going to break down",
        },
        syntaxBlocks: [
          {
            title: 'Spotting redundancy with a query',
            sql: 'SELECT fact_col, COUNT(*) AS copies\nFROM joined_view\nGROUP BY fact_col\nHAVING copies > 1;',
            description: 'Any value with copies > 1 is a fact stored (or about to be stored) more than once.',
          },
        ],
        keyTakeaway: 'Redundancy = the same fact in multiple places. One authoritative home per fact; everything else references it.',
        exampleQuery: 'SELECT p.name, COUNT(*) AS copies FROM order_items oi JOIN products p ON oi.product_id = p.product_id GROUP BY p.name ORDER BY copies DESC;',
        exampleQueryExplanation: 'Repetition made measurable - the fat table would store this many copies of each fact.',
        liveDemoSql: 'SELECT p.name, COUNT(*) AS copies FROM order_items oi JOIN products p ON oi.product_id = p.product_id GROUP BY p.name ORDER BY copies DESC LIMIT 5;',
        liveDemoNotes: 'Each row is a fact that a fat table would have copied this many times.',
        mcqs: [
          {
            question: 'Why is repetition inside a JOIN result harmless, but repetition inside a stored table dangerous?',
            options: [
              'A. JOINs are read-only',
              'B. A JOIN computes the repetition fresh from one authoritative copy; a stored table freezes copies that can drift apart',
              'C. JOINs compress data',
              'D. It is equally dangerous in both',
            ],
            correctIndex: 1,
            explanation: 'Computed repetition always agrees with the source. Stored copies can silently disagree - that is drift.',
          },
        ],
        commonMistakes: [
          'Denormalizing for speed before measuring a problem - most premature copies rot before they ever save a query.',
        ],
        masteryPoints: ['Define redundancy precisely', 'Measure repetition in any joined result'],
      },
      tasks: [
        {
          id: 'norm-c1-t1',
          title: 'Task 1 (Guided): Count the duplicates',
          description: 'Query the fat_orders table and see how many times each product name is repeated.',
          instructions: [
            'Run `SELECT product_name, COUNT(*) AS copies FROM fat_orders GROUP BY product_name ORDER BY copies DESC;`',
            'Notice: the same product name stored on every order line — that is redundancy you can measure.',
          ],
          type: 'guided',
          primaryTable: 'fat_orders',
          initialSql: '-- Count how many times each product name is stored\n',
          solutionSql: 'SELECT product_name, COUNT(*) AS copies FROM fat_orders GROUP BY product_name ORDER BY copies DESC;',
          solutionExplanation: 'Each product name repeats on every order line that mentions it — redundancy made visible as a count.',
          hints: [{ level: 1, text: 'GROUP BY product_name, COUNT(*) the rows per name.' }],
          validation: {
          requireExactResult: true, expectedRowCount: 3 },
          successMessage: 'Redundancy measured: the same fact stored many times over.',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'norm-c1-t2',
          title: 'Task 2 (Independent): Redundancy in customers',
          description: 'Find how many times each customer email appears in fat_orders.',
          instructions: [
            'Write a GROUP BY query on fat_orders that counts how many rows each customer_email appears in.',
            'Sort so the most-repeated emails show first.',
          ],
          type: 'independent',
          primaryTable: 'fat_orders',
          initialSql: '-- Find repeated customer emails\n',
          solutionSql: 'SELECT customer_email, COUNT(*) AS copies FROM fat_orders GROUP BY customer_email ORDER BY copies DESC;',
          solutionExplanation: 'Emails repeat on every order — another redundant fact, on every row instead of in one customers table.',
          hints: [{ level: 1, text: 'Same pattern as Task 1, different column.' }],
          validation: {
          requireExactResult: true, expectedRowCount: 3 },
          successMessage: 'Redundancy confirmed in a second column — it is a pattern, not a coincidence.',
          databaseLifecycle: 'fresh',
        },
      ],
    },
    {
      id: 'norm-update-anomaly',
      order: 2,
      title: '2. Update Anomaly: When Copies Disagree',
      shortDescription: 'Redundancy is theoretical until you UPDATE one copy and forget the others.',
      theory: {
        summary: 'If a fact lives in six places, changing it in five leaves the table lying. That silent inconsistency is an update anomaly — the reason redundancy is not just wasteful but dangerous.',
        introTable: {
          tableName: 'After a partial UPDATE',
          description: 'Five rows say "Wireless Mouse", one says the new name.',
          columns: ['order_id', 'product_name', 'quantity'],
          rows: [
            [1, 'Wireless Mouse V2', 2],
            [1, 'Wireless Mouse', 1],
            [2, 'Wireless Mouse', 5],
            [3, 'Wireless Mouse', 1],
            [4, 'Wireless Mouse', 3],
          ],
        },
        explanation: [
          'Someone renamed the product in one row and stopped. Now `SELECT DISTINCT product_name FROM fat_orders` returns two names for one product.',
          'QUESTION_BLOCK::COUNT::How many rows still hold the stale name?',
          'QUESTION_BLOCK::SOURCE::If the product name lived in one `products` table, how many rows would need updating?',
          'Five rows are stale. With one authoritative home, one UPDATE fixes every line item instantly.',
          'Three anomaly flavors, one root cause: update (partial change), insert (can\'t add a product without an order), delete (removing the last order erases the product).',
        ],
        targetQuery: {
          sql: "SELECT product_name, COUNT(*) AS rows_holding FROM fat_orders GROUP BY product_name HAVING product_name LIKE '%Mouse%';",
          explanation: 'Finds the disagreement: two names, unequal counts, one fact.',
          badge: "The query we're going to break down",
        },
        syntaxBlocks: [
          {
            title: 'Detecting a partial update',
            sql: "SELECT fact_col, COUNT(*) AS stale_copies FROM table_name GROUP BY fact_col HAVING COUNT(DISTINCT dependent_col) > 1;",
            description: 'More than one dependent value per fact = a copy drifted from the others.',
          },
        ],
        keyTakeaway: 'Redundancy + partial UPDATE = a table that lies. One authoritative home makes every anomaly structurally impossible.',
        exampleQuery: "SELECT product_name, COUNT(*) AS rows_holding FROM fat_orders GROUP BY product_name HAVING product_name LIKE '%Mouse%';",
        exampleQueryExplanation: 'Two names for one product — the anomaly made visible.',
        liveDemoSql: "SELECT product_name, COUNT(*) AS rows_holding FROM fat_orders GROUP BY product_name HAVING product_name LIKE '%Mouse%';",
        liveDemoNotes: 'The disagreement: one product, two names, unequal counts.',
        mcqs: [
          {
            question: 'A product name is updated in 1 of 6 rows. What is the state of the table?',
            options: ['A. Consistent', 'B. Inconsistent — five rows disagree with the sixth', 'C. The DBMS auto-syncs', 'D. The UPDATE is rejected'],
            correctIndex: 1,
            explanation: 'The DBMS does not know the six copies are the same fact. Five are now stale.',
          },
        ],
        commonMistakes: ['Thinking "I will remember to update all copies" — production tables have too many rows.'],
        masteryPoints: ['Name update/insert/delete anomalies', 'Trace each back to redundancy'],
      },
      tasks: [
        {
          id: 'norm-c2-t1',
          title: 'Task 1 (Guided): Cause an update anomaly',
          description: 'Change a product name on one row and watch the table disagree with itself.',
          instructions: [
            "Run `UPDATE fat_orders SET product_name = 'Gaming Mouse Pro' WHERE order_id = 1;`",
            'Now re-run the GROUP BY from C1 Task 1. The same product now has two different names in the table.',
          ],
          type: 'guided',
          primaryTable: 'fat_orders',
          initialSql: '-- Change the name on one row only\n',
          solutionSql: "UPDATE fat_orders SET product_name = 'Gaming Mouse Pro' WHERE order_id = 1;",
          solutionExplanation: 'One row was updated. The other rows still say the old name. The table is now internally inconsistent.',
          hints: [{ level: 1, text: 'UPDATE with a specific WHERE on order_id.' }],
          validation: { expectedRowCount: 1 },
          successMessage: 'Update anomaly triggered: the table now contradicts itself.',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'norm-c2-t2',
          title: 'Task 2 (Independent): The delete anomaly',
          description: 'Delete one order and watch a product vanish from your reports entirely.',
          instructions: [
            'Note how many distinct product names are in fat_orders right now (`SELECT DISTINCT product_name FROM fat_orders;`).',
            'Delete the only order for one product. Re-count. That product is now gone from your data entirely.',
          ],
          type: 'independent',
          primaryTable: 'fat_orders',
          initialSql: '-- Delete the only order for one product\n',
          solutionSql: 'SELECT DISTINCT product_name FROM fat_orders;',
          solutionExplanation: 'When the last order for a product is deleted, the product itself disappears from reports — even though it still exists in the catalog.',
          hints: [{ level: 1, text: 'COUNT the distinct names before and after a DELETE.' }],
          validation: {
          requireExactResult: true, expectedRowCount: 3 },
          successMessage: 'Delete anomaly confirmed: removing an order removed a product from sight.',
          databaseLifecycle: 'fresh',
        },
      ],
    },
    {
      id: 'norm-1nf',
      order: 3,
      title: '3. First Normal Form: Atomic Values Only',
      shortDescription: 'Each cell holds one value. Repeating groups are the first thing to split out.',
      theory: {
        summary: 'A table is in 1NF when every cell holds a single, atomic value — no lists, no repeating groups, no "phone1/phone2/phone3" columns.',
        introTable: {
          tableName: 'A table that violates 1NF',
          description: 'Lists inside cells, numbered phone columns — both un-atomic.',
          columns: ['student_id', 'name', 'phones', 'courses'],
          rows: [
            [1, 'Rahim', '01711111111,01711111122', 'Math,Physics'],
            [2, 'Karim', '01722222221', 'Biology'],
          ],
        },
        explanation: [
          'The phones cell holds a list. The courses cell holds a list. You cannot filter reliably on items inside a comma-separated string.',
          'QUESTION_BLOCK::COUNT::How many courses does Rahim take?',
          'QUESTION_BLOCK::SOURCE::Why does a simple equality test miss Rahim even though he takes Physics?',
          'The cell holds the string Math,Physics. A simple equality test fails because the DBMS compares whole strings. The fix: one row per (student, course) pair.',
        ],
        targetQuery: {
          sql: 'SELECT student_id, name, COUNT(*) AS course_count FROM students GROUP BY student_id, name;',
          explanation: 'After normalizing to (student, course) pairs, COUNT works naturally.',
          badge: "The query we're going to break down",
        },
        syntaxBlocks: [
          {
            title: 'A normalized junction table',
            sql: 'CREATE TABLE student_courses (\n  student_id INT,\n  course_name VARCHAR(50),\n  PRIMARY KEY (student_id, course_name)\n);',
            description: 'One row per (student, course). Now COUNT, WHERE, and JOIN all behave.',
          },
        ],
        keyTakeaway: '1NF = atomic cells only. Lists in cells break filtering, counting, and joining. Split them into their own table.',
        exampleQuery: 'SELECT student_id, name, COUNT(*) AS course_count FROM students GROUP BY student_id, name;',
        exampleQueryExplanation: 'Atomic rows make aggregation natural.',
        liveDemoSql: 'SELECT student_id, name, COUNT(*) AS course_count FROM students GROUP BY student_id, name;',
        liveDemoNotes: 'Each row is one atomic fact. COUNT just works.',
        mcqs: [
          {
            question: "A table stores tags as 'sql,python,js' in one cell. Which is true?",
            options: [
              'A. It is in 1NF — the cell holds a valid string',
              'B. It violates 1NF — the cell holds a list, not an atomic value',
              'C. It violates 2NF, not 1NF',
              'D. 1NF only applies to numeric columns',
            ],
            correctIndex: 1,
            explanation: '1NF requires atomic (single) values. A comma-separated list is multiple values in one cell.',
          },
        ],
        commonMistakes: [
          'Storing numbered columns (phone1, phone2, phone3) — still a repeating group, still violates 1NF.',
        ],
        masteryPoints: ['Detect a 1NF violation', 'Split a list into its own junction table'],
      },
      tasks: [
        {
          id: 'norm-c3-t1',
          title: 'Task 1 (Guided): Atomic cells make equality reliable',
          description: 'Prove that WHERE works because cells hold single values.',
          instructions: [
            "Run `SELECT name, department FROM students WHERE department = 'CSE';`",
            'Every CSE student comes back. Now imagine the department cell held CSE,EEE for a double-major: the equality test would silently miss them.',
          ],
          type: 'guided',
          primaryTable: 'students',
          initialSql: "-- Equality works because cells are atomic\n",
          solutionSql: "SELECT name, department FROM students WHERE department = 'CSE';",
          solutionExplanation: "WHERE department = 'CSE' compares whole values. It only works because each cell holds exactly one department.",
          hints: [{ level: 1, text: "Filter students with WHERE department = 'CSE'." }],
          validation: {
          requireExactResult: true, expectedRowCount: 3 },
          successMessage: 'Equality is trustworthy only when cells are atomic - that is 1NF paying you back.',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'norm-c3-t2',
          title: 'Task 2 (Independent): Atomic rows make counting natural',
          description: 'Aggregate per department - impossible while values hide inside comma-strings.',
          instructions: [
            'Write a GROUP BY query that counts students per department.',
            'Sort so the largest department shows first. Try to picture doing this if departments lived in one comma-separated cell.',
          ],
          type: 'independent',
          primaryTable: 'students',
          initialSql: "-- COUNT per department\n",
          solutionSql: 'SELECT department, COUNT(*) AS student_count FROM students GROUP BY department ORDER BY student_count DESC;',
          solutionExplanation: 'One row per (student, department) fact makes COUNT a one-liner. Against a comma-string cell this query is simply impossible.',
          hints: [{ level: 1, text: 'GROUP BY department, COUNT(*) the rows, ORDER BY the count.' }],
          validation: {
          requireExactResult: true, expectedRowCount: 3 },
          successMessage: '1NF is not bureaucracy - it is what makes the queries you already know possible.',
          databaseLifecycle: 'fresh',
        },
      ],
    },
    {
      id: 'norm-functional-dependency',
      order: 4,
      title: '4. Functional Dependency: What Determines What',
      shortDescription: 'Before splitting any table, trace which columns depend on which keys.',
      theory: {
        summary: 'A functional dependency X → Y means: knowing X tells you Y. It is the foundation that makes 2NF and 3NF derivable instead of memorizable.',
        introTable: {
          tableName: 'A combined order_items + products table',
          description: 'Which columns depend on the full key, and which depend on only part of it?',
          columns: ['order_id', 'product_id', 'product_name', 'product_price', 'quantity'],
          rows: [
            [1, 101, 'Wireless Mouse', 15.99, 2],
            [1, 102, 'Bluetooth Speaker', 45.5, 1],
            [2, 101, 'Wireless Mouse', 15.99, 5],
          ],
        },
        explanation: [
          'The primary key here is (order_id, product_id). quantity depends on the full key: you need both to know how many of product 101 were in order 1.',
          'But product_name depends only on product_id. Knowing order_id tells you nothing about the name. That partial dependency is the 2NF violation.',
          'QUESTION_BLOCK::SOURCE::What does product_name depend on — the full key or just product_id?',
          'QUESTION_BLOCK::COUNT::If you change the name of product 101, how many rows must you update in this combined table?',
          'product_name depends only on product_id. Changing its name requires updating every line item that mentions it — the update anomaly, now traced to a partial dependency.',
        ],
        targetQuery: {
          sql: 'SELECT product_id, product_name FROM combined_items GROUP BY product_id, product_name;',
          explanation: 'product_name is determined by product_id alone — the same name repeats for every order.',
          badge: "The query we're going to break down",
        },
        syntaxBlocks: [
          {
            title: 'Tracing a dependency',
            sql: 'PRIMARY KEY (order_id, product_id)\n  -> quantity  (depends on full key: OK)\n  -> product_name (depends on product_id only: PARTIAL)',
            description: 'A partial dependency on a composite key = the 2NF trigger.',
          },
        ],
        keyTakeaway: 'X → Y means "X determines Y." Partial dependencies are what 2NF removes.',
        exampleQuery: 'SELECT product_id, product_name FROM combined_items GROUP BY product_id, product_name;',
        exampleQueryExplanation: 'product_name is functionally dependent on product_id alone.',
        liveDemoSql: 'SELECT product_id, product_name FROM combined_items GROUP BY product_id, product_name;',
        liveDemoNotes: 'One name per product_id — the dependency that justifies the split.',
        mcqs: [
          {
            question: 'In a table with PK (student_id, course_id), which column has a partial dependency?',
            options: [
              'A. grade (depends on both student and course)',
              'B. student_name (depends only on student_id)',
              'C. enrollment_date (depends on both)',
              'D. All depend on the full key',
            ],
            correctIndex: 1,
            explanation: 'student_name is determined by student_id alone — a partial dependency on the composite key.',
          },
        ],
        commonMistakes: [
          'Memorizing "2NF = no partial dependencies" without understanding what a dependency IS.',
        ],
        masteryPoints: ['Read X → Y notation', 'Spot a partial dependency on a composite key'],
      },
      tasks: [
        {
          id: 'norm-c4-t1',
          title: 'Task 1 (Guided): See a functional dependency',
          description: 'combined_items has composite key (order_id, product_id). Watch product_name follow product_id, not the key.',
          instructions: [
            'Run `SELECT product_id, product_name FROM combined_items GROUP BY product_id, product_name;`',
            'Exactly one name per product_id - that IS the dependency product_id -> product_name, made visible.',
          ],
          type: 'guided',
          primaryTable: 'combined_items',
          secondaryTables: ['products'],
          initialSql: "-- One row per product: the dependency made visible\n",
          solutionSql: 'SELECT product_id, product_name FROM combined_items GROUP BY product_id, product_name;',
          solutionExplanation: 'GROUP BY product_id collapses to one row per product. Whatever survives with it depends on it: product_name.',
          hints: [{ level: 1, text: 'GROUP BY the two columns; the collapse shows what determines what.' }],
          validation: {
          requireExactResult: true, expectedRowCount: 2 },
          successMessage: 'Two products, two rows - product_name depends on product_id alone.',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'norm-c4-t2',
          title: 'Task 2 (Independent): Measure the partial dependency',
          description: 'Count how many rows hold each copied product fact - the update cost of the partial dependency.',
          instructions: [
            'Write a GROUP BY on combined_items that counts how many rows each product_name appears in.',
            'Sort so the most-copied fact shows first. That count is how many rows an UPDATE would have to touch.',
          ],
          type: 'independent',
          primaryTable: 'combined_items',
          initialSql: "-- How many rows hold each copy of the fact?\n",
          solutionSql: 'SELECT product_name, COUNT(*) AS rows_holding FROM combined_items GROUP BY product_name ORDER BY rows_holding DESC;',
          solutionExplanation: "Product 101 appears on 2 rows - renaming it means 2 UPDATEs. The fact belongs in products, where it is stored once.",
          hints: [{ level: 1, text: 'Same shape as the C1 tasks, but on combined_items.' }],
          validation: {
          requireExactResult: true, expectedRowCount: 2 },
          successMessage: 'A partial dependency is not abstract: it is a row count you just measured.',
          databaseLifecycle: 'fresh',
        },
      ],
    },
    {
      id: 'norm-2nf-3nf',
      order: 5,
      title: '5. Second & Third Normal Form: The Splits Dependencies Justify',
      shortDescription: '2NF removes partial dependencies. 3NF removes transitive ones. Both are derived, not memorized.',
      theory: {
        summary: '2NF: a table with a composite key must have every non-key column depend on the WHOLE key. 3NF: no non-key column may depend on ANOTHER non-key column (a transitive dependency). Both rules follow directly from the functional dependencies you traced in concept 4.',
        introTable: {
          tableName: 'A table with a transitive dependency',
          description: 'order_id → customer_id → customer_city. city depends on order only through customer.',
          columns: ['order_id', 'customer_id', 'customer_name', 'customer_city'],
          rows: [
            [1, 10, 'Rahim', 'Dhaka'],
            [2, 10, 'Rahim', 'Dhaka'],
            [3, 11, 'Karim', 'Chattogram'],
          ],
        },
        explanation: [
          'order_id → customer_id is a direct dependency. customer_id → customer_city is also direct. But order_id → customer_city is TRANSITIVE — city reaches the order only by way of customer.',
          'Why it matters: every order Rahim places repeats Dhaka. If Rahim moves, you must update every order row — the update anomaly, now traced to a transitive dependency.',
          'QUESTION_BLOCK::COUNT::If Rahim moves to Rajshahi, how many rows change in this combined table?',
          'QUESTION_BLOCK::SOURCE::After splitting into orders(customer_id) and customers(customer_id, city), how many rows change?',
          'Every order row Rahim has. After the split: one row in customers. The transitive dependency is gone, and so is the anomaly.',
        ],
        targetQuery: {
          sql: 'SELECT customer_id, customer_name, customer_city FROM combined_orders GROUP BY customer_id, customer_name, customer_city;',
          explanation: 'Name and city depend on customer_id, not on order_id — the transitive chain.',
          badge: "The query we're going to break down",
        },
        syntaxBlocks: [
          {
            title: 'The 3NF split',
            sql: 'CREATE TABLE customers (\n  customer_id INT PRIMARY KEY,\n  customer_name VARCHAR(100),\n  customer_city VARCHAR(50)\n);\nCREATE TABLE orders (\n  order_id INT PRIMARY KEY,\n  customer_id INT REFERENCES customers(customer_id)\n);',
            description: 'Now customer_city lives once, in customers. One UPDATE, not one per order.',
          },
        ],
        keyTakeaway: '2NF removes partial dependencies. 3NF removes transitive ones. Both follow from tracing what determines what.',
        exampleQuery: 'SELECT customer_id, customer_name, customer_city FROM combined_orders GROUP BY customer_id, customer_name, customer_city;',
        exampleQueryExplanation: 'The transitive chain order_id → customer_id → city, made visible as a GROUP BY.',
        liveDemoSql: 'SELECT customer_id, customer_name, customer_city FROM combined_orders GROUP BY customer_id, customer_name, customer_city;',
        liveDemoNotes: 'Name and city belong to the customer, not the order — the split 3NF prescribes.',
        mcqs: [
          {
            question: 'A table has order_id → customer_id → customer_city. Which normal form does it violate?',
            options: [
              'A. 1NF',
              'B. 2NF (partial dependency)',
              'C. 3NF (transitive dependency)',
              'D. It is fully normalized',
            ],
            correctIndex: 2,
            explanation: 'order_id → customer_city is transitive (via customer_id). That is the 3NF violation.',
          },
        ],
        commonMistakes: [
          'Thinking "normaler is always better" — real systems denormalize deliberately for read performance, but only after understanding what they are trading.',
        ],
        masteryPoints: ['Distinguish partial from transitive dependencies', 'Derive 2NF/3NF splits from dependencies'],
      },
      tasks: [
        {
          id: 'norm-c5-t1',
          title: 'Task 1 (Guided): See the transitive chain',
          description: 'In combined_orders, city rides with the customer - not with the order.',
          instructions: [
            'Run `SELECT customer_id, customer_name, customer_city, COUNT(*) AS orders FROM combined_orders GROUP BY customer_id, customer_name, customer_city;`',
            'One row per customer. order_id determines customer_id, customer_id determines city - so order_id reaches city only THROUGH the customer. That is transitivity.',
          ],
          type: 'guided',
          primaryTable: 'combined_orders',
          secondaryTables: ['customers'],
          initialSql: "-- One row per customer: the transitive chain made visible\n",
          solutionSql: 'SELECT customer_id, customer_name, customer_city, COUNT(*) AS orders FROM combined_orders GROUP BY customer_id, customer_name, customer_city;',
          solutionExplanation: 'The collapse proves order_id -> customer_id -> customer_city. The chain is why 3NF splits customers out of orders.',
          hints: [{ level: 1, text: 'GROUP BY all three customer columns; COUNT(*) shows how many orders each owns.' }],
          validation: {
          requireExactResult: true, expectedRowCount: 2 },
          successMessage: 'City follows the customer, never the order - the transitive dependency, visible in two rows.',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'norm-c5-t2',
          title: 'Task 2 (Independent): Price the transitive dependency',
          description: 'Rahim moves to Rajshahi. Count the rows that must change - before and after the 3NF split.',
          instructions: [
            'Write a query that counts how many combined_orders rows belong to Rahim (customer_name = Rahim).',
            'That count is his update cost in the combined table. After the 3NF split, the same fact lives once in customers: cost 1, always.',
          ],
          type: 'independent',
          primaryTable: 'combined_orders',
          initialSql: "-- How many rows must change when Rahim moves?\n",
          solutionSql: "SELECT customer_city, COUNT(*) AS rows_to_update FROM combined_orders WHERE customer_name = 'Rahim' GROUP BY customer_city;",
          solutionExplanation: 'Rahim holds 2 rows here. In the 3NF design his city sits in exactly one customers row - the anomaly is designed out.',
          hints: [{ level: 1, text: "WHERE customer_name = 'Rahim', then COUNT(*) the rows." }],
          validation: {
          requireExactResult: true, expectedRowCount: 1 },
          successMessage: '2 rows today, 1 row after 3NF - the split is justified by arithmetic, not by a checklist.',
          databaseLifecycle: 'fresh',
        },
      ],
    },
  ],
  challenge: {
    id: 'norm-homework',
    title: 'Day 30 - Design Challenge (Ending Activity)',
    scenario:
      'You measured the redundancy, caused the anomalies, and traced the dependencies. Now design the cure: build the normalized schema that fat_orders should have been, with every fact stored exactly once and every rule enforced by the database itself.',
    databaseLifecycle: 'fresh',
    tasks: [
      {
        id: 'norm-hw-1',
        title: 'Task 1: Create the customers lookup table',
        description: 'The customer facts that repeat on every fat_orders line get exactly one home.',
        instructions: [
          'Write `CREATE TABLE clean_customers (customer_email VARCHAR(100) PRIMARY KEY, customer_name VARCHAR(100) NOT NULL);`',
          'The email identifies the customer - it becomes the primary key, and the name is stored once beside it.',
        ],
        type: 'challenge',
        primaryTable: 'clean_customers',
        secondaryTables: ['fat_orders'],
        initialSql: '-- One home for every customer fact\n',
        solutionSql: 'CREATE TABLE clean_customers (customer_email VARCHAR(100) PRIMARY KEY, customer_name VARCHAR(100) NOT NULL);',
        solutionExplanation: 'customer_email was the redundant copy key in fat_orders; here it is the identity. NOT NULL protects the name.',
        hints: [{ level: 1, text: 'Email as PRIMARY KEY, name NOT NULL - two columns, one fact each.' }],
        validation: { targetTable: 'clean_customers', expectedRowCount: 1 },
        successMessage: 'Customer facts now live in exactly one place.',
      },
      {
        id: 'norm-hw-2',
        title: 'Task 2: Create the products lookup table with a CHECK',
        description: 'Product facts get their single home - plus a business rule the schema enforces.',
        instructions: [
          'Write `CREATE TABLE clean_products (product_name VARCHAR(100) PRIMARY KEY, product_price DECIMAL(8,2) NOT NULL CHECK (product_price >= 0));`',
          'A price can never go negative again - no matter which application writes it.',
        ],
        type: 'challenge',
        primaryTable: 'clean_products',
        secondaryTables: ['fat_orders'],
        initialSql: '-- One home for every product fact, with a rule\n',
        solutionSql: 'CREATE TABLE clean_products (product_name VARCHAR(100) PRIMARY KEY, product_price DECIMAL(8,2) NOT NULL CHECK (product_price >= 0));',
        solutionExplanation: 'The 3NF split plus a CHECK: the name is unique by key, the price is guarded by constraint. Day 27 constraints doing real design work.',
        hints: [{ level: 1, text: 'Product name as PRIMARY KEY; price with NOT NULL and CHECK (product_price >= 0).' }],
        validation: { targetTable: 'clean_products', expectedRowCount: 1 },
        successMessage: 'Product facts stored once - and the schema now rejects bad prices on its own.',
      },
      {
        id: 'norm-hw-3',
        title: 'Task 3: Create the orders fact table with enforced relationships',
        description: 'The line items reference their customer and product instead of copying them.',
        instructions: [
          'Write `CREATE TABLE clean_orders (order_id INT PRIMARY KEY, customer_email VARCHAR(100) NOT NULL, product_name VARCHAR(100) NOT NULL, quantity INT NOT NULL, FOREIGN KEY (customer_email) REFERENCES clean_customers(customer_email), FOREIGN KEY (product_name) REFERENCES clean_products(product_name));`',
          'Two FOREIGN KEY lines replace every copied column. Orphaned references are now impossible.',
        ],
        type: 'challenge',
        primaryTable: 'clean_orders',
        secondaryTables: ['fat_orders'],
        initialSql: '-- References instead of copies\n',
        solutionSql: 'CREATE TABLE clean_orders (order_id INT PRIMARY KEY, customer_email VARCHAR(100) NOT NULL, product_name VARCHAR(100) NOT NULL, quantity INT NOT NULL, FOREIGN KEY (customer_email) REFERENCES clean_customers(customer_email), FOREIGN KEY (product_name) REFERENCES clean_products(product_name));',
        solutionExplanation: 'This is fat_orders redesigned: keys and quantity stay, copied facts become enforced references. Update, insert, and delete anomalies are all designed out.',
        hints: [{ level: 1, text: 'One FOREIGN KEY (...) REFERENCES ...(...) line per relationship, after the columns.' }],
        validation: { targetTable: 'clean_orders', expectedRowCount: 1 },
        successMessage: 'The normalized schema is complete: every fact stored once, every relationship enforced. Compare it to fat_orders - that is design.',
      },
    ],
  },
};