import { ModuleData } from '../../types/curriculum';

// =============================================================================
// DAY 10 — CASE & Conditional Logic  (id: case-conditional-logic · order 10)
// Inserts after Day 9 (Aggregation & Grouping). Atomic chain:
//   C1 Basic CASE → C2 Multi-branch → C3 Evaluation order →
//   C4 CASE in aggregates → C5 CASE in ORDER BY
// =============================================================================
export const Day_10_MODULE: ModuleData = {
  id: 'case-conditional-logic',
  slug: 'case-conditional-logic',
  day: 0, // legacy positional field — ordering uses curriculumOrder (Day 10)
  title: 'Day 10 — Conditional Logic with CASE',
  shortTitle: 'Conditional Logic with CASE',
  type: 'module',
  milestoneId: 'milestone-2',
  description: 'Compute custom output columns on the fly: turn raw inventory numbers into \'In Stock\' / \'Out of Stock\' labels, build multi-branch priority tiers, and count specific conditions. CASE is how SQL asks "IF this condition, THEN show this label, ELSE show something else."',
  estimatedMinutes: 60,
  completionLearnings: [
    'Write CASE expressions inside SELECT to produce computed columns',
    'Build multi-branch tiers: use multiple WHEN conditions in a single CASE',
    'Understand evaluation order: SQL tests each WHEN top-to-bottom and stops at the first TRUE',
    'Use CASE inside aggregate functions (SUM, COUNT) to answer complex questions conditionally',
    'Sort and prioritize by computed CASE output, not stored data',
  ],
  concepts: [
    {
      id: 'case-basic',
      order: 1,
      title: '1. Create Computed Columns with CASE',
      shortDescription: 'Turn row conditions into output labels — "If quantity = 0, show \'Out of Stock\', otherwise \'Available\'".',
      theory: {
        summary: 'The marketing team wants products labeled \'Out of Stock\' or \'Available\' — but no such column exists. Labels are not stored data; they are computed. CASE is SQL\'s way of producing a different output value depending on each row\'s condition.',
        introTable: {
          tableName: 'products',
          description: 'A few rows of the products table (28 products total)',
          columns: ['product_id', 'name', 'price', 'quantity_in_stock'],
          rows: [
            [1, 'Wireless Mouse', 15.99, 40],
            [3, 'USB-C Charging Cable', 9.99, 0],
            [8, 'Electric Kettle', 34.99, 2],
          ],
        },
        explanation: [
          'A CASE expression is written **inside the SELECT list**, where a column name would go. For every row SQL evaluates the WHEN condition: TRUE → the THEN value becomes that row\'s output; otherwise the ELSE value is used.',
          '```sql\nSELECT name,\n       CASE\n         WHEN quantity_in_stock = 0 THEN \'Out of Stock\'\n         ELSE \'Available\'\n       END AS stock_status\nFROM products;\n```',
          'QUESTION_BLOCK::WHEN::What condition does this row meet?\nQUESTION_BLOCK::THEN::What value if TRUE?\nQUESTION_BLOCK::ELSE::What value if nothing matches?',
          'The computed column exists only in the **result** — the table is never changed. Always name it with **AS**.',
        ],
        targetQuery: {
          sql: "SELECT name, quantity_in_stock,\n       CASE\n         WHEN quantity_in_stock = 0 THEN 'Out of Stock'\n         ELSE 'Available'\n       END AS stock_status\nFROM products;",
          explanation: 'For each product, output a status label computed from its stock quantity.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: SQL visits each row and tests the WHEN condition',
            sqlSnippet: "WHEN quantity_in_stock = 0 THEN 'Out of Stock'",
            explanation: 'Row-by-row, exactly like WHERE. Wireless Mouse has 40 units → FALSE. USB-C Cable has 0 → TRUE.',
            tableData: {
              tableName: 'Condition check',
              columns: ['name', 'quantity_in_stock', 'quantity_in_stock = 0'],
              rows: [
                ['Wireless Mouse', 40, 'FALSE'],
                ['USB-C Charging Cable', 0, 'TRUE'],
                ['Electric Kettle', 2, 'FALSE'],
              ],
              highlightedRows: [1],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: TRUE → THEN value, FALSE → ELSE value',
            sqlSnippet: "…THEN 'Out of Stock' ELSE 'Available' END AS stock_status",
            explanation: 'The matching value becomes the new stock_status column for that row.',
            tableData: {
              tableName: 'Result',
              columns: ['name', 'quantity_in_stock', 'stock_status'],
              highlightedColumns: ['stock_status'],
              rows: [
                ['Wireless Mouse', 40, 'Available'],
                ['USB-C Charging Cable', 0, 'Out of Stock'],
                ['Electric Kettle', 2, 'Available'],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'CASE syntax',
            sql: "SELECT col,\n       CASE\n         WHEN condition THEN value_if_true\n         ELSE value_otherwise\n       END AS computed_column\nFROM table_name;",
            description: 'CASE lives in the SELECT list; AS names the computed column.',
          },
        ],
        keyTakeaway: 'CASE is a row-by-row value transformer inside SELECT: WHEN a condition is TRUE, output the THEN value; otherwise output ELSE. Always name it with AS.',
        exampleQuery: "SELECT name, CASE WHEN quantity_in_stock = 0 THEN 'Out of Stock' ELSE 'Available' END AS stock_status FROM products;",
        exampleQueryExplanation: 'Every product gets a stock_status label computed from its quantity_in_stock.',
        liveDemoSql: "SELECT name, quantity_in_stock, CASE WHEN quantity_in_stock = 0 THEN 'Out of Stock' ELSE 'Available' END AS stock_status FROM products LIMIT 6;",
        liveDemoNotes: 'Notice the computed stock_status column: the table itself is unchanged.',
        mcqs: [
          {
            question: 'Where in a query does a CASE expression live?',
            options: [
              'A. Only in the WHERE clause',
              'B. In the SELECT list, where a column name would go',
              'C. Only after ORDER BY',
              'D. In a separate query',
            ],
            correctIndex: 1,
            explanation: 'CASE produces an output value per row, so it lives in the SELECT list — and needs an AS alias.',
          },
          {
            question: 'Recall from Day 2: what must text values (like \'Out of Stock\') be wrapped in?',
            options: ['A. Double quotes', 'B. Backticks', 'C. Single quotes', 'D. Nothing — bare words work'],
            correctIndex: 2,
            explanation: 'String literals always use single quotes — including CASE THEN values.',
          },
        ],
        commonMistakes: [
          'Forgetting the AS alias — the computed column appears unnamed.',
          'Trying to put CASE in WHERE to "make a label" — CASE produces output; WHERE filters rows.',
        ],
        masteryPoints: ['Write a two-branch CASE with ELSE', 'Alias computed columns with AS'],
      },
      tasks: [
        {
          id: 'case-basic-t1',
          title: 'Task 1 (Guided): Label every product\'s stock status',
          description: 'Produce a stock_status column: \'Out of Stock\' for products with 0 units, \'Available\' for everything else.',
          instructions: [
            'Select `name`, `quantity_in_stock`, then a CASE: WHEN `quantity_in_stock = 0` THEN `\'Out of Stock\'`, ELSE `\'Available\'`.',
            'Alias it AS `stock_status`; end with a semicolon.',
          ],
          type: 'guided',
          primaryTable: 'products',
          initialSql: '-- Label each product as In/Out of stock\n',
          solutionSql: "SELECT name, quantity_in_stock, CASE WHEN quantity_in_stock = 0 THEN 'Out of Stock' ELSE 'Available' END AS stock_status FROM products;",
          solutionExplanation: 'CASE tests each row\'s quantity_in_stock: 0 → Out of Stock, everything else → Available.',
          hints: [
            { level: 1, text: "The CASE goes in the SELECT list: CASE WHEN quantity_in_stock = 0 THEN 'Out of Stock' ELSE 'Available' END AS stock_status" },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'products',
            requiredColumns: ['name', 'quantity_in_stock', 'stock_status'],
            requireCase: true,
            expectedRowCount: 28,
          },
          successMessage: 'First CASE expression! Every product now carries a computed status label.',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'case-basic-t2',
          title: 'Task 2 (Independent): Flag customers with missing emails',
          description: 'Newsletter audit: produce email_status = \'Missing\' when email is NULL, \'OK\' otherwise. (Recall Day 3: NULL needs IS NULL.)',
          instructions: [
            'Select `name`, `email`, then CASE WHEN `email IS NULL` THEN `\'Missing\'` ELSE `\'OK\'` END AS `email_status`.',
            'End with a semicolon.',
          ],
          type: 'independent',
          primaryTable: 'customers',
          initialSql: '-- Customer contact audit\n',
          solutionSql: "SELECT name, email, CASE WHEN email IS NULL THEN 'Missing' ELSE 'OK' END AS email_status FROM customers;",
          solutionExplanation: 'IS NULL is the correct NULL test inside CASE — Tanvir and Shakil show Missing.',
          hints: [
            { level: 1, text: 'Use `email IS NULL` inside WHEN — never `email = NULL`. Alias AS email_status.' },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'customers',
            requiredColumns: ['name', 'email', 'email_status'],
            requireCase: true,
            expectedRowCount: 15,
          },
          successMessage: 'Exactly right — you recycled the IS NULL test from Day 3 without being retaught it.',
          databaseLifecycle: 'fresh',
        },
      ],
    },
    {
      id: 'case-multi-branch',
      order: 2,
      title: '2. Build Multi-Branch Tiers with Stacked WHEN',
      shortDescription: 'Chain multiple WHEN conditions to classify rows into tiers (Budget / Standard / Premium).',
      theory: {
        summary: 'Two labels are rarely enough. Finance wants every product classified as Budget, Standard, or Premium by price. One WHEN per tier — chained top to bottom — turns a raw number column into a tier system.',
        introTable: {
          tableName: 'products',
          description: 'Prices from the products table (28 products: 17 under $25, 10 from $25–$99.99, 1 at $100+)',
          columns: ['name', 'price'],
          rows: [
            ['Sticky Notes Pack', 4.99],
            ['Laptop Stand', 28.75],
            ['Office Chair', 120.00],
          ],
        },
        explanation: [
          'Multiple WHEN clauses are checked top to bottom; the first TRUE one wins and SQL skips the rest.',
          '```sql\nCASE\n  WHEN price < 25 THEN \'Budget\'\n  WHEN price < 100 THEN \'Standard\'\n  ELSE \'Premium\'\nEND AS price_tier\n```',
          'Notice the second WHEN needs no lower bound: if a row reaches it, price is already ≥ 25. The ELSE catches everything left.',
        ],
        targetQuery: {
          sql: "SELECT name, price,\n       CASE\n         WHEN price < 25 THEN 'Budget'\n         WHEN price < 100 THEN 'Standard'\n         ELSE 'Premium'\n       END AS price_tier\nFROM products;",
          explanation: 'Classify all 28 products into three price tiers.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: WHEN branches checked top to bottom',
            sqlSnippet: "WHEN price < 25 THEN 'Budget' … WHEN price < 100 THEN 'Standard'",
            explanation: 'Sticky Notes (4.99) → first WHEN TRUE → Budget, done. Laptop Stand (28.75) → first FALSE, second TRUE → Standard.',
            tableData: {
              tableName: 'Branch walk',
              columns: ['name', 'price', 'WHEN price < 25', 'WHEN price < 100', 'result'],
              rows: [
                ['Sticky Notes Pack', 4.99, 'TRUE', '—', 'Budget'],
                ['Laptop Stand', 28.75, 'FALSE', 'TRUE', 'Standard'],
                ['Office Chair', 120.00, 'FALSE', 'FALSE', 'Premium (ELSE)'],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: The full result — 17 Budget, 10 Standard, 1 Premium',
            sqlSnippet: '…END AS price_tier FROM products;',
            explanation: 'Run it: 17 products land in Budget, 10 in Standard, and only the $120 Office Chair reaches ELSE → Premium.',
            tableData: {
              tableName: 'Tier distribution',
              columns: ['price_tier', 'products'],
              highlightedColumns: ['products'],
              rows: [
                ['Budget (< $25)', 17],
                ['Standard ($25–$99.99)', 10],
                ['Premium (≥ $100)', 1],
              ],
            },
          },
        ],
        keyTakeaway: 'Chain WHEN clauses top to bottom — first TRUE wins. Later WHENs can rely on earlier ones already failing, so they only need the remaining bound.',
        exampleQuery: "SELECT name, price, CASE WHEN price < 25 THEN 'Budget' WHEN price < 100 THEN 'Standard' ELSE 'Premium' END AS price_tier FROM products;",
        exampleQueryExplanation: 'Three-tier classification of the full catalog.',
        liveDemoSql: "SELECT name, price, CASE WHEN price < 25 THEN 'Budget' WHEN price < 100 THEN 'Standard' ELSE 'Premium' END AS price_tier FROM products ORDER BY price DESC LIMIT 6;",
        liveDemoNotes: 'Sorted by price descending — watch Premium appear above 100 and Budget under 25.',
        mcqs: [
          {
            question: 'In a multi-branch CASE, how many THEN values does one row receive?',
            options: [
              'A. All matching branches, stacked',
              'B. Exactly one — the first TRUE branch',
              'C. The last TRUE branch',
              'D. All of them averaged',
            ],
            correctIndex: 1,
            explanation: 'Branches are evaluated top to bottom; the first TRUE wins and the rest are skipped.',
          },
        ],
        masteryPoints: ['Chain 3+ WHEN branches', 'Rely on earlier branches failing to simplify later bounds'],
      },
      tasks: [
        {
          id: 'case-multi-t1',
          title: 'Task 1 (Guided): Build the price tier system',
          description: 'Classify products: < 25 → \'Budget\', < 100 → \'Standard\', otherwise \'Premium\'.',
          instructions: [
            'Select `name`, `price`, and a three-branch CASE AS `price_tier`.',
            'Order matters: cheapest bound first. End with a semicolon.',
          ],
          type: 'guided',
          primaryTable: 'products',
          initialSql: '-- Price tiers\n',
          solutionSql: "SELECT name, price, CASE WHEN price < 25 THEN 'Budget' WHEN price < 100 THEN 'Standard' ELSE 'Premium' END AS price_tier FROM products;",
          solutionExplanation: '17 Budget, 10 Standard, 1 Premium across the 28-product catalog.',
          hints: [
            { level: 1, text: "WHEN price < 25 THEN 'Budget', then WHEN price < 100 THEN 'Standard', then ELSE 'Premium'." },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'products',
            requiredColumns: ['name', 'price', 'price_tier'],
            requireCase: true,
            expectedRowCount: 28,
          },
          successMessage: 'Tier system built — 17 / 10 / 1 across Budget, Standard, Premium.',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'case-multi-t2',
          title: 'Task 2 (Independent): Stock health labels',
          description: 'Ops wants stock health: quantity_in_stock = 0 → \'Zero\', < 10 → \'Low\', otherwise \'Healthy\'. Same shape, different column and domain.',
          instructions: [
            'Select `name`, `quantity_in_stock`, and a three-branch CASE AS `stock_health`.',
            'Mind the order of the bounds. End with a semicolon.',
          ],
          type: 'independent',
          primaryTable: 'products',
          initialSql: '-- Stock health report\n',
          solutionSql: "SELECT name, quantity_in_stock, CASE WHEN quantity_in_stock = 0 THEN 'Zero' WHEN quantity_in_stock < 10 THEN 'Low' ELSE 'Healthy' END AS stock_health FROM products;",
          solutionExplanation: '3 Zero, 9 Low, 16 Healthy — equality first, then the range bound, ELSE last.',
          hints: [
            { level: 1, text: "First WHEN tests = 0 (equality), second tests < 10, ELSE catches 'Healthy'." },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'products',
            requiredColumns: ['name', 'quantity_in_stock', 'stock_health'],
            requireCase: true,
            expectedRowCount: 28,
          },
          successMessage: 'Transfer complete — same pattern, new domain, no hints needed.',
          databaseLifecycle: 'fresh',
        },
      ],
    },
    {
      id: 'case-evaluation-order',
      order: 3,
      title: '3. CASE Evaluation Order: First Match Wins',
      shortDescription: 'Why branch order can silently make branches unreachable.',
      theory: {
        summary: 'A tier query was reordered and suddenly nobody is \'Budget\' anymore. Branch order is not cosmetic — CASE stops at the first TRUE WHEN, so a greedy branch placed first can make every later branch unreachable. This is the bug class you must see once to never forget.',
        introTable: {
          tableName: 'products',
          description: 'The same three products, about to expose the ordering bug',
          columns: ['name', 'price'],
          rows: [
            ['Sticky Notes Pack', 4.99],
            ['Laptop Stand', 28.75],
            ['Office Chair', 120.00],
          ],
        },
        explanation: [
          'Compare these two orderings of the same tiers:',
          '```sql\n-- ✓ correct: specific (narrow) bound first\nCASE WHEN price < 25 THEN \'Budget\'\n     WHEN price < 100 THEN \'Standard\' ELSE \'Premium\' END\n\n-- ✕ broken: greedy bound first\nCASE WHEN price < 100 THEN \'Standard\'\n     WHEN price < 25 THEN \'Budget\' ELSE \'Premium\' END\n```',
          'In the broken version, every price under 100 — including 4.99 — matches the first WHEN. The `WHEN price < 25` branch can never run: **4.99 shows Standard, not Budget.** No error, no warning — just wrong labels.',
          'One more rule: if nothing matches and there is **no ELSE**, CASE outputs **NULL** (three-valued logic from Day 3 again).',
        ],
        targetQuery: {
          sql: "SELECT name, price,\n       CASE\n         WHEN price < 100 THEN 'Standard'\n         WHEN price < 25 THEN 'Budget'\n         ELSE 'Premium'\n       END AS tier\nFROM products\nORDER BY price ASC\nLIMIT 4;",
          explanation: 'The broken ordering — run it in the live demo and watch cheap products show Standard.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: Trace 4.99 through the broken CASE',
            sqlSnippet: "WHEN price < 100 THEN 'Standard'",
            explanation: '4.99 < 100 → TRUE on the first branch. SQL never looks at WHEN price < 25. Output: Standard. Wrong.',
            tableData: {
              tableName: 'Broken branch walk',
              columns: ['name', 'price', 'WHEN price < 100', 'result'],
              highlightedRows: [0],
              rows: [
                ['Sticky Notes Pack', 4.99, 'TRUE', 'Standard ✕ (should be Budget)'],
                ['Knife Sharpener', 12.50, 'TRUE', 'Standard ✕ (should be Budget)'],
                ['Office Chair', 120.00, 'FALSE → FALSE', 'Premium (ELSE)'],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: Narrow bounds first — the fix',
            sqlSnippet: "CASE WHEN price < 25 THEN 'Budget' WHEN price < 100 THEN 'Standard' ELSE 'Premium' END",
            explanation: 'With the narrow bound first, 4.99 matches Budget and Standard only catches 25–99.99. The fixed version is exactly Concept 2\'s query.',
            tableData: {
              tableName: 'After the fix',
              columns: ['price range', 'tier'],
              rows: [
                ['< 25', 'Budget'],
                ['25 – 99.99', 'Standard'],
                ['≥ 100', 'Premium (ELSE)'],
              ],
            },
          },
        ],
        debuggingExercise: {
          brokenSql: "SELECT name, price, CASE WHEN price < 100 THEN 'Standard' WHEN price < 25 THEN 'Budget' ELSE 'Premium' END AS tier FROM products;",
          bugs: [
            'The greedy branch (price < 100) is checked first, so the Budget branch (price < 25) is unreachable.',
            'Every product under $25 is mislabeled Standard — a silent wrong-result bug with no error message.',
          ],
          fixDescription: 'Order branches from narrowest to widest: WHEN price < 25 first, THEN price < 100, and let ELSE catch the rest.',
        },
        keyTakeaway: 'CASE stops at the first TRUE WHEN. Put narrow/specific bounds before greedy ones, or later branches become dead code. No ELSE + no match = NULL.',
        exampleQuery: "SELECT price, CASE WHEN price < 100 THEN 'Standard' WHEN price < 25 THEN 'Budget' ELSE 'Premium' END AS tier FROM products;",
        exampleQueryExplanation: 'Deliberately broken — the Budget branch is unreachable. Predict the output before running it.',
        liveDemoSql: "SELECT name, price, CASE WHEN price < 100 THEN 'Standard' WHEN price < 25 THEN 'Budget' ELSE 'Premium' END AS tier FROM products ORDER BY price ASC LIMIT 4;",
        liveDemoNotes: 'Look at the cheapest rows: they say Standard. Proof that branch order matters.',
        mcqs: [
          {
            question: "With `CASE WHEN price < 100 THEN 'Standard' WHEN price < 25 THEN 'Budget' ELSE 'Premium' END`, what does the row price = 4.99 output?",
            options: ["A. Budget", "B. Standard", "C. Premium", "D. NULL"],
            correctIndex: 1,
            explanation: 'The first branch (price < 100) matches, so CASE stops there — the Budget branch is unreachable.',
          },
          {
            question: 'A CASE has no ELSE and no WHEN matches. What does the row output? (Recall Day 3\'s three-valued logic.)',
            options: ['A. An error', 'B. 0', 'C. NULL', 'D. An empty string'],
            correctIndex: 2,
            explanation: 'No matching branch and no ELSE → NULL. The same UNKNOWN family you met with = NULL.',
          },
        ],
        masteryPoints: ['Diagnose unreachable WHEN branches', 'Order branches narrow → wide', 'Predict NULL output when ELSE is missing'],
      },
      tasks: [
        {
          id: 'case-order-t1',
          title: 'Task 1 (Guided): Predict, then fix the mislabeling bug',
          description: 'QC reported that cheap products show as \'Standard\'. First predict the bug\'s reach, then fix the branch order.',
          instructions: [
            'Run the broken query from the theory (it is pre-loaded in the editor) and confirm products under $25 show Standard.',
            'Rewrite it correctly: WHEN `price < 25` first, THEN `price < 100`, ELSE `\'Premium\'` — aliased AS `price_tier`. Verify Budget reappears.',
          ],
          type: 'guided',
          primaryTable: 'products',
          initialSql: "SELECT name, price, CASE WHEN price < 100 THEN 'Standard' WHEN price < 25 THEN 'Budget' ELSE 'Premium' END AS tier FROM products;\n",
          solutionSql: "SELECT name, price, CASE WHEN price < 25 THEN 'Budget' WHEN price < 100 THEN 'Standard' ELSE 'Premium' END AS price_tier FROM products;",
          solutionExplanation: 'Narrow bound first: 17 products are Budget again, and Standard only catches 25–99.99.',
          hints: [
            { level: 1, text: 'Swap the two WHEN branches — narrowest range first.' },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'products',
            requiredColumns: ['name', 'price', 'price_tier'],
            requireCase: true,
            expectedRowCount: 28,
          },
          successMessage: 'Bug fixed — you diagnosed an unreachable branch, the exact skill debugging real reports demands.',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'case-order-t2',
          title: 'Task 2 (Independent): NULL with no ELSE',
          description: 'Flag only the expensive items: tier = \'Luxury\' when price >= 100, and NO ELSE clause. Predict what the other 27 rows output before running.',
          instructions: [
            'Select `name`, `price`, and a single-branch CASE AS `tier` with no ELSE.',
            'What do non-matching rows show? Run to confirm your prediction.',
          ],
          type: 'independent',
          primaryTable: 'products',
          initialSql: '-- Luxury flag: no ELSE\n',
          solutionSql: "SELECT name, price, CASE WHEN price >= 100 THEN 'Luxury' END AS tier FROM products;",
          solutionExplanation: 'Only the Office Chair (120.00) matches; every other row outputs NULL.',
          hints: [
            { level: 1, text: 'CASE WHEN price >= 100 THEN \'Luxury\' END — and that is the whole expression.' },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'products',
            requiredColumns: ['name', 'price', 'tier'],
            requireCase: true,
            expectedRowCount: 28,
          },
          successMessage: 'NULL for non-matches — three-valued logic appearing exactly where theory said it would.',
          databaseLifecycle: 'fresh',
        },
      ],
    },
    {
      id: 'case-in-aggregates',
      order: 4,
      title: '4. CASE Inside Aggregates: Conditional Counting',
      shortDescription: 'SUM(CASE …) / COUNT(CASE …) — count two ways in one query.',
      theory: {
        summary: 'Ops asks: "How many out-of-stock products does each category have?" One WHERE can\'t answer it — WHERE filters rows before grouping, so it can\'t count matching and non-matching rows side by side. The trick: put CASE **inside** the aggregate, and let each row vote on what it contributes.',
        introTable: {
          tableName: 'products',
          description: 'Stock by category — 3 of the 28 products are out of stock (USB-C Cable, Cutting Board Set, Football)',
          columns: ['name', 'category_id', 'quantity_in_stock'],
          rows: [
            ['USB-C Charging Cable', 1, 0],
            ['Stainless Steel Pan Set', 2, 15],
            ['Football', 4, 0],
          ],
        },
        explanation: [
          'WHERE decides **which rows** enter the group. CASE inside SUM decides **what each row contributes** to the total:',
          '```sql\nSELECT category_id,\n       SUM(CASE WHEN quantity_in_stock = 0 THEN 1 ELSE 0 END) AS out_of_stock,\n       COUNT(*) AS total_products\nFROM products\nGROUP BY category_id;\n```',
          'Read the SUM line as: "each out-of-stock row contributes 1, every other row contributes 0." Summing 1s and 0s **is counting** — but only of the rows you flagged.',
          'COUNT(CASE WHEN … THEN 1 END) works the same way, except rows that match no branch produce NULL (no ELSE!) and COUNT ignores NULLs. Two tools, same idea.',
        ],
        targetQuery: {
          sql: "SELECT category_id,\n       SUM(CASE WHEN quantity_in_stock = 0 THEN 1 ELSE 0 END) AS out_of_stock,\n       COUNT(*) AS total_products\nFROM products\nGROUP BY category_id;",
          explanation: 'Per category: how many products are out of stock, next to the total.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: GROUP BY forms the buckets (Day 9 again)',
            sqlSnippet: 'GROUP BY category_id',
            explanation: 'Rows are collected per category — the Electronics bucket holds products 1–5, 26, 27.',
            tableData: {
              tableName: 'Electronics bucket (category 1)',
              columns: ['name', 'quantity_in_stock', 'CASE contributes'],
              rows: [
                ['Wireless Mouse', 40, 0],
                ['Bluetooth Speaker', 3, 0],
                ['USB-C Charging Cable', 0, 1],
                ['Mechanical Keyboard', 12, 0],
                ['Laptop Stand', 8, 0],
              ],
              highlightedRows: [2],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: SUM adds the contributions — 0+0+1+0+0 = 1',
            sqlSnippet: 'SUM(CASE WHEN quantity_in_stock = 0 THEN 1 ELSE 0 END) AS out_of_stock',
            explanation: 'Electronics: 1 out of 7. The 3 flagged 1s (USB-C, Cutting Board, Football) land in 3 different category buckets.',
            tableData: {
              tableName: 'Result (out_of_stock / total)',
              columns: ['category_id', 'out_of_stock', 'total_products'],
              highlightedColumns: ['out_of_stock'],
              rows: [
                [1, 1, 7],
                [2, 1, 5],
                [4, 1, 5],
                ['others', 0, '…'],
              ],
            },
          },
        ],
        keyTakeaway: 'WHERE filters which rows reach the group; CASE inside the aggregate decides what each row contributes. SUM(CASE … 1/0) is conditional counting — the workhorse of real reporting.',
        exampleQuery: 'SELECT category_id, SUM(CASE WHEN quantity_in_stock = 0 THEN 1 ELSE 0 END) AS out_of_stock, COUNT(*) AS total_products FROM products GROUP BY category_id;',
        exampleQueryExplanation: 'Stock-health scoreboard per category in a single pass.',
        liveDemoSql: 'SELECT category_id, SUM(CASE WHEN quantity_in_stock = 0 THEN 1 ELSE 0 END) AS out_of_stock, COUNT(*) AS total_products FROM products WHERE category_id IS NOT NULL GROUP BY category_id;',
        liveDemoNotes: 'The clearance item (NULL category) is excluded with IS NOT NULL — a Day 3 tool doing real work.',
        mcqs: [
          {
            question: 'Why can\'t `WHERE quantity_in_stock = 0` plus COUNT(*) answer "out-of-stock count per category" alongside the total?',
            options: [
              'A. It can — WHERE and CASE are equivalent here',
              'B. WHERE runs before grouping, so it removes rows from ALL counts, not just one',
              'C. COUNT(*) cannot be used with WHERE',
              'D. Because aggregates need HAVING',
            ],
            correctIndex: 1,
            explanation: 'Recall Day 9: WHERE filters rows before GROUP BY. It would delete the in-stock rows from the total too. CASE inside SUM counts both sides in one pass.',
          },
          {
            question: 'In `COUNT(CASE WHEN email IS NULL THEN 1 END)` (no ELSE), what do non-matching rows contribute?',
            options: ['A. 0', 'B. 1', 'C. NULL — which COUNT ignores', 'D. They crash the query'],
            correctIndex: 2,
            explanation: 'No ELSE → NULL, and COUNT(column) skips NULLs (Day 9). So only matching rows get counted.',
          },
        ],
        masteryPoints: ['Write SUM(CASE WHEN … THEN 1 ELSE 0 END)', 'Explain WHERE vs CASE-inside-aggregate timing'],
      },
      tasks: [
        {
          id: 'case-agg-t1',
          title: 'Task 1 (Guided): Out-of-stock count per category',
          description: 'Per category (excluding the NULL-category clearance item): count out-of-stock products next to the total.',
          instructions: [
            'Select `category_id`, `SUM(CASE WHEN quantity_in_stock = 0 THEN 1 ELSE 0 END) AS out_of_stock`, and `COUNT(*) AS total_products`.',
            'Add `WHERE category_id IS NOT NULL`, GROUP BY `category_id`, end with a semicolon.',
          ],
          type: 'guided',
          primaryTable: 'products',
          initialSql: '-- Stock-health scoreboard\n',
          solutionSql: 'SELECT category_id, SUM(CASE WHEN quantity_in_stock = 0 THEN 1 ELSE 0 END) AS out_of_stock, COUNT(*) AS total_products FROM products WHERE category_id IS NOT NULL GROUP BY category_id;',
          solutionExplanation: 'Categories 1, 2 and 4 each flag one out-of-stock product; the other categories flag none.',
          hints: [
            { level: 1, text: 'The CASE goes INSIDE the SUM parentheses — each row contributes 1 or 0.' },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'products',
            requiredColumns: ['category_id', 'out_of_stock', 'total_products'],
            requireCase: true,
            requireGroupBy: true,
            expectedRowCount: 5,
          },
          successMessage: 'Conditional counting mastered — two different counts in one pass.',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'case-agg-t2',
          title: 'Task 2 (Independent): Email audit per city',
          description: 'Per city: how many customers are missing an email? Use COUNT(CASE WHEN email IS NULL THEN 1 END) — no ELSE needed.',
          instructions: [
            'Select `city` and `COUNT(CASE WHEN email IS NULL THEN 1 END) AS missing_email`.',
            'GROUP BY `city`, end with a semicolon.',
          ],
          type: 'independent',
          primaryTable: 'customers',
          initialSql: '-- Email audit by city\n',
          solutionSql: 'SELECT city, COUNT(CASE WHEN email IS NULL THEN 1 END) AS missing_email FROM customers GROUP BY city;',
          solutionExplanation: 'Chittagong flags 1 (Tanvir), Khulna flags 1 (Shakil); every other city flags 0.',
          hints: [
            { level: 1, text: 'COUNT(CASE WHEN email IS NULL THEN 1 END) — non-matching rows produce NULL, which COUNT ignores.' },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'customers',
            requiredColumns: ['city', 'missing_email'],
            requireCase: true,
            requireGroupBy: true,
            expectedRowCount: 6,
          },
          successMessage: 'Perfect transfer — LEFT JOIN not even needed, and IS NULL did the flagging.',
          databaseLifecycle: 'fresh',
        },
      ],
    },
    {
      id: 'case-in-order-by',
      order: 5,
      title: '5. CASE in ORDER BY: Sorting by Priority',
      shortDescription: 'Sort by business urgency, not by alphabetical or numeric value.',
      theory: {
        summary: 'A picker walks the warehouse with a printed list. The most urgent items must be at the top: out-of-stock first, then the lowest stock. ORDER BY quantity_in_stock alone would put the zero-stock rows first — but only by luck, and it breaks the moment ops wants a different priority rule. CASE in ORDER BY makes the priority explicit.',
        introTable: {
          tableName: 'products',
          description: 'Stock levels — the picker needs zeros at the top, then ascending stock',
          columns: ['name', 'quantity_in_stock'],
          rows: [
            ['Sticky Notes Pack', 100],
            ['USB-C Charging Cable', 0],
            ['Electric Kettle', 2],
          ],
        },
        explanation: [
          'ORDER BY accepts any expression a SELECT can produce — including CASE. Each row\'s sort key is the CASE output:',
          '```sql\nSELECT name, quantity_in_stock\nFROM products\nORDER BY\n  CASE WHEN quantity_in_stock = 0 THEN 0 ELSE 1 END,\n  quantity_in_stock ASC;\n```',
          'The CASE assigns a **priority group**: zeros get 0, everything else gets 1 — so all zeros sort to the top. The second key, `quantity_in_stock ASC`, breaks ties *within* each group (Day 4\'s multi-column sort doing its job).',
          'Read it as two sort levels: "first by urgency flag, then by stock level."',
        ],
        targetQuery: {
          sql: "SELECT name, quantity_in_stock\nFROM products\nORDER BY\n  CASE WHEN quantity_in_stock = 0 THEN 0 ELSE 1 END,\n  quantity_in_stock ASC;",
          explanation: 'Restock list: zero-stock items first, then everything by ascending stock.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: Each row gets a priority number',
            sqlSnippet: 'CASE WHEN quantity_in_stock = 0 THEN 0 ELSE 1 END',
            explanation: 'USB-C Cable (0) → 0. Electric Kettle (2) → 1. Sticky Notes (100) → 1.',
            tableData: {
              tableName: 'Sort keys',
              columns: ['name', 'quantity_in_stock', 'priority', 'within-group key'],
              rows: [
                ['USB-C Charging Cable', 0, 0, 0],
                ['Electric Kettle', 2, 1, 2],
                ['Sticky Notes Pack', 100, 1, 100],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: Sort by priority, then by stock',
            sqlSnippet: 'ORDER BY <priority>, quantity_in_stock ASC',
            explanation: 'Priority 0 rows come first (the 3 zero-stock products), then priority 1 rows in ascending stock order.',
            tableData: {
              tableName: 'Final order (first rows)',
              columns: ['name', 'quantity_in_stock'],
              highlightedColumns: ['quantity_in_stock'],
              rows: [
                ['USB-C Charging Cable', 0],
                ['Cutting Board Set', 0],
                ['Football', 0],
                ['Electric Kettle', 2],
              ],
            },
          },
        ],
        keyTakeaway: 'CASE in ORDER BY assigns each row a computed sort priority; additional keys break ties within each priority group. This is how "urgency" becomes a sort order.',
        exampleQuery: 'SELECT name, quantity_in_stock FROM products ORDER BY CASE WHEN quantity_in_stock = 0 THEN 0 ELSE 1 END, quantity_in_stock ASC;',
        exampleQueryExplanation: 'The picker\'s list — zeros first, then ascending stock.',
        liveDemoSql: 'SELECT name, quantity_in_stock FROM products ORDER BY CASE WHEN quantity_in_stock = 0 THEN 0 ELSE 1 END, quantity_in_stock ASC LIMIT 6;',
        liveDemoNotes: 'First three rows are the zero-stock products; then stock ascends.',
        mcqs: [
          {
            question: 'What is the second sort key (`quantity_in_stock ASC`) doing in the priority query?',
            options: [
              'A. Nothing — one sort key is enough',
              'B. Breaking ties within each priority group',
              'C. Overriding the CASE',
              'D. Filtering rows',
            ],
            correctIndex: 1,
            explanation: 'Day 4\'s tie-breaking: rows with equal priority are ordered by stock ascending.',
          },
        ],
        masteryPoints: ['Use CASE as a computed sort key', 'Combine CASE priority with secondary sort keys'],
      },
      tasks: [
        {
          id: 'case-orderby-t1',
          title: 'Task 1 (Guided): Build the restock priority list',
          description: 'Zero-stock products first, then everything else by ascending stock.',
          instructions: [
            'Select `name`, `quantity_in_stock` from `products`.',
            'ORDER BY a CASE (`quantity_in_stock = 0` → 0, ELSE 1), then `quantity_in_stock ASC`. End with a semicolon.',
          ],
          type: 'guided',
          primaryTable: 'products',
          initialSql: '-- Restock priority list\n',
          solutionSql: 'SELECT name, quantity_in_stock FROM products ORDER BY CASE WHEN quantity_in_stock = 0 THEN 0 ELSE 1 END, quantity_in_stock ASC;',
          solutionExplanation: 'The 3 zero-stock products lead; the rest follow by ascending stock.',
          hints: [
            { level: 1, text: 'ORDER BY CASE WHEN quantity_in_stock = 0 THEN 0 ELSE 1 END, quantity_in_stock ASC' },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'products',
            requiredColumns: ['name', 'quantity_in_stock'],
            requireCase: true,
            expectedRowCount: 28,
          },
          successMessage: 'Priority list built — urgency is now a sort order.',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'case-orderby-t2',
          title: 'Task 2 (Independent): Department-first student directory',
          description: 'New domain, same tool: list students with CSE students first, then the rest — each group alphabetical by name.',
          instructions: [
            'Select `name`, `department`, `age` from `students`.',
            'ORDER BY CASE WHEN `department = \'CSE\'` THEN 0 ELSE 1 END, then `name ASC`. End with a semicolon.',
          ],
          type: 'independent',
          primaryTable: 'students',
          initialSql: '-- Department-first directory\n',
          solutionSql: "SELECT name, department, age FROM students ORDER BY CASE WHEN department = 'CSE' THEN 0 ELSE 1 END, name ASC;",
          solutionExplanation: 'Ayesha, Rahim, Tanvir (CSE) lead; Karim and Sumaiya follow alphabetically.',
          hints: [
            { level: 1, text: "CASE WHEN department = 'CSE' THEN 0 ELSE 1 END, then name ASC." },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'students',
            requiredColumns: ['name', 'department', 'age'],
            requireCase: true,
            expectedRowCount: 5,
          },
          successMessage: 'Third domain, same pattern — CASE priority is officially a tool you own.',
          databaseLifecycle: 'fresh',
        },
      ],
    },
  ],
  // ===========================================================================
  // DAY 10 CHALLENGE: CONDITIONAL LOGIC IN PRODUCTION REPORTS (ENDING ACTIVITY)
  // ===========================================================================
  challenge: {
    id: 'case-logic-homework',
    title: 'Day 10 — Conditional Logic Challenge (Ending Activity)',
    scenario: 'Combine CASE with everything from Milestone 2 so far — GROUP BY, LEFT JOIN, multi-key sorting:',
    databaseLifecycle: 'fresh',
    tasks: [
      {
        id: 'case-hw-1',
        title: 'Task 1: Customer loyalty tiers',
        description: 'Marketing wants every customer tagged Gold / Silver / Bronze. Gold = 3+ orders, Silver = 1–2, Bronze = 0 (they never ordered — recall the LEFT JOIN shape).',
        instructions: [
          'LEFT JOIN `orders o` on `c.customer_id = o.customer_id`, GROUP BY `c.customer_id, c.name`.',
          'Output `c.name`, `COUNT(o.order_id) AS order_count`, and a CASE on `COUNT(o.order_id)`: >= 3 → \'Gold\', >= 1 → \'Silver\', ELSE \'Bronze\' — AS `loyalty_tier`. Sort by `order_count DESC`.',
        ],
        type: 'challenge',
        primaryTable: 'customers',
        secondaryTables: ['orders'],
        initialSql: '-- Challenge: loyalty tiers\n',
        solutionSql: "SELECT c.name, COUNT(o.order_id) AS order_count, CASE WHEN COUNT(o.order_id) >= 3 THEN 'Gold' WHEN COUNT(o.order_id) >= 1 THEN 'Silver' ELSE 'Bronze' END AS loyalty_tier FROM customers c LEFT JOIN orders o ON c.customer_id = o.customer_id GROUP BY c.customer_id, c.name ORDER BY order_count DESC;",
        solutionExplanation: 'CASE evaluates the aggregate per group: 1 Gold (Rafiul, 3 orders), 11 Silver, 3 Bronze (zero-order customers the LEFT JOIN preserved).',
        hints: [
          { level: 1, text: 'The CASE conditions can reference COUNT(o.order_id) directly — the aggregate is computed per group before the CASE runs.' },
        ],
        validation: {
          requireExactResult: true,
          targetTable: 'customers',
          requiredColumns: ['name', 'order_count', 'loyalty_tier'],
          requireCase: true,
          requireJoin: true,
          requireGroupBy: true,
          expectedRowCount: 15,
        },
        successMessage: 'The final boss combo: LEFT JOIN + COUNT + CASE-on-aggregate — a genuine production report.',
      },
      {
        id: 'case-hw-2',
        title: 'Task 2: Category stock-health report',
        description: 'Per category (excluding the NULL-category clearance item), count in-stock vs out-of-stock products side by side.',
        instructions: [
          'WHERE `category_id IS NOT NULL`; GROUP BY `category_id`.',
          'Output `category_id`, `SUM(CASE WHEN quantity_in_stock = 0 THEN 1 ELSE 0 END) AS out_of_stock`, `COUNT(*) AS total_products`.',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Challenge: stock health per category\n',
        solutionSql: 'SELECT category_id, SUM(CASE WHEN quantity_in_stock = 0 THEN 1 ELSE 0 END) AS out_of_stock, COUNT(*) AS total_products FROM products WHERE category_id IS NOT NULL GROUP BY category_id;',
        solutionExplanation: 'Categories 1, 2, 4 each have exactly one out-of-stock product.',
        hints: [
          { level: 1, text: 'Identical to Concept 4\'s pattern — WHERE keeps the clearance item out of every bucket.' },
        ],
        validation: {
          requireExactResult: true,
          targetTable: 'products',
          requiredColumns: ['category_id', 'out_of_stock', 'total_products'],
          requireCase: true,
          requireGroupBy: true,
          expectedRowCount: 5,
        },
        successMessage: 'Stock-health scoreboard delivered.',
      },
      {
        id: 'case-hw-3',
        title: 'Task 3: Restock priority list (top 5)',
        description: 'The picker only walks one aisle: the 5 most urgent products. Zero-stock first, then lowest stock — and only the top 5 rows.',
        instructions: [
          'Select `name`, `quantity_in_stock` from `products`.',
          'ORDER BY the CASE priority (0 for zeros, 1 otherwise), then `quantity_in_stock ASC`, and add `LIMIT 5`.',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Challenge: top-5 restock list\n',
        solutionSql: 'SELECT name, quantity_in_stock FROM products ORDER BY CASE WHEN quantity_in_stock = 0 THEN 0 ELSE 1 END, quantity_in_stock ASC LIMIT 5;',
        solutionExplanation: 'The 3 zeros, then Electric Kettle (2) and Bluetooth Speaker (3).',
        hints: [
          { level: 1, text: 'Same ORDER BY as the Concept 5 practice — just append LIMIT 5.' },
        ],
        validation: {
          requireExactResult: true,
          targetTable: 'products',
          requiredColumns: ['name', 'quantity_in_stock'],
          requireCase: true,
          requireLimit: 5,
          expectedRowCount: 5,
        },
        successMessage: 'Priority + pagination — the list is shelf-ready.',
      },
      {
        id: 'case-hw-4',
        title: 'Task 4: Per-category tier breakdown (final boss)',
        description: 'One query, three conditional counts: per category, how many Budget (< 25), Standard (25–99.99), and Premium (>= 100) products. No WHERE — include every category, sorted by category_id.',
        instructions: [
          'Select `category_id` plus three SUM(CASE …) columns: `budget_products` (< 25), `standard_products` (>= 25 AND < 100), `premium_products` (>= 100) — each contributing 1 or 0.',
          'GROUP BY `category_id`, ORDER BY `category_id`. (The NULL-category row will appear — correct: the clearance item is Budget.)',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Challenge: tier breakdown per category\n',
        solutionSql: "SELECT category_id, SUM(CASE WHEN price < 25 THEN 1 ELSE 0 END) AS budget_products, SUM(CASE WHEN price >= 25 AND price < 100 THEN 1 ELSE 0 END) AS standard_products, SUM(CASE WHEN price >= 100 THEN 1 ELSE 0 END) AS premium_products FROM products GROUP BY category_id ORDER BY category_id;",
        solutionExplanation: 'Three flag columns per bucket: Electronics (category 1) has 2 Budget, 4 Standard, 1 Premium. The NULL-category group shows the clearance item as Budget.',
        hints: [
          { level: 1, text: 'Each SUM(CASE …) is its own 1/0 flag; the middle tier needs a compound condition: price >= 25 AND price < 100.' },
        ],
        validation: {
          requireExactResult: true,
          targetTable: 'products',
          requiredColumns: ['category_id', 'budget_products', 'standard_products', 'premium_products'],
          requireCase: true,
          requireGroupBy: true,
        },
        successMessage: 'Challenge complete — GROUP BY + three conditional flags is exactly how real BI breakdown reports are written.',
      },
    ],
  },
};
