import { ModuleData } from '../../types/curriculum';

// =============================================================================
// DAY 28 - DDL II: Column Constraints (id: ddl-column-constraints - order 28)
// Split out of the old day-20 DDL mega-module (atomic-rule fix). Atomic chain:
//   C1 NOT NULL - mandatory fields   C2 UNIQUE - no duplicates
//   C3 DEFAULT - automatic values    C4 CHECK - business rules at the DB level
// =============================================================================
export const Day_28_MODULE: ModuleData = {
  id: 'day-28',
  slug: 'ddl-column-constraints',
  day: 28,
  title: 'Day 28 - Enforce Data Quality at the Database: Column Constraints',
  shortTitle: 'DDL II (Constraints)',
  type: 'module',
  milestoneId: 'milestone-3',
  description: 'Teach the database to guard its own data: NOT NULL for mandatory fields, UNIQUE for no-duplicate guarantees, DEFAULT for automatic values, and CHECK for business rules enforced on every write.',
  estimatedMinutes: 55,
  completionLearnings: [
    'Make fields mandatory with NOT NULL so no record is ever half-complete',
    'Prevent duplicates with UNIQUE constraints (distinct from PRIMARY KEY)',
    'Populate columns automatically with DEFAULT values',
    'Encode business rules with CHECK constraints the engine enforces on every write',
  ],
  concepts: [
    {
      id: 'ddl2-not-null',
      order: 1,
      title: '1. Mandatory Fields with NOT NULL',
      shortDescription: 'A column that can never be empty.',
      theory: {
        summary: 'The NOT NULL constraint makes a column mandatory: every INSERT and UPDATE must supply a value. A row without it is rejected with a constraint error. Use it for data the business cannot function without - names, prices, dates - and save yourself a lifetime of NULL-handling in analytics.',
        introTable: {
          tableName: 'employees (schema)',
          description: 'Employees where name and salary are mandatory.',
          columns: ['emp_id (PK)', 'full_name (NOT NULL)', 'salary (NOT NULL)'],
          rows: [
            [101, 'Arif Chowdhury', 55000.0],
            [102, 'Nadia Islam', 62000.0],
          ],
        },
        explanation: [
          'The rule goes straight into the column definition, right after the data type:',
          '```sql\nCREATE TABLE employees (\n  emp_id INT PRIMARY KEY,\n  full_name VARCHAR(100) NOT NULL,\n  salary DECIMAL(10,2) NOT NULL\n);\n```',
          'QUESTION_BLOCK::WHY::What happens if an INSERT omits full_name?',
          'QUESTION_BLOCK::WHEN::Why is NOT NULL better than checking in application code?',
          'The engine rejects the insert with a constraint error - the bad row never lands. Application-level checks can be forgotten or bypassed; a database constraint cannot. That is the Day 27 lesson continuing: the schema is the first line of defense.',
          'The flip side: nullable columns are a choice too. A customer might legitimately have no email yet - forcing one would create fake data. Decide per column: mandatory, or honestly optional.',
        ],
        targetQuery: {
          sql: 'CREATE TABLE employees (\n  emp_id INT PRIMARY KEY,\n  full_name VARCHAR(100) NOT NULL,\n  salary DECIMAL(10,2) NOT NULL\n);',
          explanation: 'Every employee record must carry a name and a salary - the schema enforces it.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: Mark the mandatory columns',
            sqlSnippet: 'full_name VARCHAR(100) NOT NULL,\nsalary DECIMAL(10,2) NOT NULL',
            explanation: 'Two constraints, two guarantees: no employee can ever be saved without a name or a salary.',
            tableData: {
              tableName: 'NOT NULL schema',
              columns: ['Column', 'Requirement'],
              rows: [
                ['full_name', 'Mandatory (NOT NULL)'],
                ['salary', 'Mandatory (NOT NULL)'],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'NOT NULL syntax',
            sql: 'column_name data_type NOT NULL',
            description: 'Placed after the data type. The engine rejects any INSERT or UPDATE that leaves the column out (or sets it to NULL).',
          },
        ],
        keyTakeaway: 'NOT NULL makes a column mandatory at the database level - the engine rejects incomplete rows so your analytics never drown in unexpected NULLs.',
        exampleQuery: 'CREATE TABLE employees ( emp_id INT PRIMARY KEY, full_name VARCHAR(100) NOT NULL, salary DECIMAL(10,2) NOT NULL );',
        exampleQueryExplanation: 'An employees table where the two business-critical fields can never be empty.',
        liveDemoSql: 'SELECT product_id, name FROM products WHERE price IS NOT NULL LIMIT 3;',
        liveDemoNotes: 'The seeded products already treat price as mandatory - NOT NULL would have guaranteed it at creation time.',
        mcqs: [
          {
            question: 'What happens when an INSERT omits a NOT NULL column?',
            options: [
              'A. The row is saved with an empty string',
              'B. The engine rejects the insert with a constraint error',
              'C. The column is filled with 0',
              'D. The engine asks for confirmation',
            ],
            correctIndex: 1,
            explanation: 'NOT NULL is enforced by the engine - incomplete rows are rejected, not salvaged.',
          },
          {
            question: 'Which column should NOT be NOT NULL?',
            options: [
              'A. order_date on an orders table',
              'B. middle_name on a customers table (many people have none)',
              'C. price on a products table',
              'D. customer_id on an orders table',
            ],
            correctIndex: 1,
            explanation: 'Forcing a middle name would create fake data. Constraints should reflect reality, not optimism.',
          },
        ],
        commonMistakes: [
          'Marking everything NOT NULL until inserts start failing - choose per column based on the business reality.',
          'Confusing NOT NULL (must have a value) with UNIQUE (value must not repeat).',
        ],
        masteryPoints: ['Mark business-critical columns NOT NULL', 'Decide honestly which columns may stay nullable'],
      },
      tasks: [
        {
          id: 'ddl2-c1-t1',
          title: 'Task 1 (Guided): The mandatory-fields table',
          description: 'Create the employees table where full_name and salary can never be empty.',
          instructions: [
            'Write `CREATE TABLE employees (emp_id INT PRIMARY KEY, full_name VARCHAR(100) NOT NULL, salary DECIMAL(10,2) NOT NULL);`',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'employees',
          initialSql: '-- Employees with mandatory fields\n',
          solutionSql: 'CREATE TABLE employees (emp_id INT PRIMARY KEY, full_name VARCHAR(100) NOT NULL, salary DECIMAL(10,2) NOT NULL);',
          solutionExplanation: 'The schema now rejects any employee record missing a name or a salary.',
          hints: [{ level: 1, text: 'Add `NOT NULL` right after the data type of each mandatory column.' }],
          validation: { targetTable: 'employees', expectedRowCount: 1 },
          successMessage: 'Employees table created with mandatory fields!',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'ddl2-c1-t2',
          title: 'Task 2 (Independent): Customer signups without fake data',
          description: 'Create `customer_signups` where `signup_email` and `signup_date` are mandatory, but `referral_code` stays optional (customers may not have one).',
          instructions: [
            'Create table `customer_signups`.',
            'Columns: `signup_id INT PRIMARY KEY`, `signup_email VARCHAR(120) NOT NULL`, `signup_date DATE NOT NULL`, `referral_code VARCHAR(30)` (nullable).',
          ],
          type: 'independent',
          primaryTable: 'customer_signups',
          initialSql: '-- Customer signups: two mandatory, one optional\n',
          solutionSql: 'CREATE TABLE customer_signups (signup_id INT PRIMARY KEY, signup_email VARCHAR(120) NOT NULL, signup_date DATE NOT NULL, referral_code VARCHAR(30));',
          solutionExplanation: 'A deliberate mix: mandatory where the business needs it, honestly nullable where reality varies.',
          hints: [{ level: 1, text: 'NOT NULL only on signup_email and signup_date - leave referral_code without a constraint.' }],
          validation: { targetTable: 'customer_signups', expectedRowCount: 1 },
          successMessage: 'You modeled reality: mandatory where it matters, optional where it does not.',
          databaseLifecycle: 'fresh',
        },
      ],
    },
    {
      id: 'ddl2-unique',
      order: 2,
      title: '2. No Duplicates with UNIQUE',
      shortDescription: 'A value that can appear only once per column.',
      theory: {
        summary: 'UNIQUE guarantees no two rows share the same value in that column. It is the constraint behind usernames, product SKUs, and coupon codes. It differs from PRIMARY KEY in two ways: a table can have several UNIQUE columns, and a UNIQUE column may (in most engines) hold one NULL.',
        introTable: {
          tableName: 'users (schema)',
          description: 'user_id is the PK; username is UNIQUE - both identify a row, only one is the identity.',
          columns: ['user_id (PK)', 'username (UNIQUE)', 'display_name'],
          rows: [
            [1, 'rafiul.i', 'Rafiul I.'],
            [2, 'priya.a', 'Priya A.'],
          ],
        },
        explanation: [
          'Place UNIQUE after the data type, exactly like NOT NULL:',
          "```sql\nCREATE TABLE users (\n  user_id INT AUTO_INCREMENT PRIMARY KEY,\n  username VARCHAR(40) NOT NULL UNIQUE,\n  display_name VARCHAR(80)\n);\n```",
          'QUESTION_BLOCK::DIFF::What can a table have many of, but only one PRIMARY KEY?',
          'QUESTION_BLOCK::NULLS::Can two rows both have display_name NULL if display_name were UNIQUE?',
          "A second INSERT with username = 'rafiul.i' is rejected - the engine, not your code, prevents duplicates. And because several columns can each be UNIQUE, a products table can protect both sku and slug at once. The question blocks above: many UNIQUE columns per table (but one PK), and yes - most engines treat NULLs as distinct, so multiple NULLs do not collide.",
        ],
        targetQuery: {
          sql: 'CREATE TABLE users (\n  user_id INT AUTO_INCREMENT PRIMARY KEY,\n  username VARCHAR(40) NOT NULL UNIQUE,\n  display_name VARCHAR(80)\n);',
          explanation: 'usernames are now duplicate-proof at the schema level.',
          badge: "The query we're going to break down",
        },
        syntaxBlocks: [
          {
            title: 'UNIQUE syntax',
            sql: 'column_name data_type [NOT NULL] UNIQUE',
            description: 'Several columns per table may be UNIQUE; only one can be PRIMARY KEY. UNIQUE values identify rows; the PK is the row identity.',
          },
        ],
        keyTakeaway: 'UNIQUE forbids duplicate values in a column - several UNIQUE columns are allowed per table, unlike the single PRIMARY KEY.',
        exampleQuery: 'CREATE TABLE users ( user_id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(40) NOT NULL UNIQUE, display_name VARCHAR(80) );',
        exampleQueryExplanation: 'Every username is guaranteed unique - duplicate signups are rejected by the engine.',
        liveDemoSql: 'SELECT product_id, name FROM products GROUP BY product_id, name HAVING COUNT(*) > 1 LIMIT 3;',
        liveDemoNotes: 'Zero rows: the seeded product names are effectively unique - UNIQUE would have made that a guarantee instead of a coincidence.',
        mcqs: [
          {
            question: 'How many UNIQUE constraints can one table have?',
            options: ['A. Zero', 'B. One', 'C. One per column', 'D. Unlimited, like PRIMARY KEY'],
            correctIndex: 2,
            explanation: 'Each column (or column set) can be UNIQUE. Only the PRIMARY KEY is limited to one per table.',
          },
          {
            question: 'A coupon code must never repeat and may be absent while unused. Best design?',
            options: [
              'A. PRIMARY KEY on coupon_code',
              'B. coupon_code VARCHAR(20) UNIQUE (nullable)',
              'C. No constraint, check in code',
              'D. NOT NULL UNIQUE',
            ],
            correctIndex: 1,
            explanation: 'UNIQUE allows one NULL (unused) while still rejecting duplicate codes - exactly the requirement.',
          },
        ],
        commonMistakes: [
          'Using PRIMARY KEY where UNIQUE was meant - a table gets only one PK, but many natural keys deserve UNIQUE.',
          'Assuming UNIQUE also means NOT NULL - they are separate constraints.',
        ],
        masteryPoints: ['Protect natural keys with UNIQUE', 'Contrast UNIQUE with PRIMARY KEY precisely'],
      },
      tasks: [
        {
          id: 'ddl2-c2-t1',
          title: 'Task 1 (Guided): Duplicate-proof usernames',
          description: 'Create the users table with a UNIQUE username.',
          instructions: [
            'Write `CREATE TABLE users (user_id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(40) NOT NULL UNIQUE, display_name VARCHAR(80));`',
          ],
          type: 'guided',
          primaryTable: 'users',
          initialSql: '-- Users with unique usernames\n',
          solutionSql: 'CREATE TABLE users (user_id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(40) NOT NULL UNIQUE, display_name VARCHAR(80));',
          solutionExplanation: 'Duplicate usernames are now impossible at the schema level.',
          hints: [{ level: 1, text: 'Add UNIQUE after the username data type.' }],
          validation: { targetTable: 'users', expectedRowCount: 1 },
          successMessage: 'Usernames are duplicate-proof!',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'ddl2-c2-t2',
          title: 'Task 2 (Independent): Two natural keys at once',
          description: 'Create `warehouse_items` where BOTH `sku` and `barcode` are unique (and sku is also NOT NULL).',
          instructions: [
            'Columns: `item_id INT AUTO_INCREMENT PRIMARY KEY`, `sku VARCHAR(30) NOT NULL UNIQUE`, `barcode VARCHAR(30) UNIQUE`, `location VARCHAR(40)`.',
          ],
          type: 'independent',
          primaryTable: 'warehouse_items',
          initialSql: '-- Two UNIQUE columns in one table\n',
          solutionSql: 'CREATE TABLE warehouse_items (item_id INT AUTO_INCREMENT PRIMARY KEY, sku VARCHAR(30) NOT NULL UNIQUE, barcode VARCHAR(30) UNIQUE, location VARCHAR(40));',
          solutionExplanation: 'Two independent no-duplicate guarantees in a single table - impossible with only a PRIMARY KEY.',
          hints: [{ level: 1, text: 'UNIQUE goes after each data type you want to protect.' }],
          validation: { targetTable: 'warehouse_items', expectedRowCount: 1 },
          successMessage: 'Two natural keys, both guarded - the UNIQUE-versus-PK distinction in practice.',
          databaseLifecycle: 'fresh',
        },
      ],
    },
    {
      id: 'ddl2-default',
      order: 3,
      title: '3. Automatic Values with DEFAULT',
      shortDescription: 'A column that fills itself when you omit it.',
      theory: {
        summary: 'DEFAULT gives a column a fallback value: any INSERT that omits the column receives the default automatically. Statuses start at one value (pending), timestamps record themselves (CURRENT_TIMESTAMP), flags start off (FALSE). Less boilerplate in every INSERT, fewer forgotten fields.',
        introTable: {
          tableName: 'orders (schema)',
          description: 'Every new order starts as pending - so why type it every time?',
          columns: ['order_id (PK)', 'status (DEFAULT pending)', 'created_at (DEFAULT now)'],
          rows: [
            [19, 'pending', '2026-08-26 10:00:00'],
          ],
        },
        explanation: [
          'Place DEFAULT after the data type, followed by the fallback value:',
          "```sql\nCREATE TABLE orders (\n  order_id INT AUTO_INCREMENT PRIMARY KEY,\n  customer_id INT NOT NULL,\n  status VARCHAR(20) DEFAULT 'pending',\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP\n);\n```",
          'QUESTION_BLOCK::OMIT::What does the status column contain if an INSERT does not mention it?',
          'QUESTION_BLOCK::TIME::What does CURRENT_TIMESTAMP as a default capture?',
          "An INSERT that omits status gets 'pending' automatically (the question above: the default, pending). DEFAULT CURRENT_TIMESTAMP is even better - it records the exact moment the row was created, from the server clock, with zero application code. Defaults encode the boring-but-critical business defaults right in the schema.",
          "DEFAULT pairs well with NOT NULL: `status VARCHAR(20) NOT NULL DEFAULT 'pending'` guarantees the column is never empty AND needs no input for the common case.",
        ],
        targetQuery: {
          sql: "CREATE TABLE orders (\n  order_id INT AUTO_INCREMENT PRIMARY KEY,\n  customer_id INT NOT NULL,\n  status VARCHAR(20) NOT NULL DEFAULT 'pending',\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP\n);",
          explanation: 'New orders start pending and timestamp themselves - the schema handles the boilerplate.',
          badge: "The query we're going to break down",
        },
        syntaxBlocks: [
          {
            title: 'DEFAULT syntax',
            sql: "status VARCHAR(20) NOT NULL DEFAULT 'pending'\ncreated_at DATETIME DEFAULT CURRENT_TIMESTAMP",
            description: 'A literal default (string/number) or CURRENT_TIMESTAMP for self-recording timestamps.',
          },
        ],
        keyTakeaway: 'DEFAULT fills omitted columns automatically - literals for business defaults, CURRENT_TIMESTAMP for creation times. Combine with NOT NULL for columns that are both mandatory and predictable.',
        exampleQuery: "CREATE TABLE orders ( order_id INT AUTO_INCREMENT PRIMARY KEY, customer_id INT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', created_at DATETIME DEFAULT CURRENT_TIMESTAMP );",
        exampleQueryExplanation: 'Every future INSERT can skip status and created_at - the schema supplies them.',
        liveDemoSql: 'SELECT order_id, status FROM orders LIMIT 3;',
        liveDemoNotes: 'The seeded orders show the statuses a DEFAULT would produce automatically.',
        mcqs: [
          {
            question: 'An INSERT lists only (customer_id). What does the status column receive?',
            options: [
              'A. NULL',
              'B. An error - the column is missing',
              'C. The DEFAULT value (pending)',
              'D. An empty string',
            ],
            correctIndex: 2,
            explanation: 'Omitted columns receive their DEFAULT. That is the whole point.',
          },
          {
            question: 'Why pair NOT NULL with DEFAULT?',
            options: [
              'A. It makes inserts faster',
              'B. The column is mandatory AND needs no input for the common case',
              'C. It disables NULL handling',
              'D. They conflict',
            ],
            correctIndex: 1,
            explanation: 'DEFAULT supplies the value; NOT NULL guarantees it is never missing. Together: mandatory but effortless.',
          },
        ],
        commonMistakes: [
          'Defaults that encode fake data (DEFAULT 0 for a price you did not measure) - a default should be a true business default.',
          'Expecting DEFAULT to fill explicitly-passed NULLs - only omitted columns get the default.',
        ],
        masteryPoints: ['Set business defaults at the schema level', 'Use DEFAULT CURRENT_TIMESTAMP for audit columns'],
      },
      tasks: [
        {
          id: 'ddl2-c3-t1',
          title: 'Task 1 (Guided): Self-registering orders',
          description: 'Create `orders_v2` where status defaults to pending and created_at stamps itself.',
          instructions: [
            "Write `CREATE TABLE orders_v2 (order_id INT AUTO_INCREMENT PRIMARY KEY, customer_id INT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', created_at DATETIME DEFAULT CURRENT_TIMESTAMP);`",
          ],
          type: 'guided',
          primaryTable: 'orders_v2',
          initialSql: '-- Orders that fill in their own defaults\n',
          solutionSql: "CREATE TABLE orders_v2 (order_id INT AUTO_INCREMENT PRIMARY KEY, customer_id INT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', created_at DATETIME DEFAULT CURRENT_TIMESTAMP);",
          solutionExplanation: 'Future inserts only need customer_id - status and timestamp arrive automatically.',
          hints: [{ level: 1, text: "DEFAULT 'pending' for status; DEFAULT CURRENT_TIMESTAMP for created_at." }],
          validation: { targetTable: 'orders_v2', expectedRowCount: 1 },
          successMessage: 'The schema now carries the business defaults - inserts get shorter forever.',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'ddl2-c3-t2',
          title: 'Task 2 (Independent): A flag that starts off',
          description: 'Create `marketing_prefs` where `newsletter` is a BOOLEAN that defaults to FALSE and `customer_id` is mandatory.',
          instructions: [
            'Columns: `pref_id INT AUTO_INCREMENT PRIMARY KEY`, `customer_id INT NOT NULL`, `newsletter BOOLEAN NOT NULL DEFAULT FALSE`.',
          ],
          type: 'independent',
          primaryTable: 'marketing_prefs',
          initialSql: '-- A flag with a sane default\n',
          solutionSql: 'CREATE TABLE marketing_prefs (pref_id INT AUTO_INCREMENT PRIMARY KEY, customer_id INT NOT NULL, newsletter BOOLEAN NOT NULL DEFAULT FALSE);',
          solutionExplanation: 'Opt-in flags default to off - a compliance-friendly default baked into the schema.',
          hints: [{ level: 1, text: 'DEFAULT FALSE after the BOOLEAN type.' }],
          validation: { targetTable: 'marketing_prefs', expectedRowCount: 1 },
          successMessage: 'Opt-out by default, enforced by the schema - a quiet compliance win.',
          databaseLifecycle: 'fresh',
        },
      ],
    },
    {
      id: 'ddl2-check',
      order: 4,
      title: '4. Business Rules with CHECK',
      shortDescription: 'The database rejects values that break your rules.',
      theory: {
        summary: 'CHECK puts a TRUE/FALSE condition on a column: every INSERT and UPDATE must satisfy it or be rejected. Prices stay positive, percentages stay in range, ratings stay between 1 and 5. It is the schema encoding the rules your team currently enforces with hope.',
        introTable: {
          tableName: 'product_ratings (schema)',
          description: 'A rating outside 1-5 must never exist.',
          columns: ['rating_id (PK)', 'score (CHECK 1-5)'],
          rows: [
            [1, 5],
            [2, 3],
          ],
        },
        explanation: [
          'Write the condition in parentheses after the CHECK keyword:',
          '```sql\nCREATE TABLE product_ratings (\n  rating_id INT PRIMARY KEY,\n  score INT NOT NULL CHECK (score BETWEEN 1 AND 5)\n);\n```',
          'QUESTION_BLOCK::BAD::What happens to an INSERT with score = 6?',
          'QUESTION_BLOCK::WHERE::Why enforce this in the schema instead of the app?',
          'The insert is rejected with a CHECK violation - a rating of 6 can never exist, no matter which app writes it. CHECK conditions accept the same expressions you filter with in WHERE: comparisons, BETWEEN, IN, AND/OR. Multiple CHECKs per column are allowed.',
          'CHECK is the last line of defense: NOT NULL says a value must exist, UNIQUE says it must not repeat, CHECK says it must make sense.',
        ],
        targetQuery: {
          sql: 'CREATE TABLE product_ratings (\n  rating_id INT PRIMARY KEY,\n  score INT NOT NULL CHECK (score BETWEEN 1 AND 5)\n);',
          explanation: 'Ratings outside 1-5 are rejected by the engine on every write.',
          badge: "The query we're going to break down",
        },
        syntaxBlocks: [
          {
            title: 'CHECK syntax',
            sql: 'score INT NOT NULL CHECK (score BETWEEN 1 AND 5)\npercentage DECIMAL(4,2) CHECK (percentage >= 0 AND percentage <= 1)',
            description: 'Any boolean expression over the row. The engine evaluates it on INSERT and UPDATE.',
          },
        ],
        keyTakeaway: 'CHECK turns business rules into schema facts: invalid values are rejected at write time, in every application, forever.',
        exampleQuery: 'CREATE TABLE product_ratings ( rating_id INT PRIMARY KEY, score INT NOT NULL CHECK (score BETWEEN 1 AND 5) );',
        exampleQueryExplanation: 'A rating of 6 is now structurally impossible.',
        liveDemoSql: 'SELECT product_id, price FROM products WHERE price > 0 LIMIT 3;',
        liveDemoNotes: 'All seeded prices are positive - a CHECK (price >= 0) would have made that a guarantee.',
        mcqs: [
          {
            question: 'An application tries to insert rating = 6 into `score INT CHECK (score BETWEEN 1 AND 5)`.',
            options: [
              'A. The database rounds it down to 5',
              'B. The database rejects the write with a CHECK violation',
              'C. It inserts NULL',
              'D. It logs a warning but allows it',
            ],
            correctIndex: 1,
            explanation: 'CHECK violations reject the statement outright - invalid data never lands.',
          },
          {
            question: 'Which CHECK guards a discount percentage stored as a fraction?',
            options: [
              'A. CHECK (percentage > 100)',
              'B. CHECK (percentage BETWEEN 0 AND 1)',
              'C. CHECK (percentage IS NOT NULL)',
              'D. CHECK UNIQUE (percentage)',
            ],
            correctIndex: 1,
            explanation: 'A fraction runs 0 to 1 - BETWEEN 0 AND 1 allows the whole valid range and nothing else.',
          },
        ],
        commonMistakes: [
          'Writing CHECK conditions that reject legitimate data (e.g. CHECK (price > 0) where free samples exist - use >= 0).',
          'Confusing CHECK (a row rule) with FOREIGN KEY (a relationship rule) - Day 29 covers the latter.',
        ],
        masteryPoints: ['Encode range rules with CHECK', 'Explain the constraint ladder: NOT NULL, UNIQUE, CHECK'],
      },
      tasks: [
        {
          id: 'ddl2-c4-t1',
          title: 'Task 1 (Guided): Bounded ratings',
          description: 'Create `product_ratings` with a CHECK keeping scores between 1 and 5.',
          instructions: [
            'Write `CREATE TABLE product_ratings (rating_id INT PRIMARY KEY, score INT NOT NULL CHECK (score BETWEEN 1 AND 5));`',
          ],
          type: 'guided',
          primaryTable: 'product_ratings',
          initialSql: '-- Ratings bounded 1-5\n',
          solutionSql: 'CREATE TABLE product_ratings (rating_id INT PRIMARY KEY, score INT NOT NULL CHECK (score BETWEEN 1 AND 5));',
          solutionExplanation: 'The 1-5 rule now lives in the schema - impossible to violate from any client.',
          hints: [{ level: 1, text: 'CHECK (score BETWEEN 1 AND 5) goes after the score column definition.' }],
          validation: { targetTable: 'product_ratings', expectedRowCount: 1 },
          successMessage: 'Ratings are bounded by the schema itself!',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'ddl2-c4-t2',
          title: 'Task 2 (Independent): The full constraint ladder',
          description: 'Create `discount_campaigns` combining all four: campaign_id PK, code NOT NULL UNIQUE, discount DECIMAL(4,2) CHECK 0-1, active BOOLEAN DEFAULT FALSE.',
          instructions: [
            'Columns: `campaign_id INT AUTO_INCREMENT PRIMARY KEY`, `code VARCHAR(20) NOT NULL UNIQUE`, `discount DECIMAL(4,2) CHECK (discount >= 0 AND discount <= 1)`, `active BOOLEAN NOT NULL DEFAULT FALSE`.',
          ],
          type: 'independent',
          primaryTable: 'discount_campaigns',
          initialSql: '-- NOT NULL + UNIQUE + CHECK + DEFAULT in one table\n',
          solutionSql: "CREATE TABLE discount_campaigns (campaign_id INT AUTO_INCREMENT PRIMARY KEY, code VARCHAR(20) NOT NULL UNIQUE, discount DECIMAL(4,2) CHECK (discount >= 0 AND discount <= 1), active BOOLEAN NOT NULL DEFAULT FALSE);",
          solutionExplanation: 'All four column constraints in one definition: mandatory, unrepeatable, bounded, defaulted.',
          hints: [{ level: 1, text: 'Each constraint sits right after its column type - combine them in the order: type, NOT NULL, UNIQUE, CHECK, DEFAULT.' }],
          validation: { targetTable: 'discount_campaigns', expectedRowCount: 1 },
          successMessage: 'The complete constraint ladder in one table - the schema is now the guardian.',
          databaseLifecycle: 'fresh',
        },
      ],
    },
  ],
  challenge: {
    id: 'ddl2-homework',
    title: 'Day 28 - Constraint Challenge (Ending Activity)',
    scenario: 'Design the review system schema with every constraint it needs - then prove the CHECK actually guards the data.',
    databaseLifecycle: 'fresh',
    tasks: [
      {
        id: 'ddl2-hw-1',
        title: 'Task 1: The fully-guarded reviews table',
        description: 'Create `review_system`: review_id PK auto-increment, product_id NOT NULL, reviewer_name NOT NULL UNIQUE, score NOT NULL CHECK 1-5, verified BOOLEAN NOT NULL DEFAULT FALSE.',
        instructions: [
          'Write `CREATE TABLE review_system (review_id INT AUTO_INCREMENT PRIMARY KEY, product_id INT NOT NULL, reviewer_name VARCHAR(80) NOT NULL UNIQUE, score INT NOT NULL CHECK (score BETWEEN 1 AND 5), verified BOOLEAN NOT NULL DEFAULT FALSE);`',
        ],
        type: 'challenge',
        primaryTable: 'review_system',
        initialSql: '-- The fully-guarded reviews table\n',
        solutionSql:
          'CREATE TABLE review_system (review_id INT AUTO_INCREMENT PRIMARY KEY, product_id INT NOT NULL, reviewer_name VARCHAR(80) NOT NULL UNIQUE, score INT NOT NULL CHECK (score BETWEEN 1 AND 5), verified BOOLEAN NOT NULL DEFAULT FALSE);',
        solutionExplanation: 'Four constraint types working together: identity, mandatory, unrepeatable, bounded, defaulted.',
        hints: [{ level: 1, text: 'Reuse the constraint ladder from C4 Task 2, adapted to review data.' }],
        validation: { targetTable: 'review_system', expectedRowCount: 1 },
        successMessage: 'A production-grade table definition - every constraint earning its place.',
      },
      {
        id: 'ddl2-hw-2',
        title: 'Task 2 (Failure lab): Prove the CHECK rejects bad data',
        description: 'Try to insert a review with score 9. The task EXPECTS the constraint to reject it.',
        instructions: [
          "Run `INSERT INTO review_system (product_id, reviewer_name, score) VALUES (1, 'Cheater', 9);` - score 9 breaks the CHECK.",
          'Expect a constraint error, not a saved row.',
        ],
        type: 'challenge',
        primaryTable: 'review_system',
        initialSql: '-- This insert is SUPPOSED to fail\n',
        solutionSql: "INSERT INTO review_system (product_id, reviewer_name, score) VALUES (1, 'Cheater', 9);",
        solutionExplanation: 'The CHECK violation fired - score 9 can never exist in this table.',
        hints: [{ level: 1, text: 'Run the INSERT exactly as written - the error is the expected result.' }],
        validation: { targetTable: 'review_system', expectFailure: true },
        successMessage: 'The CHECK fired - your business rule is now enforced by the engine, not by hope.',
      },
    ],
  },
};