import { ModuleData } from '../../types/curriculum';

// =============================================================================
// DAY 17 — Set Operations  (id: day-17 · order 17)
// Inserts after Day 16 (7-Stage Pipeline Lab). Atomic chain:
//   C1 UNION ALL (stack) → C2 UNION (stack + dedupe) →
//   C3 Shape compatibility (error lab) → C4 EXCEPT (declarative anti-join)
// =============================================================================
export const Day_17_MODULE: ModuleData = {
  id: 'day-17',
  slug: 'set-operations',
  day: 17,
  title: 'Day 17 — Set Operations: UNION & EXCEPT',
  shortTitle: 'Set Operations',
  type: 'module',
  milestoneId: 'milestone-2',
  description: 'Stack two result sets into one with UNION ALL, remove duplicates with UNION, learn the shape-compatibility rules, and use EXCEPT as a declarative anti-join.',
  estimatedMinutes: 60,
  completionLearnings: [
    'Stack two same-shaped result sets into one list with UNION ALL',
    'Deduplicate the combined result with UNION — and know when dedupe is a bug',
    'Validate shape compatibility: equal column count, compatible types',
    'Replace the LEFT JOIN + IS NULL anti-join with a single EXCEPT',
  ],
  concepts: [
    {
      id: 'union-all',
      order: 1,
      title: '1. UNION ALL: Stack Two Result Sets',
      shortDescription: 'Append the rows of a second query below the first.',
      theory: {
        summary: "The ops team wants one contact list containing customers AND suppliers. Two queries produce two separate result grids — copy-pasting them together is manual work. UNION ALL does it in one statement: it runs both queries and stacks the second result directly beneath the first.",
        introTable: {
          tableName: 'customers + suppliers',
          description: 'Two separate tables, two separate queries — about to become one result',
          columns: ['customers (name)', 'suppliers (name)'],
          rows: [
            ['Rafiul Islam', 'TechSource Ltd'],
            ['Priya Akter', 'Global Kitchenware Co'],
            ['Tanvir Ahmed', 'OfficeMax Wholesale'],
            ['… 15 total', '… 6 total'],
          ],
        },
        explanation: [
          'A set operation connects **two complete SELECT queries**. Each side runs exactly as you learned since Day 1 — its own SELECT, FROM, even WHERE. Then the rows of the bottom query are appended under the rows of the top one.',
          "```sql\nSELECT name, 'Customer' AS source FROM customers\nUNION ALL\nSELECT name, 'Supplier' AS source FROM suppliers;\n```",
          'QUESTION_BLOCK::TOP::What does the first SELECT produce?\nQUESTION_BLOCK::BOTTOM::What does the second SELECT produce?\nQUESTION_BLOCK::STACK::How do the two results combine?',
          "Notice the literal column trick: `'Customer' AS source` outputs the same text on every row. When the two halves describe different *kinds* of things, a literal tag column is how you keep track of which half each row came from.",
          "The output column names come from the **first** SELECT only — the second side's aliases are ignored.",
        ],
        targetQuery: {
          sql: "SELECT name, 'Customer' AS source\nFROM customers\nUNION ALL\nSELECT name, 'Supplier' AS source\nFROM suppliers;",
          explanation: 'One contact directory: 15 customer rows on top, 6 supplier rows appended below.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: The top SELECT runs first, unchanged',
            sqlSnippet: "SELECT name, 'Customer' AS source FROM customers",
            explanation: '15 rows come back, each tagged Customer.',
            tableData: {
              tableName: 'Top result',
              columns: ['name', 'source'],
              rows: [
                ['Rafiul Islam', 'Customer'],
                ['Priya Akter', 'Customer'],
                ['… (15 rows total)', 'Customer'],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: The bottom SELECT runs — also unchanged',
            sqlSnippet: "SELECT name, 'Supplier' AS source FROM suppliers",
            explanation: '6 rows come back, each tagged Supplier.',
            tableData: {
              tableName: 'Bottom result',
              columns: ['name', 'source'],
              rows: [
                ['TechSource Ltd', 'Supplier'],
                ['Global Kitchenware Co', 'Supplier'],
                ['… (6 rows total)', 'Supplier'],
              ],
            },
          },
          {
            stepNumber: 3,
            stepTitle: 'Step 3: UNION ALL appends bottom under top — nothing else',
            sqlSnippet: '… UNION ALL …',
            explanation: 'No comparison, no sorting, no deduplication: 15 + 6 = 21 rows, top-to-bottom.',
            tableData: {
              tableName: 'Combined result',
              columns: ['name', 'source'],
              highlightedColumns: ['source'],
              rows: [
                ['Rafiul Islam', 'Customer'],
                ['…', 'Customer'],
                ['TechSource Ltd', 'Supplier'],
                ['…', 'Supplier'],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'UNION ALL syntax',
            sql: "SELECT col1, literal AS tag FROM table_a\nUNION ALL\nSELECT col1, literal AS tag FROM table_b;",
            description: 'Two full SELECTs joined by UNION ALL; each side is an independent query.',
          },
        ],
        keyTakeaway: "UNION ALL runs two SELECTs and stacks the second result under the first. Tag each side with a literal column ('Customer' AS source) so you can tell the halves apart.",
        exampleQuery: "SELECT name, 'Customer' AS source FROM customers UNION ALL SELECT name, 'Supplier' AS source FROM suppliers;",
        exampleQueryExplanation: 'The full 21-row contact directory — customers stacked above suppliers.',
        liveDemoSql: "SELECT name, 'Customer' AS source FROM customers LIMIT 3 UNION ALL SELECT name, 'Supplier' AS source FROM suppliers LIMIT 3;",
        liveDemoNotes: 'Three customer rows stacked above three supplier rows — one result grid, two sources.',
        mcqs: [
          {
            question: 'What does UNION ALL do with the rows of the second SELECT?',
            options: [
              'A. Merges them into the first result by matching IDs',
              'B. Appends them below the first result, unchanged',
              'C. Removes rows that appear in both results',
              'D. Sorts all rows together alphabetically',
            ],
            correctIndex: 1,
            explanation: 'UNION ALL is pure concatenation: top result first, bottom result appended underneath.',
          },
          {
            question: "In `SELECT name, 'Supplier' AS source FROM suppliers`, what does 'Supplier' AS source produce?",
            options: [
              'A. A filter on the suppliers table',
              'B. An error — you cannot select text',
              'C. The same literal value on every row, in a column named source',
              'D. Only rows where source = Supplier',
            ],
            correctIndex: 2,
            explanation: 'A string literal in the SELECT list repeats on every row — the tag-column trick for set operations.',
          },
          {
            question: 'If the top SELECT returns 15 rows and the bottom returns 6, how many rows does the UNION ALL return?',
            options: ['A. 15', 'B. 6', 'C. 21', 'D. Depends on duplicates'],
            correctIndex: 2,
            explanation: 'UNION ALL never drops rows: 15 + 6 = 21. (The next concept shows the operator that CAN drop rows.)',
          },
        ],
        commonMistakes: [
          'Writing only one SELECT — UNION ALL needs a full second query, not just a second table name.',
          'Forgetting the tag column — without a literal source label, the combined rows are indistinguishable.',
        ],
        masteryPoints: ['Stack two SELECTs with UNION ALL', 'Tag each side with a literal AS column'],
      },
      tasks: [
        {
          id: 'union-all-t1',
          title: 'Task 1 (Guided): One directory for customers and suppliers',
          description: 'Ops keeps two contact lists and keeps losing one of them. Stack customers and suppliers into a single name list, with a source tag per row.',
          instructions: [
            "Top query: SELECT `name`, `'Customer' AS source` FROM `customers`.",
            "Bottom query: SELECT `name`, `'Supplier' AS source` FROM `suppliers` — joined by UNION ALL.",
            'End with a semicolon. Expect 21 rows (15 + 6).',
          ],
          type: 'guided',
          primaryTable: 'customers',
          secondaryTables: ['suppliers'],
          initialSql: '-- Combined contact directory\n',
          solutionSql: "SELECT name, 'Customer' AS source FROM customers UNION ALL SELECT name, 'Supplier' AS source FROM suppliers;",
          solutionExplanation: '15 customer rows stacked above 6 supplier rows = 21 rows, each tagged with its origin.',
          hints: [
            { level: 1, text: "Two complete SELECTs joined by UNION ALL — the literal tags ('Customer' / 'Supplier' AS source) go in each side's SELECT list." },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'customers',
            requiredColumns: ['name', 'source'],
            requireSetOp: 'UNION ALL',
            expectedRowCount: 21,
          },
          successMessage: 'Two tables, one directory — and every row announces where it came from.',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'union-all-t2',
          title: 'Task 2 (Independent): All cities, duplicates and all',
          description: 'New pair of tables, same move: stack the cities of every customer with the cities of every student — no deduplication yet, raw rows only.',
          instructions: [
            'SELECT `city` FROM `customers` UNION ALL SELECT `city` FROM `students`.',
            'Expect 20 rows (15 + 5). Do NOT use DISTINCT or UNION — plain UNION ALL.',
          ],
          type: 'independent',
          primaryTable: 'customers',
          secondaryTables: ['students'],
          initialSql: '-- Every city, raw stack\n',
          solutionSql: 'SELECT city FROM customers UNION ALL SELECT city FROM students;',
          solutionExplanation: '20 raw rows: Dhaka appears three times among customers alone — duplicates included on purpose.',
          hints: [
            { level: 1, text: 'One column per side. The word ALL in UNION ALL means: keep every row, even repeats.' },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'customers',
            requiredColumns: ['city'],
            requireSetOp: 'UNION ALL',
            expectedRowCount: 20,
          },
          successMessage: '20 rows stacked — and notice how often Dhaka repeats. That repetition is exactly what the next concept removes.',
          databaseLifecycle: 'fresh',
        },
      ],
    },
    {
      id: 'union-dedupe',
      order: 2,
      title: '2. UNION: Stack Plus Deduplicate',
      shortDescription: 'UNION ALL with a built-in DISTINCT on the combined rows.',
      theory: {
        summary: 'The city report only needs each city once. UNION is UNION ALL plus one extra step: after stacking, it removes duplicate rows from the combined result. Same stack, then a dedupe pass.',
        introTable: {
          tableName: 'UNION ALL vs UNION',
          description: 'The same two city queries, with and without dedupe',
          columns: ['Operator', 'Behavior', 'City rows returned'],
          rows: [
            ['UNION ALL', 'Keep every row', '20'],
            ['UNION', 'Keep each distinct row once', '8'],
          ],
        },
        explanation: [
          'The mental model is exact: **UNION = UNION ALL + dedupe**. If you already know UNION ALL, you only need to learn when the dedupe pass matters.',
          '```sql\nSELECT city FROM customers\nUNION\nSELECT city FROM students;\n```',
          'QUESTION_BLOCK::DUPE::When does UNION return fewer rows than UNION ALL?',
          'The dedupe compares **entire rows, position by position**. Two rows are duplicates only if every column matches — not just the first column.',
          "When is dedupe a bug? When you deliberately tagged each side with a literal (`'Customer'` vs `'Supplier'`), every row is already unique — UNION silently does nothing. But when two sides legitimately contain the *same fact* (a city both kinds of people live in), keeping it once is exactly what a report wants.",
          'Cost instinct for later: dedupe means comparing every row against every row seen so far. UNION ALL is the cheaper operation — reach for UNION only when duplicates are actually unwanted.',
        ],
        targetQuery: {
          sql: 'SELECT city FROM customers\nUNION\nSELECT city FROM students;',
          explanation: 'Every city where a customer or a student lives — each listed once: 8 rows instead of 20.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: Stack, exactly like UNION ALL',
            sqlSnippet: 'SELECT city FROM customers UNION ALL SELECT city FROM students',
            explanation: 'The same 20 raw rows come out of the stack phase.',
            tableData: {
              tableName: 'After stack (first rows shown)',
              columns: ['city'],
              rows: [
                ['Dhaka'],
                ['Dhaka'],
                ['Chittagong'],
                ['… (20 rows total)'],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: Walk the stacked rows, keep each distinct value once',
            sqlSnippet: '… UNION …',
            explanation: 'Dhaka is kept the first time it appears; the next two Dhakas are dropped. 20 raw rows collapse to 8 distinct cities.',
            tableData: {
              tableName: 'After dedupe',
              columns: ['city'],
              highlightedRows: [0, 5],
              rows: [
                ['Dhaka'],
                ['Chittagong'],
                ['Sylhet'],
                ['Khulna'],
                ['Rajshahi'],
                ['Barisal'],
                ['Gazipur'],
                ['Chattogram'],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'UNION syntax',
            sql: 'SELECT col1 FROM table_a\nUNION\nSELECT col1 FROM table_b;',
            description: 'Same shape as UNION ALL — drop the word ALL to switch on dedupe.',
          },
        ],
        keyTakeaway: 'UNION = UNION ALL + dedupe of the combined rows (whole-row comparison, position by position). Use UNION when repeats are noise; use UNION ALL when every row is data.',
        exampleQuery: 'SELECT city FROM customers UNION SELECT city FROM students;',
        exampleQueryExplanation: '8 distinct cities — the raw 20-row stack collapsed by whole-row dedupe.',
        liveDemoSql: 'SELECT city FROM customers UNION ALL SELECT city FROM students;',
        liveDemoNotes: 'Run the UNION ALL version and count the Dhakas — then swap in UNION and watch them collapse to one.',
        mcqs: [
          {
            question: 'UNION is best understood as…',
            options: [
              'A. A JOIN that matches rows on a key',
              'B. UNION ALL plus a duplicate-removal pass on the combined result',
              'C. A faster version of UNION ALL',
              'D. A replacement for WHERE',
            ],
            correctIndex: 1,
            explanation: 'Identical stacking, one extra step: whole-row dedupe.',
          },
          {
            question: 'Two rows in a UNION result are duplicates when…',
            options: [
              'A. Their first column matches',
              'B. They come from the same table',
              'C. Every column matches, position by position',
              'D. They have the same primary key',
            ],
            correctIndex: 2,
            explanation: 'Set operations compare entire rows across all columns — that is why the tag column defeats dedupe: Customer and Supplier tags make every row distinct.',
          },
          {
            question: "You tagged each side with a literal ('Customer' / 'Supplier') and used UNION. What happens?",
            options: [
              'A. Error — UNION forbids literal columns',
              'B. All 21 rows stay — the tags make every row unique, so there is nothing to dedupe',
              'C. Only one row survives',
              'D. The tags are removed before comparing',
            ],
            correctIndex: 1,
            explanation: 'Dedupe compares whole rows — the differing tag column makes every row distinct. Unexpectedly large UNION row counts often mean a column is secretly uniquifying rows.',
          },
        ],
        commonMistakes: [
          'Using UNION when duplicates are meaningful data — silently losing rows.',
          'Expecting UNION to dedupe only within each side — it dedupes the combined result as a whole.',
        ],
        masteryPoints: ['Predict the row count of UNION vs UNION ALL', 'Explain why the tag column defeats dedupe'],
      },
      tasks: [
        {
          id: 'union-dedupe-t1',
          title: 'Task 1 (Guided): The one-row-per-city report',
          description: 'The city report must list each city once, whether it is home to customers, students, or both.',
          instructions: [
            'SELECT `city` FROM `customers` UNION SELECT `city` FROM `students`.',
            'Expect exactly 8 rows.',
          ],
          type: 'guided',
          primaryTable: 'customers',
          secondaryTables: ['students'],
          initialSql: '-- One row per city\n',
          solutionSql: 'SELECT city FROM customers UNION SELECT city FROM students;',
          solutionExplanation: 'The 20-row stack collapses to 8 distinct cities: Dhaka, Chittagong, Sylhet, Khulna, Rajshahi, Barisal, Gazipur, Chattogram.',
          hints: [
            { level: 1, text: 'Same query as the last task, minus the word ALL.' },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'customers',
            requiredColumns: ['city'],
            requireSetOp: 'UNION',
            expectedRowCount: 8,
          },
          successMessage: '20 rows in, 8 rows out — you just watched the dedupe pass happen.',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'union-dedupe-t2',
          title: 'Task 2 (Independent): When UNION changes nothing',
          description: 'Dedupe only matters when duplicates exist. Stack every customer email with every supplier contact email - using UNION - and watch the row count. Two customers have NULL emails, so guard them first.',
          instructions: [
            'SELECT email AS contact FROM customers WHERE email IS NOT NULL UNION SELECT contact_email AS contact FROM suppliers.',
            'Expect 19 rows - the same count UNION ALL would give (13 customer emails + 6 supplier emails, none duplicated).',
            'Watch the NULL trap: without the WHERE, the two customers missing emails collapse into a single NULL row, so UNION returns 20 - the dedupe working on NULL, not on real duplicates.',
          ],
          type: 'independent',
          primaryTable: 'customers',
          secondaryTables: ['suppliers'],
          initialSql: '-- Email directory via UNION (NULL-guarded)\n',
          solutionSql: 'SELECT email AS contact FROM customers WHERE email IS NOT NULL UNION SELECT contact_email AS contact FROM suppliers;',
          solutionExplanation: '19 rows: 13 customer emails plus 6 supplier emails, all unique, so dedupe removes nothing. The WHERE email IS NOT NULL empties both NULLs out of the picture - without it, UNION collapses the two NULL rows into one and you get 20, a silent NULL effect.',
          hints: [
            { level: 1, text: "Alias each side's column AS contact so the result has one clean column name (remember: the first side names the output)." },
            { level: 2, text: 'Two customers have NULL emails - add WHERE email IS NOT NULL to the customers side so NULL collapsing does not skew the count.' },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'customers',
            requiredColumns: ['contact'],
            requireSetOp: 'UNION',
            expectedRowCount: 19,
          },
          successMessage: 'UNION and UNION ALL agree on 19 rows once NULLs are handled - dedupe is a true no-op, and the NULL trap is defused.',
          databaseLifecycle: 'fresh',
        },
      ],
    },
    {
      id: 'shape-compatibility',
      order: 3,
      title: '3. Shape Compatibility: The Rule Both Sides Must Obey',
      shortDescription: 'Equal column count, compatible types — or the engine refuses to run.',
      theory: {
        summary: 'Stacking only makes sense if the two results have the same shape: the same number of columns, with compatible types, position by position. A 2-column result cannot be stacked on a 1-column result — and SQLens refuses loudly instead of guessing.',
        introTable: {
          tableName: 'Compatible vs incompatible shapes',
          description: 'What the engine checks before stacking',
          columns: ['Top side', 'Bottom side', 'Compatible?'],
          rows: [
            ['name (text)', 'name (text)', 'Yes'],
            ['name, city (2 cols)', 'name (1 col)', 'No — column count'],
            ['price (number)', 'price_text (text)', 'Risky — types must align'],
          ],
        },
        explanation: [
          'The rule: **both sides must return the same number of columns**, and each column pair must be type-compatible — text with text, number with number.',
          '```sql\n-- ✕ 2 columns on top, 1 below — this ERRORS:\nSELECT name, city FROM customers\nUNION ALL\nSELECT name FROM suppliers;\n```',
          'QUESTION_BLOCK::SHAPE::Why does the engine refuse instead of padding with NULLs?',
          'Why so strict? Silently padding a missing column with NULLs would produce a directory where every supplier has a mystery city. Hiding a shape mistake would corrupt reports — so the engine errors with the exact counts: "left side: 2, right side: 1".',
          "Read the error like a mechanic: it tells you **which operator** failed and **both sides' column counts**. Count your two SELECT lists and make them agree.",
          'A subtlety worth owning: column **names** do not need to match — only positions. `SELECT email AS contact … UNION ALL SELECT contact_email …` is legal, because position 1 is text on both sides. The result simply uses the first side\'s names.',
        ],
        targetQuery: {
          sql: 'SELECT name, city FROM customers\nUNION ALL\nSELECT name FROM suppliers;',
          explanation: 'A deliberately broken query: 2 columns stacked on 1. Watch the engine refuse — this error is the lesson.',
          badge: 'The query we are going to break on purpose',
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: Count the columns on the top side',
            sqlSnippet: 'SELECT name, city FROM customers',
            explanation: 'Two columns: name, city.',
            tableData: {
              tableName: 'Top side shape',
              columns: ['name', 'city'],
              rows: [['Rafiul Islam', 'Dhaka']],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: Count the columns on the bottom side',
            sqlSnippet: 'SELECT name FROM suppliers',
            explanation: 'One column: name. The shapes disagree — 2 vs 1.',
            tableData: {
              tableName: 'Bottom side shape',
              columns: ['name'],
              rows: [['TechSource Ltd']],
            },
          },
          {
            stepNumber: 3,
            stepTitle: 'Step 3: The engine refuses — loudly',
            sqlSnippet: 'UNION_ALL requires both sides to return the same number of columns (left side: 2, right side: 1).',
            explanation: 'The error names the operator and both counts. Fix = make the SELECT lists agree: drop city from the top, or add a matching column below.',
            tableData: {
              tableName: 'Error',
              columns: ['message'],
              rows: [['UNION_ALL requires both sides to return the same number of columns (left side: 2, right side: 1).']],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'The compatibility checklist',
            sql: 'SELECT colA, colB FROM t1\nUNION ALL\nSELECT colX, colY FROM t2;  -- ✓ 2 ↔ 2, types align',
            description: 'Same column count per side; each position must be type-compatible.',
          },
        ],
        keyTakeaway: "Set operations stack rows position by position, so both sides need the same column count with compatible types. The engine errors loudly on mismatches — read the two counts in the message and make the SELECT lists agree.",
        exampleQuery: 'SELECT name, city FROM customers UNION ALL SELECT name, city FROM students;',
        exampleQueryExplanation: 'A legal 2-on-2 stack: both sides produce name and city, positionally aligned.',
        liveDemoSql: 'SELECT name, city FROM customers UNION ALL SELECT name, city FROM students;',
        liveDemoNotes: 'The fixed version: 2 columns on both sides, 20 rows stacked cleanly.',
        mcqs: [
          {
            question: 'What does a set operation NOT require of its two sides?',
            options: [
              'A. The same number of columns',
              'B. Type-compatible columns at each position',
              'C. Identical column names on both sides',
              'D. Both must be SELECT queries',
            ],
            correctIndex: 2,
            explanation: "Only positions and counts matter — names come from the first side, so the second side's aliases are ignored.",
          },
          {
            question: 'The error says "left side: 2, right side: 1". What is the fix?',
            options: [
              'A. Add DISTINCT',
              'B. Make both SELECT lists return the same number of columns',
              'C. Replace UNION ALL with UNION',
              'D. Add a WHERE clause',
            ],
            correctIndex: 1,
            explanation: 'The counts must agree: remove a column from the 2-column side or add a matching column to the 1-column side.',
          },
        ],
        commonMistakes: [
          'Assuming column names must match — only count, order, and types do.',
          'Fixing a shape error by deleting random columns — always compare the two SELECT lists position by position.',
        ],
        masteryPoints: ['Diagnose a shape error from its two counts', 'Write a legal 2-column stack with aligned positions'],
      },
      tasks: [
        {
          id: 'shape-compat-t1',
          title: 'Bug Hunt (Guided): Repair the broken directory',
          description: "A teammate's combined directory refuses to run. Diagnose the shape mismatch, then fix it so both sides stack cleanly.",
          instructions: [
            'The broken query: `SELECT name, city FROM customers UNION ALL SELECT name FROM suppliers;` — run it and read the error.',
            'Fix it so both sides return 2 aligned columns: keep `name, city` on top, and on the bottom add a matching second column — `NULL AS city`.',
            'Expect 21 rows with supplier rows showing NULL city.',
          ],
          type: 'guided',
          primaryTable: 'customers',
          secondaryTables: ['suppliers'],
          initialSql: '-- Broken: run it first to see the shape error\nSELECT name, city FROM customers\nUNION ALL\nSELECT name FROM suppliers;\n',
          solutionSql: 'SELECT name, city FROM customers UNION ALL SELECT name, NULL AS city FROM suppliers;',
          solutionExplanation: 'The repair pattern: `SELECT name, NULL AS city FROM suppliers` aligns a second (NULL) column under city — legal because suppliers simply have no city data. 21 rows, supplier cities honestly NULL.',
          hints: [
            { level: 1, text: 'The bottom side needs a second column that is type-compatible with city. A literal NULL AS city is a real column position — padding honestly, not hiding.' },
            { level: 2, text: 'Fixed bottom side: SELECT name, NULL AS city FROM suppliers' },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'customers',
            requiredColumns: ['name', 'city'],
            requireSetOp: 'UNION ALL',
            expectedRowCount: 21,
          },
          successMessage: 'Shape diagnosed from the error counts and repaired with an honest NULL pad — that is how developers read production errors.',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'shape-compat-t2',
          title: 'Task 2 (Independent): Build an aligned 2-column stack',
          description: 'From scratch this time: stack customers and students (both tables have name and city) into one 2-column directory.',
          instructions: [
            'SELECT `name, city` FROM `customers` UNION ALL SELECT `name, city` FROM `students`.',
            'Both sides must be 2 columns, text-then-text. Expect 20 rows.',
          ],
          type: 'independent',
          primaryTable: 'customers',
          secondaryTables: ['students'],
          initialSql: '-- Aligned 2-column stack\n',
          solutionSql: 'SELECT name, city FROM customers UNION ALL SELECT name, city FROM students;',
          solutionExplanation: '2 ↔ 2 columns, text ↔ text at each position: 15 + 5 = 20 rows stack cleanly.',
          hints: [
            { level: 1, text: 'Both tables have exactly the columns you need: name and city. Mirror the lists position for position.' },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'customers',
            requiredColumns: ['name', 'city'],
            requireSetOp: 'UNION ALL',
            expectedRowCount: 20,
          },
          successMessage: 'Aligned stack built from scratch — the compatibility checklist is now a habit.',
          databaseLifecycle: 'fresh',
        },
      ],
    },
    {
      id: 'except-antijoin',
      order: 4,
      title: '4. EXCEPT: Set Difference as a Declarative Anti-Join',
      shortDescription: 'Rows in the first result that have no match in the second.',
      theory: {
        summary: 'Day 14 found never-ordered products with LEFT JOIN + IS NULL. There is a second, more direct way: EXCEPT returns the rows of the first SELECT that do not appear anywhere in the second. You state WHAT you want — "products minus ordered products" — instead of engineering a join that fails to match.',
        introTable: {
          tableName: 'products vs order_items',
          description: 'Two 1-column results: all product IDs, and the IDs that have actually been ordered',
          columns: ['products (product_id)', 'order_items (product_id)'],
          rows: [
            ['1', '1'],
            ['2', '4'],
            ['3', '6'],
            ['… all 28', '… 22 distinct ordered'],
          ],
        },
        explanation: [
          'EXCEPT keeps every row of the **left** query that does not appear in the **right** query. Whole-row, position-by-position comparison — same rule as UNION dedupe, but subtracting instead of collapsing.',
          '```sql\nSELECT product_id FROM products\nEXCEPT\nSELECT product_id FROM order_items;\n```',
          'QUESTION_BLOCK::LEFT::What does the left query list?\nQUESTION_BLOCK::RIGHT::What does the right query list?\nQUESTION_BLOCK::MINUS::What survives the EXCEPT?',
          'Direction matters! `A EXCEPT B` is not `B EXCEPT A`. Products-without-orders and orders-without-products are different questions — always ask which side is "the everything" and which is "the subset".',
          'Two tools, one job: the LEFT JOIN + IS NULL anti-join works on *any* pair of related tables and can carry extra columns naturally. EXCEPT needs matching shapes but states the intent directly. Owning both means you choose per situation instead of memorizing one incantation.',
        ],
        targetQuery: {
          sql: 'SELECT product_id FROM products\nEXCEPT\nSELECT product_id FROM order_items;',
          explanation: 'The 6 product IDs that exist in the catalog but appear nowhere in order_items — dead stock, found declaratively.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: The left query lists every catalog product',
            sqlSnippet: 'SELECT product_id FROM products',
            explanation: '28 IDs — the complete "everything" side.',
            tableData: {
              tableName: 'Left result (28 rows)',
              columns: ['product_id'],
              rows: [[1], [2], [3], ['…']],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: The right query lists every product that has been ordered',
            sqlSnippet: 'SELECT product_id FROM order_items',
            explanation: '22 distinct IDs appear in order_items — the "already taken" side.',
            tableData: {
              tableName: 'Right result (22 distinct rows)',
              columns: ['product_id'],
              rows: [[1], [4], [6], ['…']],
            },
          },
          {
            stepNumber: 3,
            stepTitle: 'Step 3: EXCEPT keeps left rows absent from the right',
            sqlSnippet: '… EXCEPT …',
            explanation: 'Each left ID is checked against the right set. 6 IDs never appear there: 3, 9, 19, 25, 27, 28 — the never-ordered products.',
            tableData: {
              tableName: 'EXCEPT result (6 rows)',
              columns: ['product_id'],
              highlightedRows: [0, 2, 5],
              rows: [[3], [9], [19], [25], [27], [28]],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'EXCEPT syntax',
            sql: 'SELECT col1 FROM table_a\nEXCEPT\nSELECT col1 FROM table_b;',
            description: 'Keeps left rows that never appear in the right result. Shapes must be compatible (Concept 3).',
          },
        ],
        keyTakeaway: 'EXCEPT = "rows in the first result that never appear in the second." It is the declarative version of the anti-join: state the two lists, subtract, done. Direction always matters.',
        exampleQuery: 'SELECT product_id FROM products EXCEPT SELECT product_id FROM order_items;',
        exampleQueryExplanation: 'The 6 never-ordered products — the same answer Day 14 got from LEFT JOIN + IS NULL, in two lines.',
        liveDemoSql: 'SELECT product_id FROM products EXCEPT SELECT product_id FROM order_items;',
        liveDemoNotes: 'Compare with the Day 14 anti-join on the same data — identical 6 products, different machinery.',
        mcqs: [
          {
            question: '`SELECT city FROM customers EXCEPT SELECT city FROM students` returns…',
            options: [
              'A. Cities present in both tables',
              'B. Cities of customers that no student lives in',
              'C. Cities of students that no customer lives in',
              'D. All cities from both tables, deduplicated',
            ],
            correctIndex: 1,
            explanation: 'EXCEPT keeps LEFT rows missing from the right. Direction is the whole meaning — swap the sides and you answer the opposite question.',
          },
          {
            question: 'Which concept from Day 14 answers the same question as EXCEPT?',
            options: [
              'A. INNER JOIN + GROUP BY',
              'B. LEFT JOIN + WHERE right.id IS NULL (the anti-join)',
              'C. COUNT(DISTINCT)',
              'D. Scalar subquery',
            ],
            correctIndex: 1,
            explanation: 'Both find "left rows with no match on the right." EXCEPT states it directly; the anti-join builds it from a failed match.',
          },
          {
            question: 'What shape rule does EXCEPT follow?',
            options: [
              'A. None — it compares table structures automatically',
              'B. Same as UNION: equal column count, compatible types, position by position',
              'C. The left side may have more columns',
              'D. Only single-column results are allowed',
            ],
            correctIndex: 1,
            explanation: 'EXCEPT compares whole rows positionally — identical compatibility rules as the UNION family.',
          },
        ],
        commonMistakes: [
          'Reversing the sides — `order_items EXCEPT products` answers "ordered IDs not in the catalog" (usually nothing), the opposite of the business question.',
          'Trying to EXCEPT results with different column counts — same compatibility rule as UNION, same loud error.',
        ],
        masteryPoints: ['Use EXCEPT to find rows with no match on the other side', 'Predict how swapping the two sides changes the question'],
      },
      tasks: [
        {
          id: 'except-t1',
          title: 'Task 1 (Guided): Never-ordered products, the direct way',
          description: 'Day 14 needed a LEFT JOIN and an IS NULL check for this. Now state it directly: product IDs that appear nowhere in order_items.',
          instructions: [
            'SELECT `product_id` FROM `products` EXCEPT SELECT `product_id` FROM `order_items`.',
            'Expect 6 rows. After it works, mentally replay the Day 14 anti-join — same answer, different tool.',
          ],
          type: 'guided',
          primaryTable: 'products',
          secondaryTables: ['order_items'],
          initialSql: '-- Never-ordered products via EXCEPT\n',
          solutionSql: 'SELECT product_id FROM products EXCEPT SELECT product_id FROM order_items;',
          solutionExplanation: '6 products (IDs 3, 9, 19, 25, 27, 28) have never appeared on any order line — dead stock, found in two lines.',
          hints: [
            { level: 1, text: 'The "everything" side (products) goes on the LEFT of EXCEPT; the "already taken" side (order_items) goes on the right.' },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'products',
            requiredColumns: ['product_id'],
            requireSetOp: 'EXCEPT',
            expectedRowCount: 6,
          },
          successMessage: 'Same 6 products as Day 14 — but you stated the intent instead of engineering a failed match. That is what "declarative" means.',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'except-t2',
          title: 'Task 2 (Independent): Customers who never ordered',
          description: 'New pair, same direction logic: find the IDs of customers who have never placed an order. (You met them on Day 14 as the zero-order trio.)',
          instructions: [
            'SELECT `customer_id` FROM `customers` EXCEPT SELECT `customer_id` FROM `orders`.',
            'Expect 3 rows — the zero-order customers.',
          ],
          type: 'independent',
          primaryTable: 'customers',
          secondaryTables: ['orders'],
          initialSql: '-- Zero-order customers via EXCEPT\n',
          solutionSql: 'SELECT customer_id FROM customers EXCEPT SELECT customer_id FROM orders;',
          solutionExplanation: 'Customers 13, 14, 15 appear in the catalog but never in orders — the zero-order trio, no join required.',
          hints: [
            { level: 1, text: 'Which side is "everyone"? All customers. Which side is "has ordered"? The orders. Everyone minus has-ordered.' },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'customers',
            requiredColumns: ['customer_id'],
            requireSetOp: 'EXCEPT',
            expectedRowCount: 3,
          },
          successMessage: 'Third anti-join question this milestone, answered in one operator — the pattern is officially transferable.',
          databaseLifecycle: 'fresh',
        },
      ],
    },
  ],
  // ===========================================================================
  // DAY 17 CHALLENGE: COMBINE & SUBTRACT (ENDING ACTIVITY)
  // ===========================================================================
  challenge: {
    id: 'day-17-homework',
    title: 'Day 17 — Set Operations Challenge (Ending Activity)',
    scenario: "Three deliverables that stack, tag, and subtract across the whole schema — combining today's operators with everything from Milestone 2:",
    databaseLifecycle: 'fresh',
    tasks: [
      {
        id: 'setops-hw-1',
        title: 'Task 1: The tagged all-people directory',
        description: 'One sorted list of every person in the system — customers and suppliers — each row tagged with its source. Sort by the tag (Customer first), then by name.',
        instructions: [
          "SELECT `name`, `'Customer' AS source` FROM `customers` UNION ALL SELECT `name`, `'Supplier' AS source` FROM `suppliers`.",
          'Add ORDER BY `source, name` at the very end (after the last SELECT) to sort the combined result.',
        ],
        type: 'challenge',
        primaryTable: 'customers',
        secondaryTables: ['suppliers'],
        initialSql: '-- Challenge: tagged, sorted directory\n',
        solutionSql: "SELECT name, 'Customer' AS source FROM customers UNION ALL SELECT name, 'Supplier' AS source FROM suppliers ORDER BY source, name;",
        solutionExplanation: '21 tagged rows: all 15 customers alphabetically first, then the 6 suppliers — one ORDER BY applied to the combined stack.',
        hints: [
          { level: 1, text: 'The ORDER BY comes after the FINAL SELECT and sorts the whole combined result — one ORDER BY for the union, not one per side.' },
        ],
        validation: {
          requireExactResult: true,
          targetTable: 'customers',
          requiredColumns: ['name', 'source'],
          requireSetOp: 'UNION ALL',
          expectedRowCount: 21,
        },
        successMessage: 'Directory shipped — stacking, tagging, and sorting in one statement.',
      },
      {
        id: 'setops-hw-2',
        title: 'Task 2: Dead stock report (EXCEPT edition)',
        description: "The warehouse team wants the dead-stock list — catalog products that have never sold — and this time they want product names, not just IDs.",
        instructions: [
          'Left side: SELECT `product_id, name` FROM `products`.',
          'Right side: the same two columns from the ordered products — `SELECT oi.product_id, p.name FROM order_items oi JOIN products p ON oi.product_id = p.product_id`.',
          'Combine with EXCEPT. Expect 6 rows.',
        ],
        type: 'challenge',
        primaryTable: 'products',
        secondaryTables: ['order_items'],
        initialSql: '-- Challenge: dead stock, with names\n',
        solutionSql: 'SELECT product_id, name FROM products EXCEPT SELECT oi.product_id, p.name FROM order_items oi JOIN products p ON oi.product_id = p.product_id;',
        solutionExplanation: 'A 2-column EXCEPT: the right side is itself a join, but the set operation only cares about the shape — 2 aligned columns. The 6 dead-stock products come back with names.',
        hints: [
          { level: 1, text: 'Both sides need the SAME two columns in the SAME order: product_id, then name. The right side may be any query — including a JOIN.' },
        ],
        validation: {
          requireExactResult: true,
          targetTable: 'products',
          requiredColumns: ['product_id', 'name'],
          requireSetOp: 'EXCEPT',
          expectedRowCount: 6,
        },
        successMessage: 'Dead stock named and reported — a 2-column EXCEPT with a join inside, and the compatibility rules held.',
      },
      {
        id: 'setops-hw-3',
        title: "Task 3: Cities we serve but the university doesn't (final boss)",
        description: 'A partnership report: cities where the shop has customers but no students live. One EXCEPT, one direction decision — get the sides right and the answer falls out.',
        instructions: [
          'Left side: SELECT `city` FROM `customers`.',
          'Right side: SELECT `city` FROM `students`.',
          'Combine with EXCEPT. Expect 4 rows.',
        ],
        type: 'challenge',
        primaryTable: 'customers',
        secondaryTables: ['students'],
        initialSql: '-- Challenge: customers-only cities\n',
        solutionSql: 'SELECT city FROM customers EXCEPT SELECT city FROM students;',
        solutionExplanation: 'Chittagong, Sylhet, Khulna, Barisal — customer cities with zero student residents. (Dhaka and Rajshahi drop out: students live there too.)',
        hints: [
          { level: 1, text: '"Cities we serve" = customers (left). "Cities the university covers" = students (right). Everything-on-the-left minus the right.' },
        ],
        validation: {
          requireExactResult: true,
          targetTable: 'customers',
          requiredColumns: ['city'],
          requireSetOp: 'EXCEPT',
          expectedRowCount: 4,
        },
        successMessage: 'Challenge complete — stack, tag, subtract, align: the full set-operation toolkit, applied to real reporting questions.',
      },
    ],
  },
};
