import { ModuleData } from '../../types/curriculum';

export const Day_13_MODULE: ModuleData = {
  id: 'day-10',
  slug: 'practice-reporting',
  day: 10,
  title: 'Day 10 — Guided Practice: Reporting & Aggregation',
  shortTitle: 'Practice: Reporting & Aggregation',
  type: 'practice_day',
  milestoneId: 'milestone-2',
  description: 'Construct multi-metric reporting widgets and dashboards combining COUNT, SUM, AVG, GROUP BY, and HAVING post-aggregation thresholds.',
  estimatedMinutes: 60,
  completionLearnings: [
    'Construct multi-metric category and inventory summary reports combining multiple aggregates in a single SELECT',
    'Differentiate between row-level WHERE filters and group-level HAVING filters in the same query',
    'Apply post-aggregation thresholds using HAVING to isolate high-volume categories',
  ],
  concepts: [
    {
      id: 'reporting-widgets',
      order: 1,
      title: '1. Multi-Metric Reporting Queries & Dashboards',
      shortDescription: 'Combine multiple aggregates into business summary widgets.',
      theory: {
        summary: 'Reporting queries combine multiple aggregate calculations (counts, totals, averages) with group-level filtering (HAVING) and sorting to power executive dashboards.',
        introTable: {
          tableName: 'products',
          description: 'Inventory metrics snapshot per category',
          columns: ['category_id', 'COUNT(*)', 'AVG(price)', 'SUM(quantity_in_stock)'],
          rows: [
            [1, 6, 31.79, 88],
            [2, 5, 28.56, 102],
            [3, 5, 47.15, 187],
            [4, 5, 29.10, 102],
            [5, 6, 20.62, 137],
          ],
        },
        explanation: [
          '### 1. The Multi-Metric Dashboard Pattern',
          'A single SQL query can compute item count, average price, and total stock volume simultaneously:',
          '```sql\nSELECT category_id, COUNT(*) AS product_count, AVG(price) AS avg_price, SUM(quantity_in_stock) AS total_units\nFROM products\nGROUP BY category_id\nHAVING AVG(price) > 25\nORDER BY product_count DESC;\n```',
          '### 2. The Dual-Filter Rule (WHERE vs HAVING)',
          '• **`WHERE`** filters individual rows *before* grouping (e.g. `WHERE quantity_in_stock > 0`).',
          '• **`HAVING`** filters aggregated group metrics *after* grouping (e.g. `HAVING COUNT(*) >= 5`).',
        ],
        targetQuery: {
          sql: 'SELECT category_id, COUNT(*) AS product_count, AVG(price) AS avg_price, SUM(quantity_in_stock) AS total_units\nFROM products\nGROUP BY category_id\nHAVING AVG(price) > 15\nORDER BY product_count DESC;',
          explanation: 'Generate an executive category audit report for categories averaging over $15, sorted by product count.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: FROM products GROUP BY category_id (Group and aggregate)',
            sqlSnippet: 'FROM products GROUP BY category_id',
            explanation: 'Computes product count, avg price, and total stock per category.',
            tableData: {
              tableName: 'products (Aggregated Groups)',
              columns: ['category_id', 'product_count', 'avg_price', 'total_units'],
              rows: [
                [1, 6, 31.79, 88],
                [5, 6, 20.62, 137],
                [2, 5, 28.56, 102],
                [3, 5, 47.15, 187],
                [4, 5, 29.10, 102],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: HAVING AVG(price) > 15 ORDER BY product_count DESC',
            sqlSnippet: 'HAVING AVG(price) > 15 ORDER BY product_count DESC',
            explanation: 'Filters categories averaging over $15 and sorts highest product volume first.',
            tableData: {
              tableName: 'Category Audit Report Result',
              columns: ['category_id', 'product_count', 'avg_price', 'total_units'],
              highlightedColumns: ['category_id', 'product_count', 'avg_price', 'total_units'],
              highlightedRows: [0, 1, 2, 3, 4],
              rows: [
                [1, 6, 31.79, 88],
                [5, 6, 20.62, 137],
                [2, 5, 28.56, 102],
                [3, 5, 47.15, 187],
                [4, 5, 29.10, 102],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Multi-metric dashboard query',
            sql: 'SELECT category_id, COUNT(*) AS item_count, AVG(price) AS avg_price, SUM(quantity_in_stock) AS total_stock\nFROM products\nGROUP BY category_id\nHAVING AVG(price) > 15\nORDER BY item_count DESC;',
            description: 'Comprehensive category health metric.',
          },
        ],
        keyTakeaway: 'Combine multiple aggregate functions in a single SELECT to build rich summaries.',
        exampleQuery: 'SELECT category_id, COUNT(*) AS total_items, AVG(price) AS avg_price FROM products GROUP BY category_id HAVING AVG(price) > 15 ORDER BY total_items DESC;',
        exampleQueryExplanation: 'Produces category overview for categories with average price above $15.',
        liveDemoSql: 'SELECT category_id, COUNT(*) AS total_items, AVG(price) AS avg_price FROM products GROUP BY category_id HAVING AVG(price) > 15 ORDER BY total_items DESC;',
        liveDemoNotes: 'Displays category overview report.',
        mcqs: [
          {
            question: 'Can you use multiple aggregate functions like COUNT, AVG, and SUM in the same SELECT statement?',
            options: [
              'A. No, only one aggregate function per query',
              'B. Yes, you can calculate multiple metrics simultaneously',
              'C. Only if using subqueries',
              'D. Only in MySQL 8.0+',
            ],
            correctIndex: 1,
            explanation: 'SQL allows multiple aggregate expressions in a single query.',
          },
        ],
        masteryPoints: ['Construct multi-metric reporting widgets unaided'],
      },
      tasks: [
        {
          id: 'day10-c1-t1',
          title: 'Task 1 (High Guidance): Category Overview Widget',
          description: 'Calculate product count and average price per category for categories averaging above $15, sorted by product count descending.',
          instructions: [
            'Query the `products` table.',
            'Select `category_id`, `COUNT(*) AS product_count`, and `AVG(price) AS avg_price`.',
            'Group by `category_id`.',
            'Filter with `HAVING AVG(price) > 15`.',
            'Sort by `product_count DESC`.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'products',
          initialSql: '-- Task 1: High Guidance - Category overview widget\nSELECT category_id, COUNT(*) AS product_count, AVG(price) AS avg_price\nFROM products\nGROUP BY category_id\nHAVING AVG(price) > 15\nORDER BY product_count DESC;',
          solutionSql: 'SELECT category_id, COUNT(*) AS product_count, AVG(price) AS avg_price FROM products GROUP BY category_id HAVING AVG(price) > 15 ORDER BY product_count DESC;',
          solutionExplanation: 'Computes metrics, filters categories averaging > $15, and sorts by count descending.',
          hints: [
            { level: 1, text: 'Use `GROUP BY category_id` to aggregate per category.' },
            { level: 2, text: 'Add `HAVING AVG(price) > 15 ORDER BY product_count DESC;`.' },
          ],
          validation: {
            targetTable: 'products',
            requireGroupBy: true,
            requireHaving: true,
            requireOrderBy: [{ column: 'product_count', direction: 'DESC' }],
            expectedRowCount: 5,
          },
          successMessage: 'Task 1 completed! Category overview report generated.',
        },
        {
          id: 'day10-c1-t2',
          title: 'Task 2 (Partial Guidance): Order Status Breakdown',
          description: 'Count the total number of orders for each status in the orders table, sorted by count descending.',
          instructions: [
            'Query the `orders` table.',
            'Select `status` and `COUNT(*) AS order_count`.',
            'Group by `status`.',
            'Order by `order_count DESC`.',
          ],
          type: 'independent',
          primaryTable: 'orders',
          initialSql: '-- Task 2: Partial Guidance - Order status metrics\n',
          solutionSql: 'SELECT status, COUNT(*) AS order_count FROM orders GROUP BY status ORDER BY order_count DESC;',
          solutionExplanation: 'Groups orders by status and calculates counts.',
          hints: [
            { level: 1, text: 'Select `status` and `COUNT(*) AS order_count`.' },
            { level: 2, text: 'Use `GROUP BY status ORDER BY order_count DESC;`.' },
          ],
          validation: {
            targetTable: 'orders',
            requiredColumns: ['status', 'order_count'],
            requireGroupBy: true,
            requireOrderBy: [{ column: 'order_count', direction: 'DESC' }],
            expectedRowCount: 4,
          },
          successMessage: 'Task 2 completed! Order status breakdown generated.',
        },
        {
          id: 'day10-c1-t3',
          title: 'Task 3 (Goal Only): In-Stock Category Inventory Audit',
          description: 'Count how many in-stock products each category has (ignore products with zero stock). Only include categories that have at least 4 in-stock products, and put the categories with the most in-stock products first.',
          instructions: [
            'Select `category_id` and `COUNT(*) AS in_stock_count` from `products`.',
            'Filter rows with `WHERE quantity_in_stock > 0` before grouping.',
            'Group by `category_id`.',
            'Filter groups with `HAVING COUNT(*) >= 4`.',
            'Order by `in_stock_count DESC`.',
          ],
          type: 'independent',
          primaryTable: 'products',
          initialSql: '-- Task 3: Goal Only - In-stock category inventory audit\n',
          solutionSql: 'SELECT category_id, COUNT(*) AS in_stock_count FROM products WHERE quantity_in_stock > 0 GROUP BY category_id HAVING COUNT(*) >= 4 ORDER BY in_stock_count DESC;',
          solutionExplanation: 'Combines row-level WHERE with group-level HAVING filter.',
          hints: [
            { level: 1, text: 'Use `WHERE quantity_in_stock > 0` before `GROUP BY category_id`.' },
            { level: 2, text: 'Add `HAVING COUNT(*) >= 4 ORDER BY in_stock_count DESC;`.' },
          ],
          validation: {
            targetTable: 'products',
            requireWhere: true,
            requireGroupBy: true,
            requireHaving: true,
            expectedRowCount: 5,
          },
          successMessage: 'Task 3 completed! In-stock category inventory audit generated.',
        },
      ],
    },
  ],

  // ===========================================================================
  // DAY 10 CHALLENGE: BUILD AN EXECUTIVE DASHBOARD WIDGET (ENDING ACTIVITY)
  // ===========================================================================
  challenge: {
    id: 'day-10-homework',
    title: 'Day 10 — Build an Executive Dashboard Widget (Ending Activity)',
    scenario: 'Build the Category Overview dashboard widget independently (business requirements only):',
    tasks: [
      {
        id: 'day10-hw-1',
        title: 'Task 1: "Category Overview" Dashboard Widget',
        description: '"Category Overview" dashboard widget — product count and average price per category, only categories averaging above $15, sorted by product count descending.',
        instructions: [
          'Select `category_id`, `COUNT(*) AS product_count`, `AVG(price) AS avg_price` from `products` grouped by `category_id` having `AVG(price) > 15` order by `product_count DESC`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Challenge: Category Overview dashboard widget\n',
        solutionSql: 'SELECT category_id, COUNT(*) AS product_count, AVG(price) AS avg_price FROM products GROUP BY category_id HAVING AVG(price) > 15 ORDER BY product_count DESC;',
        solutionExplanation: 'Constructs the full multi-clause category overview report.',
        hints: [{ level: 1, text: 'Use `SELECT category_id, COUNT(*) AS product_count, AVG(price) AS avg_price FROM products GROUP BY category_id HAVING AVG(price) > 15 ORDER BY product_count DESC;`' }],
        validation: {
          targetTable: 'products',
          requireGroupBy: true,
          requireHaving: true,
          requireOrderBy: [{ column: 'product_count', direction: 'DESC' }],
          expectedRowCount: 5,
        },
        successMessage: 'Challenge completed! Category Overview widget verified.',
      },
    ],
  },
};
