import { ModuleData } from '../../types/curriculum';

export const Day_18_MODULE: ModuleData = {
  id: 'day-18',
  slug: 'project-part-2-multi-table-reporting',
  day: 18,
  title: 'Day 18 — Applied Project: Build a BI Analytics Dashboard',
  shortTitle: 'Project: BI Dashboard',
  type: 'project_part',
  milestoneId: 'milestone-2',
  description: 'Real BI analyst role: build three production-ready reports — top-selling products, VIP customer leaderboard by spend, and discover dead inventory (products never ordered). Master aggregates, JOINs, and anti-JOINs in a real project.',
  estimatedMinutes: 90,
  completionLearnings: [
    'Aggregate order items to rank products by total sales volume',
    'Join 3+ tables to calculate VIP customer revenue and identify top spenders',
    'Use anti-JOINs (LEFT JOIN + WHERE IS NULL) to find items that do not exist in related tables',
  ],
  concepts: [
    {
      id: 'multi-table-reporting-patterns',
      order: 1,
      title: '1. Production BI Reports: Sales Volume, VIP Rankings & Dead Inventory',
      shortDescription: 'Aggregate products by sales, rank customers by spend, find items never ordered.',
      theory: {
        summary: 'Welcome to the Business Intelligence (BI) team! Today you build three key executive reports: sales volume by product, top spending VIP customers, and identifying catalog items that have never been ordered using anti-joins.',
        introTable: {
          tableName: 'products & order_items',
          description: 'Product catalog joined with order line items',
          columns: ['p.product_id', 'p.name', 'oi.quantity', 'oi.unit_price'],
          rows: [
            [1, 'Wireless Mouse', 2, 15.99],
            [2, 'Bluetooth Speaker', 1, 45.50],
            [4, 'Mechanical Keyboard', 2, 65.00],
            [28, 'Clearance Item', null, null],
          ],
        },
        explanation: [
          '### 1. The Anti-Join Pattern (Never Ordered)',
          'To find items that have never been purchased, `LEFT JOIN order_items` onto `products` and filter with `WHERE oi.order_item_id IS NULL`.',
          'Any product that has no matching row in `order_items` will have `NULL` for `oi.order_item_id`.',
        ],
        targetQuery: {
          sql: 'SELECT p.name, SUM(oi.quantity) AS total_units_sold\nFROM products p\nJOIN order_items oi ON p.product_id = oi.product_id\nGROUP BY p.product_id, p.name\nORDER BY total_units_sold DESC;',
          explanation: 'Aggregate line-item sales across products and rank products by total volume sold.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: FROM products p JOIN order_items oi ON p.product_id = oi.product_id',
            sqlSnippet: 'FROM products p JOIN order_items oi ON p.product_id = oi.product_id',
            explanation: 'Matches products with their order line items.',
            tableData: {
              tableName: 'Matched Product Line Items',
              columns: ['p.name', 'oi.quantity', 'oi.unit_price'],
              rows: [
                ['Wireless Mouse', 2, 15.99],
                ['Wireless Mouse', 5, 15.99],
                ['Mechanical Keyboard', 4, 65.00],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: GROUP BY p.product_id, p.name ORDER BY total_units_sold DESC',
            sqlSnippet: 'SELECT p.name, SUM(oi.quantity) AS total_units_sold GROUP BY p.product_id, p.name ORDER BY total_units_sold DESC',
            explanation: 'Sums total quantity per product and ranks top sellers first.',
            tableData: {
              tableName: 'Product Sales Volume Result',
              columns: ['name', 'total_units_sold'],
              highlightedColumns: ['name', 'total_units_sold'],
              highlightedRows: [0, 1, 2],
              rows: [
                ['Wireless Mouse', 7],
                ['Mechanical Keyboard', 4],
                ['USB-C Cable', 4],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Anti-join pattern (never ordered)',
            sql: 'SELECT p.product_id, p.name\nFROM products p\nLEFT JOIN order_items oi ON p.product_id = oi.product_id\nWHERE oi.order_item_id IS NULL;',
            description: 'Finds products with 0 purchase history.',
          },
        ],
        keyTakeaway: 'Use LEFT JOIN + IS NULL to detect non-existent relationships (anti-joins).',
        exampleQuery: 'SELECT p.name, SUM(oi.quantity) AS total_units_sold FROM products p JOIN order_items oi ON p.product_id = oi.product_id GROUP BY p.product_id, p.name ORDER BY total_units_sold DESC;',
        exampleQueryExplanation: 'Ranks products by total units sold.',
        liveDemoSql: 'SELECT p.name, SUM(oi.quantity) AS total_units_sold FROM products p JOIN order_items oi ON p.product_id = oi.product_id GROUP BY p.product_id, p.name ORDER BY total_units_sold DESC LIMIT 5;',
        liveDemoNotes: 'Displays top selling products.',
        mcqs: [
          {
            question: 'How does `LEFT JOIN order_items oi ... WHERE oi.order_item_id IS NULL` find unpurchased products?',
            options: [
              'A. By deleting purchased items',
              'B. Because unpurchased products have no match in order_items, so all order_items columns are filled with NULL',
              'C. By checking if price is 0',
              'D. By counting stock',
            ],
            correctIndex: 1,
            explanation: 'LEFT JOIN keeps unmatched left-table rows with NULLs for all right-table columns.',
          },
        ],
        masteryPoints: ['Write multi-table aggregate rankings', 'Master the LEFT JOIN + IS NULL anti-join pattern'],
      },
      tasks: [
        {
          id: 'day14-c1-t1',
          title: 'Mission 1 (Guided): Product Sales Volume Ranking',
          description: 'List products with their total units sold, sorted highest first.',
          instructions: [
            'Select `p.name`, `SUM(oi.quantity) AS total_units_sold` from `products p` JOIN `order_items oi` ON `p.product_id = oi.product_id`.',
            'Group by `p.product_id`, `p.name`.',
            'Order by `total_units_sold DESC`.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'products',
          secondaryTables: ['order_items'],
          initialSql: '-- Mission 1: Product units sold ranking\n',
          solutionSql: 'SELECT p.name, SUM(oi.quantity) AS total_units_sold FROM products p JOIN order_items oi ON p.product_id = oi.product_id GROUP BY p.product_id, p.name ORDER BY total_units_sold DESC;',
          solutionExplanation: 'Sums item quantities per product and sorts descending.',
          hints: [{ level: 1, text: 'Use `GROUP BY p.product_id, p.name ORDER BY total_units_sold DESC;`' }],
          validation: {
            requireExactResult: true,
            targetTable: 'products',
            requireJoin: true,
            requireGroupBy: true,
            requireOrderBy: [{ column: 'total_units_sold', direction: 'DESC' }],
            expectedRowCount: 22,
          },
          successMessage: 'Mission 1 complete! Product unit sales ranked.',
        },
        {
          id: 'day14-c1-t2',
          title: 'Mission 2 (Independent): Unpurchased Products Discovery',
          description: 'Identify all products that have never appeared in any order using a LEFT JOIN and IS NULL filter.',
          instructions: [
            'Query `products p` LEFT JOIN `order_items oi` ON `p.product_id = oi.product_id`.',
            'Select `p.product_id` and `p.name`.',
            'Filter where `oi.order_item_id IS NULL`.',
          ],
          type: 'independent',
          primaryTable: 'products',
          secondaryTables: ['order_items'],
          initialSql: '-- Mission 2: Anti-join for unpurchased products\n',
          solutionSql: 'SELECT p.product_id, p.name FROM products p LEFT JOIN order_items oi ON p.product_id = oi.product_id WHERE oi.order_item_id IS NULL;',
          solutionExplanation: 'Finds products with 0 recorded purchases.',
          hints: [{ level: 1, text: 'Use `WHERE oi.order_item_id IS NULL;`' }],
          validation: {
            requireExactResult: true,
            targetTable: 'products',
            requireJoin: true,
            requireWhere: true,
            whereContainsTerms: ['IS NULL'],
            expectedRowCount: 6,
          },
          successMessage: 'Mission 2 complete! Unpurchased inventory identified.',
        },
      ],
    },
  ],

  // ===========================================================================
  // DAY 14 CHALLENGE: DELIVER THE 3-PART EXECUTIVE BI REPORTING SUITE (ENDING ACTIVITY)
  // ===========================================================================
  challenge: {
    id: 'day-14-homework',
    title: 'Day 14 — Deliver the 3-Part Executive BI Reporting Suite (Ending Activity)',
    scenario: 'Construct all 3 core multi-table reports independently:',
    tasks: [
      {
        id: 'day14-hw-1',
        title: 'Report 1: Product Sales Volume Ranking',
        description: 'Products with total units sold, highest first.',
        instructions: [
          'Select `p.name`, `SUM(oi.quantity) AS total_units_sold` from `products p` JOIN `order_items oi` ON `p.product_id = oi.product_id` GROUP BY `p.product_id`, `p.name` ORDER BY `total_units_sold DESC`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        secondaryTables: ['order_items'],
        initialSql: '-- Report 1: Products with total units sold\n',
        solutionSql: 'SELECT p.name, SUM(oi.quantity) AS total_units_sold FROM products p JOIN order_items oi ON p.product_id = oi.product_id GROUP BY p.product_id, p.name ORDER BY total_units_sold DESC;',
        solutionExplanation: 'Calculates total units sold for each product.',
        hints: [{ level: 1, text: 'Use `GROUP BY p.product_id, p.name ORDER BY total_units_sold DESC;`' }],
        validation: {
          requireExactResult: true,
          targetTable: 'products',
          requireJoin: true,
          requireGroupBy: true,
          requireOrderBy: [{ column: 'total_units_sold', direction: 'DESC' }],
          expectedRowCount: 22,
        },
        successMessage: 'Report 1 verified! Product sales volume calculated.',
      },
      {
        id: 'day14-hw-2',
        title: 'Report 2: Top 5 VIP Spenders Leaderboard',
        description: 'Build a leaderboard of the 5 customers who have spent the most money across all their orders. Show each customer\'s id, name, and their total amount spent, best spender first.',
        instructions: [
          'Select `c.customer_id`, `c.name`, `SUM(oi.quantity * oi.unit_price) AS total_spent` from `customers c` JOIN `orders o` ON `c.customer_id = o.customer_id` JOIN `order_items oi` ON `o.order_id = oi.order_id` GROUP BY `c.customer_id`, `c.name` ORDER BY `total_spent DESC` LIMIT 5.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'customers',
        secondaryTables: ['orders', 'order_items'],
        initialSql: '-- Report 2: Top 5 VIP customers by spend\n',
        solutionSql: 'SELECT c.customer_id, c.name, SUM(oi.quantity * oi.unit_price) AS total_spent FROM customers c JOIN orders o ON c.customer_id = o.customer_id JOIN order_items oi ON o.order_id = oi.order_id GROUP BY c.customer_id, c.name ORDER BY total_spent DESC LIMIT 5;',
        solutionExplanation: 'Joins customers -> orders -> order_items, sums spending, and returns top 5.',
        hints: [{ level: 1, text: 'Use `GROUP BY c.customer_id, c.name ORDER BY total_spent DESC LIMIT 5;`' }],
        validation: {
          requireExactResult: true,
          targetTable: 'customers',
          requireJoin: true,
          requireGroupBy: true,
          requireOrderBy: [{ column: 'total_spent', direction: 'DESC' }],
          requireLimit: 5,
          expectedRowCount: 5,
        },
        successMessage: 'Report 2 verified! Top VIP customers identified.',
      },
      {
        id: 'day14-hw-3',
        title: 'Report 3: Unpurchased Products (Anti-Join)',
        description: 'Products that have never been ordered (LEFT JOIN + IS NULL anti-join).',
        instructions: [
          'Select `p.product_id`, `p.name` from `products p` LEFT JOIN `order_items oi` ON `p.product_id = oi.product_id` WHERE `oi.order_item_id IS NULL`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        secondaryTables: ['order_items'],
        initialSql: '-- Report 3: Products that have never been ordered\n',
        solutionSql: 'SELECT p.product_id, p.name FROM products p LEFT JOIN order_items oi ON p.product_id = oi.product_id WHERE oi.order_item_id IS NULL;',
        solutionExplanation: 'Anti-join with `WHERE oi.order_item_id IS NULL` finds products that have never appeared in any order.',
        hints: [{ level: 1, text: 'Use `WHERE oi.order_item_id IS NULL;`' }],
        validation: {
          requireExactResult: true,
          targetTable: 'products',
          requireJoin: true,
          requireWhere: true,
          whereContainsTerms: ['IS NULL'],
          expectedRowCount: 6,
        },
        successMessage: 'Report 3 verified! Unpurchased inventory identified.',
      },
    ],
  },
};
