import { ModuleData } from '../../types/curriculum';

// =============================================================================
// DAY 29 - DDL III: Schema Evolution (id: ddl-schema-evolution - order 29)
// Split out of the old day-20 DDL mega-module (atomic-rule fix). Atomic chain:
//   C1 ALTER TABLE - evolve a schema without losing data
//   C2 FOREIGN KEY - relationships the engine enforces
//   C3 DROP TABLE IF EXISTS - safe teardown for reproducible scripts
// =============================================================================
export const Day_29_MODULE: ModuleData = {
  id: 'ddl-schema-evolution',
  slug: 'ddl-schema-evolution',
  day: 0, // ordering uses curriculumOrder (Day 29)
  title: 'Day 29 - DDL III: Schema Evolution & Relationships',
  shortTitle: 'DDL III (Evolution & FK)',
  type: 'module',
  milestoneId: 'milestone-3',
  description: 'Schemas are living things: add columns without losing data via ALTER TABLE, make relationships enforceable with FOREIGN KEY, and tear down temporary schemas safely with DROP TABLE IF EXISTS.',
  estimatedMinutes: 50,
  completionLearnings: [
    'Add new columns to a live table with ALTER TABLE ... ADD COLUMN (no data loss)',
    'Connect tables with FOREIGN KEY so orphaned records become impossible',
    'Tear down tables safely with DROP TABLE IF EXISTS in reproducible scripts',
  ],
  concepts: [
    {
      id: 'ddl3-alter-table',
      order: 1,
      title: '1. Evolving a Schema with ALTER TABLE',
      shortDescription: 'Add a column to a live table - without losing data.',
      theory: {
        summary: 'Day 27 taught you to create a table. But real systems change after launch: products gain a discontinued flag, customers gain a loyalty tier. ALTER TABLE ADD COLUMN extends an existing table in place - every existing row keeps its data, and the new column is filled with NULL (or the DEFAULT you supply).',
        introTable: {
          tableName: 'products (before ALTER)',
          description: 'The catalog is live; marketing wants a short tagline per product.',
          columns: ['product_id', 'name', 'price'],
          rows: [
            [1, 'Wireless Mouse', 15.99],
            [2, 'Bluetooth Speaker', 45.5],
          ],
        },
        explanation: [
          'The syntax names the table, the new column, and its type:',
          '```sql\nALTER TABLE products\nADD COLUMN tagline VARCHAR(120);\n```',
          'QUESTION_BLOCK::DATA::After adding tagline, what do the 28 existing rows contain in that column?',
          'QUESTION_BLOCK::DEFAULT::How would you make the new column start at a non-NULL value?',
          'The question above: NULL - the column exists for every row, but no data was known at creation time. Add a DEFAULT (e.g. ADD COLUMN status VARCHAR(20) DEFAULT XactiveX) and existing rows are backfilled with it in the same statement. Either way, zero data loss - that is the whole point of ALTER over drop-and-recreate.',
          'The habit this builds: schemas evolve one safe step at a time. Recreating a table to add a column would orphan every FK pointing at it; ALTER keeps history intact.',
        ],
        targetQuery: {
          sql: 'ALTER TABLE products\nADD COLUMN tagline VARCHAR(120);',
          explanation: 'The live catalog gains a tagline column; all existing rows keep their data.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: Name the table and the new column',
            sqlSnippet: 'ALTER TABLE products ADD COLUMN tagline VARCHAR(120);',
            explanation: 'One statement, one structural change. The table grows a column; no rows are touched.',
            tableData: {
              tableName: 'After ALTER',
              columns: ['product_id', 'name', 'price', 'tagline'],
              highlightedColumns: ['tagline'],
              rows: [
                [1, 'Wireless Mouse', 15.99, null],
                [2, 'Bluetooth Speaker', 45.5, null],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'ALTER TABLE syntax',
            sql: 'ALTER TABLE table_name ADD COLUMN col_name data_type [DEFAULT value];',
            description: 'Adds a column to an existing table. Existing rows receive NULL or the supplied DEFAULT.',
          },
        ],
        keyTakeaway: 'ALTER TABLE ADD COLUMN evolves a live schema without data loss - new columns start NULL (or the DEFAULT) for existing rows.',
        exampleQuery: 'ALTER TABLE products ADD COLUMN tagline VARCHAR(120);',
        exampleQueryExplanation: '28 existing products keep everything; each gains an empty tagline ready to be filled.',
        liveDemoSql: 'ALTER TABLE products ADD COLUMN tagline VARCHAR(120);\nSELECT product_id, name, tagline FROM products LIMIT 3;',
        liveDemoNotes: 'Run the ALTER, then the SELECT: the new column is there, NULL on every existing row.',
        mcqs: [
          {
            question: 'What happens to existing rows when you ALTER TABLE ... ADD COLUMN?',
            options: [
              'A. They are deleted',
              'B. They keep their data; the new column is NULL (or its DEFAULT) for each',
              'C. The table must be empty first',
              'D. They are duplicated',
            ],
            correctIndex: 1,
            explanation: 'ALTER extends the schema in place - no data loss, new column starts NULL/DEFAULT.',
          },
          {
            question: 'How do you add a column whose existing rows should start at a real value, not NULL?',
            options: [
              'A. Impossible - new columns are always NULL',
              'B. Include DEFAULT in the ALTER - existing rows are backfilled',
              'C. Delete all rows first',
              'D. Use UPDATE only',
            ],
            correctIndex: 1,
            explanation: "ADD COLUMN status VARCHAR(20) DEFAULT 'active' backfills 'active' for every existing row in the same statement.",
          },
        ],
        commonMistakes: [
          'DROP-and-recreate to add a column - that orphans every foreign key pointing at the table.',
          'Forgetting the column type in the ALTER - ADD COLUMN needs a data type just like CREATE TABLE.',
        ],
        masteryPoints: ['Evolve a live table with ALTER TABLE ADD COLUMN', 'Choose DEFAULT vs NULL for new columns'],
      },
      tasks: [
        {
          id: 'ddl3-c1-t1',
          title: 'Task 1 (Guided): The tagline migration',
          description: 'The live products catalog needs a tagline column. Add it without touching any existing data.',
          instructions: [
            'Write `ALTER TABLE products ADD COLUMN tagline VARCHAR(120);`',
            "Then verify with `SELECT product_id, name, tagline FROM products LIMIT 3;` - tagline is NULL everywhere, data intact.",
          ],
          type: 'guided',
          primaryTable: 'products',
          initialSql: '-- Evolve the live catalog\n',
          solutionSql: 'ALTER TABLE products ADD COLUMN tagline VARCHAR(120);',
          solutionExplanation: 'The live table grew a column in one statement - all 28 rows kept their data.',
          hints: [{ level: 1, text: 'ALTER TABLE, then the table name, then ADD COLUMN with the type.' }],
          validation: { targetTable: 'products', expectedRowCount: 1 },
          successMessage: 'Live schema evolved with zero data loss!',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'ddl3-c1-t2',
          title: 'Task 2 (Independent): A backfilled status column',
          description: 'Add `lifecycle_status` to products with a DEFAULT of active, so every existing row is backfilled immediately.',
          instructions: [
            "Write `ALTER TABLE products ADD COLUMN lifecycle_status VARCHAR(20) DEFAULT 'active';`",
            "Verify: `SELECT product_id, lifecycle_status FROM products LIMIT 3;` - every row shows active.",
          ],
          type: 'independent',
          primaryTable: 'products',
          initialSql: '-- Add a backfilled column\n',
          solutionSql: "ALTER TABLE products ADD COLUMN lifecycle_status VARCHAR(20) DEFAULT 'active';",
          solutionExplanation: 'DEFAULT in the ALTER backfills existing rows - no follow-up UPDATE needed.',
          hints: [{ level: 1, text: "Include DEFAULT 'active' inside the ADD COLUMN clause." }],
          validation: { targetTable: 'products', expectedRowCount: 1 },
          successMessage: 'A backfilled migration in one statement - this is how production schemas evolve.',
          databaseLifecycle: 'inherit',
        },
      ],
    },
    {
      id: 'ddl3-foreign-key',
      order: 2,
      title: '2. Relationships with FOREIGN KEY',
      shortDescription: 'Orphaned records become structurally impossible.',
      theory: {
        summary: 'A FOREIGN KEY on a column points at another table\'s primary key. From then on, the engine refuses any value that does not exist in the parent table - an order for a nonexistent customer, a product in a category that was never created. Day 27 gave your tables identity (PK); FOREIGN KEY connects those identities into enforceable relationships.',
        introTable: {
          tableName: 'Relationship map',
          description: 'orders.customer_id references customers.customer_id.',
          columns: ['orders.customer_id (FK)', 'points at', 'customers.customer_id (PK)'],
          rows: [
            [1, '->', 1],
            [2, '->', 2],
            [99, '->', 'REJECTED - no such customer'],
          ],
        },
        explanation: [
          'Declare the reference in the column definition:',
          '```sql\nCREATE TABLE wishlist_items (\n  item_id INT AUTO_INCREMENT PRIMARY KEY,\n  product_id INT NOT NULL,\n  customer_id INT NOT NULL,\n  FOREIGN KEY (product_id) REFERENCES products(product_id),\n  FOREIGN KEY (customer_id) REFERENCES customers(customer_id)\n);\n```',
          'QUESTION_BLOCK::ORPHAN::Why is an order with a nonexistent customer_id a disaster?',
          'QUESTION_BLOCK::JOIN::Which learning-day JOIN relied on exactly this relationship existing?',
          'The disaster: joins silently lose the orphan, reports undercount, and the customer can never be contacted about their order. With the FK in place, the INSERT itself is rejected (you saw exactly this error in the Day 26 failure lab). Every JOIN you wrote since Day 14 assumed these references were true - FOREIGN KEY is what makes that assumption a guarantee.',
          'Note the direction: the FK lives on the CHILD table (orders) and points at the PARENT (customers). One customer, many orders - the FK is on the many side.',
        ],
        targetQuery: {
          sql: 'CREATE TABLE wishlist_items (\n  item_id INT AUTO_INCREMENT PRIMARY KEY,\n  product_id INT NOT NULL,\n  customer_id INT NOT NULL,\n  FOREIGN KEY (product_id) REFERENCES products(product_id),\n  FOREIGN KEY (customer_id) REFERENCES customers(customer_id)\n);',
          explanation: 'A wishlist item can only reference products and customers that actually exist.',
          badge: "The query we're going to break down",
        },
        syntaxBlocks: [
          {
            title: 'FOREIGN KEY syntax',
            sql: 'FOREIGN KEY (child_col) REFERENCES parent_table(parent_pk)',
            description: 'Declared at the bottom of CREATE TABLE (one per reference). The child column must match the parent PK type.',
          },
        ],
        keyTakeaway: 'FOREIGN KEY turns a relationship into a rule: the engine rejects any child row whose reference does not exist in the parent. Joins and reports can finally trust the data.',
        exampleQuery: 'CREATE TABLE wishlist_items ( item_id INT AUTO_INCREMENT PRIMARY KEY, product_id INT NOT NULL, customer_id INT NOT NULL, FOREIGN KEY (product_id) REFERENCES products(product_id), FOREIGN KEY (customer_id) REFERENCES customers(customer_id) );',
        exampleQueryExplanation: 'Wishlist rows are born valid - their two references are checked at insert time.',
        liveDemoSql: 'SELECT o.order_id, c.name FROM orders o JOIN customers c ON o.customer_id = c.customer_id LIMIT 3;',
        liveDemoNotes: 'This JOIN never misses a customer - with an FK on orders.customer_id, it never could.',
        mcqs: [
          {
            question: 'Where does the FOREIGN KEY live in a one-to-many relationship (one customer, many orders)?',
            options: [
              'A. On the customers table',
              'B. On the orders table (the many side), pointing at customers',
              'C. On both tables',
              'D. On neither - relationships are virtual',
            ],
            correctIndex: 1,
            explanation: 'The child (many side) carries the FK column and constraint, pointing at the parent PK.',
          },
          {
            question: 'What does the engine do with `INSERT INTO orders (customer_id, ...) VALUES (999, ...)` when orders.customer_id has an FK to customers?',
            options: [
              'A. Creates customer 999 automatically',
              'B. Accepts it with a warning',
              'C. Rejects it - customer 999 does not exist',
              'D. Inserts it as NULL',
            ],
            correctIndex: 2,
            explanation: 'FK violations are rejected at insert time - exactly the error you triggered in the Day 26 failure lab.',
          },
        ],
        commonMistakes: [
          'Pointing the FK at the wrong column - it must reference the parent PRIMARY KEY (or a UNIQUE column).',
          'Mismatched types - an INT child column cannot reference a VARCHAR parent key.',
        ],
        masteryPoints: ['Declare FK relationships on the child table', 'Explain why orphans corrupt joins and reports'],
      },
      tasks: [
        {
          id: 'ddl3-c2-t1',
          title: 'Task 1 (Guided): A relationship-guarded table',
          description: 'Create `wishlist_items` whose product and customer references are both enforced.',
          instructions: [
            'Write `CREATE TABLE wishlist_items (item_id INT AUTO_INCREMENT PRIMARY KEY, product_id INT NOT NULL, customer_id INT NOT NULL, FOREIGN KEY (product_id) REFERENCES products(product_id), FOREIGN KEY (customer_id) REFERENCES customers(customer_id));`',
          ],
          type: 'guided',
          primaryTable: 'wishlist_items',
          secondaryTables: ['products', 'customers'],
          initialSql: '-- A relationship-guarded table\n',
          solutionSql: 'CREATE TABLE wishlist_items (item_id INT AUTO_INCREMENT PRIMARY KEY, product_id INT NOT NULL, customer_id INT NOT NULL, FOREIGN KEY (product_id) REFERENCES products(product_id), FOREIGN KEY (customer_id) REFERENCES customers(customer_id));',
          solutionExplanation: 'Two FKs: a wishlist item cannot reference a product or customer that does not exist.',
          hints: [{ level: 1, text: 'One FOREIGN KEY (...) REFERENCES ... line per reference, at the bottom of the CREATE TABLE.' }],
          validation: { targetTable: 'wishlist_items', expectedRowCount: 1 },
          successMessage: 'Orphans are now structurally impossible in the wishlist.',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'ddl3-c2-t2',
          title: 'Task 2 (Independent): Feel the FK reject an orphan',
          description: 'Insert a wishlist item referencing product 999. The task EXPECTS the FK to reject it.',
          instructions: [
            'Run `INSERT INTO wishlist_items (product_id, customer_id) VALUES (999, 1);` - product 999 does not exist.',
            'Expect the foreign-key error.',
          ],
          type: 'independent',
          primaryTable: 'wishlist_items',
          initialSql: '-- This insert is SUPPOSED to fail\n',
          solutionSql: 'INSERT INTO wishlist_items (product_id, customer_id) VALUES (999, 1);',
          solutionExplanation: 'The FK fired: no product 999, so the insert is rejected. The relationship is enforced, not assumed.',
          hints: [{ level: 1, text: 'Run the INSERT exactly as written - the error is the expected result.' }],
          validation: { targetTable: 'wishlist_items', expectFailure: true },
          successMessage: 'The FK rejected the orphan - your Day 26 failure lab, now by design.',
          databaseLifecycle: 'inherit',
        },
      ],
    },
    {
      id: 'ddl3-drop-table',
      order: 3,
      title: '3. Safe Teardown with DROP TABLE IF EXISTS',
      shortDescription: 'Reproducible scripts never crash on a missing table.',
      theory: {
        summary: 'DROP TABLE removes a table and all its rows - permanently. Plain DROP TABLE errors if the table does not exist, which breaks migration scripts that should run cleanly twice. DROP TABLE IF EXISTS tears the table down if present and does nothing (no error) if absent - the idempotent way to write setup and teardown scripts.',
        introTable: {
          tableName: 'Script behavior compared',
          description: 'Running the same teardown script twice.',
          columns: ['Statement', '1st run (table exists)', '2nd run (table gone)'],
          rows: [
            ['DROP TABLE temp_staging;', 'dropped', 'ERROR - crashes the script'],
            ['DROP TABLE IF EXISTS temp_staging;', 'dropped', 'no-op, script continues'],
          ],
        },
        explanation: [
          'The syntax adds two words to the dangerous statement:',
          '```sql\nDROP TABLE IF EXISTS temp_order_staging;\n```',
          'QUESTION_BLOCK::IDEM::What does it mean for a script to be idempotent?',
          'QUESTION_BLOCK::DANGER::Why does DROP deserve more care than DELETE?',
          'Idempotent: running it a second time leaves the same result as running it once - no errors, no side effects. That is essential for migration scripts that get replayed across environments.',
          'The danger: DELETE removes rows (the table and schema survive); DROP removes the table itself - structure, rows, and any indexes - gone in one statement. There is no undo outside a transaction. That is why teardown scripts pair DROP with IF EXISTS, and why you should never DROP a table you did not create in the same script.',
        ],
        targetQuery: {
          sql: 'DROP TABLE IF EXISTS temp_order_staging;',
          explanation: 'Destroys the staging table if it exists; silently succeeds if it does not.',
          badge: "The query we're going to break down",
        },
        syntaxBlocks: [
          {
            title: 'DROP TABLE syntax',
            sql: 'DROP TABLE [IF EXISTS] table_name;',
            description: 'IF EXISTS suppresses the missing-table error - the difference between a reproducible script and a crashing one.',
          },
        ],
        keyTakeaway: 'DROP TABLE IF EXISTS is the teardown primitive for reproducible scripts: destructive on purpose, silent when there is nothing to destroy.',
        exampleQuery: 'DROP TABLE IF EXISTS temp_order_staging;',
        exampleQueryExplanation: 'Safe to run once, twice, or a hundred times - same outcome.',
        liveDemoSql: 'DROP TABLE IF EXISTS temp_order_staging;\nDROP TABLE IF EXISTS temp_order_staging;',
        liveDemoNotes: 'Run it twice: both succeed. Plain DROP TABLE would have errored on the second run.',
        mcqs: [
          {
            question: 'Why prefer DROP TABLE IF EXISTS in migration scripts?',
            options: [
              'A. It is faster',
              'B. It prevents the script from crashing when the table is already gone - the script stays replayable',
              'C. It backs up data first',
              'D. It only drops empty tables',
            ],
            correctIndex: 1,
            explanation: 'IF EXISTS makes the script idempotent - safe to re-run in any environment state.',
          },
          {
            question: 'DELETE FROM products vs DROP TABLE products - the key difference?',
            options: [
              'A. No difference',
              'B. DELETE removes rows but keeps the table; DROP removes the table itself',
              'C. DELETE removes the table; DROP removes rows',
              'D. DROP is recoverable, DELETE is not',
            ],
            correctIndex: 1,
            explanation: 'DELETE is a DML row operation; DROP is DDL - the schema object itself disappears.',
          },
        ],
        commonMistakes: [
          'Plain DROP TABLE inside setup scripts - the second run crashes on the missing table.',
          'Dropping a parent table that children still reference - drop children first (or design FKs with ON DELETE rules).',
        ],
        masteryPoints: ['Write idempotent teardown scripts', 'Explain DELETE (rows) vs DROP (table) precisely'],
      },
      tasks: [
        {
          id: 'ddl3-c3-t1',
          title: 'Task 1 (Guided): Create, then tear down',
          description: 'Create a staging table, then drop it with the safe form. Run the DROP twice to see idempotence in action.',
          instructions: [
            'Run `CREATE TABLE IF NOT EXISTS temp_order_staging (staging_id INT PRIMARY KEY, note VARCHAR(80));`',
            'Run `DROP TABLE IF EXISTS temp_order_staging;`',
            'Run the DROP a second time - no error. That is idempotence.',
          ],
          type: 'guided',
          primaryTable: 'temp_order_staging',
          initialSql: '-- Create, drop, drop again\n',
          solutionSql: 'DROP TABLE IF EXISTS temp_order_staging;',
          solutionExplanation: 'Both drops succeeded: the first removed the table, the second found nothing and stayed silent.',
          hints: [{ level: 1, text: 'The DROP statement is the same both times - IF EXISTS makes the second run a no-op.' }],
          validation: { targetTable: 'temp_order_staging', expectedRowCount: 1 },
          successMessage: 'A twice-safe teardown - the migration-script primitive.',
          databaseLifecycle: 'fresh',
        },
        {
          id: 'ddl3-c3-t2',
          title: 'Task 2 (Independent): The reproducible setup script',
          description: 'Write the final teardown for a legacy table as part of a replayable cleanup script.',
          instructions: [
            'Write `DROP TABLE IF EXISTS legacy_student_grades;`',
          ],
          type: 'independent',
          primaryTable: 'legacy_student_grades',
          initialSql: '-- Reproducible teardown\n',
          solutionSql: 'DROP TABLE IF EXISTS legacy_student_grades;',
          solutionExplanation: 'Runs clean whether or not the legacy table exists - safe to replay in any environment.',
          hints: [{ level: 1, text: 'DROP TABLE, then IF EXISTS, then the table name.' }],
          validation: { targetTable: 'legacy_student_grades', expectedRowCount: 1 },
          successMessage: 'Legacy teardown written the reproducible way.',
          databaseLifecycle: 'fresh',
        },
      ],
    },
  ],
  challenge: {
    id: 'ddl3-homework',
    title: 'Day 29 - Evolution Challenge (Ending Activity)',
    scenario:
      'A schema migration from start to finish: create a child table with enforced relationships, extend an existing table, and tear down a temp table - all replayable.',
    databaseLifecycle: 'fresh',
    tasks: [
      {
        id: 'ddl3-hw-1',
        title: 'Task 1: Create the child table with FKs',
        description: 'Create `wishlists`: wishlist_id PK auto-increment, product_id NOT NULL with FK to products(product_id), customer_id NOT NULL with FK to customers(customer_id).',
        instructions: [
          'Write `CREATE TABLE wishlists (wishlist_id INT AUTO_INCREMENT PRIMARY KEY, product_id INT NOT NULL, customer_id INT NOT NULL, FOREIGN KEY (product_id) REFERENCES products(product_id), FOREIGN KEY (customer_id) REFERENCES customers(customer_id));`',
        ],
        type: 'challenge',
        primaryTable: 'wishlists',
        secondaryTables: ['products', 'customers'],
        initialSql: '-- Child table with enforced relationships\n',
        solutionSql:
          'CREATE TABLE wishlists (wishlist_id INT AUTO_INCREMENT PRIMARY KEY, product_id INT NOT NULL, customer_id INT NOT NULL, FOREIGN KEY (product_id) REFERENCES products(product_id), FOREIGN KEY (customer_id) REFERENCES customers(customer_id));',
        solutionExplanation: 'Both references are enforced - orphaned wishlist rows cannot exist.',
        hints: [{ level: 1, text: 'Two FOREIGN KEY lines at the bottom of the CREATE TABLE, one per reference.' }],
        validation: { targetTable: 'wishlists', expectedRowCount: 1 },
        successMessage: 'Relationships enforced at creation time.',
      },
      {
        id: 'ddl3-hw-2',
        title: 'Task 2: Extend the products table',
        description: 'Add `featured BOOLEAN NOT NULL DEFAULT FALSE` to products - a backfilled migration.',
        instructions: [
          "Write `ALTER TABLE products ADD COLUMN featured BOOLEAN NOT NULL DEFAULT FALSE;`",
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Backfilled migration\n',
        solutionSql: "ALTER TABLE products ADD COLUMN featured BOOLEAN NOT NULL DEFAULT FALSE;",
        solutionExplanation: 'One statement adds the column and backfills every existing row with FALSE.',
        hints: [{ level: 1, text: 'ADD COLUMN with the full definition including NOT NULL DEFAULT.' }],
        validation: { targetTable: 'products', expectedRowCount: 1 },
        successMessage: 'Live schema evolved - every product now carries a featured flag.',
      },
      {
        id: 'ddl3-hw-3',
        title: 'Task 3: Idempotent teardown',
        description: 'Finish the migration with a safe teardown of the temp import table.',
        instructions: ['Write `DROP TABLE IF EXISTS temp_import_orders;`'],
        type: 'challenge',
        primaryTable: 'temp_import_orders',
        initialSql: '-- Safe teardown\n',
        solutionSql: 'DROP TABLE IF EXISTS temp_import_orders;',
        solutionExplanation: 'The script now runs cleanly in any environment state.',
        hints: [{ level: 1, text: 'DROP TABLE IF EXISTS - the replayable form.' }],
        validation: { targetTable: 'temp_import_orders', expectedRowCount: 1 },
        successMessage: 'Create, evolve, tear down - a complete, replayable migration.',
      },
    ],
  },
};