import { ModuleData } from '../../types/curriculum';

export const Day_08_MODULE: ModuleData = {
  id: 'day-08',
  slug: 'milestone-1-assessment',
  day: 8,
  title: 'Day 8 — Milestone 1 Challenge: Single-Table Mastery',
  shortTitle: 'Milestone 1 Challenge',
  type: 'assignment',
  milestoneId: 'milestone-1',
  description: 'Your first real test: the warehouse manager is counting on you to write queries without hand-holding. Prove you can independently retrieve, filter, sort, and paginate single-table datasets. This is the difference between "learning SQL" and "using SQL."',
  estimatedMinutes: 75,
  completionLearnings: [
    'Independently write working single-table queries from business requirements',
    'Combine multiple clauses (WHERE + ORDER BY + LIMIT) in real scenarios',
    'Troubleshoot your own queries without templates or step-by-step hints',
  ],
  concepts: [
    {
      id: 'milestone-1-eval',
      order: 1,
      title: '1. Real Warehouse Scenario: Restock Alert Query',
      shortDescription: 'A realistic inventory management task — no templates, just business requirements.',
      theory: {
        summary: 'The warehouse manager just sent you an email: "I need a list of products that have fallen below reorder point, sorted by urgency (worst stock first), and I only want to see the top 5 items for immediate action." This is your real job. Write the query.',
        introTable: {
          tableName: 'products',
          description: 'Milestone evaluation test dataset',
          columns: ['product_id', 'name', 'price', 'quantity_in_stock', 'reorder_level'],
          rows: [
            [1, 'Wireless Mouse', 25.00, 42, 10],
            [9, 'Wireless Charging Pad', 19.99, 0, 15],
            [15, 'Steel Cable Management Tray', 22.00, 2, 8],
            [20, 'Steel Frame Footrest', 45.00, 0, 5],
          ],
        },
        explanation: [
          '### Challenge: Break Down the Business Requirement',
          'The manager\'s email has three parts. Can you turn them into SQL?',
          '1. **What rows?** Products where quantity_in_stock ≤ reorder_level',
          '2. **In what order?** Sort by quantity ascending (worst stock first)',
          '3. **How many?** Show only the top 5 (LIMIT 5)',
          '',
          'In Milestone 1, you\'ve learned everything you need. No more hints from here — just structure your query.',
        ],
        targetQuery: {
          sql: 'SELECT name, quantity_in_stock, reorder_level\nFROM products\nWHERE quantity_in_stock <= reorder_level\nORDER BY quantity_in_stock ASC\nLIMIT 5;',
          explanation: 'The complete warehouse query: FROM the products table, filter WHERE stock is below reorder level, sort worst-first (ASC), and LIMIT to top 5 for the manager\'s action list.',
          badge: "The solution (revealed after you try)",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: FROM products (Find all products)',
            sqlSnippet: 'FROM products',
            explanation: 'Start by accessing the products table.',
            tableData: {
              tableName: 'All Products (4 rows)',
              columns: ['name', 'quantity_in_stock', 'reorder_level'],
              rows: [
                ['Wireless Mouse', 42, 10],
                ['Wireless Charging Pad', 0, 15],
                ['Steel Cable Management Tray', 2, 8],
                ['Steel Frame Footrest', 0, 5],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: WHERE quantity_in_stock <= reorder_level (Filter critical stock)',
            sqlSnippet: 'WHERE quantity_in_stock <= reorder_level',
            explanation: 'Keep only products where current stock has fallen to or below the reorder threshold. Wireless Mouse (42 ≤ 10) → FALSE, so it\'s excluded. Wireless Charging Pad (0 ≤ 15) → TRUE, it stays.',
            tableData: {
              tableName: 'Low-Stock Products (3 rows)',
              columns: ['name', 'quantity_in_stock', 'reorder_level'],
              highlightedRows: [0, 1, 2],
              rows: [
                ['Wireless Charging Pad', 0, 15],
                ['Steel Frame Footrest', 0, 5],
                ['Steel Cable Management Tray', 2, 8],
              ],
            },
          },
          {
            stepNumber: 3,
            stepTitle: 'Step 3: ORDER BY quantity_in_stock ASC (Worst stock first)',
            sqlSnippet: 'ORDER BY quantity_in_stock ASC',
            explanation: 'Sort ascending by quantity — items with 0 stock appear first (most urgent). This tells the warehouse which items to reorder first.',
            tableData: {
              tableName: 'Sorted by Urgency (3 rows)',
              columns: ['name', 'quantity_in_stock', 'reorder_level'],
              rows: [
                ['Wireless Charging Pad', 0, 15],
                ['Steel Frame Footrest', 0, 5],
                ['Steel Cable Management Tray', 2, 8],
              ],
            },
          },
          {
            stepNumber: 4,
            stepTitle: 'Step 4: LIMIT 5 (Show top 5 for immediate action)',
            sqlSnippet: 'LIMIT 5',
            explanation: 'The manager\'s screen might be crowded, so LIMIT 5 shows just the 5 most urgent items. Since we only have 3 low-stock items, all 3 appear.',
            tableData: {
              tableName: 'Final Result (3 rows)',
              columns: ['name', 'quantity_in_stock', 'reorder_level'],
              highlightedColumns: ['name', 'quantity_in_stock'],
              highlightedRows: [0, 1, 2],
              rows: [
                ['Wireless Charging Pad', 0, 15],
                ['Steel Frame Footrest', 0, 5],
                ['Steel Cable Management Tray', 2, 8],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Single table mastery',
            sql: 'SELECT DISTINCT ... FROM ... WHERE ... ORDER BY ... LIMIT ... OFFSET ...;',
            description: 'The complete single-table query foundation.',
          },
        ],
        keyTakeaway: 'Demonstrate full mastery of single-table data retrieval.',
        exampleQuery: 'SELECT * FROM products WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;',
        exampleQueryExplanation: 'Evaluates low-stock items worst first.',
        liveDemoSql: 'SELECT * FROM products WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;',
        liveDemoNotes: 'Displays critical inventory items.',
        mcqs: [
          {
            question: 'Spiral check from Day 2: a product has price = 50.00. Which filter keeps it?',
            options: [
              'A. WHERE price > 50',
              'B. WHERE price >= 50',
              'C. WHERE price != 50',
              'D. WHERE price < 50',
            ],
            correctIndex: 1,
            explanation: 'Only >= includes the boundary itself (Day 2). Checkpoints deliberately re-test earlier milestones - if this felt shaky, revisit Day 2 before the deliverables below.',
          },
          {
            question: 'What is the primary objective of Milestone 1?',
            options: [
              'A. Writing complex multi-table joins',
              'B. Independently retrieving, filtering, sorting, and paginating single-table queries',
              'C. Designing database indexes',
              'D. Setting up database replication',
            ],
            correctIndex: 1,
            explanation: 'Milestone 1 establishes single-table query mastery.',
          },
        ],
        masteryPoints: ['Pass all 5 Milestone 1 independent checkpoint tasks'],
      },
      tasks: [
        {
          id: 'day08-c1-t1',
          title: 'Warmup 1: Low Stock Products (Lowest Stock First)',
          description: 'List products that need restocking — their stock has reached or fallen below their reorder level. Put the lowest stock at the top.',
          instructions: [
            'Select `name`, `quantity_in_stock`, `reorder_level` from `products`.',
            'Where `quantity_in_stock <= reorder_level`.',
            'Order by `quantity_in_stock ASC`.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'products',
          initialSql: '-- Warmup 1: Low stock products worst-first\n',
          solutionSql: 'SELECT name, quantity_in_stock, reorder_level FROM products WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;',
          solutionExplanation: 'Finds products below reorder level, ordered from lowest stock to highest.',
          hints: [{ level: 1, text: 'Use `WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;`' }],
          validation: {
            requireExactResult: true,
            targetTable: 'products',
            requiredColumns: ['name', 'quantity_in_stock', 'reorder_level'],
            requireWhere: true,
            requireOrderBy: [{ column: 'quantity_in_stock', direction: 'ASC' }],
            expectedRowCount: 8,
          },
          successMessage: 'Warmup 1 completed! Low stock items listed lowest stock first.',
        },
        {
          id: 'day08-c1-t2',
          title: 'Warmup 2: Unique Customer City Directory',
          description: 'Retrieve a distinct list of cities from the customers table, ordered alphabetically.',
          instructions: [
            'Query the `customers` table.',
            'Select `DISTINCT city`.',
            'Order by `city ASC`.',
          ],
          type: 'independent',
          primaryTable: 'customers',
          initialSql: '-- Warmup 2: Distinct cities sorted alphabetically\n',
          solutionSql: 'SELECT DISTINCT city FROM customers ORDER BY city ASC;',
          solutionExplanation: 'Returns unique customer cities sorted from A to Z.',
          hints: [{ level: 1, text: 'Use `SELECT DISTINCT city FROM customers ORDER BY city ASC;`' }],
          validation: {
            requireExactResult: true,
            targetTable: 'customers',
            requiredColumns: ['city'],
            requireDistinct: true,
            requireOrderBy: [{ column: 'city', direction: 'ASC' }],
            expectedRowCount: 6,
          },
          successMessage: 'Warmup 2 completed! Unique customer locations sorted alphabetically.',
        },
      ],
    },
  ],

  // ===========================================================================
  // DAY 8 CHALLENGE: MILESTONE 1 MASTERY CHECKPOINT (ENDING ACTIVITY)
  // ===========================================================================
  challenge: {
    id: 'day-08-homework',
    title: 'Day 8 — Milestone 1 Mastery Checkpoint (Ending Activity)',
    scenario: 'The warehouse manager needs five answers before the morning stand-up — no hints, no walkthroughs. Each deliverable draws on one skill from Days 1–7; land all five and Milestone 1 is yours:',
    tasks: [
      {
        id: 'day08-hw-1',
        title: 'Deliverable 1 (Core): Products at or below reorder level, lowest stock first',
        description: 'Find every product that needs restocking — its stock has reached or dropped below its reorder level — and list the most critical (lowest stock) first.',
        instructions: [
          'Select from `products` where `quantity_in_stock <= reorder_level` ordered by `quantity_in_stock ASC`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Deliverable 1: Products at or below reorder level, lowest stock first\n',
        solutionSql: 'SELECT * FROM products WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;',
        solutionExplanation: 'Sorts products below reorder level by stock quantity ascending.',
        hints: [{ level: 1, text: 'Use `WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;`' }],
        validation: {
          requireExactResult: true,
          targetTable: 'products',
          requireWhere: true,
          requireOrderBy: [{ column: 'quantity_in_stock', direction: 'ASC' }],
          expectedRowCount: 8,
        },
        successMessage: 'Deliverable 1 verified! Low stock items sorted lowest stock first.',
      },
      {
        id: 'day08-hw-2',
        title: 'Deliverable 2 (Combination): Distinct supplier IDs in low-stock inventory',
        description: 'Which suppliers are affected by the low-stock situation? List each affected supplier only once, even if several low-stock products come from the same supplier.',
        instructions: [
          'Select `DISTINCT supplier_id` from `products` where `quantity_in_stock <= reorder_level`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Deliverable 2: Distinct supplier IDs in low-stock list\n',
        solutionSql: 'SELECT DISTINCT supplier_id FROM products WHERE quantity_in_stock <= reorder_level;',
        solutionExplanation: '`DISTINCT supplier_id` extracts unique suppliers affected by low stock.',
        hints: [{ level: 1, text: 'Use `SELECT DISTINCT supplier_id FROM products WHERE quantity_in_stock <= reorder_level;`' }],
        validation: {
          requireExactResult: true,
          targetTable: 'products',
          requiredColumns: ['supplier_id'],
          requireDistinct: true,
          requireWhere: true,
          expectedRowCount: 5,
        },
        successMessage: 'Deliverable 2 verified! Suppliers affected by low stock listed.',
      },
      {
        id: 'day08-hw-3',
        title: 'Deliverable 3 (Transfer): The single newest customer signup',
        description: 'Find the customer who signed up most recently.',
        instructions: [
          'Select from `customers` ordered by `signup_date DESC LIMIT 1`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'customers',
        initialSql: '-- Deliverable 3: The single most recently added customer\n',
        solutionSql: 'SELECT * FROM customers ORDER BY signup_date DESC LIMIT 1;',
        solutionExplanation: '`ORDER BY signup_date DESC LIMIT 1` finds the newest customer signup.',
        hints: [{ level: 1, text: 'Use `ORDER BY signup_date DESC LIMIT 1;`' }],
        validation: {
          requireExactResult: true,
          targetTable: 'customers',
          requireOrderBy: [{ column: 'signup_date', direction: 'DESC' }],
          requireLimit: 1,
          expectedRowCount: 1,
        },
        successMessage: 'Deliverable 3 verified! Most recent customer found.',
      },
      {
        id: 'day08-hw-4',
        title: 'Deliverable 4 (Transfer): Top 5 cheapest products',
        description: 'Show the 5 cheapest products in the catalog.',
        instructions: [
          'Select from `products` ordered by `price ASC LIMIT 5`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Deliverable 4: The 5 cheapest products\n',
        solutionSql: 'SELECT * FROM products ORDER BY price ASC LIMIT 5;',
        solutionExplanation: '`ORDER BY price ASC LIMIT 5` returns the 5 lowest priced products.',
        hints: [{ level: 1, text: 'Use `ORDER BY price ASC LIMIT 5;`' }],
        validation: {
          requireExactResult: true,
          targetTable: 'products',
          requireOrderBy: [{ column: 'price', direction: 'ASC' }],
          requireLimit: 5,
          expectedRowCount: 5,
        },
        successMessage: 'Deliverable 4 verified! 5 cheapest products retrieved.',
      },
      {
        id: 'day08-hw-5',
        title: 'Deliverable 5 (Hard Problem): Customer Directory Page 2 Pagination',
        description: 'Retrieve Page 2 of the customer directory (5 customers per page, sorted by signup_date DESC).',
        instructions: [
          'Select all columns from `customers`.',
          'Order by `signup_date DESC LIMIT 5 OFFSET 5`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'customers',
        initialSql: '-- Deliverable 5: Page 2 of customer directory (5 per page)\n',
        solutionSql: 'SELECT * FROM customers ORDER BY signup_date DESC LIMIT 5 OFFSET 5;',
        solutionExplanation: 'Orders customers by newest signup first and retrieves Page 2 (skipping 5 with OFFSET 5, taking 5 with LIMIT 5).',
        hints: [{ level: 1, text: 'Use `ORDER BY signup_date DESC LIMIT 5 OFFSET 5;`' }],
        validation: {
          requireExactResult: true,
          targetTable: 'customers',
          requireOrderBy: [{ column: 'signup_date', direction: 'DESC' }],
          requireLimit: 5,
          requireOffset: 5,
          expectedRowCount: 5,
        },
        successMessage: 'Deliverable 5 verified! Page 2 of customer directory retrieved.',
      },
    ],
  },
};
