import { ModuleData } from '../../types/curriculum';

export const Day_36_MODULE: ModuleData = {
  id: 'day-36',
  slug: 'milestone-3-final-assessment',
  day: 36,
  title: 'Day 36 - Comprehensive Skills Assessment: Milestone 3 Finale',
  shortTitle: 'Milestone 3 Final Assessment',
  type: 'assignment',
  milestoneId: 'milestone-3',
  description: 'Comprehensive capstone assessment covering advanced CTEs, correlated subqueries, schema DDL modifications, index creation, and DML data integrity. Prove full database engineering proficiency.',
  estimatedMinutes: 120,
  completionLearnings: [
    'Write complex multi-table queries with CTEs and window functions',
    'Calculate correlated metrics using Common Table Expressions',
    'Execute schema modifications with ALTER TABLE',
    'Create targeted performance indexes and validate with EXPLAIN',
  ],
  concepts: [
    {
      id: 'capstone-evaluation',
      order: 1,
      title: '1. Milestone 3 Capstone Skill Verification',
      shortDescription: 'Final comprehensive SQL certification assessment across all 38 days.',
      theory: {
        summary: 'The certification exam has arrived — no templates, no scaffold. Prove full database engineering: rank categories by revenue across three joined tables, find above-average customers with CTEs, migrate a live schema with ALTER TABLE,and create an index that EXPLAIN confirms. Four production-grade deliverables, one final assessment.',
        introTable: {
          tableName: 'categories & products & order_items',
          description: 'Multi-table revenue aggregation pipeline',
          columns: ['cat.name', 'p.name', 'oi.quantity', 'oi.unit_price'],
          rows: [
            ['Electronics', 'Wireless Mouse', 2, 15.99],
            ['Electronics', 'Mechanical Keyboard', 1, 65.00],
            ['Office Furniture', 'Office Chair', 1, 120.00],
          ],
        },
        explanation: [
          '### 1. Final Assessment Deliverables',
          '• **Deliverable 1 (Complex Retrieval)**: Top 3 product categories by total sales revenue.',
          '• **Deliverable 2 (CTE Analysis)**: Customers with above-average total spending.',
          '• **Deliverable 3 (Schema DDL)**: Add a `status` column with a default value to `products`.',
          '• **Deliverable 4 (Index DDL)**: Create an index on `orders(customer_id)` for lookup acceleration.',
        ],
        targetQuery: {
          sql: 'SELECT cat.name, SUM(oi.quantity * oi.unit_price) AS category_revenue\nFROM categories cat\nJOIN products p ON cat.category_id = p.category_id\nJOIN order_items oi ON p.product_id = oi.product_id\nGROUP BY cat.category_id, cat.name\nORDER BY category_revenue DESC\nLIMIT 3;',
          explanation: 'Aggregate total sales revenue per product category across 3 joined tables and limit to top 3 rankings.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: Top 3 Categories by Revenue Ranking',
            sqlSnippet: 'SELECT cat.name, SUM(oi.quantity * oi.unit_price) AS category_revenue\nFROM categories cat\nJOIN products p ON cat.category_id = p.category_id\nJOIN order_items oi ON p.product_id = oi.product_id\nGROUP BY cat.category_id, cat.name\nORDER BY category_revenue DESC\nLIMIT 3;',
            explanation: 'Aggregates sales revenue per product category and limits to the top 3.',
            tableData: {
              tableName: 'Top 3 Revenue Categories',
              columns: ['name', 'category_revenue'],
              highlightedColumns: ['name', 'category_revenue'],
              rows: [
                ['Electronics', 448.47],
                ['Office Furniture', 209.99],
                ['Accessories', 161.42],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Mastery SQL syntax',
            sql: 'WITH CategoryRevenue AS (\n  SELECT c.category_id, c.name, SUM(oi.quantity * oi.unit_price) AS rev\n  FROM categories c\n  JOIN products p ON c.category_id = p.category_id\n  JOIN order_items oi ON p.product_id = oi.product_id\n  GROUP BY c.category_id, c.name\n)\nSELECT * FROM CategoryRevenue ORDER BY rev DESC LIMIT 3;',
            description: 'Capstone multi-stage CTE analysis.',
          },
        ],
        keyTakeaway: 'Demonstrate complete fluency in advanced SQL.',
        exampleQuery: 'SELECT c.name, SUM(oi.quantity * oi.unit_price) AS rev FROM categories c JOIN products p ON c.category_id = p.category_id JOIN order_items oi ON p.product_id = oi.product_id GROUP BY c.category_id, c.name ORDER BY rev DESC LIMIT 3;',
        exampleQueryExplanation: 'Top 3 categories by total revenue.',
        liveDemoSql: 'SELECT c.name, SUM(oi.quantity * oi.unit_price) AS rev FROM categories c JOIN products p ON c.category_id = p.category_id JOIN order_items oi ON p.product_id = oi.product_id GROUP BY c.category_id, c.name ORDER BY rev DESC LIMIT 3;',
        liveDemoNotes: 'The three revenue leaders, ranked.',
        mcqs: [
          {
            question: 'What combination of tools enables optimal read performance in high-scale relational databases?',
            options: [
              'A. Targeted B-tree indexes, normalized schema design, and clean JOINs without Cartesian fan-out',
              'B. Removing all constraints',
              'C. Storing everything in 1 text column',
              'D. Disabling foreign keys',
            ],
            correctIndex: 0,
            explanation: 'Targeted indexes, normalization, and precise joins provide maximum efficiency.',
          },
        ],
        masteryPoints: ['Complete all Milestone 3 Capstone deliverables'],
      },
      tasks: [
        {
          id: 'day24-c1-t1',
          title: 'Warmup 1: Top 3 Categories by Revenue',
          description: 'Calculate top 3 categories by total revenue generated across order items.',
          instructions: [
            'Select `cat.name`, `SUM(oi.quantity * oi.unit_price) AS category_revenue` from `categories cat` JOIN `products p` ON `cat.category_id = p.category_id` JOIN `order_items oi` ON `p.product_id = oi.product_id`.',
            'Group by `cat.category_id`, `cat.name`.',
            'Order by `category_revenue DESC` LIMIT 3.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'categories',
          secondaryTables: ['products', 'order_items'],
          initialSql: '-- Warmup 1: Top 3 categories by revenue\n',
          solutionSql: 'SELECT cat.name, SUM(oi.quantity * oi.unit_price) AS category_revenue FROM categories cat JOIN products p ON cat.category_id = p.category_id JOIN order_items oi ON p.product_id = oi.product_id GROUP BY cat.category_id, cat.name ORDER BY category_revenue DESC LIMIT 3;',
          solutionExplanation: 'Ranks top 3 categories by revenue.',
          hints: [{ level: 1, text: 'Use `GROUP BY cat.category_id, cat.name ORDER BY category_revenue DESC LIMIT 3;`' }],
          validation: {
            requireExactResult: true,
            targetTable: 'categories',
            requireJoin: true,
            requireGroupBy: true,
            requireOrderBy: [{ column: 'category_revenue', direction: 'DESC' }],
            requireLimit: 3,
            expectedRowCount: 3,
          },
          successMessage: 'Warmup 1 completed! Top 3 revenue categories calculated.',
        },
        {
          id: 'day24-c1-t2',
          title: 'Warmup 2: Above-Average Customer Spenders (CTE)',
          description: 'Find customers whose total spend is higher than the overall average customer spend using a CTE.',
          instructions: [
            'Define `WITH CustomerTotals AS (SELECT c.customer_id, c.name, SUM(oi.quantity * oi.unit_price) AS total_spent FROM customers c JOIN orders o ON c.customer_id = o.customer_id JOIN order_items oi ON o.order_id = oi.order_id GROUP BY c.customer_id, c.name)`.',
            'Select all columns from `CustomerTotals` where `total_spent > (SELECT AVG(total_spent) FROM CustomerTotals)` ordered by `total_spent DESC`.',
          ],
          type: 'independent',
          primaryTable: 'customers',
          secondaryTables: ['orders', 'order_items'],
          initialSql: '-- High-spending customer benchmark\n',
          solutionSql: 'WITH CustomerTotals AS (SELECT c.customer_id, c.name, SUM(oi.quantity * oi.unit_price) AS total_spent FROM customers c JOIN orders o ON c.customer_id = o.customer_id JOIN order_items oi ON o.order_id = oi.order_id GROUP BY c.customer_id, c.name) SELECT * FROM CustomerTotals WHERE total_spent > (SELECT AVG(total_spent) FROM CustomerTotals) ORDER BY total_spent DESC;',
          solutionExplanation: 'Finds customers whose spend beats the catalog average — a benchmark comparison, not a fixed cutoff.',
          hints: [{ level: 1, text: 'Use `WHERE total_spent > (SELECT AVG(total_spent) FROM CustomerTotals) ORDER BY total_spent DESC;`' }],
          validation: {
            requireExactResult: true,
            targetTable: 'customers',
            expectedRowCount: 5,
          },
          successMessage: 'Warmup 2 completed! Above-average spenders filtered with CTE benchmark.',
        },
      ],
    },
  ],

  // ===========================================================================
  // DAY 24 CHALLENGE: MILESTONE 3 CAPSTONE ASSESSMENT (ENDING ACTIVITY)
  // ===========================================================================
  challenge: {
    id: 'day-36-homework',
    title: 'Day 36 — Milestone 3 Capstone Assessment (Ending Activity)',
    scenario: 'Complete all 4 capstone deliverables independently to achieve SQL certification:',
    tasks: [
      {
        id: 'day24-hw-1',
        title: 'Deliverable 1 (Complex Retrieval): Top 3 categories by revenue',
        description: 'Top 3 categories by revenue (categories → products → order_items).',
        instructions: [
          'Select `cat.name`, `SUM(oi.quantity * oi.unit_price) AS category_revenue` from `categories cat` JOIN `products p` ON `cat.category_id = p.category_id` JOIN `order_items oi` ON `p.product_id = oi.product_id` GROUP BY `cat.category_id`, `cat.name` ORDER BY `category_revenue DESC` LIMIT 3.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'categories',
        secondaryTables: ['products', 'order_items'],
        initialSql: '-- Deliverable 1: Top 3 categories by revenue\n',
        solutionSql: 'SELECT cat.name, SUM(oi.quantity * oi.unit_price) AS category_revenue FROM categories cat JOIN products p ON cat.category_id = p.category_id JOIN order_items oi ON p.product_id = oi.product_id GROUP BY cat.category_id, cat.name ORDER BY category_revenue DESC LIMIT 3;',
        solutionExplanation: 'Walks categories → products → order_items and tallies revenue per category, keeping only the top three.',
        hints: [{ level: 1, text: 'Use `ORDER BY category_revenue DESC LIMIT 3;`' }],
        validation: {
          requireExactResult: true,
          targetTable: 'categories',
          requireJoin: true,
          requireGroupBy: true,
          requireOrderBy: [{ column: 'category_revenue', direction: 'DESC' }],
          requireLimit: 3,
          expectedRowCount: 3,
        },
        successMessage: 'Deliverable 1 verified! Top 3 revenue categories calculated.',
      },
      {
        id: 'day24-hw-2',
        title: 'Deliverable 2 (CTE Analysis): Customers with above-average total spend',
        description: 'Find customers whose total spend is higher than the overall average customer spend.',
        instructions: [
          'Use `WITH CustomerTotals AS (SELECT c.customer_id, c.name, SUM(oi.quantity * oi.unit_price) AS total_spent FROM customers c JOIN orders o ON c.customer_id = o.customer_id JOIN order_items oi ON o.order_id = oi.order_id GROUP BY c.customer_id, c.name) SELECT * FROM CustomerTotals WHERE total_spent > (SELECT AVG(total_spent) FROM CustomerTotals) ORDER BY total_spent DESC;`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'customers',
        secondaryTables: ['orders', 'order_items'],
        initialSql: '-- Deliverable 2: Customers with above-average total spend\n',
        solutionSql: 'WITH CustomerTotals AS (SELECT c.customer_id, c.name, SUM(oi.quantity * oi.unit_price) AS total_spent FROM customers c JOIN orders o ON c.customer_id = o.customer_id JOIN order_items oi ON o.order_id = oi.order_id GROUP BY c.customer_id, c.name) SELECT * FROM CustomerTotals WHERE total_spent > (SELECT AVG(total_spent) FROM CustomerTotals) ORDER BY total_spent DESC;',
        solutionExplanation: 'Uses CTE with subquery benchmark to filter high-spending accounts.',
        hints: [{ level: 1, text: 'Use `WITH CustomerTotals AS (...) SELECT * FROM CustomerTotals WHERE total_spent > (SELECT AVG(total_spent) FROM CustomerTotals);`' }],
        validation: {
          requireExactResult: true,
          targetTable: 'customers',
          expectedRowCount: 5,
        },
        successMessage: 'Deliverable 2 verified! High-value customer benchmark verified.',
      },
      {
        id: 'day24-hw-3',
        title: 'Deliverable 3 (Schema DDL): Add status column to products with default',
        description: 'Add a status column to products: `ALTER TABLE products ADD COLUMN status VARCHAR(20) DEFAULT \'active\';`.',
        instructions: [
          'Execute `ALTER TABLE products ADD COLUMN status VARCHAR(20) DEFAULT \'active\';`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Deliverable 3: Alter table products add status column\n',
        solutionSql: 'ALTER TABLE products ADD COLUMN status VARCHAR(20) DEFAULT \'active\';',
        solutionExplanation: 'Alters products table schema by appending the status column with default value.',
        hints: [{ level: 1, text: 'Use `ALTER TABLE products ADD COLUMN status VARCHAR(20) DEFAULT \'active\';`' }],
        validation: {
          targetTable: 'products',
          expectedRowCount: 1,
        },
        successMessage: 'Deliverable 3 verified! Schema altered with status column.',
      },
      {
        id: 'day24-hw-4',
        title: 'Deliverable 4 (Index Optimization): Create index on orders(customer_id)',
        description: 'Create an index named idx_orders_customer_id on orders(customer_id).',
        instructions: [
          'Execute `CREATE INDEX idx_orders_customer_id ON orders(customer_id);`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'orders',
        initialSql: '-- Deliverable 4: Create index on orders(customer_id)\n',
        solutionSql: 'CREATE INDEX idx_orders_customer_id ON orders(customer_id);',
        solutionExplanation: 'Creates a B-tree index on orders foreign key customer_id.',
        hints: [{ level: 1, text: 'Use `CREATE INDEX idx_orders_customer_id ON orders(customer_id);`' }],
        validation: {
          targetTable: 'orders',
          expectedRowCount: 1,
        },
        successMessage: 'Deliverable 4 verified! Index created on orders(customer_id).',
      },
    ],
  },
};
