import { ModuleData } from '../../types/curriculum';

export const Day_07_MODULE: ModuleData = {
  id: 'day-07',
  slug: 'project-part-1-explore-schema',
  day: 7,
  title: 'Day 7 — Applied Project: Full Schema Exploration',
  shortTitle: 'Project: Schema Exploration',
  type: 'project_part',
  milestoneId: 'milestone-1',
  description: 'Join the E-Commerce Data Team to audit and explore the full 6-table database schema (suppliers, categories, products, customers, orders, order_items) using single-table queries.',
  estimatedMinutes: 75,
  completionLearnings: [
    'Navigate the full 6-table e-commerce relational schema independently',
    'Query suppliers, products, and categories using targeted single-table audits',
    'Identify primary key and foreign key reference columns across entities',
  ],
  concepts: [
    {
      id: 'schema-navigation',
      order: 1,
      title: '1. E-Commerce Data Team Onboarding & Schema Audit',
      shortDescription: 'Hands-on exploration of the complete relational schema.',
      theory: {
        summary: 'Welcome to the data engineering team! Before running analytical joins or modifying records, your onboarding mission is to audit and inspect all tables in the production e-commerce database.',
        introTable: {
          tableName: 'suppliers',
          description: 'Suppliers directory table',
          columns: ['supplier_id', 'name', 'contact_email'],
          rows: [
            [1, 'LogiTech Direct', 'supply@logitech-direct.com'],
            [2, 'KeyChron Components', 'orders@keychron-comp.com'],
            [3, 'Apex Cables & Hubs', 'sales@apexcables.io'],
          ],
        },
        explanation: [
          '### 1. The E-Commerce Schema Map',
          'The platform stores data across 6 interconnected entities:',
          '• **`suppliers`**: Directory of vendor partners (`supplier_id`, `name`, `contact_email`).',
          '• **`categories`**: Catalog taxonomy labels (`category_id`, `name`).',
          '• **`products`**: Inventory catalog (`product_id`, `name`, `supplier_id`, `category_id`, `price`, `quantity_in_stock`, `reorder_level`).',
          '• **`customers`**: Registered shoppers (`customer_id`, `name`, `email`, `city`, `signup_date`).',
          '• **`orders`**: Customer checkout records (`order_id`, `customer_id`, `order_date`, `status`).',
          '• **`order_items`**: Individual line items (`order_item_id`, `order_id`, `product_id`, `quantity`, `unit_price`).',
        ],
        targetQuery: {
          sql: 'SELECT supplier_id, name, contact_email\nFROM suppliers\nORDER BY supplier_id ASC;',
          explanation: 'Audit all registered supplier partners in the directory ordered by ID.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: FROM suppliers (Scan directory table)',
            sqlSnippet: 'FROM suppliers',
            explanation: 'Loads all registered vendor partner records.',
            tableData: {
              tableName: 'suppliers',
              columns: ['supplier_id', 'name', 'contact_email'],
              rows: [
                [1, 'LogiTech Direct', 'supply@logitech-direct.com'],
                [2, 'KeyChron Components', 'orders@keychron-comp.com'],
                [3, 'Apex Cables & Hubs', 'sales@apexcables.io'],
                [4, 'ErgoComfort Workspace', 'wholesale@ergocomfort.com'],
                [5, 'SoundWave Acoustic', 'b2b@soundwave.net'],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: SELECT supplier_id, name, contact_email ORDER BY supplier_id ASC',
            sqlSnippet: 'SELECT supplier_id, name, contact_email ORDER BY supplier_id ASC',
            explanation: 'Extracts supplier contact profiles in numeric ID order.',
            tableData: {
              tableName: 'Audited Supplier Directory',
              columns: ['supplier_id', 'name', 'contact_email'],
              highlightedColumns: ['supplier_id', 'name', 'contact_email'],
              highlightedRows: [0, 1, 2, 3, 4],
              rows: [
                [1, 'LogiTech Direct', 'supply@logitech-direct.com'],
                [2, 'KeyChron Components', 'orders@keychron-comp.com'],
                [3, 'Apex Cables & Hubs', 'sales@apexcables.io'],
                [4, 'ErgoComfort Workspace', 'wholesale@ergocomfort.com'],
                [5, 'SoundWave Acoustic', 'b2b@soundwave.net'],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Inspecting individual tables',
            sql: 'SELECT * FROM suppliers;\nSELECT * FROM categories;\nSELECT * FROM products;',
            description: 'Explore the structural layout of each entity.',
          },
        ],
        keyTakeaway: 'Audit all tables confidently using targeted single-table queries.',
        exampleQuery: 'SELECT * FROM suppliers;',
        exampleQueryExplanation: 'Lists all supplier partner records.',
        liveDemoSql: 'SELECT * FROM suppliers;',
        liveDemoNotes: 'Displays all suppliers in the database.',
        mcqs: [
          {
            question: 'Which table connects orders to products in this schema?',
            options: ['A. customers', 'B. order_items', 'C. categories', 'D. suppliers'],
            correctIndex: 1,
            explanation: '`order_items` stores individual line items for each order, referencing both order_id and product_id.',
          },
        ],
        masteryPoints: ['Explore any table in the schema using single-table queries'],
      },
      tasks: [
        {
          id: 'day07-c1-t1',
          title: 'Mission 1 (Guided): Inspect Supplier Directory',
          description: 'Retrieve all columns from the `suppliers` table.',
          instructions: ['Select all columns from `suppliers`.', 'End with a semicolon (;).'],
          type: 'guided',
          primaryTable: 'suppliers',
          initialSql: '-- Mission 1: List all supplier partners\n',
          solutionSql: 'SELECT * FROM suppliers;',
          solutionExplanation: 'Retrieves all registered vendor records.',
          hints: [{ level: 1, text: 'Use `SELECT * FROM suppliers;`' }],
          validation: {
            targetTable: 'suppliers',
            expectedRowCount: 6,
          },
          successMessage: 'Mission 1 complete! Supplier directory retrieved.',
        },
        {
          id: 'day07-c1-t2',
          title: 'Mission 2 (Semi-Guided): Audit Supplier #1 Catalog',
          description: 'Find products supplied by supplier_id 1, sorted by price ascending.',
          instructions: [
            'Query the `products` table.',
            'Select `name`, `price`, and `quantity_in_stock`.',
            'Filter where `supplier_id = 1`.',
            'Order by `price ASC`.',
          ],
          type: 'independent',
          primaryTable: 'products',
          initialSql: '-- Mission 2: Products from supplier #1\n',
          solutionSql: 'SELECT name, price, quantity_in_stock FROM products WHERE supplier_id = 1 ORDER BY price ASC;',
          solutionExplanation: 'Finds products from LogiTech Direct sorted by price.',
          hints: [{ level: 1, text: 'Use `WHERE supplier_id = 1 ORDER BY price ASC;`' }],
          validation: {
            targetTable: 'products',
            requiredColumns: ['name', 'price', 'quantity_in_stock'],
            requireWhere: true,
            requireOrderBy: [{ column: 'price', direction: 'ASC' }],
            expectedRowCount: 7,
          },
          successMessage: 'Mission 2 complete! Supplier catalog audited.',
        },
      ],
    },
  ],

  // ===========================================================================
  // DAY 7 CHALLENGE: SCHEMA EXPLORATION MISSION CHECKLIST (ENDING ACTIVITY)
  // ===========================================================================
  challenge: {
    id: 'day-07-homework',
    title: 'Day 7 — Schema Exploration Mission Checklist (Ending Activity)',
    scenario: 'Execute these 5 single-table audits across the e-commerce schema:',
    tasks: [
      {
        id: 'day07-hw-1',
        title: 'Task 1: List all suppliers',
        description: 'List all supplier records in the directory.',
        instructions: ['Select all columns from `suppliers`.', 'End with a semicolon (;).'],
        type: 'challenge',
        primaryTable: 'suppliers',
        initialSql: '-- Task 1: List all suppliers\n',
        solutionSql: 'SELECT * FROM suppliers;',
        solutionExplanation: 'Lists all supplier records.',
        hints: [{ level: 1, text: 'Use `SELECT * FROM suppliers;`' }],
        validation: {
          targetTable: 'suppliers',
          expectedRowCount: 6,
        },
        successMessage: 'Task 1 completed! All suppliers listed.',
      },
      {
        id: 'day07-hw-2',
        title: 'Task 2: Products from Supplier #1 sorted by price',
        description: 'Products from supplier_id 1, sorted by price ascending.',
        instructions: [
          'Select from `products` where `supplier_id = 1` order by `price ASC`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 2: Products from supplier #1 sorted by price\n',
        solutionSql: 'SELECT * FROM products WHERE supplier_id = 1 ORDER BY price ASC;',
        solutionExplanation: 'Filters by supplier_id = 1 and sorts price ascending.',
        hints: [{ level: 1, text: 'Use `WHERE supplier_id = 1 ORDER BY price ASC;`' }],
        validation: {
          targetTable: 'products',
          requireWhere: true,
          requireOrderBy: [{ column: 'price', direction: 'ASC' }],
          expectedRowCount: 7,
        },
        successMessage: 'Task 2 completed! Supplier products sorted by price.',
      },
      {
        id: 'day07-hw-3',
        title: 'Task 3: Distinct categories in the system',
        description: 'Distinct category names in the catalog taxonomy.',
        instructions: [
          'Select distinct category names from `categories`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'categories',
        initialSql: '-- Task 3: Distinct categories in the system\n',
        solutionSql: 'SELECT DISTINCT name FROM categories;',
        solutionExplanation: 'Lists distinct category names.',
        hints: [{ level: 1, text: 'Use `SELECT DISTINCT name FROM categories;`' }],
        validation: {
          targetTable: 'categories',
          requireDistinct: true,
          expectedRowCount: 6,
        },
        successMessage: 'Task 3 completed! Distinct categories retrieved.',
      },
      {
        id: 'day07-hw-4',
        title: 'Task 4: The 3 most expensive products',
        description: 'Retrieve the 3 highest priced products in the catalog.',
        instructions: [
          'Select from `products` ordered by `price DESC LIMIT 3`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 4: The 3 most expensive products\n',
        solutionSql: 'SELECT * FROM products ORDER BY price DESC LIMIT 3;',
        solutionExplanation: '`ORDER BY price DESC LIMIT 3` retrieves the 3 highest priced items.',
        hints: [{ level: 1, text: 'Use `ORDER BY price DESC LIMIT 3;`' }],
        validation: {
          targetTable: 'products',
          requireOrderBy: [{ column: 'price', direction: 'DESC' }],
          requireLimit: 3,
          expectedRowCount: 3,
        },
        successMessage: 'Task 4 completed! Top 3 most expensive products retrieved.',
      },
      {
        id: 'day07-hw-5',
        title: 'Task 5: Page 2 of the full product catalog',
        description: 'Page 2 of the full product catalog (10 per page, sorted by product_id ASC).',
        instructions: [
          'Select from `products` ordered by `product_id ASC LIMIT 10 OFFSET 10`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 5: Page 2 of the full product catalog\n',
        solutionSql: 'SELECT * FROM products ORDER BY product_id ASC LIMIT 10 OFFSET 10;',
        solutionExplanation: 'Paginates to page 2 of the products table.',
        hints: [{ level: 1, text: 'Use `LIMIT 10 OFFSET 10;`' }],
        validation: {
          targetTable: 'products',
          requireLimit: 10,
          requireOffset: 10,
          expectedRowCount: 10,
        },
        successMessage: 'Task 5 completed! Page 2 of product catalog retrieved.',
      },
    ],
  },
};
