import { ModuleData } from '../../types/curriculum';

export const Day_05_MODULE: ModuleData = {
  id: 'day-05',
  slug: 'practice-retrieval-filtering-shaping',
  day: 5,
  title: 'Day 5 — Complete Single-Table Queries',
  shortTitle: 'Complete Single-Table Queries',
  type: 'practice_day',
  milestoneId: 'milestone-1',
  description: 'Put it all together: filter rows with WHERE, sort results with ORDER BY, and paginate with LIMIT/OFFSET. Build real operational queries that inventory teams and managers actually run.',
  estimatedMinutes: 60,
  completionLearnings: [
    'Assemble complete queries combining FROM, WHERE, SELECT, ORDER BY, LIMIT, and OFFSET',
    'Query inventory: find low-stock items, sort by urgency, show 10 per page',
    'Paginate results correctly using LIMIT/OFFSET arithmetic',
    'Sort by date, number, and text columns in both ascending and descending order',
  ],
  concepts: [
    {
      id: 'day-05-pipelines',
      order: 1,
      title: '1. Combine Clauses into Real Operational Queries',
      shortDescription: 'Write complete queries that filter, sort, and paginate — the real SQL you see in production applications.',
      theory: {
        summary: 'In real applications, you do not write isolated clauses. You construct unified query pipelines that filter records on multiple business conditions, sort by priority, and paginate for UI displays.',
        introTable: {
          tableName: 'products',
          description: 'Full inventory snapshot for operations dashboard',
          columns: ['product_id', 'name', 'price', 'quantity_in_stock', 'reorder_level'],
          rows: [
            [1, 'Wireless Mouse', 25.00, 42, 10],
            [9, 'Wireless Charging Pad', 19.99, 0, 15],
            [15, 'Steel Cable Management Tray', 22.00, 2, 8],
            [20, 'Steel Frame Footrest', 45.00, 0, 5],
          ],
        },
        explanation: [
          '### 1. The Anatomy of an Operational Pipeline',
          'Every complete single-table query follows a predictable pipeline flow:',
          '1. `SELECT [columns]` — Choose only the fields you need.',
          '2. `FROM [table]` — Identify the source table.',
          '3. `WHERE [conditions]` — Filter rows based on business rules.',
          '4. `ORDER BY [column ASC|DESC]` — Organize the output rows.',
          '5. `LIMIT [count] OFFSET [skip]` — Slice the specific page to display.',
        ],
        targetQuery: {
          sql: 'SELECT name, price, quantity_in_stock, reorder_level\nFROM products\nWHERE quantity_in_stock <= reorder_level\nORDER BY quantity_in_stock ASC\nLIMIT 5;',
          explanation: 'Find the 5 most urgently low-stock products (at or below reorder level), sorted lowest stock first.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: FROM products WHERE quantity_in_stock <= reorder_level',
            sqlSnippet: 'FROM products WHERE quantity_in_stock <= reorder_level',
            explanation: 'SQL visits products and isolates items at or below the reorder threshold.',
            tableData: {
              tableName: 'Low-Stock Candidates',
              columns: ['name', 'price', 'quantity_in_stock', 'reorder_level'],
              rows: [
                ['Wireless Charging Pad', 19.99, 0, 15],
                ['Steel Frame Footrest', 45.00, 0, 5],
                ['Steel Cable Management Tray', 22.00, 2, 8],
                ['Adjustable Standing Desk', 420.00, 3, 5],
                ['4K UltraHD Monitor (27-inch)', 349.99, 6, 10],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: ORDER BY quantity_in_stock ASC LIMIT 5',
            sqlSnippet: 'ORDER BY quantity_in_stock ASC LIMIT 5',
            explanation: 'Sorts lowest stock first and takes the top 5 urgent items.',
            tableData: {
              tableName: 'Priority Restock List',
              columns: ['name', 'price', 'quantity_in_stock', 'reorder_level'],
              highlightedColumns: ['name', 'quantity_in_stock'],
              highlightedRows: [0, 1, 2, 3, 4],
              rows: [
                ['Wireless Charging Pad', 19.99, 0, 15],
                ['Steel Frame Footrest', 45.00, 0, 5],
                ['Steel Cable Management Tray', 22.00, 2, 8],
                ['Adjustable Standing Desk', 420.00, 3, 5],
                ['4K UltraHD Monitor (27-inch)', 349.99, 6, 10],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Full single-table pipeline',
            sql: 'SELECT name, price, quantity_in_stock\nFROM products\nWHERE quantity_in_stock <= reorder_level\nORDER BY quantity_in_stock ASC\nLIMIT 10 OFFSET 0;',
            description: 'Integrated filter, sort, and slice.',
          },
        ],
        keyTakeaway: 'Combine filtering conditions, sorting, and pagination into clean, multi-clause query pipelines.',
        exampleQuery: 'SELECT name, price FROM products WHERE quantity_in_stock = 0 ORDER BY price DESC;',
        exampleQueryExplanation: 'Finds all out-of-stock items sorted by price highest first.',
        liveDemoSql: 'SELECT name, price, quantity_in_stock FROM products WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC LIMIT 5;',
        liveDemoNotes: 'Displays urgent low-stock items worst-first.',
        mcqs: [
          {
            question: 'What query retrieves Page 2 of a product catalog showing 10 products per page?',
            options: [
              'A. LIMIT 10 OFFSET 10',
              'B. LIMIT 20 OFFSET 10',
              'C. OFFSET 2 LIMIT 10',
              'D. LIMIT 10 OFFSET 2',
            ],
            correctIndex: 0,
            explanation: 'Page 2 skips the first 10 rows and takes the next 10: `LIMIT 10 OFFSET 10`.',
          },
        ],
        masteryPoints: ['Assemble full single-table query pipelines with progressive scaffolding'],
      },
      tasks: [
        {
          id: 'day05-c1-t1',
          title: 'Task 1 (High Guidance): Products Needing Restock',
          description: 'Find products where `quantity_in_stock <= reorder_level`, ordered by `quantity_in_stock ASC`.',
          instructions: [
            'Query the `products` table.',
            'Select `name`, `quantity_in_stock`, and `reorder_level`.',
            'Filter with `WHERE quantity_in_stock <= reorder_level`.',
            'Order by `quantity_in_stock ASC`.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'products',
          initialSql: '-- Task 1: High Guidance - Low stock inventory worst-first\nSELECT name, quantity_in_stock, reorder_level\nFROM products\nWHERE ;',
          solutionSql: 'SELECT name, quantity_in_stock, reorder_level FROM products WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;',
          solutionExplanation: 'Filters for items at or below the reorder threshold and sorts lowest stock first.',
          hints: [
            { level: 1, text: 'Use `WHERE quantity_in_stock <= reorder_level` to find low stock items.' },
            { level: 2, text: 'Add `ORDER BY quantity_in_stock ASC;` to sort from lowest stock to highest.' },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'products',
            requiredColumns: ['name', 'quantity_in_stock', 'reorder_level'],
            requireWhere: true,
            requireOrderBy: [{ column: 'quantity_in_stock', direction: 'ASC' }],
            expectedRowCount: 8,
          },
          successMessage: 'Task 1 completed! Low-stock items identified worst-first.',
        },
        {
          id: 'day05-c1-t2',
          title: 'Task 2 (Partial Guidance): Active Customer Roster',
          description: 'Select name, email, and city from customers where email is NOT NULL, ordered by name ASC and limited to 5.',
          instructions: [
            'Query the `customers` table.',
            'Select `name`, `email`, and `city`.',
            'Filter for customers with a verified email (`email IS NOT NULL`).',
            'Sort alphabetically by `name ASC` and limit output to `5`.',
          ],
          type: 'independent',
          primaryTable: 'customers',
          initialSql: '-- Task 2: Partial Guidance - Active customer roster\n',
          solutionSql: 'SELECT name, email, city FROM customers WHERE email IS NOT NULL ORDER BY name ASC LIMIT 5;',
          solutionExplanation: 'Filters out null emails, sorts names alphabetically, and limits to 5.',
          hints: [
            { level: 1, text: 'Remember to use `IS NOT NULL` (not `!= NULL`) to check for valid emails.' },
            { level: 2, text: 'Use `WHERE email IS NOT NULL ORDER BY name ASC LIMIT 5;`' },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'customers',
            requiredColumns: ['name', 'email', 'city'],
            requireWhere: true,
            requireOrderBy: [{ column: 'name', direction: 'ASC' }],
            requireLimit: 5,
            expectedRowCount: 5,
          },
          successMessage: 'Task 2 completed! Active customer roster retrieved.',
        },
        {
          id: 'day05-c1-t3',
          title: 'Task 3 (Goal Only): Product Catalog Page 2',
          description: 'Retrieve Page 2 of the product catalog (10 items per page, sorted by product_id ASC).',
          instructions: [
            'Select all columns from `products`.',
            'Sort by `product_id ASC`.',
            'Use `LIMIT` and `OFFSET` to display items 11 through 20 (Page 2).',
          ],
          type: 'independent',
          primaryTable: 'products',
          initialSql: '-- Task 3: Goal Only - Catalog pagination Page 2\n',
          solutionSql: 'SELECT * FROM products ORDER BY product_id ASC LIMIT 10 OFFSET 10;',
          solutionExplanation: '`LIMIT 10 OFFSET 10` skips the first 10 products and returns products 11 through 20.',
          hints: [
            { level: 1, text: 'To get page 2 with 10 items per page, skip 10 items using `OFFSET 10` and take 10 with `LIMIT 10`.' },
            { level: 2, text: 'Use `ORDER BY product_id ASC LIMIT 10 OFFSET 10;`' },
          ],
          validation: {
            requireExactResult: true,
            targetTable: 'products',
            requireOrderBy: [{ column: 'product_id', direction: 'ASC' }],
            requireLimit: 10,
            requireOffset: 10,
            expectedRowCount: 10,
          },
          successMessage: 'Task 3 completed! Page 2 of product catalog retrieved.',
        },
      ],
    },
  ],

  // ===========================================================================
  // DAY 5 CHALLENGE: INDEPENDENT PIPELINE CHALLENGE (ENDING ACTIVITY)
  // ===========================================================================
  challenge: {
    id: 'day-05-homework',
    title: 'Day 5 — Independent Pipeline Challenge (Ending Activity)',
    scenario: 'Solve these 4 operational query pipelines independently (business requirements only):',
    tasks: [
      {
        id: 'day05-hw-1',
        title: 'Task 1: All Out-of-Stock Products',
        description: 'Retrieve all products that currently have 0 units in stock.',
        instructions: [
          'Select all columns from `products` where `quantity_in_stock = 0`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Challenge 1: All out-of-stock products\n',
        solutionSql: 'SELECT * FROM products WHERE quantity_in_stock = 0;',
        solutionExplanation: 'Filters for items where quantity_in_stock is exactly 0.',
        hints: [{ level: 1, text: 'Use `WHERE quantity_in_stock = 0;`' }],
        validation: {
          requireExactResult: true,
          targetTable: 'products',
          requireWhere: true,
          whereContainsTerms: ['quantity_in_stock', '=', '0'],
          expectedRowCount: 3,
        },
        successMessage: 'Challenge 1 completed! Out-of-stock products found.',
      },
      {
        id: 'day05-hw-2',
        title: 'Task 2: Priority Reorder Products',
        description: 'Find all products whose current stock has reached or dropped below their reorder level. Show them starting with the ones closest to running out.',
        instructions: [
          'Select `name`, `quantity_in_stock`, `reorder_level` from `products`.',
          'Where `quantity_in_stock <= reorder_level` ordered by `quantity_in_stock ASC`.',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Challenge 2: Products needing reorder\n',
        solutionSql: 'SELECT name, quantity_in_stock, reorder_level FROM products WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;',
        solutionExplanation: 'Identifies inventory at or below threshold ordered by urgency.',
        hints: [{ level: 1, text: 'Use `WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;`' }],
        validation: {
          requireExactResult: true,
          targetTable: 'products',
          requireWhere: true,
          requireOrderBy: [{ column: 'quantity_in_stock', direction: 'ASC' }],
          expectedRowCount: 8,
        },
        successMessage: 'Challenge 2 completed! Reorder items listed.',
      },
      {
        id: 'day05-hw-3',
        title: 'Task 3: Catalog Page 2 Pagination',
        description: 'Page 2 of the product catalog, 10 per page, sorted by product_id ASC.',
        instructions: [
          'Select all columns from `products` ordered by `product_id ASC LIMIT 10 OFFSET 10`.',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Challenge 3: Page 2 of product catalog\n',
        solutionSql: 'SELECT * FROM products ORDER BY product_id ASC LIMIT 10 OFFSET 10;',
        solutionExplanation: 'Paginates through products skipping the first 10 rows.',
        hints: [{ level: 1, text: 'Use `ORDER BY product_id ASC LIMIT 10 OFFSET 10;`' }],
        validation: {
          requireExactResult: true,
          targetTable: 'products',
          requireLimit: 10,
          requireOffset: 10,
          expectedRowCount: 10,
        },
        successMessage: 'Challenge 3 completed! Page 2 of catalog retrieved.',
      },
      {
        id: 'day05-hw-4',
        title: 'Task 4: Newest Customer Signups (Top 5)',
        description: 'Retrieve the 5 most recently registered customers, sorted newest first.',
        instructions: [
          'Select `customer_id`, `name`, `signup_date` from `customers`.',
          'Order by `signup_date DESC LIMIT 5`.',
        ],
        type: 'challenge',
        primaryTable: 'customers',
        initialSql: '-- Challenge 4: Top 5 newest customer signups\n',
        solutionSql: 'SELECT customer_id, name, signup_date FROM customers ORDER BY signup_date DESC LIMIT 5;',
        solutionExplanation: 'Orders customers by signup date descending and limits to top 5.',
        hints: [{ level: 1, text: 'Use `ORDER BY signup_date DESC LIMIT 5;`' }],
        validation: {
          requireExactResult: true,
          targetTable: 'customers',
          requiredColumns: ['customer_id', 'name', 'signup_date'],
          requireOrderBy: [{ column: 'signup_date', direction: 'DESC' }],
          requireLimit: 5,
          expectedRowCount: 5,
        },
        successMessage: 'Challenge 4 completed! Top 5 newest customer signups retrieved.',
      },
    ],
  },
};
