import { ModuleData } from '../../types/curriculum';

// =============================================================================
// DAY 4: Result Shaping
// =============================================================================
export const DAY_04_MODULE: ModuleData = {
  id: 'day-04',
  slug: 'result-shaping',
  day: 4,
  title: 'Day 4 — Result Shaping',
  shortTitle: 'Result Shaping',
  type: 'module',
  milestoneId: 'milestone-1',
  description: 'Shape and organize output rows using DISTINCT to eliminate duplicates, ORDER BY for ascending and descending sorts, and LIMIT with OFFSET for pagination.',
  estimatedMinutes: 45,
  completionLearnings: [
    'Sort output records alphabetically, numerically, and chronologically with ORDER BY (ASC and DESC)',
    'Eliminate duplicate values from result sets using DISTINCT',
    'Cap output record counts using LIMIT',
    'Skip preceding rows for pagination using OFFSET',
  ],
  concepts: [
    // =========================================================================
    // CONCEPT 1a: Single-Column Sorting with ORDER BY (ASC & DESC)
    // =========================================================================
    {
      id: 'order-by-single-column',
      order: 1,
      title: '1. Single-Column Sorting (ASC & DESC)',
      shortDescription: 'Sort query results by a single column in ascending or descending order.',
      theory: {
        summary: 'Without an ORDER BY clause, relational databases return rows in arbitrary storage order. ORDER BY allows you to sort records explicitly.',
        introTable: {
          tableName: 'products',
          description: 'Inventory items with price and stock levels.',
          columns: ['product_id', 'name', 'price', 'quantity_in_stock'],
          rows: [
            [1, 'Wireless Mouse', 15.99, 40],
            [2, 'Bluetooth Speaker', 45.50, 3],
            [3, 'USB-C Charging Cable', 9.99, 0],
            [4, 'Mechanical Keyboard', 65.00, 12],
            [14, 'Office Chair', 120.00, 5],
          ],
        },
        explanation: [
          '### 1. Ascending vs Descending Order',
          '`ORDER BY price ASC` sorts from lowest to highest (`ASC` is the default direction).',
          '`ORDER BY price DESC` sorts from highest to lowest (useful for "top expensive" or "newest").',
          'ORDER BY is always placed at the end of single-table queries after any WHERE conditions.',
        ],
        targetQuery: {
          sql: 'SELECT name, price\nFROM products\nORDER BY price DESC;',
          explanation: 'Sort all products by price starting from the highest price down to the lowest.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: FROM products (Unordered rows)',
            sqlSnippet: 'FROM products',
            explanation: 'SQL reads the products table in storage order.',
            tableData: {
              tableName: 'products (Source Rows)',
              columns: ['product_id', 'name', 'price'],
              rows: [
                [1, 'Wireless Mouse', 15.99],
                [2, 'Bluetooth Speaker', 45.50],
                [4, 'Mechanical Keyboard', 65.00],
                [14, 'Office Chair', 120.00],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: ORDER BY price DESC (Sort highest first)',
            sqlSnippet: 'ORDER BY price DESC',
            explanation: 'SQL arranges all rows starting from highest price ($120.00) down to lowest ($15.99).',
            tableData: {
              tableName: 'Final Sorted Result',
              columns: ['name', 'price'],
              highlightedColumns: ['price'],
              highlightedRows: [0, 1, 2, 3],
              rows: [
                ['Office Chair', 120.00],
                ['Mechanical Keyboard', 65.00],
                ['Bluetooth Speaker', 45.50],
                ['Wireless Mouse', 15.99],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Sorting descending by price',
            sql: 'SELECT name, price\nFROM products\nORDER BY price DESC;',
            description: 'Sorts output in descending order by price.',
          },
          {
            title: 'Ascending alphabetical sort',
            sql: 'SELECT name, city\nFROM customers\nORDER BY name ASC;',
            description: 'Sorts names alphabetically from A to Z.',
          },
        ],
        keyTakeaway: 'Use ORDER BY column ASC for lowest-to-highest and ORDER BY column DESC for highest-to-lowest.',
        exampleQuery: 'SELECT name, price FROM products ORDER BY price DESC;',
        exampleQueryExplanation: 'Sorts products by price highest first.',
        liveDemoSql: 'SELECT name, price FROM products ORDER BY price DESC LIMIT 5;',
        liveDemoNotes: 'Displays top 5 most expensive products.',
        mcqs: [
          {
            question: 'What is the default sort direction if neither ASC nor DESC is specified?',
            options: ['A. Descending (DESC)', 'B. Ascending (ASC)', 'C. Random order', 'D. Insertion order'],
            correctIndex: 1,
            explanation: 'In SQL, ASC (ascending) is the default sort order.',
          },
        ],
        masteryPoints: ['Use ORDER BY with ASC and DESC', 'Sort by numbers, dates, and text'],
      },
      tasks: [
        {
          id: 'day04-c1a-t1',
          title: 'Task 1: Sort Products by Price Descending',
          description: 'Sort all products by price starting with the highest price.',
          instructions: [
            'Select `name` and `price` from `products`.',
            'Order by `price DESC`.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'products',
          initialSql: '-- Write your SQL query here\n',
          solutionSql: 'SELECT name, price FROM products ORDER BY price DESC;',
          solutionExplanation: '`ORDER BY price DESC` sorts output from highest price to lowest.',
          hints: [{ level: 1, text: 'Use `ORDER BY price DESC;`' }],
          validation: {
            targetTable: 'products',
            requiredColumns: ['name', 'price'],
            requireOrderBy: [{ column: 'price', direction: 'DESC' }],
            expectedRowCount: 28,
          },
          successMessage: 'Products sorted by price descending!',
        },
        {
          id: 'day04-c1a-t2',
          title: 'Task 2: Customers Alphabetical Directory',
          description: 'Show customer name and city, sorted alphabetically by name from A to Z.',
          instructions: [
            'Query the `customers` table.',
            'Select `name` and `city`.',
            'Order by `name ASC`.',
          ],
          type: 'independent',
          primaryTable: 'customers',
          initialSql: '-- Write your SQL query here\n',
          solutionSql: 'SELECT name, city FROM customers ORDER BY name ASC;',
          solutionExplanation: '`ORDER BY name ASC` lists customers from A to Z.',
          hints: [{ level: 1, text: 'Use `ORDER BY name ASC;`' }],
          validation: {
            targetTable: 'customers',
            requiredColumns: ['name', 'city'],
            requireOrderBy: [{ column: 'name', direction: 'ASC' }],
            expectedRowCount: 15,
          },
          successMessage: 'Perfect! Customer directory sorted alphabetically.',
        },
      ],
    },

    // =========================================================================
    // CONCEPT 1b: Multi-Column Sorting (Tie-Breaking)
    // =========================================================================
    {
      id: 'order-by-multi-column',
      order: 2,
      title: '2. Multi-Column Sorting (Tie-Breaking)',
      shortDescription: 'How to use secondary sort columns to resolve identical values.',
      theory: {
        summary: 'When multiple rows share the same value in the primary sort column, secondary sort columns resolve ties.',
        introTable: {
          tableName: 'students',
          description: 'Students table with shared ages',
          columns: ['id', 'name', 'age', 'department'],
          rows: [
            [1, 'Rahim', 21, 'CSE'],
            [2, 'Karim', 22, 'EEE'],
            [3, 'Ayesha', 20, 'CSE'],
            [4, 'Sumaiya', 23, 'BBA'],
            [5, 'Tanvir', 21, 'CSE'],
          ],
        },
        explanation: [
          '### 1. Why Secondary Columns Matter',
          'Notice that both Rahim and Tanvir are age 21. If we sort only by `age ASC`, SQL puts them in an arbitrary tie order.',
          '### 2. Resolving Ties with Comma Separation',
          'Adding a second column tells SQL: *"Sort by age first; whenever two students have the same age, sort them alphabetically by name"*:\n`ORDER BY age ASC, name ASC;`',
          '### 3. Independent Directions per Column',
          'Each column can have its own sort direction: `ORDER BY category_id ASC, price DESC` groups categories from 1 to 5, and shows the most expensive products first within each category.',
        ],
        targetQuery: {
          sql: "SELECT name, age\nFROM students\nORDER BY age ASC, name ASC;",
          explanation: "Sort students youngest first; when ages match, sort alphabetically by name.",
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: Primary Sort on age ASC',
            sqlSnippet: 'ORDER BY age ASC',
            explanation: 'Students ordered by age: Ayesha (20), then age 21 tie, Karim (22), Sumaiya (23).',
            tableData: {
              tableName: 'Primary Sort (Age Groups)',
              columns: ['name', 'age'],
              rows: [
                ['Ayesha', 20],
                ['Rahim', 21],
                ['Tanvir', 21],
                ['Karim', 22],
                ['Sumaiya', 23],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: Secondary Tiebreaker on name ASC',
            sqlSnippet: 'ORDER BY age ASC, name ASC',
            explanation: 'On the age 21 tie, Rahim (R) precedes Tanvir (T) alphabetically.',
            tableData: {
              tableName: 'Final Tiebroken Result',
              columns: ['name', 'age'],
              highlightedColumns: ['name', 'age'],
              highlightedRows: [1, 2],
              rows: [
                ['Ayesha', 20],
                ['Rahim', 21],
                ['Tanvir', 21],
                ['Karim', 22],
                ['Sumaiya', 23],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Multi-column sort syntax',
            sql: 'SELECT name, category_id, price\nFROM products\nORDER BY category_id ASC, price DESC;',
            description: 'Groups by category ascending, then sorts price descending within each category.',
          },
        ],
        keyTakeaway: 'In ORDER BY col1, col2, col2 acts as a tiebreaker whenever col1 values are identical.',
        exampleQuery: 'SELECT name, age FROM students ORDER BY age ASC, name ASC;',
        exampleQueryExplanation: 'Sorts by age youngest first, breaking ties alphabetically.',
        liveDemoSql: 'SELECT name, category_id, price FROM products ORDER BY category_id ASC, price DESC LIMIT 6;',
        liveDemoNotes: 'Displays categories in order with highest priced items first.',
        mcqs: [
          {
            question: 'In `ORDER BY category_id ASC, price DESC`, which column resolves ties when two products have the same category_id?',
            options: [
              'A. category_id',
              'B. price',
              'C. product_id',
              'D. name',
            ],
            correctIndex: 1,
            explanation: 'The secondary column (`price`) acts as the tiebreaker when primary `category_id` values match.',
          },
        ],
        masteryPoints: [
          'Use comma-separated column lists in ORDER BY',
          'Specify distinct ASC/DESC directions for each column',
        ],
      },
      tasks: [
        {
          id: 'day04-c1b-t1',
          title: 'Task 1: Students Sorted by Age and Name',
          description: 'Show student name and age, sorted youngest first (age ASC), and alphabetically by name (name ASC) for any age ties.',
          instructions: [
            'Select `name` and `age` from `students`.',
            'Order by `age ASC, name ASC`.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'students',
          initialSql: '-- Sort by age then name\n',
          solutionSql: 'SELECT name, age FROM students ORDER BY age ASC, name ASC;',
          solutionExplanation: '`ORDER BY age ASC, name ASC` sorts youngest first and alphabetically breaks ties (Rahim before Tanvir).',
          hints: [{ level: 1, text: 'Use `ORDER BY age ASC, name ASC;`' }],
          validation: {
            targetTable: 'students',
            requiredColumns: ['name', 'age'],
            requireOrderBy: [
              { column: 'age', direction: 'ASC' },
              { column: 'name', direction: 'ASC' },
            ],
            expectedRowCount: 5,
          },
          successMessage: 'Great job! You resolved sorting ties with multi-column ORDER BY.',
        },
        {
          id: 'day04-c1b-t2',
          title: 'Task 2: Products by Category and Price',
          description: 'Show name, category_id, and price from products, sorted by category_id ascending, and price descending within each category.',
          instructions: [
            'Query the `products` table.',
            'Select `name`, `category_id`, and `price`.',
            'Order by `category_id ASC, price DESC`.',
          ],
          type: 'independent',
          primaryTable: 'products',
          initialSql: '-- Sort by category then price descending\n',
          solutionSql: 'SELECT name, category_id, price FROM products ORDER BY category_id ASC, price DESC;',
          solutionExplanation: '`ORDER BY category_id ASC, price DESC` organizes products by category with highest price items first.',
          hints: [{ level: 1, text: 'Use `ORDER BY category_id ASC, price DESC;`' }],
          validation: {
            targetTable: 'products',
            requiredColumns: ['name', 'category_id', 'price'],
            requireOrderBy: [
              { column: 'category_id', direction: 'ASC' },
              { column: 'price', direction: 'DESC' },
            ],
            expectedRowCount: 28,
          },
          successMessage: 'Well done! You applied multi-column sorting with mixed directions.',
        },
      ],
    },

    // =========================================================================
    // CONCEPT 2: Deduplication with DISTINCT
    // =========================================================================
    {
      id: 'distinct-deduplication',
      order: 3,
      title: '3. Deduplication with DISTINCT',
      shortDescription: 'Eliminate duplicate rows to discover unique values.',
      theory: {
        summary: 'When multiple rows contain the same value in a column (e.g. several customers residing in "Dhaka"), `DISTINCT` collapses duplicates into a single unique list.',
        introTable: {
          tableName: 'customers',
          description: 'Customer list with overlapping cities.',
          columns: ['customer_id', 'name', 'city'],
          rows: [
            [1, 'Rafiul Islam', 'Dhaka'],
            [2, 'Priya Akter', 'Dhaka'],
            [3, 'Tanvir Ahmed', 'Chittagong'],
            [4, 'Nusrat Jahan', 'Chittagong'],
            [5, 'Kamal Hossain', 'Sylhet'],
          ],
        },
        explanation: [
          '### 1. Finding Unique Values',
          '`SELECT DISTINCT city FROM customers;` examines all rows and discards duplicate values so each city appears only once.',
          'Notice: DISTINCT is purely for row deduplication — it does not calculate totals or summaries.',
        ],
        targetQuery: {
          sql: 'SELECT DISTINCT city\nFROM customers;',
          explanation: 'Find all unique cities where customers live, discarding duplicate entries.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: FROM customers (Raw column values with duplicates)',
            sqlSnippet: 'FROM customers',
            explanation: 'SQL scans the city column for all customers.',
            tableData: {
              tableName: 'customers (Raw Cities)',
              columns: ['name', 'city'],
              rows: [
                ['Rafiul Islam', 'Dhaka'],
                ['Priya Akter', 'Dhaka'],
                ['Tanvir Ahmed', 'Chittagong'],
                ['Nusrat Jahan', 'Chittagong'],
                ['Kamal Hossain', 'Sylhet'],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: SELECT DISTINCT city (Collapse duplicates)',
            sqlSnippet: 'SELECT DISTINCT city',
            explanation: 'Duplicates of Dhaka and Chittagong are removed, producing unique city names.',
            tableData: {
              tableName: 'Final Unique Cities',
              columns: ['city'],
              highlightedColumns: ['city'],
              highlightedRows: [0, 1, 2],
              rows: [
                ['Dhaka'],
                ['Chittagong'],
                ['Sylhet'],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Deduplicating rows with DISTINCT',
            sql: 'SELECT DISTINCT column_name\nFROM table_name;',
            description: 'Returns only unique values in the specified column.',
          },
        ],
        keyTakeaway: 'DISTINCT removes duplicate output rows across the selected columns.',
        exampleQuery: 'SELECT DISTINCT city FROM customers;',
        exampleQueryExplanation: 'Lists every unique city where customers live.',
        liveDemoSql: 'SELECT DISTINCT city FROM customers ORDER BY city ASC;',
        liveDemoNotes: 'Returns alphabetical list of unique cities.',
        mcqs: [
          {
            question: 'Where must the DISTINCT keyword be placed in a SQL query?',
            options: [
              'A. At the very end after WHERE',
              'B. Immediately following SELECT before column names',
              'C. Inside the FROM clause',
              'D. Before the database name',
            ],
            correctIndex: 1,
            explanation: 'DISTINCT is written right after SELECT (e.g. `SELECT DISTINCT column FROM table`).',
          },
        ],
        masteryPoints: ['Use DISTINCT to extract unique categories and locations'],
      },
      tasks: [
        {
          id: 'day04-c2-t1',
          title: 'Task 1: Distinct Customer Cities',
          description: 'Get a unique list of all cities where customers are based.',
          instructions: [
            'Select `DISTINCT city` from `customers`.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'customers',
          initialSql: '-- Write your SQL query here\n',
          solutionSql: 'SELECT DISTINCT city FROM customers;',
          solutionExplanation: '`SELECT DISTINCT city FROM customers;` returns each city name once.',
          hints: [{ level: 1, text: 'Use `SELECT DISTINCT city FROM customers;`' }],
          validation: {
            targetTable: 'customers',
            requiredColumns: ['city'],
            requireDistinct: true,
            expectedRowCount: 6,
          },
          successMessage: 'Distinct cities listed!',
        },
        {
          id: 'day04-c2-t2',
          title: 'Task 2: Distinct Product Categories',
          description: 'Show a unique list of all category_id values present in the products table.',
          instructions: [
            'Query the `products` table.',
            'Select `DISTINCT category_id`.',
          ],
          type: 'independent',
          primaryTable: 'products',
          initialSql: '-- Write your SQL query here\n',
          solutionSql: 'SELECT DISTINCT category_id FROM products;',
          solutionExplanation: 'Returns unique category IDs (1, 2, 3, 4, 5, and null).',
          hints: [{ level: 1, text: 'Use `SELECT DISTINCT category_id FROM products;`' }],
          validation: {
            targetTable: 'products',
            requiredColumns: ['category_id'],
            requireDistinct: true,
            expectedRowCount: 6,
          },
          successMessage: 'Perfect! Unique categories identified.',
        },
      ],
    },

    // =========================================================================
    // CONCEPT 3: Pagination with LIMIT and OFFSET
    // =========================================================================
    {
      id: 'limit-and-offset',
      order: 4,
      title: '4. Pagination with LIMIT & OFFSET',
      shortDescription: 'Restrict row counts and skip rows for multi-page displays.',
      theory: {
        summary: 'Web applications rarely display thousands of records at once. `LIMIT` restricts how many rows to return, and `OFFSET` skips a specified number of rows before returning results.',
        introTable: {
          tableName: 'products',
          description: 'Product catalog rows 1 through 6',
          columns: ['product_id', 'name', 'price'],
          rows: [
            [1, 'Wireless Mouse', 15.99],
            [2, 'Bluetooth Speaker', 45.50],
            [3, 'USB-C Charging Cable', 9.99],
            [4, 'Mechanical Keyboard', 65.00],
            [14, 'Office Chair', 120.00],
            [15, 'Filing Cabinet', 89.99],
          ],
        },
        explanation: [
          '### 1. LIMIT and OFFSET Syntax',
          '`LIMIT 5` returns at most 5 rows.',
          '`LIMIT 10 OFFSET 10` returns 10 rows starting from row 11 (Page 2).',
          'Pagination Formula: Page $N$ with size $S$ is `LIMIT S OFFSET (N - 1) * S`.',
        ],
        targetQuery: {
          sql: 'SELECT name, price\nFROM products\nORDER BY price DESC\nLIMIT 3 OFFSET 0;',
          explanation: 'Retrieve the top 3 most expensive products (Page 1).',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: FROM products ORDER BY price DESC (Full sorted list)',
            sqlSnippet: 'FROM products ORDER BY price DESC',
            explanation: 'SQL sorts the catalog highest price first.',
            tableData: {
              tableName: 'Sorted Catalog',
              columns: ['name', 'price'],
              rows: [
                ['Office Chair', 120.00],
                ['Filing Cabinet', 89.99],
                ['Mechanical Keyboard', 65.00],
                ['Bluetooth Speaker', 45.50],
                ['Wireless Mouse', 15.99],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: LIMIT 3 OFFSET 0 (Slice Page 1)',
            sqlSnippet: 'LIMIT 3 OFFSET 0',
            explanation: 'Slices the first 3 most expensive products.',
            tableData: {
              tableName: 'Page 1 (Top 3 Items)',
              columns: ['name', 'price'],
              highlightedColumns: ['name', 'price'],
              highlightedRows: [0, 1, 2],
              rows: [
                ['Office Chair', 120.00],
                ['Filing Cabinet', 89.99],
                ['Mechanical Keyboard', 65.00],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Slicing and paginating results',
            sql: 'SELECT * FROM products ORDER BY price DESC LIMIT 5 OFFSET 0;\nSELECT * FROM products ORDER BY price DESC LIMIT 5 OFFSET 5;',
            description: 'Page 1 and Page 2 with 5 items per page.',
          },
        ],
        keyTakeaway: 'LIMIT controls batch size; OFFSET specifies how many rows to skip.',
        exampleQuery: 'SELECT name, quantity_in_stock FROM products ORDER BY quantity_in_stock ASC LIMIT 5;',
        exampleQueryExplanation: 'Returns the 5 lowest stock items.',
        liveDemoSql: 'SELECT name, quantity_in_stock FROM products ORDER BY quantity_in_stock ASC LIMIT 5;',
        liveDemoNotes: 'Displays lowest-stock products.',
        mcqs: [
          {
            question: 'How do you query Page 3 of a table with 10 records per page?',
            options: [
              'A. LIMIT 10 OFFSET 30',
              'B. LIMIT 10 OFFSET 20',
              'C. OFFSET 10 LIMIT 3',
              'D. LIMIT 30 OFFSET 10',
            ],
            correctIndex: 1,
            explanation: 'Page 3 skips 20 rows (2 * 10) and takes 10: `LIMIT 10 OFFSET 20`.',
          },
        ],
        masteryPoints: ['Use LIMIT to cap result sizes', 'Use OFFSET for pagination'],
      },
      tasks: [
        {
          id: 'day04-c3-t1',
          title: 'Task 1: Top 5 Lowest Stock Products',
          description: 'Find the 5 products with the lowest stock quantities.',
          instructions: [
            'Select `name` and `quantity_in_stock` from `products`.',
            'Order by `quantity_in_stock ASC` with `LIMIT 5`.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'products',
          initialSql: '-- Write your SQL query here\n',
          solutionSql: 'SELECT name, quantity_in_stock FROM products ORDER BY quantity_in_stock ASC LIMIT 5;',
          solutionExplanation: 'Sorts ascending by stock count and limits to the top 5.',
          hints: [{ level: 1, text: 'Use `ORDER BY quantity_in_stock ASC LIMIT 5;`' }],
          validation: {
            targetTable: 'products',
            requiredColumns: ['name', 'quantity_in_stock'],
            requireOrderBy: [{ column: 'quantity_in_stock', direction: 'ASC' }],
            requireLimit: 5,
            expectedRowCount: 5,
          },
          successMessage: 'Lowest stock products identified!',
        },
        {
          id: 'day04-c3-t2',
          title: 'Task 2: Page 2 of Customers (5 per page)',
          description: 'Fetch page 2 of customer records (5 per page), sorted by customer_id ascending.',
          instructions: [
            'Query the `customers` table.',
            'Select `customer_id`, `name`, and `city`.',
            'Order by `customer_id ASC` with `LIMIT 5 OFFSET 5`.',
          ],
          type: 'independent',
          primaryTable: 'customers',
          initialSql: '-- Fetch Page 2 of customers (LIMIT 5 OFFSET 5)\n',
          solutionSql: 'SELECT customer_id, name, city FROM customers ORDER BY customer_id ASC LIMIT 5 OFFSET 5;',
          solutionExplanation: 'Skips the first 5 customers and returns customers 6 through 10.',
          hints: [{ level: 1, text: 'Use `ORDER BY customer_id ASC LIMIT 5 OFFSET 5;`' }],
          validation: {
            targetTable: 'customers',
            requiredColumns: ['customer_id', 'name', 'city'],
            requireOrderBy: [{ column: 'customer_id', direction: 'ASC' }],
            requireLimit: 5,
            requireOffset: 5,
            expectedRowCount: 5,
          },
          successMessage: 'Spot on! You paginated to Page 2 of customers.',
        },
      ],
    },
  ],

  // ===========================================================================
  // DAY 4 CHALLENGE (MASTER CURRICULUM ASSIGNMENT)
  // ===========================================================================
  challenge: {
    id: 'day-04-homework',
    title: 'Day 4 — Result Shaping (Homework)',
    scenario: 'Apply sorting, deduplication, and row slicing to real inventory queries:',
    tasks: [
      {
        id: 'day04-hw-1',
        title: 'Task 1: Products sorted by price, highest first',
        description: 'Products sorted by price, highest first.',
        instructions: [
          'Select from `products` and sort by `price DESC`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 1: Products sorted by price, highest first\n',
        solutionSql: 'SELECT * FROM products ORDER BY price DESC;',
        solutionExplanation: '`ORDER BY price DESC` sorts all products starting with the highest price.',
        hints: [{ level: 1, text: 'Use `SELECT * FROM products ORDER BY price DESC;`' }],
        validation: {
          targetTable: 'products',
          requireOrderBy: [{ column: 'price', direction: 'DESC' }],
          expectedRowCount: 28,
        },
        successMessage: 'Task 1 completed! Products sorted highest first.',
      },
      {
        id: 'day04-hw-2',
        title: 'Task 2: Distinct list of cities customers are based in',
        description: 'Distinct list of cities customers are based in.',
        instructions: [
          'Select `DISTINCT city` from `customers`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'customers',
        initialSql: '-- Task 2: Distinct list of cities customers are based in\n',
        solutionSql: 'SELECT DISTINCT city FROM customers;',
        solutionExplanation: '`DISTINCT city` eliminates duplicate city names.',
        hints: [{ level: 1, text: 'Use `SELECT DISTINCT city FROM customers;`' }],
        validation: {
          targetTable: 'customers',
          requiredColumns: ['city'],
          requireDistinct: true,
          expectedRowCount: 6,
        },
        successMessage: 'Task 2 completed! Distinct cities listed.',
      },
      {
        id: 'day04-hw-3',
        title: 'Task 3: The 5 lowest-stock products',
        description: 'The 5 lowest-stock products (ORDER BY + LIMIT).',
        instructions: [
          'Select from `products` ordered by `quantity_in_stock ASC` with `LIMIT 5`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 3: The 5 lowest-stock products\n',
        solutionSql: 'SELECT * FROM products ORDER BY quantity_in_stock ASC LIMIT 5;',
        solutionExplanation: '`ORDER BY quantity_in_stock ASC LIMIT 5` returns the 5 lowest stock items.',
        hints: [{ level: 1, text: 'Use `ORDER BY quantity_in_stock ASC LIMIT 5;`' }],
        validation: {
          targetTable: 'products',
          requireOrderBy: [{ column: 'quantity_in_stock', direction: 'ASC' }],
          requireLimit: 5,
          expectedRowCount: 5,
        },
        successMessage: 'Task 3 completed! 5 lowest-stock products retrieved.',
      },
    ],
  },
};

// =============================================================================
// DAY 5: Guided Practice: Full Single-Table Query Pipelines (Mode 2)
// =============================================================================
export const DAY_05_MODULE: ModuleData = {
  id: 'day-05',
  slug: 'practice-retrieval-filtering-shaping',
  day: 5,
  title: 'Day 5 — Guided Practice: Retrieval, Filtering & Shaping',
  shortTitle: 'Practice: Single-Table Pipelines',
  type: 'practice_day',
  milestoneId: 'milestone-1',
  description: 'Consolidate single-table query construction by combining condition filtering, multi-column sorting, and pagination across inventory and customer operational pipelines.',
  estimatedMinutes: 60,
  completionLearnings: [
    'Assemble complete single-table operational pipelines (SELECT ... FROM ... WHERE ... ORDER BY ... LIMIT ... OFFSET)',
    'Filter inventory with thresholds like quantity_in_stock = 0 and <= reorder_level',
    'Paginate multi-page catalog datasets using LIMIT and OFFSET calculations',
    'Filter null-safe records and sort chronologically with LIMIT',
  ],
  concepts: [
    {
      id: 'day-05-pipelines',
      order: 1,
      title: '1. Assembling Full Single-Table Query Pipelines',
      shortDescription: 'From isolated keywords to complete operational pipelines.',
      theory: {
        summary: 'In real applications, you do not write isolated clauses. You construct unified query pipelines that filter records on multiple business conditions, sort by priority, and paginate for UI displays.',
        introTable: {
          tableName: 'products',
          description: 'Full inventory snapshot for operations dashboard',
          columns: ['product_id', 'name', 'price', 'quantity_in_stock', 'reorder_level'],
          rows: [
            [1, 'Wireless Mouse', 25.00, 42, 10],
            [9, 'Wireless Charging Pad', 19.99, 0, 15],
            [15, 'Steel Cable Management Tray', 22.00, 2, 8],
            [20, 'Steel Frame Footrest', 45.00, 0, 5],
          ],
        },
        explanation: [
          '### 1. The Anatomy of an Operational Pipeline',
          'Every complete single-table query follows a predictable pipeline flow:',
          '1. `SELECT [columns]` — Choose only the fields you need.',
          '2. `FROM [table]` — Identify the source table.',
          '3. `WHERE [conditions]` — Filter rows based on business rules.',
          '4. `ORDER BY [column ASC|DESC]` — Organize the output rows.',
          '5. `LIMIT [count] OFFSET [skip]` — Slice the specific page to display.',
        ],
        targetQuery: {
          sql: 'SELECT name, price, quantity_in_stock, reorder_level\nFROM products\nWHERE quantity_in_stock <= reorder_level\nORDER BY quantity_in_stock ASC\nLIMIT 5;',
          explanation: 'Find the 5 most urgently low-stock products (at or below reorder level), sorted lowest stock first.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: FROM products WHERE quantity_in_stock <= reorder_level',
            sqlSnippet: 'FROM products WHERE quantity_in_stock <= reorder_level',
            explanation: 'SQL visits products and isolates items at or below the reorder threshold.',
            tableData: {
              tableName: 'Low-Stock Candidates',
              columns: ['name', 'price', 'quantity_in_stock', 'reorder_level'],
              rows: [
                ['Wireless Charging Pad', 19.99, 0, 15],
                ['Steel Frame Footrest', 45.00, 0, 5],
                ['Steel Cable Management Tray', 22.00, 2, 8],
                ['Adjustable Standing Desk', 420.00, 3, 5],
                ['4K UltraHD Monitor (27-inch)', 349.99, 6, 10],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: ORDER BY quantity_in_stock ASC LIMIT 5',
            sqlSnippet: 'ORDER BY quantity_in_stock ASC LIMIT 5',
            explanation: 'Sorts lowest stock first and takes the top 5 urgent items.',
            tableData: {
              tableName: 'Priority Restock List',
              columns: ['name', 'price', 'quantity_in_stock', 'reorder_level'],
              highlightedColumns: ['name', 'quantity_in_stock'],
              highlightedRows: [0, 1, 2, 3, 4],
              rows: [
                ['Wireless Charging Pad', 19.99, 0, 15],
                ['Steel Frame Footrest', 45.00, 0, 5],
                ['Steel Cable Management Tray', 22.00, 2, 8],
                ['Adjustable Standing Desk', 420.00, 3, 5],
                ['4K UltraHD Monitor (27-inch)', 349.99, 6, 10],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Full single-table pipeline',
            sql: 'SELECT name, price, quantity_in_stock\nFROM products\nWHERE quantity_in_stock <= reorder_level\nORDER BY quantity_in_stock ASC\nLIMIT 10 OFFSET 0;',
            description: 'Integrated filter, sort, and slice.',
          },
        ],
        keyTakeaway: 'Combine filtering conditions, sorting, and pagination into clean, multi-clause query pipelines.',
        exampleQuery: 'SELECT name, price FROM products WHERE quantity_in_stock = 0 ORDER BY price DESC;',
        exampleQueryExplanation: 'Finds all out-of-stock items sorted by price highest first.',
        liveDemoSql: 'SELECT name, price, quantity_in_stock FROM products WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC LIMIT 5;',
        liveDemoNotes: 'Displays urgent low-stock items worst-first.',
        mcqs: [
          {
            question: 'What query retrieves Page 2 of a product catalog showing 10 products per page?',
            options: [
              'A. LIMIT 10 OFFSET 10',
              'B. LIMIT 20 OFFSET 10',
              'C. OFFSET 2 LIMIT 10',
              'D. LIMIT 10 OFFSET 2',
            ],
            correctIndex: 0,
            explanation: 'Page 2 skips the first 10 rows and takes the next 10: `LIMIT 10 OFFSET 10`.',
          },
        ],
        masteryPoints: ['Assemble full single-table query pipelines with progressive scaffolding'],
      },
      tasks: [
        {
          id: 'day05-c1-t1',
          title: 'Task 1 (High Guidance): Products Needing Restock',
          description: 'Find products where `quantity_in_stock <= reorder_level`, ordered by `quantity_in_stock ASC`.',
          instructions: [
            'Query the `products` table.',
            'Select `name`, `quantity_in_stock`, and `reorder_level`.',
            'Filter with `WHERE quantity_in_stock <= reorder_level`.',
            'Order by `quantity_in_stock ASC`.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'products',
          initialSql: '-- Task 1: High Guidance - Low stock inventory worst-first\nSELECT name, quantity_in_stock, reorder_level\nFROM products\nWHERE quantity_in_stock <= reorder_level\nORDER BY quantity_in_stock ASC;',
          solutionSql: 'SELECT name, quantity_in_stock, reorder_level FROM products WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;',
          solutionExplanation: 'Filters for items at or below the reorder threshold and sorts lowest stock first.',
          hints: [
            { level: 1, text: 'Use `WHERE quantity_in_stock <= reorder_level` to find low stock items.' },
            { level: 2, text: 'Add `ORDER BY quantity_in_stock ASC;` to sort from lowest stock to highest.' },
          ],
          validation: {
            targetTable: 'products',
            requiredColumns: ['name', 'quantity_in_stock', 'reorder_level'],
            requireWhere: true,
            requireOrderBy: [{ column: 'quantity_in_stock', direction: 'ASC' }],
            expectedRowCount: 8,
          },
          successMessage: 'Task 1 completed! Low-stock items identified worst-first.',
        },
        {
          id: 'day05-c1-t2',
          title: 'Task 2 (Partial Guidance): Active Customer Roster',
          description: 'Select name, email, and city from customers where email is NOT NULL, ordered by name ASC and limited to 5.',
          instructions: [
            'Query the `customers` table.',
            'Select `name`, `email`, and `city`.',
            'Filter for customers with a verified email (`email IS NOT NULL`).',
            'Sort alphabetically by `name ASC` and limit output to `5`.',
          ],
          type: 'independent',
          primaryTable: 'customers',
          initialSql: '-- Task 2: Partial Guidance - Active customer roster\n',
          solutionSql: 'SELECT name, email, city FROM customers WHERE email IS NOT NULL ORDER BY name ASC LIMIT 5;',
          solutionExplanation: 'Filters out null emails, sorts names alphabetically, and limits to 5.',
          hints: [
            { level: 1, text: 'Remember to use `IS NOT NULL` (not `!= NULL`) to check for valid emails.' },
            { level: 2, text: 'Use `WHERE email IS NOT NULL ORDER BY name ASC LIMIT 5;`' },
          ],
          validation: {
            targetTable: 'customers',
            requiredColumns: ['name', 'email', 'city'],
            requireWhere: true,
            requireOrderBy: [{ column: 'name', direction: 'ASC' }],
            requireLimit: 5,
            expectedRowCount: 5,
          },
          successMessage: 'Task 2 completed! Active customer roster retrieved.',
        },
        {
          id: 'day05-c1-t3',
          title: 'Task 3 (Goal Only): Product Catalog Page 2',
          description: 'Retrieve Page 2 of the product catalog (10 items per page, sorted by product_id ASC).',
          instructions: [
            'Select all columns from `products`.',
            'Sort by `product_id ASC`.',
            'Use `LIMIT` and `OFFSET` to display items 11 through 20 (Page 2).',
          ],
          type: 'independent',
          primaryTable: 'products',
          initialSql: '-- Task 3: Goal Only - Catalog pagination Page 2\n',
          solutionSql: 'SELECT * FROM products ORDER BY product_id ASC LIMIT 10 OFFSET 10;',
          solutionExplanation: '`LIMIT 10 OFFSET 10` skips the first 10 products and returns products 11 through 20.',
          hints: [
            { level: 1, text: 'To get page 2 with 10 items per page, skip 10 items using `OFFSET 10` and take 10 with `LIMIT 10`.' },
            { level: 2, text: 'Use `ORDER BY product_id ASC LIMIT 10 OFFSET 10;`' },
          ],
          validation: {
            targetTable: 'products',
            requireOrderBy: [{ column: 'product_id', direction: 'ASC' }],
            requireLimit: 10,
            requireOffset: 10,
            expectedRowCount: 10,
          },
          successMessage: 'Task 3 completed! Page 2 of product catalog retrieved.',
        },
      ],
    },
  ],

  // ===========================================================================
  // DAY 5 CHALLENGE: INDEPENDENT PIPELINE CHALLENGE (ENDING ACTIVITY)
  // ===========================================================================
  challenge: {
    id: 'day-05-homework',
    title: 'Day 5 — Independent Pipeline Challenge (Ending Activity)',
    scenario: 'Solve these 4 operational query pipelines independently (business requirements only):',
    tasks: [
      {
        id: 'day05-hw-1',
        title: 'Task 1: All Out-of-Stock Products',
        description: 'Retrieve all products that currently have 0 units in stock.',
        instructions: [
          'Select all columns from `products` where `quantity_in_stock = 0`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Challenge 1: All out-of-stock products\n',
        solutionSql: 'SELECT * FROM products WHERE quantity_in_stock = 0;',
        solutionExplanation: 'Filters for items where quantity_in_stock is exactly 0.',
        hints: [{ level: 1, text: 'Use `WHERE quantity_in_stock = 0;`' }],
        validation: {
          targetTable: 'products',
          requireWhere: true,
          whereContainsTerms: ['quantity_in_stock', '=', '0'],
          expectedRowCount: 3,
        },
        successMessage: 'Challenge 1 completed! Out-of-stock products found.',
      },
      {
        id: 'day05-hw-2',
        title: 'Task 2: Priority Reorder Products',
        description: 'Find all products whose current stock has reached or dropped below their reorder level. Show them starting with the ones closest to running out.',
        instructions: [
          'Select `name`, `quantity_in_stock`, `reorder_level` from `products`.',
          'Where `quantity_in_stock <= reorder_level` ordered by `quantity_in_stock ASC`.',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Challenge 2: Products needing reorder\n',
        solutionSql: 'SELECT name, quantity_in_stock, reorder_level FROM products WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;',
        solutionExplanation: 'Identifies inventory at or below threshold ordered by urgency.',
        hints: [{ level: 1, text: 'Use `WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;`' }],
        validation: {
          targetTable: 'products',
          requireWhere: true,
          requireOrderBy: [{ column: 'quantity_in_stock', direction: 'ASC' }],
          expectedRowCount: 8,
        },
        successMessage: 'Challenge 2 completed! Reorder items listed.',
      },
      {
        id: 'day05-hw-3',
        title: 'Task 3: Catalog Page 2 Pagination',
        description: 'Page 2 of the product catalog, 10 per page, sorted by product_id ASC.',
        instructions: [
          'Select all columns from `products` ordered by `product_id ASC LIMIT 10 OFFSET 10`.',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Challenge 3: Page 2 of product catalog\n',
        solutionSql: 'SELECT * FROM products ORDER BY product_id ASC LIMIT 10 OFFSET 10;',
        solutionExplanation: 'Paginates through products skipping the first 10 rows.',
        hints: [{ level: 1, text: 'Use `ORDER BY product_id ASC LIMIT 10 OFFSET 10;`' }],
        validation: {
          targetTable: 'products',
          requireLimit: 10,
          requireOffset: 10,
          expectedRowCount: 10,
        },
        successMessage: 'Challenge 3 completed! Page 2 of catalog retrieved.',
      },
      {
        id: 'day05-hw-4',
        title: 'Task 4: Newest Customer Signups (Top 5)',
        description: 'Retrieve the 5 most recently registered customers, sorted newest first.',
        instructions: [
          'Select `customer_id`, `name`, `signup_date` from `customers`.',
          'Order by `signup_date DESC LIMIT 5`.',
        ],
        type: 'challenge',
        primaryTable: 'customers',
        initialSql: '-- Challenge 4: Top 5 newest customer signups\n',
        solutionSql: 'SELECT customer_id, name, signup_date FROM customers ORDER BY signup_date DESC LIMIT 5;',
        solutionExplanation: 'Orders customers by signup date descending and limits to top 5.',
        hints: [{ level: 1, text: 'Use `ORDER BY signup_date DESC LIMIT 5;`' }],
        validation: {
          targetTable: 'customers',
          requiredColumns: ['customer_id', 'name', 'signup_date'],
          requireOrderBy: [{ column: 'signup_date', direction: 'DESC' }],
          requireLimit: 5,
          expectedRowCount: 5,
        },
        successMessage: 'Challenge 4 completed! Top 5 newest customer signups retrieved.',
      },
    ],
  },
};

// =============================================================================
// DAY 6: Visual Concept Lab: Logical Query Processing Order (Mode 1)
// =============================================================================
export const DAY_06_MODULE: ModuleData = {
  id: 'day-06',
  slug: 'logical-query-processing-simple',
  day: 6,
  title: 'Day 6 — Visual Concept Lab: Logical Query Processing Order (Simple Pass)',
  shortTitle: 'Logical Query Processing (Simple)',
  type: 'conceptual_session',
  milestoneId: 'milestone-1',
  description: 'Understand the 5-step logical execution order: FROM → WHERE → SELECT → ORDER BY → LIMIT, and why WHERE cannot reference SELECT column aliases.',
  estimatedMinutes: 45,
  completionLearnings: [
    'Explain the 5-step simple logical query processing order: FROM → WHERE → SELECT → ORDER BY → LIMIT',
    'Understand why WHERE cannot reference aliases defined in SELECT',
    'Distinguish between the standard logical execution model and database-specific syntax extensions (like MySQL)',
  ],
  concepts: [
    {
      id: 'simple-logical-order',
      order: 1,
      title: '1. The 5-Step Evaluation Lifecycle & Alias Visibility',
      shortDescription: 'FROM → WHERE → SELECT → ORDER BY → LIMIT.',
      theory: {
        summary: 'SQL queries are written starting with SELECT, but the database engine evaluates them in a completely different logical order. Understanding this lifecycle explains why column aliases created in SELECT cannot be used in WHERE.',
        introTable: {
          tableName: 'products',
          description: 'Sample products for execution tracing',
          columns: ['product_id', 'name', 'price'],
          rows: [
            [1, 'Wireless Mouse', 25.00],
            [2, 'Mechanical Keyboard', 89.99],
            [6, '4K UltraHD Monitor', 349.99],
          ],
        },
        explanation: [
          '### 1. The Core Misconception',
          'Why does this query fail with an error?',
          '```sql\nSELECT name, price * 1.15 AS taxed_price\nFROM products\nWHERE taxed_price > 50;\n```',
          'Because the database does not evaluate `SELECT` first! It evaluates `WHERE` before `SELECT`.',
          '### 2. The 5-Step Evaluation Timeline',
          '1. **Step 1: `FROM products`** — The engine identifies and loads the source table.',
          '2. **Step 2: `WHERE ...`** — Individual rows are filtered. (*`taxed_price` does not exist yet!*)',
          '3. **Step 3: `SELECT ...`** — Specific columns are extracted, calculated, and assigned aliases.',
          '4. **Step 4: `ORDER BY ...`** — The resulting rows are sorted. (*Can see SELECT aliases!*)',
          '5. **Step 5: `LIMIT / OFFSET`** — The sorted output is sliced.',
        ],
        targetQuery: {
          sql: 'SELECT name, price * 1.15 AS taxed_price\nFROM products\nWHERE price * 1.15 > 50\nORDER BY taxed_price DESC\nLIMIT 5;',
          explanation: 'Find products with a taxed price over $50, sort highest first, and return the top 5.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: FROM products',
            sqlSnippet: 'FROM products',
            explanation: 'SQL identifies the products table with all records.',
            tableData: {
              tableName: 'products (Source Table)',
              columns: ['name', 'price'],
              rows: [
                ['Wireless Mouse', 25.00],
                ['Mechanical Keyboard', 89.99],
                ['4K UltraHD Monitor', 349.99],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: WHERE price * 1.15 > 50 (Filter using raw expression)',
            sqlSnippet: 'WHERE price * 1.15 > 50',
            explanation: 'SQL filters rows using raw math (the alias taxed_price is not created yet).',
            tableData: {
              tableName: 'Filtered Surviving Rows',
              columns: ['name', 'price'],
              rows: [
                ['Mechanical Keyboard', 89.99],
                ['4K UltraHD Monitor', 349.99],
              ],
            },
          },
          {
            stepNumber: 3,
            stepTitle: 'Step 3: SELECT name, price * 1.15 AS taxed_price (Alias created)',
            sqlSnippet: 'SELECT name, price * 1.15 AS taxed_price',
            explanation: 'SQL computes the expression and assigns the alias taxed_price.',
            tableData: {
              tableName: 'Calculated Columns',
              columns: ['name', 'taxed_price'],
              rows: [
                ['Mechanical Keyboard', 103.49],
                ['4K UltraHD Monitor', 402.49],
              ],
            },
          },
          {
            stepNumber: 4,
            stepTitle: 'Step 4: ORDER BY taxed_price DESC (Alias is visible here)',
            sqlSnippet: 'ORDER BY taxed_price DESC',
            explanation: 'ORDER BY runs after SELECT, so it safely sees and sorts by taxed_price.',
            tableData: {
              tableName: 'Sorted Calculation',
              columns: ['name', 'taxed_price'],
              highlightedColumns: ['taxed_price'],
              rows: [
                ['4K UltraHD Monitor', 402.49],
                ['Mechanical Keyboard', 103.49],
              ],
            },
          },
          {
            stepNumber: 5,
            stepTitle: 'Step 5: LIMIT 5 (Slice final rows)',
            sqlSnippet: 'LIMIT 5',
            explanation: 'Takes the top 5 highest-priced rows.',
            tableData: {
              tableName: 'Final Query Result',
              columns: ['name', 'taxed_price'],
              highlightedColumns: ['name', 'taxed_price'],
              highlightedRows: [0, 1],
              rows: [
                ['4K UltraHD Monitor', 402.49],
                ['Mechanical Keyboard', 103.49],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Logical evaluation order',
            sql: '1. FROM table_name\n2. WHERE filter_condition (raw expressions)\n3. SELECT column_list (aliases created)\n4. ORDER BY sort_expression (can use aliases)\n5. LIMIT row_count;',
            description: 'The logical order of visibility across clauses.',
          },
        ],
        keyTakeaway: 'WHERE executes before SELECT (so WHERE cannot see SELECT aliases), while ORDER BY executes after SELECT.',
        exampleQuery: 'SELECT name, price * 1.15 AS taxed_price FROM products WHERE price * 1.15 > 50 ORDER BY taxed_price DESC LIMIT 5;',
        exampleQueryExplanation: 'Uses raw math in WHERE and alias in ORDER BY.',
        liveDemoSql: 'SELECT name, price * 1.15 AS taxed_price FROM products WHERE price * 1.15 > 50 ORDER BY taxed_price DESC LIMIT 5;',
        liveDemoNotes: 'Observes the full logical sequence in action.',
        mcqs: [
          {
            question: 'Why does `SELECT name, price * 1.15 AS taxed_price FROM products WHERE taxed_price > 50;` cause an error in standard SQL?',
            options: [
              'A. Because 1.15 is not a valid decimal',
              'B. Because the WHERE clause is evaluated at Step 2, before the SELECT clause creates the alias at Step 3',
              'C. Because AS is not allowed on calculated columns',
              'D. Because WHERE only accepts integer comparisons',
            ],
            correctIndex: 1,
            explanation: 'Logically, WHERE filters rows before SELECT creates column aliases.',
          },
        ],
        masteryPoints: ['Explain the 5-step execution lifecycle', 'Place aliases correctly in ORDER BY rather than WHERE'],
      },
      tasks: [
        {
          id: 'day06-c1-t1',
          title: 'Task 1 (Guided Fix): Fix the Alias in WHERE Error',
          description: 'Repair the broken query by placing the raw calculation in `WHERE` and using the alias in `ORDER BY`.',
          instructions: [
            'Select `name` and `price * 1.15 AS taxed_price` from `products`.',
            'Filter with `WHERE price * 1.15 > 50` (use raw math in WHERE).',
            'Sort by `taxed_price DESC` (use the alias in ORDER BY).',
            'Limit output to `5`.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'products',
          initialSql: '-- Fix the broken query below\nSELECT name, price * 1.15 AS taxed_price\nFROM products\nWHERE taxed_price > 50\nORDER BY taxed_price DESC\nLIMIT 5;',
          solutionSql: 'SELECT name, price * 1.15 AS taxed_price FROM products WHERE price * 1.15 > 50 ORDER BY taxed_price DESC LIMIT 5;',
          solutionExplanation: 'Raw expression is evaluated in WHERE at Step 2; the alias taxed_price is used in ORDER BY at Step 4.',
          hints: [
            { level: 1, text: 'Replace `WHERE taxed_price > 50` with `WHERE price * 1.15 > 50`.' },
            { level: 2, text: 'Keep `ORDER BY taxed_price DESC LIMIT 5;` since ORDER BY runs after SELECT.' },
          ],
          validation: {
            targetTable: 'products',
            requireWhere: true,
            requireOrderBy: [{ column: 'taxed_price', direction: 'DESC' }],
            requireLimit: 5,
            expectedRowCount: 5,
          },
          successMessage: 'Task 1 completed! Query repaired with correct clause visibility.',
        },
        {
          id: 'day06-c1-t2',
          title: 'Task 2 (Transfer): Customer Alias Sorting',
          description: 'Select customer name aliased as customer_name and city from customers in Dhaka, sorted by customer_name ASC.',
          instructions: [
            'Query the `customers` table.',
            'Select `name AS customer_name` and `city`.',
            "Filter where `city = 'Dhaka'`.",
            'Sort by `customer_name ASC`.',
          ],
          type: 'independent',
          primaryTable: 'customers',
          initialSql: '-- Select with alias in ORDER BY\n',
          solutionSql: "SELECT name AS customer_name, city FROM customers WHERE city = 'Dhaka' ORDER BY customer_name ASC;",
          solutionExplanation: 'WHERE uses actual column city; ORDER BY uses the created alias customer_name.',
          hints: [
            { level: 1, text: "Use `WHERE city = 'Dhaka'`." },
            { level: 2, text: "Add `ORDER BY customer_name ASC;`." },
          ],
          validation: {
            targetTable: 'customers',
            requiredColumns: ['customer_name', 'city'],
            requiredAliases: { name: 'customer_name' },
            requireWhere: true,
            requireOrderBy: [{ column: 'customer_name', direction: 'ASC' }],
            expectedRowCount: 6,
          },
          successMessage: 'Task 2 completed! Clause execution order verified.',
        },
      ],
    },
  ],

  // ===========================================================================
  // DAY 6 CHALLENGE: PREDICTION & ALIAS TRACING TEST (ENDING ACTIVITY)
  // ===========================================================================
  challenge: {
    id: 'day-06-homework',
    title: 'Day 6 — Prediction & Alias Tracing Test (Ending Activity)',
    scenario: 'Demonstrate your mastery of the 5-step query processing order:',
    tasks: [
      {
        id: 'day06-hw-1',
        title: 'Task 1: Trace execution order with WHERE and ORDER BY',
        description: 'Select products with price > 40, alias price as catalog_price, order by catalog_price DESC, limit 5.',
        instructions: [
          'Select `name`, `price AS catalog_price` from `products` where `price > 40` order by `catalog_price DESC` limit 5.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 1: Trace execution order with WHERE and ORDER BY\n',
        solutionSql: 'SELECT name, price AS catalog_price FROM products WHERE price > 40 ORDER BY catalog_price DESC LIMIT 5;',
        solutionExplanation: 'Uses raw column in WHERE and alias in ORDER BY.',
        hints: [{ level: 1, text: 'Use `WHERE price > 40 ORDER BY catalog_price DESC LIMIT 5;`' }],
        validation: {
          targetTable: 'products',
          requireWhere: true,
          requireOrderBy: [{ column: 'catalog_price', direction: 'DESC' }],
          requireLimit: 5,
          expectedRowCount: 5,
        },
        successMessage: 'Challenge completed! Execution lifecycle verified.',
      },
    ],
  },
};

// =============================================================================
// DAY 7: Applied Project: Full Schema Exploration (Mode 4)
// =============================================================================
export const DAY_07_MODULE: ModuleData = {
  id: 'day-07',
  slug: 'project-part-1-explore-schema',
  day: 7,
  title: 'Day 7 — Applied Project: Full Schema Exploration',
  shortTitle: 'Project: Schema Exploration',
  type: 'project_part',
  milestoneId: 'milestone-1',
  description: 'Join the E-Commerce Data Team to audit and explore the full 6-table database schema (suppliers, categories, products, customers, orders, order_items) using single-table queries.',
  estimatedMinutes: 75,
  completionLearnings: [
    'Navigate the full 6-table e-commerce relational schema independently',
    'Query suppliers, products, and categories using targeted single-table audits',
    'Identify primary key and foreign key reference columns across entities',
  ],
  concepts: [
    {
      id: 'schema-navigation',
      order: 1,
      title: '1. E-Commerce Data Team Onboarding & Schema Audit',
      shortDescription: 'Hands-on exploration of the complete relational schema.',
      theory: {
        summary: 'Welcome to the data engineering team! Before running analytical joins or modifying records, your onboarding mission is to audit and inspect all tables in the production e-commerce database.',
        introTable: {
          tableName: 'suppliers',
          description: 'Suppliers directory table',
          columns: ['supplier_id', 'name', 'contact_email'],
          rows: [
            [1, 'LogiTech Direct', 'supply@logitech-direct.com'],
            [2, 'KeyChron Components', 'orders@keychron-comp.com'],
            [3, 'Apex Cables & Hubs', 'sales@apexcables.io'],
          ],
        },
        explanation: [
          '### 1. The E-Commerce Schema Map',
          'The platform stores data across 6 interconnected entities:',
          '• **`suppliers`**: Directory of vendor partners (`supplier_id`, `name`, `contact_email`).',
          '• **`categories`**: Catalog taxonomy labels (`category_id`, `name`).',
          '• **`products`**: Inventory catalog (`product_id`, `name`, `supplier_id`, `category_id`, `price`, `quantity_in_stock`, `reorder_level`).',
          '• **`customers`**: Registered shoppers (`customer_id`, `name`, `email`, `city`, `signup_date`).',
          '• **`orders`**: Customer checkout records (`order_id`, `customer_id`, `order_date`, `status`).',
          '• **`order_items`**: Individual line items (`order_item_id`, `order_id`, `product_id`, `quantity`, `unit_price`).',
        ],
        targetQuery: {
          sql: 'SELECT supplier_id, name, contact_email\nFROM suppliers\nORDER BY supplier_id ASC;',
          explanation: 'Audit all registered supplier partners in the directory ordered by ID.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: FROM suppliers (Scan directory table)',
            sqlSnippet: 'FROM suppliers',
            explanation: 'Loads all registered vendor partner records.',
            tableData: {
              tableName: 'suppliers',
              columns: ['supplier_id', 'name', 'contact_email'],
              rows: [
                [1, 'LogiTech Direct', 'supply@logitech-direct.com'],
                [2, 'KeyChron Components', 'orders@keychron-comp.com'],
                [3, 'Apex Cables & Hubs', 'sales@apexcables.io'],
                [4, 'ErgoComfort Workspace', 'wholesale@ergocomfort.com'],
                [5, 'SoundWave Acoustic', 'b2b@soundwave.net'],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: SELECT supplier_id, name, contact_email ORDER BY supplier_id ASC',
            sqlSnippet: 'SELECT supplier_id, name, contact_email ORDER BY supplier_id ASC',
            explanation: 'Extracts supplier contact profiles in numeric ID order.',
            tableData: {
              tableName: 'Audited Supplier Directory',
              columns: ['supplier_id', 'name', 'contact_email'],
              highlightedColumns: ['supplier_id', 'name', 'contact_email'],
              highlightedRows: [0, 1, 2, 3, 4],
              rows: [
                [1, 'LogiTech Direct', 'supply@logitech-direct.com'],
                [2, 'KeyChron Components', 'orders@keychron-comp.com'],
                [3, 'Apex Cables & Hubs', 'sales@apexcables.io'],
                [4, 'ErgoComfort Workspace', 'wholesale@ergocomfort.com'],
                [5, 'SoundWave Acoustic', 'b2b@soundwave.net'],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Inspecting individual tables',
            sql: 'SELECT * FROM suppliers;\nSELECT * FROM categories;\nSELECT * FROM products;',
            description: 'Explore the structural layout of each entity.',
          },
        ],
        keyTakeaway: 'Audit all tables confidently using targeted single-table queries.',
        exampleQuery: 'SELECT * FROM suppliers;',
        exampleQueryExplanation: 'Lists all supplier partner records.',
        liveDemoSql: 'SELECT * FROM suppliers;',
        liveDemoNotes: 'Displays all suppliers in the database.',
        mcqs: [
          {
            question: 'Which table connects orders to products in this schema?',
            options: ['A. customers', 'B. order_items', 'C. categories', 'D. suppliers'],
            correctIndex: 1,
            explanation: '`order_items` stores individual line items for each order, referencing both order_id and product_id.',
          },
        ],
        masteryPoints: ['Explore any table in the schema using single-table queries'],
      },
      tasks: [
        {
          id: 'day07-c1-t1',
          title: 'Mission 1 (Guided): Inspect Supplier Directory',
          description: 'Retrieve all columns from the `suppliers` table.',
          instructions: ['Select all columns from `suppliers`.', 'End with a semicolon (;).'],
          type: 'guided',
          primaryTable: 'suppliers',
          initialSql: '-- Mission 1: List all supplier partners\n',
          solutionSql: 'SELECT * FROM suppliers;',
          solutionExplanation: 'Retrieves all registered vendor records.',
          hints: [{ level: 1, text: 'Use `SELECT * FROM suppliers;`' }],
          validation: {
            targetTable: 'suppliers',
            expectedRowCount: 6,
          },
          successMessage: 'Mission 1 complete! Supplier directory retrieved.',
        },
        {
          id: 'day07-c1-t2',
          title: 'Mission 2 (Semi-Guided): Audit Supplier #1 Catalog',
          description: 'Find products supplied by supplier_id 1, sorted by price ascending.',
          instructions: [
            'Query the `products` table.',
            'Select `name`, `price`, and `quantity_in_stock`.',
            'Filter where `supplier_id = 1`.',
            'Order by `price ASC`.',
          ],
          type: 'independent',
          primaryTable: 'products',
          initialSql: '-- Mission 2: Products from supplier #1\n',
          solutionSql: 'SELECT name, price, quantity_in_stock FROM products WHERE supplier_id = 1 ORDER BY price ASC;',
          solutionExplanation: 'Finds products from LogiTech Direct sorted by price.',
          hints: [{ level: 1, text: 'Use `WHERE supplier_id = 1 ORDER BY price ASC;`' }],
          validation: {
            targetTable: 'products',
            requiredColumns: ['name', 'price', 'quantity_in_stock'],
            requireWhere: true,
            requireOrderBy: [{ column: 'price', direction: 'ASC' }],
            expectedRowCount: 7,
          },
          successMessage: 'Mission 2 complete! Supplier catalog audited.',
        },
      ],
    },
  ],

  // ===========================================================================
  // DAY 7 CHALLENGE: SCHEMA EXPLORATION MISSION CHECKLIST (ENDING ACTIVITY)
  // ===========================================================================
  challenge: {
    id: 'day-07-homework',
    title: 'Day 7 — Schema Exploration Mission Checklist (Ending Activity)',
    scenario: 'Execute these 5 single-table audits across the e-commerce schema:',
    tasks: [
      {
        id: 'day07-hw-1',
        title: 'Task 1: List all suppliers',
        description: 'List all supplier records in the directory.',
        instructions: ['Select all columns from `suppliers`.', 'End with a semicolon (;).'],
        type: 'challenge',
        primaryTable: 'suppliers',
        initialSql: '-- Task 1: List all suppliers\n',
        solutionSql: 'SELECT * FROM suppliers;',
        solutionExplanation: 'Lists all supplier records.',
        hints: [{ level: 1, text: 'Use `SELECT * FROM suppliers;`' }],
        validation: {
          targetTable: 'suppliers',
          expectedRowCount: 6,
        },
        successMessage: 'Task 1 completed! All suppliers listed.',
      },
      {
        id: 'day07-hw-2',
        title: 'Task 2: Products from Supplier #1 sorted by price',
        description: 'Products from supplier_id 1, sorted by price ascending.',
        instructions: [
          'Select from `products` where `supplier_id = 1` order by `price ASC`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 2: Products from supplier #1 sorted by price\n',
        solutionSql: 'SELECT * FROM products WHERE supplier_id = 1 ORDER BY price ASC;',
        solutionExplanation: 'Filters by supplier_id = 1 and sorts price ascending.',
        hints: [{ level: 1, text: 'Use `WHERE supplier_id = 1 ORDER BY price ASC;`' }],
        validation: {
          targetTable: 'products',
          requireWhere: true,
          requireOrderBy: [{ column: 'price', direction: 'ASC' }],
          expectedRowCount: 7,
        },
        successMessage: 'Task 2 completed! Supplier products sorted by price.',
      },
      {
        id: 'day07-hw-3',
        title: 'Task 3: Distinct categories in the system',
        description: 'Distinct category names in the catalog taxonomy.',
        instructions: [
          'Select distinct category names from `categories`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'categories',
        initialSql: '-- Task 3: Distinct categories in the system\n',
        solutionSql: 'SELECT DISTINCT name FROM categories;',
        solutionExplanation: 'Lists distinct category names.',
        hints: [{ level: 1, text: 'Use `SELECT DISTINCT name FROM categories;`' }],
        validation: {
          targetTable: 'categories',
          requireDistinct: true,
          expectedRowCount: 6,
        },
        successMessage: 'Task 3 completed! Distinct categories retrieved.',
      },
      {
        id: 'day07-hw-4',
        title: 'Task 4: The 3 most expensive products',
        description: 'Retrieve the 3 highest priced products in the catalog.',
        instructions: [
          'Select from `products` ordered by `price DESC LIMIT 3`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 4: The 3 most expensive products\n',
        solutionSql: 'SELECT * FROM products ORDER BY price DESC LIMIT 3;',
        solutionExplanation: '`ORDER BY price DESC LIMIT 3` retrieves the 3 highest priced items.',
        hints: [{ level: 1, text: 'Use `ORDER BY price DESC LIMIT 3;`' }],
        validation: {
          targetTable: 'products',
          requireOrderBy: [{ column: 'price', direction: 'DESC' }],
          requireLimit: 3,
          expectedRowCount: 3,
        },
        successMessage: 'Task 4 completed! Top 3 most expensive products retrieved.',
      },
      {
        id: 'day07-hw-5',
        title: 'Task 5: Page 2 of the full product catalog',
        description: 'Page 2 of the full product catalog (10 per page, sorted by product_id ASC).',
        instructions: [
          'Select from `products` ordered by `product_id ASC LIMIT 10 OFFSET 10`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 5: Page 2 of the full product catalog\n',
        solutionSql: 'SELECT * FROM products ORDER BY product_id ASC LIMIT 10 OFFSET 10;',
        solutionExplanation: 'Paginates to page 2 of the products table.',
        hints: [{ level: 1, text: 'Use `LIMIT 10 OFFSET 10;`' }],
        validation: {
          targetTable: 'products',
          requireLimit: 10,
          requireOffset: 10,
          expectedRowCount: 10,
        },
        successMessage: 'Task 5 completed! Page 2 of product catalog retrieved.',
      },
    ],
  },
};

// =============================================================================
// DAY 8: Milestone 1: Single-Table Mastery Checkpoint (Mode 5)
// =============================================================================
export const DAY_08_MODULE: ModuleData = {
  id: 'day-08',
  slug: 'milestone-1-assessment',
  day: 8,
  title: 'Day 8 — Milestone 1: Single-Table Mastery Checkpoint',
  shortTitle: 'Milestone 1 Checkpoint',
  type: 'assignment',
  milestoneId: 'milestone-1',
  description: 'Independent competency verification for Milestone 1: prove proficiency in retrieving, filtering, sorting, and paginating single-table datasets unaided.',
  estimatedMinutes: 75,
  completionLearnings: [
    'Independently retrieve, filter, sort, and paginate single-table datasets',
    'Demonstrate complete fluency with Milestone 1 competencies without templates or skeletons',
  ],
  concepts: [
    {
      id: 'milestone-1-eval',
      order: 1,
      title: '1. Milestone 1 Core Competency Verification',
      shortDescription: 'Independent skill verification across Days 1–7.',
      theory: {
        summary: 'Milestone 1 Skill Verification: Prove your ability to independently translate business requirements into working single-table SQL queries without templates or assistance.',
        introTable: {
          tableName: 'products',
          description: 'Milestone evaluation test dataset',
          columns: ['product_id', 'name', 'price', 'quantity_in_stock', 'reorder_level'],
          rows: [
            [1, 'Wireless Mouse', 25.00, 42, 10],
            [9, 'Wireless Charging Pad', 19.99, 0, 15],
            [15, 'Steel Cable Management Tray', 22.00, 2, 8],
            [20, 'Steel Frame Footrest', 45.00, 0, 5],
          ],
        },
        explanation: [
          '### 1. Milestone 1 Verification Objectives',
          '• **Core Skill**: Filter inventory below reorder thresholds worst-first.',
          '• **Combination**: Extract unique supplier IDs from filtered subsets (`DISTINCT`).',
          '• **Transfer**: Retrieve extreme values (`LIMIT 1`).',
          '• **Hard Problem**: Multi-clause date interval pagination (`LIMIT` + `OFFSET`).',
        ],
        targetQuery: {
          sql: 'SELECT name, quantity_in_stock, reorder_level\nFROM products\nWHERE quantity_in_stock <= reorder_level\nORDER BY quantity_in_stock ASC\nLIMIT 5;',
          explanation: 'Assemble a complete single-table query filtering low-stock inventory, sorting worst-first, and limiting to 5.',
          badge: "The query we're going to break down",
        },
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: FROM products WHERE quantity_in_stock <= reorder_level',
            sqlSnippet: 'FROM products WHERE quantity_in_stock <= reorder_level',
            explanation: 'Filters all items where quantity_in_stock is at or below the reorder point.',
            tableData: {
              tableName: 'Low-Stock Products',
              columns: ['name', 'quantity_in_stock', 'reorder_level'],
              rows: [
                ['Wireless Charging Pad', 0, 15],
                ['Steel Frame Footrest', 0, 5],
                ['Steel Cable Management Tray', 2, 8],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: ORDER BY quantity_in_stock ASC LIMIT 5',
            sqlSnippet: 'ORDER BY quantity_in_stock ASC LIMIT 5',
            explanation: 'Sorts by stock quantity ascending and slices the top 5 urgent restock items.',
            tableData: {
              tableName: 'Final Query Result',
              columns: ['name', 'quantity_in_stock', 'reorder_level'],
              highlightedColumns: ['name', 'quantity_in_stock'],
              highlightedRows: [0, 1, 2],
              rows: [
                ['Wireless Charging Pad', 0, 15],
                ['Steel Frame Footrest', 0, 5],
                ['Steel Cable Management Tray', 2, 8],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Single table mastery',
            sql: 'SELECT DISTINCT ... FROM ... WHERE ... ORDER BY ... LIMIT ... OFFSET ...;',
            description: 'The complete single-table query foundation.',
          },
        ],
        keyTakeaway: 'Demonstrate full mastery of single-table data retrieval.',
        exampleQuery: 'SELECT * FROM products WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;',
        exampleQueryExplanation: 'Evaluates low-stock items worst first.',
        liveDemoSql: 'SELECT * FROM products WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;',
        liveDemoNotes: 'Displays critical inventory items.',
        mcqs: [
          {
            question: 'Spiral check from Day 2: a product has price = 50.00. Which filter keeps it?',
            options: [
              'A. WHERE price > 50',
              'B. WHERE price >= 50',
              'C. WHERE price != 50',
              'D. WHERE price < 50',
            ],
            correctIndex: 1,
            explanation: 'Only >= includes the boundary itself (Day 2). Checkpoints deliberately re-test earlier milestones - if this felt shaky, revisit Day 2 before the deliverables below.',
          },
          {
            question: 'What is the primary objective of Milestone 1?',
            options: [
              'A. Writing complex multi-table joins',
              'B. Independently retrieving, filtering, sorting, and paginating single-table queries',
              'C. Designing database indexes',
              'D. Setting up database replication',
            ],
            correctIndex: 1,
            explanation: 'Milestone 1 establishes single-table query mastery.',
          },
        ],
        masteryPoints: ['Pass all 5 Milestone 1 independent checkpoint tasks'],
      },
      tasks: [
        {
          id: 'day08-c1-t1',
          title: 'Warmup 1: Low Stock Products (Lowest Stock First)',
          description: 'List products that need restocking — their stock has reached or fallen below their reorder level. Put the lowest stock at the top.',
          instructions: [
            'Select `name`, `quantity_in_stock`, `reorder_level` from `products`.',
            'Where `quantity_in_stock <= reorder_level`.',
            'Order by `quantity_in_stock ASC`.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'products',
          initialSql: '-- Warmup 1: Low stock products worst-first\n',
          solutionSql: 'SELECT name, quantity_in_stock, reorder_level FROM products WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;',
          solutionExplanation: 'Finds products below reorder level, ordered from lowest stock to highest.',
          hints: [{ level: 1, text: 'Use `WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;`' }],
          validation: {
            targetTable: 'products',
            requiredColumns: ['name', 'quantity_in_stock', 'reorder_level'],
            requireWhere: true,
            requireOrderBy: [{ column: 'quantity_in_stock', direction: 'ASC' }],
            expectedRowCount: 8,
          },
          successMessage: 'Warmup 1 completed! Low stock items listed lowest stock first.',
        },
        {
          id: 'day08-c1-t2',
          title: 'Warmup 2: Unique Customer City Directory',
          description: 'Retrieve a distinct list of cities from the customers table, ordered alphabetically.',
          instructions: [
            'Query the `customers` table.',
            'Select `DISTINCT city`.',
            'Order by `city ASC`.',
          ],
          type: 'independent',
          primaryTable: 'customers',
          initialSql: '-- Warmup 2: Distinct cities sorted alphabetically\n',
          solutionSql: 'SELECT DISTINCT city FROM customers ORDER BY city ASC;',
          solutionExplanation: 'Returns unique customer cities sorted from A to Z.',
          hints: [{ level: 1, text: 'Use `SELECT DISTINCT city FROM customers ORDER BY city ASC;`' }],
          validation: {
            targetTable: 'customers',
            requiredColumns: ['city'],
            requireDistinct: true,
            requireOrderBy: [{ column: 'city', direction: 'ASC' }],
            expectedRowCount: 6,
          },
          successMessage: 'Warmup 2 completed! Unique customer locations sorted alphabetically.',
        },
      ],
    },
  ],

  // ===========================================================================
  // DAY 8 CHALLENGE: MILESTONE 1 MASTERY CHECKPOINT (ENDING ACTIVITY)
  // ===========================================================================
  challenge: {
    id: 'day-08-homework',
    title: 'Day 8 — Milestone 1 Mastery Checkpoint (Ending Activity)',
    scenario: 'Complete all 5 deliverables independently to verify Milestone 1 mastery:',
    tasks: [
      {
        id: 'day08-hw-1',
        title: 'Deliverable 1 (Core): Products at or below reorder level, lowest stock first',
        description: 'Find every product that needs restocking — its stock has reached or dropped below its reorder level — and list the most critical (lowest stock) first.',
        instructions: [
          'Select from `products` where `quantity_in_stock <= reorder_level` ordered by `quantity_in_stock ASC`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Deliverable 1: Products at or below reorder level, lowest stock first\n',
        solutionSql: 'SELECT * FROM products WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;',
        solutionExplanation: 'Sorts products below reorder level by stock quantity ascending.',
        hints: [{ level: 1, text: 'Use `WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;`' }],
        validation: {
          targetTable: 'products',
          requireWhere: true,
          requireOrderBy: [{ column: 'quantity_in_stock', direction: 'ASC' }],
          expectedRowCount: 8,
        },
        successMessage: 'Deliverable 1 verified! Low stock items sorted lowest stock first.',
      },
      {
        id: 'day08-hw-2',
        title: 'Deliverable 2 (Combination): Distinct supplier IDs in low-stock inventory',
        description: 'Which suppliers are affected by the low-stock situation? List each affected supplier only once, even if several low-stock products come from the same supplier.',
        instructions: [
          'Select `DISTINCT supplier_id` from `products` where `quantity_in_stock <= reorder_level`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Deliverable 2: Distinct supplier IDs in low-stock list\n',
        solutionSql: 'SELECT DISTINCT supplier_id FROM products WHERE quantity_in_stock <= reorder_level;',
        solutionExplanation: '`DISTINCT supplier_id` extracts unique suppliers affected by low stock.',
        hints: [{ level: 1, text: 'Use `SELECT DISTINCT supplier_id FROM products WHERE quantity_in_stock <= reorder_level;`' }],
        validation: {
          targetTable: 'products',
          requiredColumns: ['supplier_id'],
          requireDistinct: true,
          requireWhere: true,
          expectedRowCount: 5,
        },
        successMessage: 'Deliverable 2 verified! Suppliers affected by low stock listed.',
      },
      {
        id: 'day08-hw-3',
        title: 'Deliverable 3 (Transfer): The single newest customer signup',
        description: 'Find the customer who signed up most recently.',
        instructions: [
          'Select from `customers` ordered by `signup_date DESC LIMIT 1`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'customers',
        initialSql: '-- Deliverable 3: The single most recently added customer\n',
        solutionSql: 'SELECT * FROM customers ORDER BY signup_date DESC LIMIT 1;',
        solutionExplanation: '`ORDER BY signup_date DESC LIMIT 1` finds the newest customer signup.',
        hints: [{ level: 1, text: 'Use `ORDER BY signup_date DESC LIMIT 1;`' }],
        validation: {
          targetTable: 'customers',
          requireOrderBy: [{ column: 'signup_date', direction: 'DESC' }],
          requireLimit: 1,
          expectedRowCount: 1,
        },
        successMessage: 'Deliverable 3 verified! Most recent customer found.',
      },
      {
        id: 'day08-hw-4',
        title: 'Deliverable 4 (Transfer): Top 5 cheapest products',
        description: 'Show the 5 cheapest products in the catalog.',
        instructions: [
          'Select from `products` ordered by `price ASC LIMIT 5`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Deliverable 4: The 5 cheapest products\n',
        solutionSql: 'SELECT * FROM products ORDER BY price ASC LIMIT 5;',
        solutionExplanation: '`ORDER BY price ASC LIMIT 5` returns the 5 lowest priced products.',
        hints: [{ level: 1, text: 'Use `ORDER BY price ASC LIMIT 5;`' }],
        validation: {
          targetTable: 'products',
          requireOrderBy: [{ column: 'price', direction: 'ASC' }],
          requireLimit: 5,
          expectedRowCount: 5,
        },
        successMessage: 'Deliverable 4 verified! 5 cheapest products retrieved.',
      },
      {
        id: 'day08-hw-5',
        title: 'Deliverable 5 (Hard Problem): Customer Directory Page 2 Pagination',
        description: 'Retrieve Page 2 of the customer directory (5 customers per page, sorted by signup_date DESC).',
        instructions: [
          'Select all columns from `customers`.',
          'Order by `signup_date DESC LIMIT 5 OFFSET 5`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'customers',
        initialSql: '-- Deliverable 5: Page 2 of customer directory (5 per page)\n',
        solutionSql: 'SELECT * FROM customers ORDER BY signup_date DESC LIMIT 5 OFFSET 5;',
        solutionExplanation: 'Orders customers by newest signup first and retrieves Page 2 (skipping 5 with OFFSET 5, taking 5 with LIMIT 5).',
        hints: [{ level: 1, text: 'Use `ORDER BY signup_date DESC LIMIT 5 OFFSET 5;`' }],
        validation: {
          targetTable: 'customers',
          requireOrderBy: [{ column: 'signup_date', direction: 'DESC' }],
          requireLimit: 5,
          requireOffset: 5,
          expectedRowCount: 5,
        },
        successMessage: 'Deliverable 5 verified! Page 2 of customer directory retrieved.',
      },
    ],
  },
};

