import { ModuleData } from '../../types/curriculum';

// =============================================================================
// DAY 4: Result Shaping
// =============================================================================
export const DAY_04_MODULE: ModuleData = {
  id: 'day-04',
  slug: 'result-shaping',
  day: 4,
  title: 'Day 4 — Result Shaping',
  shortTitle: 'Result Shaping',
  type: 'module',
  milestoneId: 'milestone-1',
  description: 'Shape and organize output rows using DISTINCT to eliminate duplicates, ORDER BY for ascending and descending sorts, and LIMIT with OFFSET for pagination.',
  estimatedMinutes: 45,
  completionLearnings: [
    'Sort output records alphabetically, numerically, and chronologically with ORDER BY (ASC and DESC)',
    'Eliminate duplicate values from result sets using DISTINCT',
    'Cap output record counts using LIMIT',
    'Skip preceding rows for pagination using OFFSET',
  ],
  concepts: [
    // =========================================================================
    // CONCEPT 1a: Single-Column Sorting with ORDER BY (ASC & DESC)
    // =========================================================================
    {
      id: 'order-by-single-column',
      order: 1,
      title: '1. Single-Column Sorting (ASC & DESC)',
      shortDescription: 'Sort query results by a single column in ascending or descending order.',
      theory: {
        summary: 'Without an ORDER BY clause, relational databases return rows in arbitrary storage order. ORDER BY allows you to sort records explicitly.',
        introTable: {
          tableName: 'products',
          description: 'Inventory items with price and stock levels.',
          columns: ['product_id', 'name', 'price', 'quantity_in_stock'],
          rows: [
            [1, 'Wireless Mouse', 15.99, 40],
            [2, 'Bluetooth Speaker', 45.50, 3],
            [3, 'USB-C Charging Cable', 9.99, 0],
            [4, 'Mechanical Keyboard', 65.00, 12],
            [14, 'Office Chair', 120.00, 5],
          ],
        },
        explanation: [
          '### 1. Ascending vs Descending Order',
          '`ORDER BY price ASC` sorts from lowest to highest (`ASC` is the default direction).',
          '`ORDER BY price DESC` sorts from highest to lowest (useful for "top expensive" or "newest").',
          'QUESTION_BLOCK::ORDER BY Clause::Always placed after the WHERE clause: `SELECT ... FROM ... WHERE ... ORDER BY ...`',
        ],
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: FROM products',
            sqlSnippet: 'FROM products',
            explanation: 'SQL scans the products table.',
            tableData: {
              tableName: 'products',
              columns: ['product_id', 'name', 'price'],
              rows: [
                [1, 'Wireless Mouse', 15.99],
                [2, 'Bluetooth Speaker', 45.50],
                [4, 'Mechanical Keyboard', 65.00],
                [14, 'Office Chair', 120.00],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: ORDER BY price DESC',
            sqlSnippet: 'ORDER BY price DESC',
            explanation: 'SQL arranges all rows starting from highest price ($120.00) down to lowest ($15.99).',
            tableData: {
              tableName: 'Sorted Result',
              columns: ['name', 'price'],
              highlightedColumns: ['price'],
              rows: [
                ['Office Chair', 120.00],
                ['Mechanical Keyboard', 65.00],
                ['Bluetooth Speaker', 45.50],
                ['Wireless Mouse', 15.99],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Sorting descending by price',
            sql: 'SELECT name, price\nFROM products\nORDER BY price DESC;',
            description: 'Sorts output in descending order by price.',
          },
          {
            title: 'Ascending alphabetical sort',
            sql: 'SELECT name, city\nFROM customers\nORDER BY name ASC;',
            description: 'Sorts names alphabetically from A to Z.',
          },
        ],
        keyTakeaway: 'Use ORDER BY column ASC for lowest-to-highest and ORDER BY column DESC for highest-to-lowest.',
        exampleQuery: 'SELECT name, price FROM products ORDER BY price DESC;',
        exampleQueryExplanation: 'Sorts products by price highest first.',
        liveDemoSql: 'SELECT name, price FROM products ORDER BY price DESC LIMIT 5;',
        liveDemoNotes: 'Displays top 5 most expensive products.',
        mcqs: [
          {
            question: 'What is the default sort direction if neither ASC nor DESC is specified?',
            options: ['A. Descending (DESC)', 'B. Ascending (ASC)', 'C. Random order', 'D. Insertion order'],
            correctIndex: 1,
            explanation: 'In SQL, ASC (ascending) is the default sort order.',
          },
        ],
        masteryPoints: ['Use ORDER BY with ASC and DESC', 'Sort by numbers, dates, and text'],
      },
      tasks: [
        {
          id: 'day04-c1a-t1',
          title: 'Task 1: Sort Products by Price Descending',
          description: 'Sort all products by price starting with the highest price.',
          instructions: [
            'Select `name` and `price` from `products`.',
            'Order by `price DESC`.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'products',
          initialSql: '-- Write your SQL query here\n',
          solutionSql: 'SELECT name, price FROM products ORDER BY price DESC;',
          solutionExplanation: '`ORDER BY price DESC` sorts output from highest price to lowest.',
          hints: [{ level: 1, text: 'Use `ORDER BY price DESC;`' }],
          validation: {
            targetTable: 'products',
            requiredColumns: ['name', 'price'],
            requireOrderBy: [{ column: 'price', direction: 'DESC' }],
            expectedRowCount: 28,
          },
          successMessage: 'Products sorted by price descending!',
        },
        {
          id: 'day04-c1a-t2',
          title: 'Task 2: Customers Alphabetical Directory',
          description: 'Show customer name and city, sorted alphabetically by name from A to Z.',
          instructions: [
            'Query the `customers` table.',
            'Select `name` and `city`.',
            'Order by `name ASC`.',
          ],
          type: 'independent',
          primaryTable: 'customers',
          initialSql: '-- Write your SQL query here\n',
          solutionSql: 'SELECT name, city FROM customers ORDER BY name ASC;',
          solutionExplanation: '`ORDER BY name ASC` lists customers from A to Z.',
          hints: [{ level: 1, text: 'Use `ORDER BY name ASC;`' }],
          validation: {
            targetTable: 'customers',
            requiredColumns: ['name', 'city'],
            requireOrderBy: [{ column: 'name', direction: 'ASC' }],
            expectedRowCount: 15,
          },
          successMessage: 'Perfect! Customer directory sorted alphabetically.',
        },
      ],
    },

    // =========================================================================
    // CONCEPT 1b: Multi-Column Sorting (Tie-Breaking)
    // =========================================================================
    {
      id: 'order-by-multi-column',
      order: 2,
      title: '2. Multi-Column Sorting (Tie-Breaking)',
      shortDescription: 'How to use secondary sort columns to resolve identical values.',
      theory: {
        summary: 'When multiple rows share the same value in the primary sort column, secondary sort columns resolve ties.',
        introTable: {
          tableName: 'students',
          description: 'Students table with shared ages',
          columns: ['id', 'name', 'age', 'department'],
          rows: [
            [1, 'Rahim', 21, 'CSE'],
            [2, 'Karim', 22, 'EEE'],
            [3, 'Ayesha', 20, 'CSE'],
            [4, 'Sumaiya', 23, 'BBA'],
            [5, 'Tanvir', 21, 'CSE'],
          ],
        },
        explanation: [
          '### 1. Why Secondary Columns Matter',
          'Notice that both Rahim and Tanvir are age 21. If we sort only by `age ASC`, SQL puts them in an arbitrary tie order.',
          '### 2. Resolving Ties with Comma Separation',
          'Adding a second column tells SQL: *"Sort by age first; whenever two students have the same age, sort them alphabetically by name"*\n```sql\nSELECT name, age\nFROM students\nORDER BY age ASC, name ASC;\n```\nBecause `R` comes before `T`, Rahim is listed before Tanvir.',
          '### 3. Independent Directions per Column',
          'Each column can have its own sort direction: `ORDER BY category_id ASC, price DESC` groups categories from 1 to 5, and shows the most expensive products first within each category.',
        ],
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: Primary Sort on age ASC',
            sqlSnippet: 'ORDER BY age ASC',
            explanation: 'Students ordered by age: Ayesha (20), then age 21 tie, Karim (22), Sumaiya (23).',
            tableData: {
              tableName: 'Primary Sort',
              columns: ['name', 'age'],
              rows: [
                ['Ayesha', 20],
                ['Rahim', 21],
                ['Tanvir', 21],
                ['Karim', 22],
                ['Sumaiya', 23],
              ],
            },
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: Secondary Tiebreaker on name ASC',
            sqlSnippet: 'ORDER BY age ASC, name ASC',
            explanation: 'On the age 21 tie, Rahim (R) precedes Tanvir (T) alphabetically.',
            tableData: {
              tableName: 'Final Tiebroken Result',
              columns: ['name', 'age'],
              highlightedColumns: ['name', 'age'],
              rows: [
                ['Ayesha', 20],
                ['Rahim', 21],
                ['Tanvir', 21],
                ['Karim', 22],
                ['Sumaiya', 23],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Multi-column sort syntax',
            sql: 'SELECT name, category_id, price\nFROM products\nORDER BY category_id ASC, price DESC;',
            description: 'Groups by category ascending, then sorts price descending within each category.',
          },
        ],
        keyTakeaway: 'In ORDER BY col1, col2, col2 acts as a tiebreaker whenever col1 values are identical.',
        exampleQuery: 'SELECT name, age FROM students ORDER BY age ASC, name ASC;',
        exampleQueryExplanation: 'Sorts by age youngest first, breaking ties alphabetically.',
        liveDemoSql: 'SELECT name, category_id, price FROM products ORDER BY category_id ASC, price DESC LIMIT 6;',
        liveDemoNotes: 'Displays categories in order with highest priced items first.',
        mcqs: [
          {
            question: 'In `ORDER BY category_id ASC, price DESC`, which column resolves ties when two products have the same category_id?',
            options: [
              'A. category_id',
              'B. price',
              'C. product_id',
              'D. name',
            ],
            correctIndex: 1,
            explanation: 'The secondary column (`price`) acts as the tiebreaker when primary `category_id` values match.',
          },
        ],
        masteryPoints: [
          'Use comma-separated column lists in ORDER BY',
          'Specify distinct ASC/DESC directions for each column',
        ],
      },
      tasks: [
        {
          id: 'day04-c1b-t1',
          title: 'Task 1: Students Sorted by Age and Name',
          description: 'Show student name and age, sorted youngest first (age ASC), and alphabetically by name (name ASC) for any age ties.',
          instructions: [
            'Select `name` and `age` from `students`.',
            'Order by `age ASC, name ASC`.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'students',
          initialSql: '-- Sort by age then name\n',
          solutionSql: 'SELECT name, age FROM students ORDER BY age ASC, name ASC;',
          solutionExplanation: '`ORDER BY age ASC, name ASC` sorts youngest first and alphabetically breaks ties (Rahim before Tanvir).',
          hints: [{ level: 1, text: 'Use `ORDER BY age ASC, name ASC;`' }],
          validation: {
            targetTable: 'students',
            requiredColumns: ['name', 'age'],
            requireOrderBy: [
              { column: 'age', direction: 'ASC' },
              { column: 'name', direction: 'ASC' },
            ],
            expectedRowCount: 5,
          },
          successMessage: 'Great job! You resolved sorting ties with multi-column ORDER BY.',
        },
        {
          id: 'day04-c1b-t2',
          title: 'Task 2: Products by Category and Price',
          description: 'Show name, category_id, and price from products, sorted by category_id ascending, and price descending within each category.',
          instructions: [
            'Query the `products` table.',
            'Select `name`, `category_id`, and `price`.',
            'Order by `category_id ASC, price DESC`.',
          ],
          type: 'independent',
          primaryTable: 'products',
          initialSql: '-- Sort by category then price descending\n',
          solutionSql: 'SELECT name, category_id, price FROM products ORDER BY category_id ASC, price DESC;',
          solutionExplanation: '`ORDER BY category_id ASC, price DESC` organizes products by category with highest price items first.',
          hints: [{ level: 1, text: 'Use `ORDER BY category_id ASC, price DESC;`' }],
          validation: {
            targetTable: 'products',
            requiredColumns: ['name', 'category_id', 'price'],
            requireOrderBy: [
              { column: 'category_id', direction: 'ASC' },
              { column: 'price', direction: 'DESC' },
            ],
            expectedRowCount: 28,
          },
          successMessage: 'Well done! You applied multi-column sorting with mixed directions.',
        },
      ],
    },

    // =========================================================================
    // CONCEPT 2: Deduplication with DISTINCT
    // =========================================================================
    {
      id: 'distinct-deduplication',
      order: 3,
      title: '3. Deduplication with DISTINCT',
      shortDescription: 'Eliminate duplicate rows to discover unique values.',
      theory: {
        summary: 'When multiple rows contain the same value in a column (e.g. several customers residing in "Dhaka"), `DISTINCT` collapses duplicates into a single unique list.',
        introTable: {
          tableName: 'customers',
          description: 'Customer list with overlapping cities.',
          columns: ['customer_id', 'name', 'city'],
          rows: [
            [1, 'Rafiul Islam', 'Dhaka'],
            [2, 'Priya Akter', 'Dhaka'],
            [3, 'Tanvir Ahmed', 'Chittagong'],
            [4, 'Nusrat Jahan', 'Chittagong'],
            [5, 'Kamal Hossain', 'Sylhet'],
          ],
        },
        explanation: [
          '### 1. Finding Unique Values',
          '`SELECT DISTINCT city FROM customers;` examines all rows and discards duplicates.',
          'QUESTION_BLOCK::DISTINCT Keyword::Placed immediately after SELECT: `SELECT DISTINCT column1, column2 FROM ...`',
          'Notice: DISTINCT is purely for row deduplication — it does not calculate totals or summaries.',
        ],
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: Extracting Unique Cities',
            sqlSnippet: 'SELECT DISTINCT city\nFROM customers;',
            explanation: 'SQL finds all cities and removes duplicates, outputting each city exactly once.',
            tableData: {
              tableName: 'Result',
              columns: ['city'],
              highlightedColumns: ['city'],
              rows: [
                ['Dhaka'],
                ['Chittagong'],
                ['Sylhet'],
                ['Khulna'],
                ['Rajshahi'],
                ['Barisal'],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Deduplicating rows with DISTINCT',
            sql: 'SELECT DISTINCT column_name\nFROM table_name;',
            description: 'Returns only unique values in the specified column.',
          },
        ],
        keyTakeaway: 'DISTINCT removes duplicate output rows across the selected columns.',
        exampleQuery: 'SELECT DISTINCT city FROM customers;',
        exampleQueryExplanation: 'Lists every unique city where customers live.',
        liveDemoSql: 'SELECT DISTINCT city FROM customers ORDER BY city ASC;',
        liveDemoNotes: 'Returns alphabetical list of unique cities.',
        mcqs: [
          {
            question: 'Where must the DISTINCT keyword be placed in a SQL query?',
            options: [
              'A. At the very end after WHERE',
              'B. Immediately following SELECT before column names',
              'C. Inside the FROM clause',
              'D. Before the database name',
            ],
            correctIndex: 1,
            explanation: 'DISTINCT is written right after SELECT (e.g. `SELECT DISTINCT column FROM table`).',
          },
        ],
        masteryPoints: ['Use DISTINCT to extract unique categories and locations'],
      },
      tasks: [
        {
          id: 'day04-c2-t1',
          title: 'Task 1: Distinct Customer Cities',
          description: 'Get a unique list of all cities where customers are based.',
          instructions: [
            'Select `DISTINCT city` from `customers`.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'customers',
          initialSql: '-- Write your SQL query here\n',
          solutionSql: 'SELECT DISTINCT city FROM customers;',
          solutionExplanation: '`SELECT DISTINCT city FROM customers;` returns each city name once.',
          hints: [{ level: 1, text: 'Use `SELECT DISTINCT city FROM customers;`' }],
          validation: {
            targetTable: 'customers',
            requiredColumns: ['city'],
            requireDistinct: true,
            expectedRowCount: 6,
          },
          successMessage: 'Distinct cities listed!',
        },
        {
          id: 'day04-c2-t2',
          title: 'Task 2: Distinct Product Categories',
          description: 'Show a unique list of all category_id values present in the products table.',
          instructions: [
            'Query the `products` table.',
            'Select `DISTINCT category_id`.',
          ],
          type: 'independent',
          primaryTable: 'products',
          initialSql: '-- Write your SQL query here\n',
          solutionSql: 'SELECT DISTINCT category_id FROM products;',
          solutionExplanation: 'Returns unique category IDs (1, 2, 3, 4, 5, and null).',
          hints: [{ level: 1, text: 'Use `SELECT DISTINCT category_id FROM products;`' }],
          validation: {
            targetTable: 'products',
            requiredColumns: ['category_id'],
            requireDistinct: true,
            expectedRowCount: 6,
          },
          successMessage: 'Perfect! Unique categories identified.',
        },
      ],
    },

    // =========================================================================
    // CONCEPT 3: Pagination with LIMIT and OFFSET
    // =========================================================================
    {
      id: 'limit-and-offset',
      order: 4,
      title: '4. Pagination with LIMIT & OFFSET',
      shortDescription: 'Restrict row counts and skip rows for multi-page displays.',
      theory: {
        summary: 'Web applications rarely display thousands of records at once. `LIMIT` restricts how many rows to return, and `OFFSET` skips a specified number of rows before returning results.',
        introTable: {
          tableName: 'products',
          description: 'Product catalog rows 1 through 6',
          columns: ['product_id', 'name', 'price'],
          rows: [
            [1, 'Wireless Mouse', 15.99],
            [2, 'Bluetooth Speaker', 45.50],
            [3, 'USB-C Charging Cable', 9.99],
            [4, 'Mechanical Keyboard', 65.00],
            [14, 'Office Chair', 120.00],
            [15, 'Filing Cabinet', 89.99],
          ],
        },
        explanation: [
          '### 1. LIMIT and OFFSET Syntax',
          '`LIMIT 5` returns at most 5 rows.',
          '`LIMIT 10 OFFSET 10` returns 10 rows starting from row 11 (Page 2).',
          'QUESTION_BLOCK::Pagination Formula::Page $N$ with size $S$: `LIMIT S OFFSET (N - 1) * S`',
        ],
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: Top 3 items (LIMIT 3 OFFSET 0)',
            sqlSnippet: 'SELECT name, price FROM products ORDER BY price DESC LIMIT 3 OFFSET 0;',
            explanation: 'Slices the first 3 most expensive products.',
            tableData: {
              tableName: 'Page 1 (Top 3)',
              columns: ['name', 'price'],
              rows: [
                ['Office Chair', 120.00],
                ['Filing Cabinet', 89.99],
                ['Mechanical Keyboard', 65.00],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Slicing and paginating results',
            sql: 'SELECT * FROM products ORDER BY price DESC LIMIT 5 OFFSET 0;\nSELECT * FROM products ORDER BY price DESC LIMIT 5 OFFSET 5;',
            description: 'Page 1 and Page 2 with 5 items per page.',
          },
        ],
        keyTakeaway: 'LIMIT controls batch size; OFFSET specifies how many rows to skip.',
        exampleQuery: 'SELECT name, quantity_in_stock FROM products ORDER BY quantity_in_stock ASC LIMIT 5;',
        exampleQueryExplanation: 'Returns the 5 lowest stock items.',
        liveDemoSql: 'SELECT name, quantity_in_stock FROM products ORDER BY quantity_in_stock ASC LIMIT 5;',
        liveDemoNotes: 'Displays lowest-stock products.',
        mcqs: [
          {
            question: 'How do you query Page 3 of a table with 10 records per page?',
            options: [
              'A. LIMIT 10 OFFSET 30',
              'B. LIMIT 10 OFFSET 20',
              'C. OFFSET 10 LIMIT 3',
              'D. LIMIT 30 OFFSET 10',
            ],
            correctIndex: 1,
            explanation: 'Page 3 skips 20 rows (2 * 10) and takes 10: `LIMIT 10 OFFSET 20`.',
          },
        ],
        masteryPoints: ['Use LIMIT to cap result sizes', 'Use OFFSET for pagination'],
      },
      tasks: [
        {
          id: 'day04-c3-t1',
          title: 'Task 1: Top 5 Lowest Stock Products',
          description: 'Find the 5 products with the lowest stock quantities.',
          instructions: [
            'Select `name` and `quantity_in_stock` from `products`.',
            'Order by `quantity_in_stock ASC` with `LIMIT 5`.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'products',
          initialSql: '-- Write your SQL query here\n',
          solutionSql: 'SELECT name, quantity_in_stock FROM products ORDER BY quantity_in_stock ASC LIMIT 5;',
          solutionExplanation: 'Sorts ascending by stock count and limits to the top 5.',
          hints: [{ level: 1, text: 'Use `ORDER BY quantity_in_stock ASC LIMIT 5;`' }],
          validation: {
            targetTable: 'products',
            requiredColumns: ['name', 'quantity_in_stock'],
            requireOrderBy: [{ column: 'quantity_in_stock', direction: 'ASC' }],
            requireLimit: 5,
            expectedRowCount: 5,
          },
          successMessage: 'Lowest stock products identified!',
        },
        {
          id: 'day04-c3-t2',
          title: 'Task 2: Page 2 of Customers (5 per page)',
          description: 'Fetch page 2 of customer records (5 per page), sorted by customer_id ascending.',
          instructions: [
            'Query the `customers` table.',
            'Select `customer_id`, `name`, and `city`.',
            'Order by `customer_id ASC` with `LIMIT 5 OFFSET 5`.',
          ],
          type: 'independent',
          primaryTable: 'customers',
          initialSql: '-- Fetch Page 2 of customers (LIMIT 5 OFFSET 5)\n',
          solutionSql: 'SELECT customer_id, name, city FROM customers ORDER BY customer_id ASC LIMIT 5 OFFSET 5;',
          solutionExplanation: 'Skips the first 5 customers and returns customers 6 through 10.',
          hints: [{ level: 1, text: 'Use `ORDER BY customer_id ASC LIMIT 5 OFFSET 5;`' }],
          validation: {
            targetTable: 'customers',
            requiredColumns: ['customer_id', 'name', 'city'],
            requireOrderBy: [{ column: 'customer_id', direction: 'ASC' }],
            requireLimit: 5,
            requireOffset: 5,
            expectedRowCount: 5,
          },
          successMessage: 'Spot on! You paginated to Page 2 of customers.',
        },
      ],
    },
  ],

  // ===========================================================================
  // DAY 4 CHALLENGE (MASTER CURRICULUM ASSIGNMENT)
  // ===========================================================================
  challenge: {
    id: 'day-04-homework',
    title: 'Day 4 — Result Shaping (Homework)',
    scenario: 'Apply sorting, deduplication, and row slicing to real inventory queries:',
    tasks: [
      {
        id: 'day04-hw-1',
        title: 'Task 1: Products sorted by price, highest first',
        description: 'Products sorted by price, highest first.',
        instructions: [
          'Select from `products` and sort by `price DESC`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 1: Products sorted by price, highest first\n',
        solutionSql: 'SELECT * FROM products ORDER BY price DESC;',
        solutionExplanation: '`ORDER BY price DESC` sorts all products starting with the highest price.',
        hints: [{ level: 1, text: 'Use `SELECT * FROM products ORDER BY price DESC;`' }],
        validation: {
          targetTable: 'products',
          requireOrderBy: [{ column: 'price', direction: 'DESC' }],
          expectedRowCount: 28,
        },
        successMessage: 'Task 1 completed! Products sorted highest first.',
      },
      {
        id: 'day04-hw-2',
        title: 'Task 2: Distinct list of cities customers are based in',
        description: 'Distinct list of cities customers are based in.',
        instructions: [
          'Select `DISTINCT city` from `customers`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'customers',
        initialSql: '-- Task 2: Distinct list of cities customers are based in\n',
        solutionSql: 'SELECT DISTINCT city FROM customers;',
        solutionExplanation: '`DISTINCT city` eliminates duplicate city names.',
        hints: [{ level: 1, text: 'Use `SELECT DISTINCT city FROM customers;`' }],
        validation: {
          targetTable: 'customers',
          requiredColumns: ['city'],
          requireDistinct: true,
          expectedRowCount: 6,
        },
        successMessage: 'Task 2 completed! Distinct cities listed.',
      },
      {
        id: 'day04-hw-3',
        title: 'Task 3: The 5 lowest-stock products',
        description: 'The 5 lowest-stock products (ORDER BY + LIMIT).',
        instructions: [
          'Select from `products` ordered by `quantity_in_stock ASC` with `LIMIT 5`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 3: The 5 lowest-stock products\n',
        solutionSql: 'SELECT * FROM products ORDER BY quantity_in_stock ASC LIMIT 5;',
        solutionExplanation: '`ORDER BY quantity_in_stock ASC LIMIT 5` returns the 5 lowest stock items.',
        hints: [{ level: 1, text: 'Use `ORDER BY quantity_in_stock ASC LIMIT 5;`' }],
        validation: {
          targetTable: 'products',
          requireOrderBy: [{ column: 'quantity_in_stock', direction: 'ASC' }],
          requireLimit: 5,
          expectedRowCount: 5,
        },
        successMessage: 'Task 3 completed! 5 lowest-stock products retrieved.',
      },
    ],
  },
};

// =============================================================================
// DAY 5: Practice Day: Retrieval + Filtering + Shaping
// =============================================================================
export const DAY_05_MODULE: ModuleData = {
  id: 'day-05',
  slug: 'practice-retrieval-filtering-shaping',
  day: 5,
  title: 'Day 5 — Practice Day: Retrieval + Filtering + Shaping',
  shortTitle: 'Practice: Retrieval, Filtering & Shaping',
  type: 'practice_day',
  milestoneId: 'milestone-1',
  description: 'First full reuse checkpoint across Days 1–4. Consolidate retrieval, condition filtering, and result shaping through hands-on practice problems.',
  estimatedMinutes: 75,
  completionLearnings: [
    'Solve practical inventory and customer queries without guidance',
    'Combine condition filtering with thresholds like quantity_in_stock = 0 and <= reorder_level',
    'Paginate through multi-page catalog sets using LIMIT and OFFSET',
    'Filter temporal signups and sort chronologically with LIMIT',
  ],
  concepts: [
    {
      id: 'day-05-consolidation',
      order: 1,
      title: '1. Consolidated Query Pipelines',
      shortDescription: 'Practical application of Days 1–4 querying toolkit.',
      theory: {
        summary: 'No new syntax today — this practice module combines everything from Days 1 through 4 into practical operational queries.',
        introTable: {
          tableName: 'products',
          description: 'Full inventory snapshot for operations dashboard',
          columns: ['product_id', 'name', 'price', 'quantity_in_stock', 'reorder_level'],
          rows: [
            [1, 'Wireless Mouse', 25.00, 42, 10],
            [9, 'Wireless Charging Pad', 19.99, 0, 15],
            [15, 'Steel Cable Management Tray', 22.00, 2, 8],
            [20, 'Steel Frame Footrest', 45.00, 0, 5],
          ],
        },
        explanation: [
          '### 1. Pure Reuse Across Days 1–4',
          'Filtering on out-of-stock items (`quantity_in_stock = 0`) and restock triggers (`quantity_in_stock <= reorder_level`).',
          'Real pagination: Page 1 is `LIMIT 10 OFFSET 0`, Page 2 is `LIMIT 10 OFFSET 10`.',
          'Sorting and slicing: `ORDER BY price DESC LIMIT 5`.',
        ],
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: Full Pipeline (Filter + Sort + Slice)',
            sqlSnippet: 'SELECT name, price, quantity_in_stock\nFROM products\nWHERE quantity_in_stock <= reorder_level\nORDER BY quantity_in_stock ASC\nLIMIT 5;',
            explanation: 'Filters low-stock items, sorts from worst stock level to highest, and limits output to 5 items.',
            tableData: {
              tableName: 'Priority Restock List',
              columns: ['name', 'price', 'quantity_in_stock'],
              rows: [
                ['Wireless Charging Pad', 19.99, 0],
                ['Steel Frame Footrest', 45.00, 0],
                ['Steel Cable Management Tray', 22.00, 2],
                ['Adjustable Standing Desk', 420.00, 3],
                ['4K UltraHD Monitor (27-inch)', 349.99, 6],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Full single-table query pipeline',
            sql: 'SELECT name, price, quantity_in_stock\nFROM products\nWHERE quantity_in_stock <= reorder_level\nORDER BY quantity_in_stock ASC\nLIMIT 10 OFFSET 0;',
            description: 'Integrated filter, sort, and slice.',
          },
        ],
        keyTakeaway: 'Confidently integrate WHERE conditions, sorting, and pagination without assistance.',
        exampleQuery: 'SELECT * FROM products WHERE quantity_in_stock = 0;',
        exampleQueryExplanation: 'Finds all out-of-stock items.',
        liveDemoSql: 'SELECT * FROM products WHERE quantity_in_stock = 0;',
        liveDemoNotes: 'Finds items requiring immediate restocking.',
        mcqs: [
          {
            question: 'What query retrieves Page 2 of a product catalog showing 10 products per page?',
            options: [
              'A. LIMIT 10 OFFSET 10',
              'B. LIMIT 20 OFFSET 10',
              'C. OFFSET 2 LIMIT 10',
              'D. LIMIT 10 OFFSET 2',
            ],
            correctIndex: 0,
            explanation: 'Page 2 skips 10 records and takes the next 10: `LIMIT 10 OFFSET 10`.',
          },
        ],
        masteryPoints: ['Solve retrieval, filtering, and shaping queries unaided'],
      },
      tasks: [
        {
          id: 'day05-c1-t1',
          title: 'Task 1: Products Needing Reorder',
          description: 'Find products where `quantity_in_stock <= reorder_level`.',
          instructions: [
            'Select `name`, `quantity_in_stock`, and `reorder_level` from `products` where `quantity_in_stock <= reorder_level`.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'products',
          initialSql: '-- Write your SQL query here\n',
          solutionSql: 'SELECT name, quantity_in_stock, reorder_level FROM products WHERE quantity_in_stock <= reorder_level;',
          solutionExplanation: 'Identifies inventory at or below the reorder threshold.',
          hints: [{ level: 1, text: 'Use `WHERE quantity_in_stock <= reorder_level;`' }],
          validation: {
            targetTable: 'products',
            requiredColumns: ['name', 'quantity_in_stock', 'reorder_level'],
            requireWhere: true,
            expectedRowCount: 8,
          },
          successMessage: 'Reorder query verified!',
        },
        {
          id: 'day05-c1-t2',
          title: 'Task 2: Active Customer Roster',
          description: 'Select name, email, and city from customers where email is NOT NULL, ordered by name ASC and limited to 5.',
          instructions: [
            'Query the `customers` table.',
            'Select `name`, `email`, and `city`.',
            'Filter where `email IS NOT NULL`.',
            'Order by `name ASC LIMIT 5`.',
          ],
          type: 'independent',
          primaryTable: 'customers',
          initialSql: '-- Active customers with email\n',
          solutionSql: 'SELECT name, email, city FROM customers WHERE email IS NOT NULL ORDER BY name ASC LIMIT 5;',
          solutionExplanation: 'Filters for valid emails, sorts alphabetically, and limits to 5.',
          hints: [{ level: 1, text: 'Use `WHERE email IS NOT NULL ORDER BY name ASC LIMIT 5;`' }],
          validation: {
            targetTable: 'customers',
            requiredColumns: ['name', 'email', 'city'],
            requireWhere: true,
            requireOrderBy: [{ column: 'name', direction: 'ASC' }],
            requireLimit: 5,
            expectedRowCount: 5,
          },
          successMessage: 'Great job! You executed a multi-clause customer query.',
        },
      ],
    },
  ],

  // ===========================================================================
  // DAY 5 CHALLENGE (MASTER CURRICULUM ASSIGNMENT)
  // ===========================================================================
  challenge: {
    id: 'day-05-homework',
    title: 'Day 5 — Practice Day: Retrieval + Filtering + Shaping (Homework)',
    scenario: 'Solve these 4 practical operational queries independently (no notes, no help):',
    tasks: [
      {
        id: 'day05-hw-1',
        title: 'Task 1: All out-of-stock products',
        description: 'All out-of-stock products (quantity_in_stock = 0).',
        instructions: [
          'Select from `products` where `quantity_in_stock = 0`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 1: All out-of-stock products (quantity_in_stock = 0)\n',
        solutionSql: 'SELECT * FROM products WHERE quantity_in_stock = 0;',
        solutionExplanation: 'Filters for items with 0 stock.',
        hints: [{ level: 1, text: 'Use `WHERE quantity_in_stock = 0;`' }],
        validation: {
          targetTable: 'products',
          requireWhere: true,
          whereContainsTerms: ['quantity_in_stock', '=', '0'],
          expectedRowCount: 3,
        },
        successMessage: 'Task 1 completed! Out-of-stock products found.',
      },
      {
        id: 'day05-hw-2',
        title: 'Task 2: Products needing reorder (quantity_in_stock <= reorder_level)',
        description: 'Products needing reorder (quantity_in_stock <= reorder_level).',
        instructions: [
          'Select from `products` where `quantity_in_stock <= reorder_level`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 2: Products needing reorder (quantity_in_stock <= reorder_level)\n',
        solutionSql: 'SELECT * FROM products WHERE quantity_in_stock <= reorder_level;',
        solutionExplanation: 'Identifies inventory at or below minimum threshold.',
        hints: [{ level: 1, text: 'Use `WHERE quantity_in_stock <= reorder_level;`' }],
        validation: {
          targetTable: 'products',
          requireWhere: true,
          expectedRowCount: 8,
        },
        successMessage: 'Task 2 completed! Reorder items listed.',
      },
      {
        id: 'day05-hw-3',
        title: 'Task 3: Page 2 of the product catalog, 10 per page (LIMIT + OFFSET)',
        description: 'Page 2 of the product catalog, 10 per page (LIMIT + OFFSET).',
        instructions: [
          'Select from `products` ordered by `product_id ASC` with `LIMIT 10 OFFSET 10`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 3: Page 2 of the product catalog, 10 per page (LIMIT + OFFSET)\n',
        solutionSql: 'SELECT * FROM products ORDER BY product_id ASC LIMIT 10 OFFSET 10;',
        solutionExplanation: '`LIMIT 10 OFFSET 10` skips the first 10 products and returns products 11 through 20.',
        hints: [{ level: 1, text: 'Use `LIMIT 10 OFFSET 10;`' }],
        validation: {
          targetTable: 'products',
          requireLimit: 10,
          requireOffset: 10,
          expectedRowCount: 10,
        },
        successMessage: 'Task 3 completed! Page 2 of product catalog retrieved.',
      },
      {
        id: 'day05-hw-4',
        title: 'Task 4: Customers who joined in the last 30 days, sorted most-recent first, top 5 only',
        description: 'Customers who joined in the last 30 days, sorted most-recent first, top 5 only.',
        instructions: [
          'Select from `customers` where `signup_date >= CURDATE() - INTERVAL 30 DAY` (or `signup_date >= \'2026-07-25\'`).',
          'Order by `signup_date DESC` and `LIMIT 5`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'customers',
        initialSql: '-- Task 4: Customers who joined in the last 30 days, sorted most-recent first, top 5 only\n',
        solutionSql: 'SELECT * FROM customers WHERE signup_date >= CURDATE() - INTERVAL 30 DAY ORDER BY signup_date DESC LIMIT 5;',
        solutionExplanation: 'Filters for recent signups, sorts descending by signup date, and limits output to 5.',
        hints: [{ level: 1, text: 'Use `WHERE signup_date >= CURDATE() - INTERVAL 30 DAY ORDER BY signup_date DESC LIMIT 5;`' }],
        validation: {
          targetTable: 'customers',
          requireWhere: true,
          requireOrderBy: [{ column: 'signup_date', direction: 'DESC' }],
          requireLimit: 5,
          expectedRowCount: 5,
        },
        successMessage: 'Task 4 completed! Top 5 recent customers retrieved.',
      },
    ],
  },
};

// =============================================================================
// DAY 6: Conceptual Session: Logical Query Processing Order (Simple Pass)
// =============================================================================
export const DAY_06_MODULE: ModuleData = {
  id: 'day-06',
  slug: 'logical-query-processing-simple',
  day: 6,
  title: 'Day 6 — Conceptual Session: Logical Query Processing Order (Simple Pass)',
  shortTitle: 'Logical Query Processing (Simple)',
  type: 'conceptual_session',
  milestoneId: 'milestone-1',
  description: 'Understand the logical execution order of SQL clauses: FROM → WHERE → SELECT → ORDER BY → LIMIT, and why WHERE cannot reference SELECT column aliases.',
  estimatedMinutes: 30,
  completionLearnings: [
    'Explain the simple logical query processing order: FROM → WHERE → SELECT → ORDER BY → LIMIT',
    'Understand why WHERE cannot reference aliases defined in SELECT',
    'Understand the distinction between logical reasoning order and physical query execution',
  ],
  concepts: [
    {
      id: 'simple-logical-order',
      order: 1,
      title: '1. Logical Query Processing Order (Simple Pass)',
      shortDescription: 'FROM → WHERE → SELECT → ORDER BY → LIMIT.',
      theory: {
        summary: 'This is the logical order: how to reason about which clause "sees" what. It is not necessarily MySQL\'s literal internal execution steps — the optimizer can reorder operations for performance. This model is for understanding correctness, not predicting internals.',
        introTable: {
          tableName: 'products',
          description: 'Sample products for execution tracing',
          columns: ['product_id', 'name', 'price'],
          rows: [
            [1, 'Wireless Mouse', 25.00],
            [2, 'Mechanical Keyboard', 89.99],
            [6, '4K UltraHD Monitor', 349.99],
          ],
        },
        explanation: [
          '### 1. The 5-Step Simple Logical Order',
          '1. **FROM**: Identify and load the table.',
          '2. **WHERE**: Filter individual rows before any projection.',
          '3. **SELECT**: Pick and compute columns / assign aliases.',
          '4. **ORDER BY**: Sort the resulting rows (CAN see SELECT aliases!).',
          '5. **LIMIT / OFFSET**: Slice the final sorted output.',
          'QUESTION_BLOCK::Why WHERE cannot use SELECT aliases::Because WHERE executes at Step 2, while SELECT aliases are not created until Step 3!',
        ],
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: FROM products',
            sqlSnippet: 'FROM products',
            explanation: 'SQL identifies the products table with all rows.',
          },
          {
            stepNumber: 2,
            stepTitle: 'Step 2: WHERE price > 50',
            sqlSnippet: 'WHERE price > 50',
            explanation: 'SQL filters the rows, keeping only items priced over $50.',
          },
          {
            stepNumber: 3,
            stepTitle: 'Step 3: SELECT name, price AS product_price',
            sqlSnippet: 'SELECT name, price AS product_price',
            explanation: 'SQL extracts the name and price columns and creates the alias product_price.',
          },
          {
            stepNumber: 4,
            stepTitle: 'Step 4: ORDER BY product_price DESC',
            sqlSnippet: 'ORDER BY product_price DESC',
            explanation: 'ORDER BY executes after SELECT, so it CAN use the alias product_price.',
          },
          {
            stepNumber: 5,
            stepTitle: 'Step 5: LIMIT 3',
            sqlSnippet: 'LIMIT 3',
            explanation: 'Takes the top 3 rows.',
          },
        ],
        syntaxBlocks: [
          {
            title: 'Logical evaluation order',
            sql: '1. FROM table_name\n2. WHERE filter_condition\n3. SELECT column_list\n4. ORDER BY sort_expression\n5. LIMIT row_count;',
            description: 'The logical order of visibility across clauses.',
          },
        ],
        keyTakeaway: 'WHERE executes before SELECT (so WHERE cannot see SELECT aliases), while ORDER BY executes after SELECT.',
        exampleQuery: 'SELECT name, price AS cost FROM products WHERE price > 50 ORDER BY cost DESC LIMIT 3;',
        exampleQueryExplanation: 'WHERE price > 50 uses original column; ORDER BY cost DESC uses the alias.',
        liveDemoSql: 'SELECT name, price AS cost FROM products WHERE price > 50 ORDER BY cost DESC LIMIT 3;',
        liveDemoNotes: 'Observes the full logical sequence in action.',
        mcqs: [
          {
            question: 'Why does `SELECT name, price * 1.15 AS price_with_tax FROM products WHERE price_with_tax > 50;` cause an error?',
            options: [
              'A. Because 1.15 is not a valid decimal',
              'B. Because the WHERE clause is evaluated before the SELECT clause creates the alias price_with_tax',
              'C. Because AS is not allowed on calculated columns',
              'D. Because WHERE only accepts integer comparisons',
            ],
            correctIndex: 1,
            explanation: 'Logically, WHERE filters rows before SELECT creates column aliases.',
          },
        ],
        masteryPoints: ['Explain the 5-step simple execution order', 'Understand alias visibility rules'],
      },
      tasks: [
        {
          id: 'day06-c1-t1',
          title: 'Task 1: Trace Query Execution Order',
          description: 'Write a query that filters products by price, aliases price as unit_cost, and sorts by unit_cost.',
          instructions: [
            'Select `name` and `price AS unit_cost` from `products`.',
            'Filter with `WHERE price > 30` (using the original column name in WHERE).',
            'Sort by `unit_cost DESC` and `LIMIT 5`.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'products',
          initialSql: '-- Write your SQL query here\n',
          solutionSql: 'SELECT name, price AS unit_cost FROM products WHERE price > 30 ORDER BY unit_cost DESC LIMIT 5;',
          solutionExplanation: 'Demonstrates original column in WHERE and alias in ORDER BY.',
          hints: [{ level: 1, text: 'Use original column in WHERE and alias in ORDER BY.' }],
          validation: {
            targetTable: 'products',
            requireWhere: true,
            requireOrderBy: [{ column: 'unit_cost', direction: 'DESC' }],
            requireLimit: 5,
            expectedRowCount: 5,
          },
          successMessage: 'Logical query processing order demonstrated!',
        },
        {
          id: 'day06-c1-t2',
          title: 'Task 2: Customer Alias Sort',
          description: 'Select customer name aliased as customer_name and city from customers in Dhaka, sorted by customer_name ASC.',
          instructions: [
            'Query the `customers` table.',
            'Select `name AS customer_name` and `city`.',
            "Filter where `city = 'Dhaka'`.",
            'Sort by `customer_name ASC`.',
          ],
          type: 'independent',
          primaryTable: 'customers',
          initialSql: '-- Select with alias in ORDER BY\n',
          solutionSql: "SELECT name AS customer_name, city FROM customers WHERE city = 'Dhaka' ORDER BY customer_name ASC;",
          solutionExplanation: 'WHERE uses actual column city; ORDER BY uses the created alias customer_name.',
          hints: [{ level: 1, text: "Use `WHERE city = 'Dhaka' ORDER BY customer_name ASC;`" }],
          validation: {
            targetTable: 'customers',
            requiredColumns: ['customer_name', 'city'],
            requiredAliases: { name: 'customer_name' },
            requireWhere: true,
            requireOrderBy: [{ column: 'customer_name', direction: 'ASC' }],
            expectedRowCount: 6,
          },
          successMessage: 'Perfect! You demonstrated clause execution visibility.',
        },
      ],
    },
  ],

  // ===========================================================================
  // DAY 6 CHALLENGE (MASTER CURRICULUM ASSIGNMENT)
  // ===========================================================================
  challenge: {
    id: 'day-06-homework',
    title: 'Day 6 — Conceptual Session: Execution Order (Homework)',
    scenario: 'Demonstrate your mastery of logical query processing order:',
    tasks: [
      {
        id: 'day06-hw-1',
        title: 'Task 1: Trace single-table queries through execution steps',
        description: 'Select products with price > 40, alias price as catalog_price, order by catalog_price DESC, limit 5.',
        instructions: [
          'Select `name`, `price AS catalog_price` from `products` where `price > 40` order by `catalog_price DESC` limit 5.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 1: Trace execution order with WHERE and ORDER BY\n',
        solutionSql: 'SELECT name, price AS catalog_price FROM products WHERE price > 40 ORDER BY catalog_price DESC LIMIT 5;',
        solutionExplanation: 'Uses original column in WHERE and alias in ORDER BY.',
        hints: [{ level: 1, text: 'Use `WHERE price > 40 ORDER BY catalog_price DESC LIMIT 5;`' }],
        validation: {
          targetTable: 'products',
          requireWhere: true,
          requireLimit: 5,
          expectedRowCount: 5,
        },
        successMessage: 'Task 1 completed! Execution order verified.',
      },
    ],
  },
};

// =============================================================================
// DAY 7: Project Part 1: Explore & Query the Full Schema
// =============================================================================
export const DAY_07_MODULE: ModuleData = {
  id: 'day-07',
  slug: 'project-part-1-explore-schema',
  day: 7,
  title: 'Day 7 — Project Part 1: Explore & Query the Full Schema',
  shortTitle: 'Project Part 1: Full Schema Exploration',
  type: 'project_part',
  milestoneId: 'milestone-1',
  description: 'Navigate and inspect the complete inventory schema (suppliers, categories, products, customers, orders, order_items) using single-table queries.',
  estimatedMinutes: 90,
  completionLearnings: [
    'Navigate the full schema independently',
    'Query suppliers, products, and categories using single-table statements',
    'Identify primary key and foreign key reference columns',
  ],
  concepts: [
    {
      id: 'schema-navigation',
      order: 1,
      title: '1. Navigating the Inventory Schema',
      shortDescription: 'Hands-on exploration of the complete database.',
      theory: {
        summary: 'Today is an application day. You explore the entire schema: suppliers, products, categories, customers, orders, and order_items using single-table queries.',
        introTable: {
          tableName: 'suppliers',
          description: 'Suppliers directory table',
          columns: ['supplier_id', 'name', 'contact_email'],
          rows: [
            [1, 'LogiTech Direct', 'supply@logitech-direct.com'],
            [2, 'KeyChron Components', 'orders@keychron-comp.com'],
            [3, 'Apex Cables & Hubs', 'sales@apexcables.io'],
          ],
        },
        explanation: [
          '### 1. Schema Overview',
          '• **suppliers**: `supplier_id`, `name`, `contact_email`',
          '• **categories**: `category_id`, `name`',
          '• **products**: `product_id`, `name`, `supplier_id`, `category_id`, `price`, `quantity_in_stock`, `reorder_level`',
          '• **customers**: `customer_id`, `name`, `email`, `city`, `signup_date`',
          '• **orders**: `order_id`, `customer_id`, `order_date`, `status`',
          '• **order_items**: `order_item_id`, `order_id`, `product_id`, `quantity`, `unit_price`',
        ],
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: Inspecting suppliers table',
            sqlSnippet: 'SELECT * FROM suppliers;',
            explanation: 'Loads all supplier records.',
            tableData: {
              tableName: 'suppliers',
              columns: ['supplier_id', 'name', 'contact_email'],
              rows: [
                [1, 'LogiTech Direct', 'supply@logitech-direct.com'],
                [2, 'KeyChron Components', 'orders@keychron-comp.com'],
                [3, 'Apex Cables & Hubs', 'sales@apexcables.io'],
                [4, 'ErgoComfort Workspace', 'wholesale@ergocomfort.com'],
                [5, 'SoundWave Acoustic', 'b2b@soundwave.net'],
              ],
            },
          },
        ],
        syntaxBlocks: [
          {
            title: 'Inspecting individual tables',
            sql: 'SELECT * FROM suppliers;\nSELECT * FROM categories;\nSELECT * FROM products;',
            description: 'Explore the structural layout of each entity.',
          },
        ],
        keyTakeaway: 'Navigate all tables confidently using single-table queries.',
        exampleQuery: 'SELECT * FROM suppliers;',
        exampleQueryExplanation: 'Lists all supplier records.',
        liveDemoSql: 'SELECT * FROM suppliers;',
        liveDemoNotes: 'Displays all suppliers in the database.',
        mcqs: [
          {
            question: 'Which table connects orders to products in this schema?',
            options: ['A. customers', 'B. order_items', 'C. categories', 'D. suppliers'],
            correctIndex: 1,
            explanation: '`order_items` stores individual line items for each order, referencing both order_id and product_id.',
          },
        ],
        masteryPoints: ['Explore any table in the schema using single-table queries'],
      },
      tasks: [
        {
          id: 'day07-c1-t1',
          title: 'Task 1: List All Suppliers',
          description: 'Retrieve all columns from the `suppliers` table.',
          instructions: ['Select all columns from `suppliers`.', 'End with a semicolon (;).'],
          type: 'guided',
          primaryTable: 'suppliers',
          initialSql: '-- Write your SQL query here\n',
          solutionSql: 'SELECT * FROM suppliers;',
          solutionExplanation: 'Retrieves all suppliers.',
          hints: [{ level: 1, text: 'Use `SELECT * FROM suppliers;`' }],
          validation: {
            targetTable: 'suppliers',
            expectedRowCount: 6,
          },
          successMessage: 'All suppliers retrieved!',
        },
        {
          id: 'day07-c1-t2',
          title: 'Task 2: Supplier Catalog Filter',
          description: 'Find products supplied by supplier_id 1, sorted by price ascending.',
          instructions: [
            'Query the `products` table.',
            'Select `name`, `price`, and `quantity_in_stock`.',
            'Filter where `supplier_id = 1`.',
            'Order by `price ASC`.',
          ],
          type: 'independent',
          primaryTable: 'products',
          initialSql: '-- Products from supplier #1\n',
          solutionSql: 'SELECT name, price, quantity_in_stock FROM products WHERE supplier_id = 1 ORDER BY price ASC;',
          solutionExplanation: 'Finds products from LogiTech Direct sorted by price.',
          hints: [{ level: 1, text: 'Use `WHERE supplier_id = 1 ORDER BY price ASC;`' }],
          validation: {
            targetTable: 'products',
            requiredColumns: ['name', 'price', 'quantity_in_stock'],
            requireWhere: true,
            requireOrderBy: [{ column: 'price', direction: 'ASC' }],
            expectedRowCount: 7,
          },
          successMessage: 'Perfect! Supplier catalog filtered and sorted.',
        },
      ],
    },
  ],

  // ===========================================================================
  // DAY 7 CHALLENGE (MASTER CURRICULUM ASSIGNMENT)
  // ===========================================================================
  challenge: {
    id: 'day-07-homework',
    title: 'Day 7 — Project Part 1: Schema Exploration (Homework)',
    scenario: 'Execute these 5 single-table queries across the full inventory schema:',
    tasks: [
      {
        id: 'day07-hw-1',
        title: 'Task 1: List all suppliers',
        description: 'List all suppliers.',
        instructions: [
          'Select all columns from `suppliers`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'suppliers',
        initialSql: '-- Task 1: List all suppliers\n',
        solutionSql: 'SELECT * FROM suppliers;',
        solutionExplanation: '`SELECT * FROM suppliers;` lists all supplier records.',
        hints: [{ level: 1, text: 'Use `SELECT * FROM suppliers;`' }],
        validation: {
          targetTable: 'suppliers',
          expectedRowCount: 6,
        },
        successMessage: 'Task 1 completed! All suppliers listed.',
      },
      {
        id: 'day07-hw-2',
        title: 'Task 2: Products from one chosen supplier, sorted by price',
        description: 'Products from supplier_id 1, sorted by price ascending.',
        instructions: [
          'Select from `products` where `supplier_id = 1` order by `price ASC`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 2: Products from chosen supplier sorted by price\n',
        solutionSql: 'SELECT * FROM products WHERE supplier_id = 1 ORDER BY price ASC;',
        solutionExplanation: 'Filters by supplier_id = 1 and sorts price ascending.',
        hints: [{ level: 1, text: 'Use `WHERE supplier_id = 1 ORDER BY price ASC;`' }],
        validation: {
          targetTable: 'products',
          requireWhere: true,
          requireOrderBy: [{ column: 'price', direction: 'ASC' }],
          expectedRowCount: 7,
        },
        successMessage: 'Task 2 completed! Supplier products sorted by price.',
      },
      {
        id: 'day07-hw-3',
        title: 'Task 3: Distinct categories in the system',
        description: 'Distinct category names in the system.',
        instructions: [
          'Select distinct category names from `categories`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'categories',
        initialSql: '-- Task 3: Distinct categories in the system\n',
        solutionSql: 'SELECT DISTINCT name FROM categories;',
        solutionExplanation: 'Lists distinct category names.',
        hints: [{ level: 1, text: 'Use `SELECT DISTINCT name FROM categories;`' }],
        validation: {
          targetTable: 'categories',
          requireDistinct: true,
          expectedRowCount: 6,
        },
        successMessage: 'Task 3 completed! Distinct categories retrieved.',
      },
      {
        id: 'day07-hw-4',
        title: 'Task 4: The 3 most expensive products',
        description: 'The 3 most expensive products.',
        instructions: [
          'Select from `products` ordered by `price DESC LIMIT 3`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 4: The 3 most expensive products\n',
        solutionSql: 'SELECT * FROM products ORDER BY price DESC LIMIT 3;',
        solutionExplanation: '`ORDER BY price DESC LIMIT 3` retrieves the 3 highest priced items.',
        hints: [{ level: 1, text: 'Use `ORDER BY price DESC LIMIT 3;`' }],
        validation: {
          targetTable: 'products',
          requireOrderBy: [{ column: 'price', direction: 'DESC' }],
          requireLimit: 3,
          expectedRowCount: 3,
        },
        successMessage: 'Task 4 completed! Top 3 most expensive products retrieved.',
      },
      {
        id: 'day07-hw-5',
        title: 'Task 5: Page 2 of the full product catalog',
        description: 'Page 2 of the full product catalog (10 per page, sorted by product_id).',
        instructions: [
          'Select from `products` ordered by `product_id ASC LIMIT 10 OFFSET 10`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 5: Page 2 of the full product catalog\n',
        solutionSql: 'SELECT * FROM products ORDER BY product_id ASC LIMIT 10 OFFSET 10;',
        solutionExplanation: 'Paginates to page 2 of the products table.',
        hints: [{ level: 1, text: 'Use `LIMIT 10 OFFSET 10;`' }],
        validation: {
          targetTable: 'products',
          requireLimit: 10,
          requireOffset: 10,
          expectedRowCount: 10,
        },
        successMessage: 'Task 5 completed! Page 2 of product catalog retrieved.',
      },
    ],
  },
};

// =============================================================================
// DAY 8: Milestone Assignment 1 (Checkpoint)
// =============================================================================
export const DAY_08_MODULE: ModuleData = {
  id: 'day-08',
  slug: 'milestone-1-assessment',
  day: 8,
  title: 'Day 8 — Milestone Assignment 1 (Checkpoint)',
  shortTitle: 'Milestone 1 Assessment',
  type: 'assignment',
  milestoneId: 'milestone-1',
  description: 'Independent assessment for Milestone 1: prove proficiency in independently retrieving, filtering, sorting, and paging through data from a single table.',
  estimatedMinutes: 75,
  completionLearnings: [
    'Independently retrieve, filter, sort, and paginate single-table datasets',
    'Demonstrate complete mastery of Milestone 1 competencies',
  ],
  concepts: [
    {
      id: 'milestone-1-eval',
      order: 1,
      title: '1. Milestone 1 Core Competency Assessment',
      shortDescription: 'Independent evaluation across Days 1–7.',
      theory: {
        summary: 'Milestone 1 Checkpoint: "Can independently retrieve, filter, sort, and page through data from a single table without guidance."',
        introTable: {
          tableName: 'products',
          description: 'Milestone evaluation test dataset',
          columns: ['product_id', 'name', 'price', 'quantity_in_stock', 'reorder_level'],
          rows: [
            [1, 'Wireless Mouse', 25.00, 42, 10],
            [9, 'Wireless Charging Pad', 19.99, 0, 15],
            [15, 'Steel Cable Management Tray', 22.00, 2, 8],
            [20, 'Steel Frame Footrest', 45.00, 0, 5],
          ],
        },
        explanation: [
          '### 1. Assessment Objectives',
          '1. Products below reorder level, worst-first.',
          '2. Distinct supplier IDs represented in that low-stock list.',
          '3. The single most recently added customer.',
          '4. The 5 cheapest products.',
          '5. Page 2 of customers who signed up in the last 60 days.',
        ],
        stepBreakdowns: [
          {
            stepNumber: 1,
            stepTitle: 'Step 1: Evaluation Pipeline',
            sqlSnippet: 'SELECT * FROM products WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;',
            explanation: 'Demonstrates end-to-end single table mastery.',
          },
        ],
        syntaxBlocks: [
          {
            title: 'Single table mastery',
            sql: 'SELECT DISTINCT ... FROM ... WHERE ... ORDER BY ... LIMIT ... OFFSET ...;',
            description: 'The complete single-table query foundation.',
          },
        ],
        keyTakeaway: 'Demonstrate full mastery of single-table data retrieval.',
        exampleQuery: 'SELECT * FROM products WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;',
        exampleQueryExplanation: 'Evaluates low-stock items worst first.',
        liveDemoSql: 'SELECT * FROM products WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;',
        liveDemoNotes: 'Displays critical inventory items.',
        mcqs: [
          {
            question: 'What is the primary objective of Milestone 1?',
            options: [
              'A. Writing complex multi-table joins',
              'B. Independently retrieving, filtering, sorting, and paginating single-table queries',
              'C. Designing database indexes',
              'D. Setting up database replication',
            ],
            correctIndex: 1,
            explanation: 'Milestone 1 establishes single-table query mastery.',
          },
        ],
        masteryPoints: ['Pass all 5 Milestone 1 independent tasks'],
      },
      tasks: [
        {
          id: 'day08-c1-t1',
          title: 'Task 1: Low Stock Products Worst-First',
          description: 'Select products where `quantity_in_stock <= reorder_level`, ordered by `quantity_in_stock ASC`.',
          instructions: [
            'Select `name`, `quantity_in_stock`, `reorder_level` from `products`.',
            'Where `quantity_in_stock <= reorder_level`.',
            'Order by `quantity_in_stock ASC`.',
            'End with a semicolon (;).',
          ],
          type: 'guided',
          primaryTable: 'products',
          initialSql: '-- Write your SQL query here\n',
          solutionSql: 'SELECT name, quantity_in_stock, reorder_level FROM products WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;',
          solutionExplanation: 'Finds products below reorder level, ordered from lowest stock to highest.',
          hints: [{ level: 1, text: 'Use `WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;`' }],
          validation: {
            targetTable: 'products',
            requiredColumns: ['name', 'quantity_in_stock', 'reorder_level'],
            requireWhere: true,
            requireOrderBy: [{ column: 'quantity_in_stock', direction: 'ASC' }],
            expectedRowCount: 8,
          },
          successMessage: 'Low stock items identified worst-first!',
        },
        {
          id: 'day08-c1-t2',
          title: 'Task 2: Unique Customer City Directory',
          description: 'Retrieve a distinct list of cities from the customers table, ordered alphabetically.',
          instructions: [
            'Query the `customers` table.',
            'Select `DISTINCT city`.',
            'Order by `city ASC`.',
          ],
          type: 'independent',
          primaryTable: 'customers',
          initialSql: '-- Distinct cities sorted alphabetically\n',
          solutionSql: 'SELECT DISTINCT city FROM customers ORDER BY city ASC;',
          solutionExplanation: 'Returns unique customer cities sorted from A to Z.',
          hints: [{ level: 1, text: 'Use `SELECT DISTINCT city FROM customers ORDER BY city ASC;`' }],
          validation: {
            targetTable: 'customers',
            requiredColumns: ['city'],
            requireDistinct: true,
            requireOrderBy: [{ column: 'city', direction: 'ASC' }],
            expectedRowCount: 6,
          },
          successMessage: 'Spot on! Unique customer locations sorted alphabetically.',
        },
      ],
    },
  ],

  // ===========================================================================
  // DAY 8 CHALLENGE (MASTER CURRICULUM ASSIGNMENT)
  // ===========================================================================
  challenge: {
    id: 'day-08-homework',
    title: 'Day 8 — Milestone Assignment 1 (Assessment)',
    scenario: 'Complete all 5 tasks independently to clear Milestone 1:',
    tasks: [
      {
        id: 'day08-hw-1',
        title: 'Task 1: Products below reorder level, worst-first',
        description: 'Products below reorder level, worst-first (lowest quantity_in_stock first).',
        instructions: [
          'Select from `products` where `quantity_in_stock <= reorder_level` ordered by `quantity_in_stock ASC`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 1: Products below reorder level, worst-first\n',
        solutionSql: 'SELECT * FROM products WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;',
        solutionExplanation: 'Sorts products below reorder level by stock quantity ascending.',
        hints: [{ level: 1, text: 'Use `WHERE quantity_in_stock <= reorder_level ORDER BY quantity_in_stock ASC;`' }],
        validation: {
          targetTable: 'products',
          requireWhere: true,
          requireOrderBy: [{ column: 'quantity_in_stock', direction: 'ASC' }],
          expectedRowCount: 8,
        },
        successMessage: 'Task 1 completed! Low stock items sorted worst-first.',
      },
      {
        id: 'day08-hw-2',
        title: 'Task 2: Distinct supplier names/IDs represented in that low-stock list',
        description: 'Distinct supplier IDs represented in that low-stock list.',
        instructions: [
          'Select `DISTINCT supplier_id` from `products` where `quantity_in_stock <= reorder_level`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 2: Distinct supplier IDs in low-stock list\n',
        solutionSql: 'SELECT DISTINCT supplier_id FROM products WHERE quantity_in_stock <= reorder_level;',
        solutionExplanation: '`DISTINCT supplier_id` extracts unique suppliers affected by low stock.',
        hints: [{ level: 1, text: 'Use `SELECT DISTINCT supplier_id FROM products WHERE quantity_in_stock <= reorder_level;`' }],
        validation: {
          targetTable: 'products',
          requiredColumns: ['supplier_id'],
          requireDistinct: true,
          requireWhere: true,
          expectedRowCount: 5,
        },
        successMessage: 'Task 2 completed! Suppliers affected by low stock listed.',
      },
      {
        id: 'day08-hw-3',
        title: 'Task 3: The single most recently added customer',
        description: 'The single most recently added customer.',
        instructions: [
          'Select from `customers` ordered by `signup_date DESC LIMIT 1`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'customers',
        initialSql: '-- Task 3: The single most recently added customer\n',
        solutionSql: 'SELECT * FROM customers ORDER BY signup_date DESC LIMIT 1;',
        solutionExplanation: '`ORDER BY signup_date DESC LIMIT 1` finds the newest customer signup.',
        hints: [{ level: 1, text: 'Use `ORDER BY signup_date DESC LIMIT 1;`' }],
        validation: {
          targetTable: 'customers',
          requireOrderBy: [{ column: 'signup_date', direction: 'DESC' }],
          requireLimit: 1,
          expectedRowCount: 1,
        },
        successMessage: 'Task 3 completed! Most recent customer found.',
      },
      {
        id: 'day08-hw-4',
        title: 'Task 4: The 5 cheapest products',
        description: 'The 5 cheapest products.',
        instructions: [
          'Select from `products` ordered by `price ASC LIMIT 5`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'products',
        initialSql: '-- Task 4: The 5 cheapest products\n',
        solutionSql: 'SELECT * FROM products ORDER BY price ASC LIMIT 5;',
        solutionExplanation: '`ORDER BY price ASC LIMIT 5` returns the 5 lowest priced products.',
        hints: [{ level: 1, text: 'Use `ORDER BY price ASC LIMIT 5;`' }],
        validation: {
          targetTable: 'products',
          requireOrderBy: [{ column: 'price', direction: 'ASC' }],
          requireLimit: 5,
          expectedRowCount: 5,
        },
        successMessage: 'Task 4 completed! 5 cheapest products retrieved.',
      },
      {
        id: 'day08-hw-5',
        title: 'Task 5: Page 2 of customers who signed up in the last 60 days',
        description: 'Page 2 of customers who signed up in the last 60 days (10 per page, sorted by signup_date DESC).',
        instructions: [
          'Select from `customers` where `signup_date >= CURDATE() - INTERVAL 60 DAY` (or `signup_date >= \'2026-06-25\'`) ordered by `signup_date DESC LIMIT 10 OFFSET 10`.',
          'End with a semicolon (;).',
        ],
        type: 'challenge',
        primaryTable: 'customers',
        initialSql: '-- Task 5: Page 2 of customers who signed up in the last 60 days\n',
        solutionSql: 'SELECT * FROM customers WHERE signup_date >= CURDATE() - INTERVAL 60 DAY ORDER BY signup_date DESC LIMIT 10 OFFSET 10;',
        solutionExplanation: 'Filters for signups in the last 60 days, orders descending, and retrieves page 2 (OFFSET 10).',
        hints: [{ level: 1, text: 'Use `WHERE signup_date >= CURDATE() - INTERVAL 60 DAY ORDER BY signup_date DESC LIMIT 10 OFFSET 10;`' }],
        validation: {
          targetTable: 'customers',
          requireWhere: true,
          requireOrderBy: [{ column: 'signup_date', direction: 'DESC' }],
          requireLimit: 10,
          requireOffset: 10,
          expectedRowCount: 5,
        },
        successMessage: 'Task 5 completed! Page 2 of recent customer signups retrieved.',
      },
    ],
  },
};
