import { TableRow } from '../../types/database';

export const INITIAL_TABLES: Record<string, TableRow[]> = {
  categories: [
    { category_id: 1, name: 'Electronics' },
    { category_id: 2, name: 'Accessories' },
    { category_id: 3, name: 'Office Furniture' },
    { category_id: 4, name: 'Storage & Media' },
    { category_id: 5, name: 'Audio & Video' },
  ],

  suppliers: [
    { supplier_id: 1, name: 'LogiTech Direct', contact_email: 'supply@logitech-direct.com' },
    { supplier_id: 2, name: 'KeyChron Components', contact_email: 'orders@keychron-comp.com' },
    { supplier_id: 3, name: 'Apex Cables & Hubs', contact_email: 'sales@apexcables.io' },
    { supplier_id: 4, name: 'ErgoComfort Workspace', contact_email: 'wholesale@ergocomfort.com' },
    { supplier_id: 5, name: 'SoundWave Acoustic', contact_email: 'b2b@soundwave.net' },
    { supplier_id: 6, name: 'UltraView Displays', contact_email: 'corporate@ultraview.com' },
    { supplier_id: 7, name: 'Nordic Steel Works', contact_email: 'info@nordicsteel.se' },
    { supplier_id: 8, name: 'Silicon Memory Corp', contact_email: 'contact@siliconmem.com' },
    { supplier_id: 9, name: 'GreenPack Logistics', contact_email: null },
    { supplier_id: 10, name: 'Apex Precision Metals', contact_email: 'support@apexprecision.org' },
  ],

  products: [
    { product_id: 1, name: 'Wireless Mouse', category_id: 2, supplier_id: 1, price: 25.00, quantity_in_stock: 42, reorder_level: 10 },
    { product_id: 2, name: 'Mechanical Keyboard', category_id: 1, supplier_id: 2, price: 89.99, quantity_in_stock: 15, reorder_level: 5 },
    { product_id: 3, name: 'USB-C Cable (2m)', category_id: 2, supplier_id: 3, price: 12.50, quantity_in_stock: 120, reorder_level: 20 },
    { product_id: 4, name: 'Ergonomic Desk Chair', category_id: 3, supplier_id: 4, price: 249.00, quantity_in_stock: 8, reorder_level: 5 },
    { product_id: 5, name: 'Noise-Cancelling Headphones', category_id: 5, supplier_id: 5, price: 179.50, quantity_in_stock: 22, reorder_level: 8 },
    { product_id: 6, name: '4K UltraHD Monitor (27-inch)', category_id: 1, supplier_id: 6, price: 349.99, quantity_in_stock: 6, reorder_level: 4 },
    { product_id: 7, name: 'Adjustable Standing Desk', category_id: 3, supplier_id: 4, price: 420.00, quantity_in_stock: 3, reorder_level: 5 },
    { product_id: 8, name: 'External SSD 1TB', category_id: 4, supplier_id: 8, price: 95.00, quantity_in_stock: 34, reorder_level: 10 },
    { product_id: 9, name: 'Wireless Charging Pad', category_id: 2, supplier_id: 1, price: 19.99, quantity_in_stock: 0, reorder_level: 15 },
    { product_id: 10, name: 'Steel Monitor Arm Dual', category_id: 3, supplier_id: 7, price: 65.00, quantity_in_stock: 14, reorder_level: 6 },
    { product_id: 11, name: 'Desk LED Lamp', category_id: 3, supplier_id: 4, price: 35.00, quantity_in_stock: 28, reorder_level: 10 },
    { product_id: 12, name: 'Bluetooth Conference Speaker', category_id: 5, supplier_id: 5, price: 110.00, quantity_in_stock: 9, reorder_level: 5 },
    { product_id: 13, name: 'Thunderbolt 4 Docking Station', category_id: 2, supplier_id: 3, price: 185.00, quantity_in_stock: 11, reorder_level: 5 },
    { product_id: 14, name: 'Gaming Mousepad XL', category_id: 2, supplier_id: 1, price: 18.00, quantity_in_stock: 55, reorder_level: 15 },
    { product_id: 15, name: 'Steel Cable Management Tray', category_id: 3, supplier_id: 7, price: 22.00, quantity_in_stock: 2, reorder_level: 8 },
    { product_id: 16, name: 'Webcam 1080p Pro', category_id: 1, supplier_id: 6, price: 58.00, quantity_in_stock: 19, reorder_level: 10 },
    { product_id: 17, name: 'Studio Condenser Microphone', category_id: 5, supplier_id: 5, price: 129.00, quantity_in_stock: 7, reorder_level: 5 },
    { product_id: 18, name: 'USB Flash Drive 128GB', category_id: 4, supplier_id: 8, price: 14.99, quantity_in_stock: 85, reorder_level: 25 },
    { product_id: 19, name: 'Ergonomic Vertical Mouse', category_id: 2, supplier_id: 1, price: 32.50, quantity_in_stock: 16, reorder_level: 8 },
    { product_id: 20, name: 'Steel Frame Footrest', category_id: 3, supplier_id: 7, price: 45.00, quantity_in_stock: 0, reorder_level: 5 },
  ],

  customers: [
    { customer_id: 1, name: 'Rahim Chowdhury', email: 'rahim@email.com', city: 'Dhaka', signup_date: '2026-08-10' },
    { customer_id: 2, name: 'Karim Ahmed', email: 'karim@email.com', city: 'Chittagong', signup_date: '2026-08-15' },
    { customer_id: 3, name: 'Ayesha Siddika', email: 'ayesha.s@workmail.com', city: 'Dhaka', signup_date: '2026-07-28' },
    { customer_id: 4, name: 'Tanvir Hossain', email: 'tanvir@fastmail.com', city: 'Sylhet', signup_date: '2026-08-18' },
    { customer_id: 5, name: 'Fatima Noor', email: null, city: 'Dhaka', signup_date: '2026-08-01' },
    { customer_id: 6, name: 'David Miller', email: 'david.m@globalcorp.com', city: 'Boston', signup_date: '2026-06-12' },
    { customer_id: 7, name: 'Elena Rostova', email: 'elena@techflow.io', city: 'London', signup_date: '2026-07-04' },
    { customer_id: 8, name: 'Marcus Vance', email: 'marcus.v@fintech.co', city: 'London', signup_date: '2026-08-14' },
    { customer_id: 9, name: 'Sara Khan', email: 'sara.k@gmail.com', city: 'Chittagong', signup_date: '2026-08-20' },
    { customer_id: 10, name: 'Nafis Iqbal', email: null, city: 'Dhaka', signup_date: '2026-07-19' },
    { customer_id: 11, name: 'Sophia Chen', email: 'sophia.c@designlab.org', city: 'Boston', signup_date: '2026-08-05' },
    { customer_id: 12, name: 'Liam O’Connor', email: 'liam@dublindev.ie', city: 'Dublin', signup_date: '2026-07-10' },
    { customer_id: 13, name: 'Anika Rahman', email: 'anika.r@banglamail.com', city: 'Sylhet', signup_date: '2026-08-12' },
    { customer_id: 14, name: 'Zubair Al-Mamun', email: 'zubair@cloudhost.net', city: 'Dhaka', signup_date: '2026-08-19' },
    { customer_id: 15, name: 'Lucas Rossi', email: 'lucas.rossi@milanodesign.it', city: 'Milan', signup_date: '2026-05-30' },
  ],

  orders: [
    { order_id: 101, customer_id: 1, order_date: '2026-08-11', status: 'delivered' },
    { order_id: 102, customer_id: 2, order_date: '2026-08-16', status: 'shipped' },
    { order_id: 103, customer_id: 3, order_date: '2026-08-12', status: 'delivered' },
    { order_id: 104, customer_id: 1, order_date: '2026-08-17', status: 'pending' },
    { order_id: 105, customer_id: 6, order_date: '2026-08-14', status: 'delivered' },
    { order_id: 106, customer_id: 7, order_date: '2026-08-15', status: 'cancelled' },
    { order_id: 107, customer_id: 8, order_date: '2026-08-18', status: 'pending' },
    { order_id: 108, customer_id: 4, order_date: '2026-08-19', status: 'pending' },
    { order_id: 109, customer_id: 11, order_date: '2026-08-13', status: 'delivered' },
    { order_id: 110, customer_id: 13, order_date: '2026-08-20', status: 'pending' },
    { order_id: 111, customer_id: 14, order_date: '2026-08-21', status: 'pending' },
    { order_id: 112, customer_id: 3, order_date: '2026-08-21', status: 'pending' },
  ],

  order_items: [
    { order_item_id: 1, order_id: 101, product_id: 1, quantity: 2, unit_price: 25.00 },
    { order_item_id: 2, order_id: 101, product_id: 3, quantity: 1, unit_price: 12.50 },
    { order_item_id: 3, order_id: 102, product_id: 2, quantity: 1, unit_price: 89.99 },
    { order_item_id: 4, order_id: 103, product_id: 6, quantity: 1, unit_price: 349.99 },
    { order_item_id: 5, order_id: 103, product_id: 10, quantity: 1, unit_price: 65.00 },
    { order_item_id: 6, order_id: 104, product_id: 8, quantity: 2, unit_price: 95.00 },
    { order_item_id: 7, order_id: 105, product_id: 4, quantity: 1, unit_price: 249.00 },
    { order_item_id: 8, order_id: 105, product_id: 11, quantity: 2, unit_price: 35.00 },
    { order_item_id: 9, order_id: 106, product_id: 5, quantity: 1, unit_price: 179.50 },
    { order_item_id: 10, order_id: 107, product_id: 7, quantity: 1, unit_price: 420.00 },
    { order_item_id: 11, order_id: 108, product_id: 14, quantity: 3, unit_price: 18.00 },
    { order_item_id: 12, order_id: 109, product_id: 17, quantity: 1, unit_price: 129.00 },
    { order_item_id: 13, order_id: 110, product_id: 19, quantity: 1, unit_price: 32.50 },
    { order_item_id: 14, order_id: 111, product_id: 1, quantity: 1, unit_price: 25.00 },
    { order_item_id: 15, order_id: 112, product_id: 3, quantity: 4, unit_price: 12.50 },
  ],

  students: [
    { id: 1, name: 'Rahim', age: 21, department: 'CSE', city: 'Dhaka' },
    { id: 2, name: 'Karim', age: 22, department: 'EEE', city: 'Gazipur' },
    { id: 3, name: 'Ayesha', age: 20, department: 'CSE', city: 'Dhaka' },
    { id: 4, name: 'Sumaiya', age: 23, department: 'BBA', city: 'Chattogram' },
    { id: 5, name: 'Tanvir', age: 21, department: 'CSE', city: 'Rajshahi' },
  ],

  student_records: [
    { std_id: 1, std_nm: 'Rahim', std_age: 21, dept: 'CSE' },
    { std_id: 2, std_nm: 'Karim', std_age: 22, dept: 'EEE' },
    { std_id: 3, std_nm: 'Ayesha', std_age: 20, dept: 'CSE' },
    { std_id: 4, std_nm: 'Sumaiya', std_age: 23, dept: 'BBA' },
    { std_id: 5, std_nm: 'Tanvir', std_age: 21, dept: 'CSE' },
  ],
};
