import { MilestoneData } from '../types/curriculum';

export const ROADMAP_MILESTONES: MilestoneData[] = [
  {
    id: 'milestone-1',
    number: 1,
    title: 'Milestone 1',
    subtitle: 'Core Retrieval, Filtering & Shaping',
    description: 'Master single-table operations: SELECT syntax, precise column selection, conditional filtering, ranges, pattern matching, sorting, and pagination.',
    daysRange: 'Days 1–8',
    moduleIds: [
      'day-01',
      'day-02',
      'day-03',
      'day-04',
      'day-05',
      'day-06',
      'day-07',
      'day-08',
    ],
  },
  {
    id: 'milestone-2',
    number: 2,
    title: 'Milestone 2',
    subtitle: 'Aggregation & Relationships',
    description: 'Combine tables and summarize insights: aggregate metrics, group-by slicing, multi-table JOINs, relational modeling, and fan-out prevention.',
    daysRange: 'Days 9–20',
    moduleIds: [
      'day-09',
      'case-conditional-logic',
      'string-functions',
      'date-functions',
      'day-10',
      'day-11',
      'day-12',
      'day-13',
      'set-operations',
      'day-14',
      'day-15',
      'day-16',
    ],
  },
  {
    id: 'milestone-3',
    number: 3,
    title: 'Milestone 3',
    subtitle: 'Modification, Advanced Queries & Transactions',
    description: 'Safely modify data, craft subqueries and CTEs, protect multi-step operations with transactions, and build complete production-grade backend queries.',
    daysRange: 'Days 21–38',
    moduleIds: [
      'day-17',
      'day-18',
      'window-ranking',
      'window-running-metrics',
      'day-19',
      'dml-transactions',
      'day-20',
      'ddl-column-constraints',
      'ddl-schema-evolution',
      'schema-design-normalization',
      'day-21',
      'security-production-safety',
      'capstone-bookstore',
      'day-22',
      'day-23',
      'day-24',
      'interview-gauntlet',
      'day-25',
    ],
  },
];
