import { MilestoneData } from '../types/curriculum';

export const ROADMAP_MILESTONES: MilestoneData[] = [
  {
    id: 'milestone-1',
    number: 1,
    title: 'Foundations',
    subtitle: 'Ask the Right Questions — Single-Table Mastery',
    description: 'Learn to ask the database precisely what you need: retrieve specific columns, filter rows by condition, shape results the way you want them, and retrieve data in the order that matters. By Day 8, you\'ll write confident single-table queries without second-guessing.',
    daysRange: 'Days 1–8',
    moduleIds: [
      'day-01',
      'day-02',
      'day-03',
      'day-04',
      'day-05',
      'day-06',
      'day-07',
      'day-08',
    ],
  },
  {
    id: 'milestone-2',
    number: 2,
    title: 'Analysis',
    subtitle: 'See the Big Picture — Multi-Table Insights & Reporting',
    description: 'Connect the dots across tables, summarize data into actionable metrics, and build the queries that power dashboards and reports. You\'ll combine tables with JOINs, count and sum across groups, and answer real business questions that require data from multiple sources. Welcome to the role of analyst.',
    daysRange: 'Days 9–20',
    moduleIds: [
      'day-09',
      'day-10',
      'day-11',
      'day-12',
      'day-13',
      'day-14',
      'day-15',
      'day-16',
      'day-17',
      'day-18',
      'day-19',
      'day-20',
    ],
  },
  {
    id: 'milestone-3',
    number: 3,
    title: 'Mastery',
    subtitle: 'Build & Defend — Data Modification, Schema Design & Production Safety',
    description: 'Move beyond querying to building: design your own tables, modify data safely using transactions, craft sophisticated multi-step queries with subqueries and CTEs, and secure your database against common pitfalls. You\'ll complete a capstone project and defend your SQL knowledge against real-world interview questions. By Day 38, you\'re production-ready.',
    daysRange: 'Days 21–38',
    moduleIds: [
      'day-21',
      'day-22',
      'day-23',
      'day-24',
      'day-25',
      'day-26',
      'day-27',
      'day-28',
      'day-29',
      'day-30',
      'day-31',
      'day-32',
      'day-33',
      'day-34',
      'day-35',
      'day-36',
      'day-37',
      'day-38',
    ],
  },
  {
    id: 'milestone-4',
    number: 4,
    title: 'Engineering',
    subtitle: 'Encapsulate, Automate & Scale — Advanced Database Engineering',
    description: 'Graduate from query writing to database engineering. Encapsulate logic in views, recursive CTEs, stored functions, procedures, and triggers. Guarantee data integrity through transaction isolation levels and locking. Diagnose slow queries with EXPLAIN, accelerate them with composite and covering indexes, and handle JSON semi-structured data. Operate safely with user roles, least-privilege access, and schema migrations. By Day 57, you can design, build, and run a production database system.',
    daysRange: 'Days 39–57',
    moduleIds: [
      'day-39',
      'day-40',
      'day-41',
      'day-42',
      'day-43',
      'day-44',
      'day-45',
      'day-46',
      'day-47',
      'day-48',
      'day-49',
      'day-50',
      'day-51',
      'day-52',
      'day-53',
      'day-54',
      'day-55',
      'day-56',
      'day-57',
    ],
  },
];
