import type { ModuleData } from '../../../types/curriculum';
import { prismaReadTask, prismaSnippetTask, prismaTheory } from '../phase6-tasks';

/** Prisma Day 5 — Migrations + Seeding. */
export const Prisma_05_MODULE: ModuleData = {
  id: 'prisma-05',
  slug: 'migrations-and-seeding',
  day: 5,
  title: 'Day 5 — Migrations + Seeding',
  shortTitle: 'Migrations & Seeding',
  type: 'module',
  track: 'prisma',
  milestoneId: 'prisma-milestone-2',
  description: 'Turn schema.prisma into versioned SQL migrations and seed data deterministically.',
  estimatedMinutes: 50,
  curriculumOrder: 5,
  displayLabel: 'Day 5',
  completionLearnings: [
    'Run `migrate dev` to author a migration from the schema',
    'Promote migrations with `migrate deploy` instead of re-authoring them',
    'Register and execute seed scripts with `db seed`',
    'Reset and re-seed a development database with `migrate reset`',
  ],
  concepts: [
    {
      id: 'migrate-workflow',
      order: 1,
      title: 'The Prisma Migrate Workflow',
      shortDescription: '`migrate dev` writes versioned SQL; `migrate deploy` applies it.',
      theory: prismaTheory(
        'Prisma Migrate compares schema.prisma with the migration history, writes the missing SQL into a timestamped folder, and records it in `_prisma_migrations`. Production never authors migrations — it only applies the ones already committed.',
        'Dev authors migrations; production only deploys them.',
        'SELECT id, name\nFROM users\nWHERE id = 1;',
        'npx prisma migrate dev --name add_user_model',
        'bash',
        'One command diffs the schema, writes SQL, applies it and regenerates the client.',
      ),
      tasks: [
        prismaSnippetTask({
          id: 'prisma05-c1-t1',
          title: 'Author the first migration',
          description: 'Create a named migration from the current schema.',
          instructions: ['Use `prisma migrate dev`', 'Give it a `--name`'],
          hint: '`npx prisma migrate dev --name init_users`.',
          scaffold: '-- The table the migration creates:\nSELECT id, name FROM users WHERE id = 99;',
          solutionSql: 'SELECT id, name FROM users WHERE id = 1;',
          why: 'A named migration is a reviewable SQL file plus a row in the migration table.',
          cols: ['id', 'name'],
          rows: 1,
          code0: 'const cmd = "npx prisma db push";',
          code1: 'const cmd = "npx prisma migrate dev --name init_users";',
          need: ['npx prisma migrate dev', '--name'],
          ban: ['db push'],
        }),
        prismaSnippetTask({
          id: 'prisma05-c1-t2',
          title: 'Promote to production',
          description: 'Apply the committed migrations without authoring new ones.',
          instructions: ['Use `migrate deploy`', 'Never author migrations in production'],
          hint: '`npx prisma migrate deploy` applies what is already committed.',
          scaffold: '-- The migration already created this row:\nSELECT id, name FROM users WHERE id = 99;',
          solutionSql: "SELECT id, name FROM users WHERE email = 'mina@prisma.io';",
          why: 'Deploy is idempotent: applied migrations are skipped.',
          cols: ['id', 'name'],
          rows: 1,
          code0: 'const cmd = "npx prisma migrate dev --name prod_sync";',
          code1: 'const cmd = "npx prisma migrate deploy";',
          need: ['npx prisma migrate deploy'],
          ban: ['migrate dev'],
        }),
      ],
    },
    {
      id: 'idempotent-seed',
      order: 2,
      title: 'Seeding Workflows',
      shortDescription: 'Register and execute seed scripts using the Prisma CLI.',
      theory: prismaTheory(
        'A seed script populates baseline data in fresh environments. Once configured in package.json under `prisma.seed`, you can execute it whenever needed using `npx prisma db seed`.',
        'Register your seed script in package.json, then run `npx prisma db seed`.',
        "SELECT id, email\nFROM users\nWHERE email = 'alex@prisma.io';",
        '# Execute the configured seed script:\nnpx prisma db seed',
        'bash',
        'db seed reads package.json and executes your seeder command.',
      ),
      tasks: [
        prismaSnippetTask({
          id: 'prisma05-c2-t1',
          title: 'Run the seed script',
          description: 'Execute the project seed script using the Prisma CLI.',
          instructions: ['Run `npx prisma db seed` to trigger the configured seeder'],
          hint: '`npx prisma db seed` reads the seed command from package.json and executes it.',
          scaffold: '-- The rows a successful seed command leaves behind:\nSELECT id, email FROM users WHERE id = 99;',
          solutionSql: "SELECT id, email FROM users WHERE email = 'alex@prisma.io';",
          why: 'npx prisma db seed executes the registered seed script to populate data.',
          cols: ['id', 'email'],
          rows: 1,
          code0: 'const cmd = "node prisma/seed.js";',
          code1: 'const cmd = "npx prisma db seed";',
          need: ['npx prisma db seed'],
          ban: ['node '],
        }),
        prismaSnippetTask({
          id: 'prisma05-c2-t2',
          title: 'Register the seed script',
          description: 'Tell the Prisma CLI which command seeds a fresh database.',
          instructions: ['Add a `prisma` block to package.json', 'Point `seed` at prisma/seed.ts'],
          hint: '`"seed": "tsx prisma/seed.ts"` inside `"prisma": { ... }`.',
          scaffold: '-- Seeded rows are readable straight away:\nSELECT id, email FROM users WHERE id = 99;',
          solutionSql: "SELECT id, email FROM users WHERE email = 'alex@prisma.io';",
          why: '`prisma migrate reset` and `db seed` both call the registered script.',
          cols: ['id', 'email'],
          rows: 1,
          code0: '{\n  "name": "api",\n  "scripts": {\n    "seed": "node seed.js"\n  }\n}',
          code1:
            '{\n  "name": "api",\n  "prisma": {\n    "seed": "tsx prisma/seed.ts"\n  }\n}',
          need: ['"prisma": {', '"seed": "tsx prisma/seed.ts"'],
          ban: ['"seed": "node seed.js"'],
        }),
      ],
    },
  ],
  challenge: {
    id: 'prisma05-challenge',
    title: 'Final Challenge — Deterministic Dev Reset',
    scenario: 'A development database must be completely reset and re-seeded in one command.',
    databaseLifecycle: 'fresh',
    tasks: [
      {
        ...prismaSnippetTask({
          id: 'prisma05-hw-1',
          title: 'Deterministic Database Reset & Seed',
          description: 'Reset a development database, re-apply all migrations, and run seeding in one step.',
          instructions: ['Use `npx prisma migrate reset`', 'Add `--force` to skip interactive confirmation'],
          hint: '`npx prisma migrate reset --force` drops the schema, applies migrations, and executes the seed script.',
          scaffold: '-- The reset database with freshly seeded rows:\nSELECT id, email FROM users WHERE id = 99;',
          solutionSql: 'SELECT id, email FROM users WHERE id IN (1, 2, 3);',
          why: 'migrate reset drops the database, runs all migrations, and invokes db seed automatically.',
          cols: ['id', 'email'],
          rows: 3,
          code0: 'const resetCmd = "npx prisma db push --force-reset";',
          code1: 'const resetCmd = "npx prisma migrate reset --force";',
          need: ['npx prisma migrate reset', '--force'],
          ban: ['db push'],
        }),
        type: 'challenge',
      },
    ],
  },
};
