import type { ModuleData } from '../../../types/curriculum';
import { prismaReadTask, prismaSnippetTask, prismaTheory } from '../phase6-tasks';

/** Prisma Day 2 — Setup & Connection. CLI lifecycle + pooled datasource. */
export const Prisma_02_MODULE: ModuleData = {
  id: 'prisma-02',
  slug: 'setup-and-connection',
  day: 2,
  title: 'Day 2 — Setup & Connection',
  shortTitle: 'Setup & Connection',
  type: 'module',
  track: 'prisma',
  milestoneId: 'prisma-milestone-1',
  description: 'Run the CLI lifecycle and connect PostgreSQL with pooling.',
  estimatedMinutes: 45,
  curriculumOrder: 2,
  displayLabel: 'Day 2',
  completionLearnings: [
    'Run init, generate, migrate dev in order',
    'Regenerate the client after schema edits',
    'Build a pooled PostgreSQL connection string',
    'Prove the connection with a seeded read',
  ],
  concepts: [
    {
      id: 'cli-lifecycle',
      order: 1,
      title: 'The Prisma CLI Lifecycle',
      shortDescription: 'init scaffolds, generate compiles, migrate moves the schema.',
      theory: prismaTheory(
        'init scaffolds, generate compiles the client, migrate dev applies versioned SQL.',
        'Generate after every schema change, then prove it with a read.',
        'SELECT id, name, email\nFROM users\nWHERE id = 1;',
        'export function getGenerateCommand(): string {\n  return "npx prisma generate";\n}',
        'typescript',
        'The command that recompiles the client.',
      ),
      tasks: [
        prismaSnippetTask({
          id: 'prisma02-c1-t1',
          title: 'Regenerate the client',
          description: 'Return the CLI command that recompiles the client.',
          instructions: ['Starts with `npx prisma`', 'Ends with `generate`'],
          hint: 'Starts with `npx prisma ...`, ends with `generate`.',
          scaffold: '-- Prove the chain:\nSELECT id, name, email FROM users WHERE id = 99;',
          solutionSql: 'SELECT id, name, email FROM users WHERE id = 1;',
          why: 'One seeded row proves the chain works.',
          cols: ['id', 'name', 'email'],
          rows: 1,
          code0: 'export function getGenerateCommand(): string {\n  return "";\n}',
          code1: 'export function getGenerateCommand(): string {\n  return "npx prisma generate";\n}',
          need: ['npx prisma generate'],
        }),
        prismaSnippetTask({
          id: 'prisma02-c1-t2',
          title: 'Build a pooled connection string',
          description: 'Append PgBouncer pooling parameters to a PostgreSQL URL.',
          instructions: ['Keep the base URL', 'Add pgbouncer + connection_limit'],
          hint: 'URL search params: pgbouncer=true, connection_limit=10.',
          scaffold: '-- Same proof:\nSELECT id, name, email FROM users WHERE id = 99;',
          solutionSql: 'SELECT id, name, email FROM users WHERE id = 2;',
          why: 'A second seeded row confirms the pooled URL connects.',
          cols: ['id', 'name', 'email'],
          rows: 1,
          code0: 'export function formatPooledDbUrl(u: string): string {\n  return u;\n}',
          code1: "export function fmt(u: string): string {\n  const url = new URL(u);\n  url.searchParams.set('pgbouncer', 'true');\n  url.searchParams.set('connection_limit', '10');\n  return url.toString();\n}",
          need: ['pgbouncer', 'connection_limit'],
        }),
      ],
    },
    {
      id: 'datasource-mapping',
      order: 2,
      title: 'Datasource & Schema Mapping',
      shortDescription: 'Env-sourced URL plus @map for legacy tables.',
      theory: prismaTheory(
        'Datasource reads the URL from env; @map keeps snake_case tables queryable.',
        'Datasource via env; legacy names via @map.',
        "SELECT id, email\nFROM users\nWHERE email = 'mina@prisma.io';",
        'datasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}',
        'prisma',
        'Provider plus env-sourced URL.',
      ),
      tasks: [
        prismaSnippetTask({
          id: 'prisma02-c2-t1',
          title: 'Wire the datasource',
          description: 'Point schema.prisma at PostgreSQL via the environment.',
          instructions: ['provider is postgresql', 'url reads DATABASE_URL'],
          hint: 'url = env("DATABASE_URL").',
          scaffold: '-- Same proof:\nSELECT id, email FROM users WHERE id = 99;',
          solutionSql: "SELECT id, email FROM users WHERE email = 'mina@prisma.io';",
          why: 'Env-wired datasource still reads the seed.',
          cols: ['id', 'email'],
          rows: 1,
          code0: 'datasource db {\n  provider = "sqlite"\n  url      = "file:./dev.db"\n}',
          code1: 'datasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}',
          need: ['postgresql', 'DATABASE_URL'],
          ban: ['sqlite'],
        }),
        prismaSnippetTask({
          id: 'prisma02-c2-t2',
          title: 'Map a legacy table',
          description: 'Keep model Customer while the table stays tbl_customers.',
          instructions: ['Map email to cust_email', 'Map model to tbl_customers'],
          hint: '@map on the field, @@map on the model.',
          scaffold: '-- Same proof:\nSELECT id FROM users WHERE id = 99;',
          solutionSql: 'SELECT id, name, email FROM users WHERE id = 3;',
          why: 'Mapping is cosmetic; the seed still reads.',
          cols: ['id', 'name', 'email'],
          rows: 1,
          code0: 'model Customer {\n  id    Int    @id @default(autoincrement())\n  email String\n}',
          code1: 'model Customer {\n  id    Int    @id @default(autoincrement())\n  email String @map("cust_email")\n\n  @@map("tbl_customers")\n}',
          need: ['@map("cust_email")', '@@map("tbl_customers")'],
        }),
      ],
    },
  ],
  challenge: {
    id: 'prisma02-challenge',
    title: 'Final Challenge — Connect and Prove It',
    scenario: 'Wire the client and prove the database answers.',
    databaseLifecycle: 'fresh',
    tasks: [
      {
        ...prismaReadTask({
          id: 'prisma02-hw-1',
          title: 'Key lookup over the wire',
          description: 'Return id + email for alex@prisma.io.',
          instructions: ['findUnique on where: { email }', 'select id + email only'],
          hint: 'where on email, select id + email.',
          scaffold: "-- Expected shape:\nSELECT id, email FROM users WHERE email = 'nobody@prisma.io';",
          solutionSql: "SELECT id, email FROM users WHERE email = 'alex@prisma.io';",
          why: 'One row, two columns — connected.',
          cols: ['id', 'email'],
          noCols: ['name'],
          rows: 1,
          code0: 'export async function lookupMember(email: string) {\n  return await prisma.user.findUnique({\n    // TODO: where + select\n  });\n}',
          code1: 'export async function lookupMember(email: string) {\n  return await prisma.user.findUnique({\n    where: { email },\n    select: { id: true, email: true },\n  });\n}',
          rtype: '{ id: number; email: string } | null',
        }),
        type: 'challenge',
      },
    ],
  },
};
