import type { ModuleData } from '../../../types/curriculum';
import { prismaReadTask, prismaSnippetTask, prismaTheory } from '../phase6-tasks';

/** Prisma Day 6 — PrismaClient Lifecycle & Connections. */
export const Prisma_06_MODULE: ModuleData = {
  id: 'prisma-06',
  slug: 'client-lifecycle-connections',
  day: 6,
  title: 'Day 6 — PrismaClient Lifecycle & Connections',
  shortTitle: 'Client Lifecycle',
  type: 'module',
  track: 'prisma',
  milestoneId: 'prisma-milestone-2',
  description: 'Keep one PrismaClient per process, log the queries you cannot see, and shut down cleanly.',
  estimatedMinutes: 45,
  curriculumOrder: 6,
  displayLabel: 'Day 6',
  completionLearnings: [
    'Explain why hot reload must not create a client per reload',
    'Cache the client on globalThis in development',
    'Turn on query logging to see real SQL',
    'Disconnect before the process exits',
  ],
  concepts: [
    {
      id: 'singleton-pattern',
      order: 1,
      title: 'The Global PrismaClient Singleton',
      shortDescription: 'One client per process — cached across hot reloads.',
      theory: prismaTheory(
        'Every PrismaClient owns a connection pool. A dev server that reloads on save would build a new pool per reload until the database refuses connections, so the client is cached on `globalThis` outside production.',
        'One client per process: `globalThis.prisma ?? new PrismaClient()`.',
        'SELECT id, name\nFROM users\nWHERE id = 1;',
        'const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };\n\nexport const prisma = globalForPrisma.prisma ?? new PrismaClient();\n\nif (process.env.NODE_ENV !== \'production\') globalForPrisma.prisma = prisma;',
        'typescript',
        'The cache survives a hot reload because `globalThis` is not module-scoped.',
      ),
      tasks: [
        prismaSnippetTask({
          id: 'prisma06-c1-t1',
          title: 'Stop creating a client per reload',
          description: 'The current module builds a brand-new client on every reload.',
          instructions: ['Read the cached client from `globalThis`', 'Fall back to `new PrismaClient()`'],
          hint: '`globalForPrisma.prisma ?? new PrismaClient()`.',
          scaffold: '-- Pooled reads still hit the same rows:\nSELECT id, name FROM users WHERE id = 99;',
          solutionSql: 'SELECT id, name FROM users WHERE id = 1;',
          why: 'A cached client reuses one connection pool instead of leaking many.',
          cols: ['id', 'name'],
          rows: 1,
          code0: 'export const prisma = new PrismaClient();',
          code1:
            'const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };\n\nexport const prisma = globalForPrisma.prisma ?? new PrismaClient();',
          need: ['globalThis', '?? new PrismaClient()'],
        }),
        prismaSnippetTask({
          id: 'prisma06-c1-t2',
          title: 'Cache it in development only',
          description: 'Production must keep a single module-scoped instance.',
          instructions: ['Write the client back to `globalThis`', 'Guard with `NODE_ENV`'],
          hint: '`if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;`',
          scaffold: '-- Production reads behave identically:\nSELECT id, name FROM users WHERE id = 99;',
          solutionSql: "SELECT id, name FROM users WHERE email = 'mina@prisma.io';",
          why: 'The cache exists to serve hot reload, not to change production behaviour.',
          cols: ['id', 'name'],
          rows: 1,
          code0:
            'const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };\n\nexport const prisma = globalForPrisma.prisma ?? new PrismaClient();\n\nglobalForPrisma.prisma = prisma;',
          code1:
            'const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };\n\nexport const prisma = globalForPrisma.prisma ?? new PrismaClient();\n\nif (process.env.NODE_ENV !== \'production\') globalForPrisma.prisma = prisma;',
          need: ["NODE_ENV !== 'production'", 'globalForPrisma.prisma = prisma'],
        }),
      ],
    },
    {
      id: 'query-logging-disconnect',
      order: 2,
      title: 'Query Logging & Graceful Shutdown',
      shortDescription: '`log: [...]` shows the generated SQL; `$disconnect` releases the pool.',
      theory: prismaTheory(
        'The SQL Lens is authored — the log config is how you see it live. `log: [\'query\']` prints every statement Prisma sends, and `$disconnect()` closes the pool so a script can exit.',
        'Turn on query logging to see real SQL; disconnect before exit.',
        "SELECT id, email\nFROM users\nWHERE email = 'rafi@prisma.io';",
        "const prisma = new PrismaClient({ log: ['query', 'warn', 'error'] });\n\nprocess.on('beforeExit', async () => {\n  await prisma.$disconnect();\n});",
        'typescript',
        'The log array is your only window into the SQL Prisma actually sends.',
      ),
      tasks: [
        prismaSnippetTask({
          id: 'prisma06-c2-t1',
          title: 'Log every query',
          description: 'Print the SQL Prisma sends and keep warnings visible.',
          instructions: ["Add `log: ['query', 'warn', 'error']`"],
          hint: "`new PrismaClient({ log: ['query', 'warn', 'error'] })`.",
          scaffold: '-- The statement the log will print:\nSELECT id, email FROM users WHERE id = 99;',
          solutionSql: 'SELECT id, email FROM users WHERE id = 2;',
          why: 'The query log is the ground truth behind the authored SQL lens.',
          cols: ['id', 'email'],
          rows: 1,
          code0: 'export const prisma = new PrismaClient();',
          code1: "export const prisma = new PrismaClient({ log: ['query', 'warn', 'error'] });",
          need: ["log: ['query'", "'error'"],
        }),
        prismaSnippetTask({
          id: 'prisma06-c2-t2',
          title: 'Disconnect before exit',
          description: 'A script that never disconnects hangs with open connections.',
          instructions: ['Listen for `beforeExit`', 'Call `$disconnect()`'],
          hint: "`process.on('beforeExit', async () => { await prisma.$disconnect(); });`",
          scaffold: '-- Reads complete, then the pool is released:\nSELECT id, email FROM users WHERE id = 99;',
          solutionSql: "SELECT id, email FROM users WHERE email = 'rafi@prisma.io';",
          why: 'Disconnecting returns connections to the pool before the process dies.',
          cols: ['id', 'email'],
          rows: 1,
          code0: "process.on('beforeExit', async () => {\n  console.log('bye');\n});",
          code1: "process.on('beforeExit', async () => {\n  await prisma.$disconnect();\n});",
          need: ['prisma.$disconnect()', 'beforeExit'],
        }),
      ],
    },
  ],
  challenge: {
    id: 'prisma06-challenge',
    title: 'Final Challenge — Enterprise Database Gateway',
    scenario: 'A long-lived service that shares one client and closes it politely.',
    databaseLifecycle: 'fresh',
    tasks: [
      {
        ...prismaReadTask({
          id: 'prisma06-hw-1',
          title: 'Deterministic roster read',
          description: 'Return id + email for every user, sorted by id.',
          instructions: ['findMany with `select: { id, email }`', 'Sort with `orderBy: { id: "asc" }`'],
          hint: '`orderBy: { id: "asc" }` keeps the page stable between requests.',
          scaffold: '-- A stable roster query needs its ORDER BY:\nSELECT id, email FROM users WHERE id = 99;',
          solutionSql: 'SELECT id, email FROM users ORDER BY id ASC;',
          why: 'An explicit ORDER BY is what makes paging reproducible.',
          cols: ['id', 'email'],
          noCols: ['name'],
          orderBy: [{ field: 'id', direction: 'asc' }],
          rows: 3,
          code0:
            'export async function roster() {\n  return await prisma.user.findMany({\n    select: { id: true, email: true },\n  });\n}',
          code1:
            'export async function roster() {\n  return await prisma.user.findMany({\n    select: { id: true, email: true },\n    orderBy: { id: \'asc\' },\n  });\n}',
          rtype: '{ id: number; email: string }[]',
        }),
        type: 'challenge',
      },
    ],
  },
};
