import type { ModuleData } from '../../../types/curriculum';
import { prismaReadTask, prismaSnippetTask, prismaTheory } from '../phase6-tasks';

/** Prisma Day 5 — Migrations + Seeding. */
export const Prisma_05_MODULE: ModuleData = {
  id: 'prisma-05',
  slug: 'migrations-and-seeding',
  day: 5,
  title: 'Day 5 — Migrations + Seeding',
  shortTitle: 'Migrations & Seeding',
  type: 'module',
  track: 'prisma',
  milestoneId: 'prisma-milestone-2',
  description: 'Turn schema.prisma into versioned SQL migrations and seed data deterministically.',
  estimatedMinutes: 50,
  curriculumOrder: 5,
  displayLabel: 'Day 5',
  completionLearnings: [
    'Run `migrate dev` to author a migration from the schema',
    'Promote migrations with `migrate deploy` instead of re-authoring them',
    'Seed with `upsert` so a re-run is safe',
    'Register the seed script in package.json',
  ],
  concepts: [
    {
      id: 'migrate-workflow',
      order: 1,
      title: 'The Prisma Migrate Workflow',
      shortDescription: '`migrate dev` writes versioned SQL; `migrate deploy` applies it.',
      theory: prismaTheory(
        'Prisma Migrate compares schema.prisma with the migration history, writes the missing SQL into a timestamped folder, and records it in `_prisma_migrations`. Production never authors migrations — it only applies the ones already committed.',
        'Dev authors migrations; production only deploys them.',
        'SELECT id, name\nFROM users\nWHERE id = 1;',
        'npx prisma migrate dev --name add_user_model',
        'bash',
        'One command diffs the schema, writes SQL, applies it and regenerates the client.',
      ),
      tasks: [
        prismaSnippetTask({
          id: 'prisma05-c1-t1',
          title: 'Author the first migration',
          description: 'Create a named migration from the current schema.',
          instructions: ['Use `prisma migrate dev`', 'Give it a `--name`'],
          hint: '`npx prisma migrate dev --name init_users`.',
          scaffold: '-- The table the migration creates:\nSELECT id, name FROM users WHERE id = 99;',
          solutionSql: 'SELECT id, name FROM users WHERE id = 1;',
          why: 'A named migration is a reviewable SQL file plus a row in the migration table.',
          cols: ['id', 'name'],
          rows: 1,
          code0: 'const cmd = "npx prisma db push";',
          code1: 'const cmd = "npx prisma migrate dev --name init_users";',
          need: ['npx prisma migrate dev', '--name'],
          ban: ['db push'],
        }),
        prismaSnippetTask({
          id: 'prisma05-c1-t2',
          title: 'Promote to production',
          description: 'Apply the committed migrations without authoring new ones.',
          instructions: ['Use `migrate deploy`', 'Never author migrations in production'],
          hint: '`npx prisma migrate deploy` applies what is already committed.',
          scaffold: '-- The migration already created this row:\nSELECT id, name FROM users WHERE id = 99;',
          solutionSql: "SELECT id, name FROM users WHERE email = 'mina@prisma.io';",
          why: 'Deploy is idempotent: applied migrations are skipped.',
          cols: ['id', 'name'],
          rows: 1,
          code0: 'const cmd = "npx prisma migrate dev --name prod_sync";',
          code1: 'const cmd = "npx prisma migrate deploy";',
          need: ['npx prisma migrate deploy'],
          ban: ['migrate dev'],
        }),
      ],
    },
    {
      id: 'idempotent-seed',
      order: 2,
      title: 'Idempotent Seeding',
      shortDescription: 'A seed script that can run twice without duplicating rows.',
      theory: prismaTheory(
        'A seeder runs on every fresh environment, so it must be idempotent: `upsert` matches on a unique key and inserts only when the row is missing. Running it twice must leave the same rows behind.',
        'Seed with `upsert` keyed on a unique column — a re-run changes nothing.',
        "SELECT id, email\nFROM users\nWHERE email = 'rafi@prisma.io';",
        'for (const user of users) {\n  await prisma.user.upsert({\n    where: { email: user.email },\n    update: {},\n    create: user,\n  });\n}',
        'typescript',
        '`update: {}` means "match me, change nothing" — the second run is a no-op.',
      ),
      tasks: [
        prismaSnippetTask({
          id: 'prisma05-c2-t1',
          title: 'Make the seeder re-runnable',
          description: 'The seeder currently crashes or duplicates on the second run.',
          instructions: ['Seed with `prisma.user.upsert`', 'Pass `update: {}`'],
          hint: 'Upsert needs a unique `where` — `email` is unique.',
          scaffold: '-- The rows a re-runnable seeder leaves behind:\nSELECT id, email FROM users WHERE id = 99;',
          solutionSql: "SELECT id, email FROM users WHERE email = 'rafi@prisma.io';",
          why: 'Upsert keys on a unique column, so a second run touches nothing.',
          cols: ['id', 'email'],
          rows: 1,
          code0:
            'for (const user of users) {\n  await prisma.user.create({ data: user });\n}',
          code1:
            'for (const user of users) {\n  await prisma.user.upsert({\n    where: { email: user.email },\n    update: {},\n    create: user,\n  });\n}',
          need: ['prisma.user.upsert(', 'update: {}'],
          ban: ['prisma.user.create('],
        }),
        prismaSnippetTask({
          id: 'prisma05-c2-t2',
          title: 'Register the seed script',
          description: 'Tell the Prisma CLI which command seeds a fresh database.',
          instructions: ['Add a `prisma` block to package.json', 'Point `seed` at prisma/seed.ts'],
          hint: '`"seed": "tsx prisma/seed.ts"` inside `"prisma": { ... }`.',
          scaffold: '-- Seeded rows are readable straight away:\nSELECT id, email FROM users WHERE id = 99;',
          solutionSql: "SELECT id, email FROM users WHERE email = 'alex@prisma.io';",
          why: '`prisma migrate reset` and `db seed` both call the registered script.',
          cols: ['id', 'email'],
          rows: 1,
          code0: '{\n  "name": "api",\n  "scripts": {\n    "seed": "node seed.js"\n  }\n}',
          code1:
            '{\n  "name": "api",\n  "prisma": {\n    "seed": "tsx prisma/seed.ts"\n  }\n}',
          need: ['"prisma": {', '"seed": "tsx prisma/seed.ts"'],
          ban: ['"seed": "node seed.js"'],
        }),
      ],
    },
  ],
  challenge: {
    id: 'prisma05-challenge',
    title: 'Final Challenge — Deterministic Seeder',
    scenario: 'A fresh database must reach the exact same state on every run.',
    databaseLifecycle: 'fresh',
    tasks: [
      {
        ...prismaSnippetTask({
          id: 'prisma05-hw-1',
          title: 'Batch seed with duplicate protection',
          description: 'Insert the seed batch in one round trip and survive re-runs.',
          instructions: ['Use `createMany`', 'Add `skipDuplicates: true`'],
          hint: '`prisma.user.createMany({ data: users, skipDuplicates: true })`.',
          scaffold: '-- The batch lands three rows:\nSELECT id, email FROM users WHERE id = 99;',
          solutionSql: 'SELECT id, email FROM users WHERE id IN (1, 2, 3);',
          why: 'One batch insert plus `skipDuplicates` is idempotent and fast.',
          cols: ['id', 'email'],
          rows: 3,
          code0: 'for (const user of users) {\n  await prisma.user.create({ data: user });\n}',
          code1:
            'await prisma.user.createMany({\n  data: users,\n  skipDuplicates: true,\n});',
          need: ['prisma.user.createMany(', 'skipDuplicates: true'],
        }),
        type: 'challenge',
      },
    ],
  },
};
