import type { ModuleData } from '../../../types/curriculum';
import { prismaReadTask, prismaSnippetTask, prismaTheory } from '../phase6-tasks';

/** Prisma Day 5 — Migrations + Seeding. */
export const Prisma_05_MODULE: ModuleData = {
  id: 'prisma-05',
  slug: 'migrations-and-seeding',
  day: 5,
  title: 'Day 5 — Migrations + Seeding',
  shortTitle: 'Migrations & Seeding',
  type: 'module',
  track: 'prisma',
  milestoneId: 'prisma-milestone-2',
  description: 'Turn schema.prisma into versioned SQL migrations and seed data deterministically.',
  estimatedMinutes: 50,
  curriculumOrder: 5,
  displayLabel: 'Day 5',
  completionLearnings: [
    'Prototyping with `db push` vs versioned migrations with `migrate dev`',
    'Promote migrations with `migrate deploy` instead of re-authoring them',
    'Write idempotent seed scripts using `prisma.user.upsert`',
    'Reset and re-seed a development database with `migrate reset`',
  ],
  concepts: [
    {
      id: 'migrate-workflow',
      order: 1,
      title: 'The Prisma Migrate Workflow & Prototyping',
      shortDescription: '`db push` for rapid prototyping; `migrate dev` for versioned team migrations.',
      theory: prismaTheory(
        'Prisma offers two ways to sync schema to database: `prisma db push` syncs changes directly without writing migration files (ideal for rapid local prototyping). `prisma migrate dev` generates versioned SQL migration files stored in source control. Production environments only apply committed migrations with `prisma migrate deploy`.',
        'Use db push to prototype; migrate dev to commit migrations; migrate deploy in production.',
        'SELECT id, name\nFROM users\nWHERE id = 1;',
        '# Rapid local prototyping:\nnpx prisma db push\n\n# Versioned team migration:\nnpx prisma migrate dev --name add_user_model',
        'bash',
        'db push modifies the database directly; migrate dev creates tracked SQL migration files.',
      ),
      tasks: [
        prismaSnippetTask({
          id: 'prisma05-c1-t1',
          title: 'Rapid schema prototyping with db push',
          description: 'Synchronize your schema changes directly to the database without generating SQL migration files.',
          instructions: [
            'Return the command used for rapid local prototyping without migrations',
            'Use `npx prisma db push`',
          ],
          hint: '`npx prisma db push` syncs schema changes directly to your database without creating files.',
          scaffold: '-- Validating prototyping sync command:\nSELECT id, name FROM users WHERE id = 99;',
          solutionSql: 'SELECT id, name FROM users WHERE id = 1;',
          why: 'db push allows rapid iteration during initial development before freezing the schema into migrations.',
          cols: ['id', 'name'],
          rows: 1,
          code0: 'export function getPrototypeSyncCommand(): string {\n  return "";\n}',
          code1: 'export function getPrototypeSyncCommand(): string {\n  return "npx prisma db push";\n}',
          need: ['npx prisma db push'],
          ban: ['migrate dev'],
        }),
        prismaSnippetTask({
          id: 'prisma05-c1-t2',
          title: 'Promote migrations to production',
          description: 'Apply committed migrations to production without authoring new ones.',
          instructions: ['Use `migrate deploy`', 'Never author migrations in production'],
          hint: '`npx prisma migrate deploy` applies what is already committed.',
          scaffold: '-- The migration already created this row:\nSELECT id, name FROM users WHERE id = 99;',
          solutionSql: "SELECT id, name FROM users WHERE email = 'mina@prisma.io';",
          why: 'Deploy is idempotent: applied migrations are skipped.',
          cols: ['id', 'name'],
          rows: 1,
          code0: 'const cmd = "npx prisma migrate dev --name prod_sync";',
          code1: 'const cmd = "npx prisma migrate deploy";',
          need: ['npx prisma migrate deploy'],
          ban: ['migrate dev'],
        }),
      ],
    },
    {
      id: 'idempotent-seed',
      order: 2,
      title: 'Writing Idempotent Seed Scripts',
      shortDescription: 'Write reproducible seeds using `upsert` so re-running never throws P2002 errors.',
      theory: prismaTheory(
        'A seed script must be idempotent: executing it twice on the same database should never throw a unique constraint error (P2002). Using `prisma.user.upsert({ where, update, create })` guarantees that missing records are inserted and existing ones are left intact or updated cleanly.',
        'Use upsert for idempotent seeding: insert if missing, do nothing or update if present.',
        "SELECT id, email\nFROM users\nWHERE email = 'alex@prisma.io';",
        'await prisma.user.upsert({\n  where: { email: "alex@prisma.io" },\n  update: {},\n  create: { email: "alex@prisma.io", name: "Alex" },\n});',
        'typescript',
        'upsert ensures your seed script can be run dozens of times without crashing.',
      ),
      tasks: [
        prismaSnippetTask({
          id: 'prisma05-c2-t1',
          title: 'Write an idempotent user seed with upsert',
          description: 'Ensure seeding a user will not fail with unique constraint violations if the record already exists.',
          instructions: [
            'Use `prisma.user.upsert` to make the insert idempotent',
            'Match `where: { email }`',
            'Leave `update: {}` empty so existing data is untouched',
            'Define `create: { email, name }` for fresh environments',
          ],
          hint: '`prisma.user.upsert({ where: { email }, update: {}, create: { email, name } })`.',
          scaffold: '-- Seed rows survive multiple idempotent runs:\nSELECT id, email FROM users WHERE id = 99;',
          solutionSql: "SELECT id, email FROM users WHERE email = 'alex@prisma.io';",
          why: 'upsert checks uniqueness before inserting, preventing P2002 errors on subsequent runs.',
          cols: ['id', 'email'],
          rows: 1,
          code0:
            'export async function seedUser(email: string, name: string) {\n  // Bug: this throws on second run if user exists!\n  return await prisma.user.create({\n    data: { email, name },\n  });\n}',
          code1:
            'export async function seedUser(email: string, name: string) {\n  return await prisma.user.upsert({\n    where: { email },\n    update: {},\n    create: { email, name },\n  });\n}',
          need: ['prisma.user.upsert', 'where: { email }', 'update: {}', 'create: { email, name }'],
          ban: ['prisma.user.create({'],
        }),
        prismaSnippetTask({
          id: 'prisma05-c2-t2',
          title: 'Register the seed script in package.json',
          description: 'Tell the Prisma CLI which command seeds a fresh database.',
          instructions: ['Add a `prisma` block to package.json', 'Point `seed` at tsx prisma/seed.ts'],
          hint: '`"seed": "tsx prisma/seed.ts"` inside `"prisma": { ... }`.',
          scaffold: '-- Seeded rows are readable straight away:\nSELECT id, email FROM users WHERE id = 99;',
          solutionSql: "SELECT id, email FROM users WHERE email = 'alex@prisma.io';",
          why: '`prisma migrate reset` and `db seed` both call the registered script.',
          cols: ['id', 'email'],
          rows: 1,
          code0: '{\n  "name": "api",\n  "scripts": {\n    "seed": "node seed.js"\n  }\n}',
          code1:
            '{\n  "name": "api",\n  "prisma": {\n    "seed": "tsx prisma/seed.ts"\n  }\n}',
          need: ['"prisma": {', '"seed": "tsx prisma/seed.ts"'],
          ban: ['"seed": "node seed.js"'],
        }),
      ],
    },
  ],
  challenge: {
    id: 'prisma05-challenge',
    title: 'Final Challenge — Deterministic Dev Reset',
    scenario: 'A development database must be completely reset and re-seeded in one command.',
    databaseLifecycle: 'fresh',
    tasks: [
      {
        ...prismaSnippetTask({
          id: 'prisma05-hw-1',
          title: 'Deterministic Database Reset & Seed',
          description: 'Reset a development database, re-apply all migrations, and run seeding in one step.',
          instructions: ['Use `npx prisma migrate reset`', 'Add `--force` to skip interactive confirmation'],
          hint: '`npx prisma migrate reset --force` drops the schema, applies migrations, and executes the seed script.',
          scaffold: '-- The reset database with freshly seeded rows:\nSELECT id, email FROM users WHERE id = 99;',
          solutionSql: 'SELECT id, email FROM users WHERE id IN (1, 2, 3);',
          why: 'migrate reset drops the database, runs all migrations, and invokes db seed automatically.',
          cols: ['id', 'email'],
          rows: 3,
          code0: 'const resetCmd = "npx prisma db push --force-reset";',
          code1: 'const resetCmd = "npx prisma migrate reset --force";',
          need: ['npx prisma migrate reset', '--force'],
          ban: ['db push'],
        }),
        type: 'challenge',
      },
    ],
  },
};
